import type { RequiredPluginEndpointMeta } from 'corsair/core';
import { cloudinaryOperations } from '../operations';
import {
	AdaptiveEndpoints,
	AnalysisEndpoints,
	AssetEndpoints,
	AssetsEndpoints,
	ChunkEndpoints,
	ConfigEndpoints,
	ContextEndpoints,
	CreateEndpoints,
	DatasourceEndpoints,
	DeleteEndpoints,
	DerivedEndpoints,
	EntriesEndpoints,
	FileEndpoints,
	FolderEndpoints,
	FoldersEndpoints,
	GenerateEndpoints,
	ImageEndpoints,
	ImagesEndpoints,
	LiveEndpoints,
	MappingEndpoints,
	MappingsEndpoints,
	MetadataEndpoints,
	MultiEndpoints,
	PingEndpoints,
	PresetEndpoints,
	PresetsEndpoints,
	RawEndpoints,
	ResourceEndpoints,
	ResourcesEndpoints,
	RootEndpoints,
	SlideshowEndpoints,
	SpriteEndpoints,
	StreamingEndpoints,
	TagsEndpoints,
	Transformation2Endpoints,
	TransformationEndpoints,
	TransformationsEndpoints,
	TriggersEndpoints,
	UpdateEndpoints,
	UsageEndpoints,
	VideoEndpoints,
	VideosEndpoints,
} from './index';
import { CloudinaryEndpointInputSchemas, CloudinaryEndpointOutputSchemas } from './types';

export const cloudinaryEndpointsNested = {
	live: LiveEndpoints,
	asset: AssetEndpoints,
	folder: FolderEndpoints,
	root: RootEndpoints,
	resources: ResourcesEndpoints,
	folders: FoldersEndpoints,
	image: ImageEndpoints,
	multi: MultiEndpoints,
	slideshow: SlideshowEndpoints,
	streaming: StreamingEndpoints,
	adaptive: AdaptiveEndpoints,
	transformation: TransformationEndpoints,
	transformation2: Transformation2Endpoints,
	transformations: TransformationsEndpoints,
	metadata: MetadataEndpoints,
	entries: EntriesEndpoints,
	datasource: DatasourceEndpoints,
	create: CreateEndpoints,
	delete: DeleteEndpoints,
	triggers: TriggersEndpoints,
	update: UpdateEndpoints,
	mapping: MappingEndpoints,
	mappings: MappingsEndpoints,
	preset: PresetEndpoints,
	presets: PresetsEndpoints,
	resource: ResourceEndpoints,
	images: ImagesEndpoints,
	raw: RawEndpoints,
	videos: VideosEndpoints,
	assets: AssetsEndpoints,
	context: ContextEndpoints,
	tags: TagsEndpoints,
	derived: DerivedEndpoints,
	file: FileEndpoints,
	chunk: ChunkEndpoints,
	generate: GenerateEndpoints,
	sprite: SpriteEndpoints,
	config: ConfigEndpoints,
	usage: UsageEndpoints,
	video: VideoEndpoints,
	analysis: AnalysisEndpoints,
	cloudinary: PingEndpoints,
} as const;

export const cloudinaryEndpointMeta = Object.fromEntries(
	cloudinaryOperations.map((operation) => [
		`${operation.group}.${operation.key}`,
		{
			riskLevel: operation.riskLevel,
			...(operation.irreversible ? { irreversible: true as const } : {}),
			description: operation.description,
		},
	]),
) as RequiredPluginEndpointMeta<typeof cloudinaryEndpointsNested>;

export const cloudinaryEndpointSchemas = Object.fromEntries(
	cloudinaryOperations.map((operation) => [
		`${operation.group}.${operation.key}`,
		{
			input: CloudinaryEndpointInputSchemas[operation.key],
			output: CloudinaryEndpointOutputSchemas[operation.key],
		},
	]),
);
