/**
 * Recognizable brands surfaced first in the list and by "Pick one for me"; order
 * is priority. Slugs must match real catalog rows — an unmatched one is a silent
 * no-op (see featuredRank). Already-built flagships (stripe, github, slack, …) are
 * absent by design: they're hidden from the catalog, so they can't be featured.
 */
export const FEATURED_SLUGS = [
	'salesforce',
	'shopify',
	'quickbooks',
	'xero',
	'snowflake',
	'databricks',
	'datadog',
	'servicenow',
	'netsuite',
	'workday',
	'mailchimp',
	'sendgrid',
	'segment',
	'klaviyo',
	'pipedrive',
	'docusign',
	'square',
	'confluence',
	'bitbucket',
	'circleci',
	'algolia',
	'elasticsearch',
	'contentful',
	'mixpanel',
	'metabase',
	'brex',
	'ramp',
	'coupa',
	'freshdesk',
	'freshservice',
	'freshbooks',
	'clickup',
	'webflow',
	'wix',
	'basecamp',
	'wrike',
	'shortcut',
	'coda',
	'brevo',
	'active_campaign',
	'customerio',
	'jotform',
	'pandadoc',
	'dropbox_sign',
	'new_relic',
	'bugsnag',
	'rollbar',
	'honeybadger',
	'bamboohr',
	'lever',
	'ashby',
	'workable',
	'help_scout',
	'gorgias',
	'close',
	'nutshell',
	'dialpad',
	'postmark',
	'jumpcloud',
	'egnyte',
	'render',
	'fly',
	'buildkite',
	'prismic',
	'storyblok',
	'productboard',
	'zoho',
	'zoho_books',
	'zoho_desk',
	'zoho_mail',
	'zoho_bigin',
	'zoho_inventory',
	'zoho_invoice',
	'monday_mcp',
	'openai',
	'canva',
	'miro',
	'supabase',
	'whatsapp',
	'elevenlabs',
	'apollo',
	'gong',
	'neon',
	'clickhouse',
	'prisma',
	'deepgram',
	'pinecone',
	'replicate',
	'cloudinary',
	'gumroad',
	'datarobot',
	'heygen',
	'mailerlite',
	'omnisend',
	'kaggle',
	'lemlist',
	'instantly',
	'reply',
	'runpod',
	'humanloop',
	'fathom',
	'recruitee',
	'freeagent',
	'celigo',
	'pingdom',
	'uptimerobot',
	'paperform',
	'slite',
	'pexels',
	'imgix',
	'uploadcare',
	'plasmic',
	'hex',
	'svix',
	'hookdeck',
	'doppler',
	'turso',
	'payhip',
	'telnyx',
	'shippo',
] as const;

const RANK_BY_SLUG = new Map<string, number>(
	FEATURED_SLUGS.map((slug, i) => [slug, i]),
);

/** Sort key: lower is more prominent. Non-featured slugs sort after all featured. */
export function featuredRank(slug: string): number {
	return RANK_BY_SLUG.get(slug) ?? Number.POSITIVE_INFINITY;
}
