"""Algolia Composio slug -> (method, path, hostType) mappings for all 133 operations."""

from __future__ import annotations

# hostType: search | analytics | ingestion | insights | querySuggestions | usage | personalization
RAW_ROUTES: list[tuple[str, str, str, str]] = [
    ("ALGOLIA_ADD_AB_TEST", "POST", "/2/abtests", "analytics"),
    ("ALGOLIA_ADD_OR_REPLACE_RECORD", "PUT", "/1/indexes/{indexName}/{objectID}", "search"),
    ("ALGOLIA_ADD_RECORD", "POST", "/1/indexes/{indexName}", "search"),
    ("ALGOLIA_BROWSE_INDEX", "POST", "/1/indexes/{indexName}/browse", "search"),
    ("ALGOLIA_CLEAR_OBJECTS", "POST", "/1/indexes/{indexName}/clear", "search"),
    ("ALGOLIA_CLEAR_RULES", "POST", "/1/indexes/{indexName}/rules/clear", "search"),
    ("ALGOLIA_CLEAR_SYNONYMS", "POST", "/1/indexes/{indexName}/synonyms/clear", "search"),
    ("ALGOLIA_CLICKED_OBJECT_IDS", "POST", "/1/events", "insights"),
    ("ALGOLIA_CLICKED_OBJECT_IDS_AFTER_SEARCH", "POST", "/1/events", "insights"),
    ("ALGOLIA_COMPUTE_REALTIME_USER", "POST", "/2/realtime/users/{userToken}/compute", "personalization"),
    ("ALGOLIA_CONVERTED_OBJECT_IDS", "POST", "/1/events", "insights"),
    ("ALGOLIA_COPY_INDEX", "POST", "/1/indexes/{indexName}/operation", "search"),
    ("ALGOLIA_CREATE_API_KEY", "POST", "/1/keys", "search"),
    ("ALGOLIA_CREATE_AUTHENTICATION", "POST", "/1/authentications", "ingestion"),
    ("ALGOLIA_CREATE_DESTINATION", "POST", "/1/destinations", "ingestion"),
    ("ALGOLIA_CREATE_INGESTION_TASK", "POST", "/2/tasks", "ingestion"),
    (
        "ALGOLIA_CREATE_OR_UPDATE_RECOMMEND_RULES",
        "POST",
        "/1/indexes/{indexName}/{model}/recommend/rules/batch",
        "search",
    ),
    ("ALGOLIA_CREATE_QS_CONFIG", "POST", "/1/configs", "querySuggestions"),
    ("ALGOLIA_CREATE_SOURCE", "POST", "/1/sources", "ingestion"),
    ("ALGOLIA_CREATE_TRANSFORMATION", "POST", "/1/transformations", "ingestion"),
    ("ALGOLIA_DELETE_AB_TEST", "DELETE", "/2/abtests/{id}", "analytics"),
    ("ALGOLIA_DELETE_API_KEY", "DELETE", "/1/keys/{key}", "search"),
    ("ALGOLIA_DELETE_AUTHENTICATION", "DELETE", "/1/authentications/{authenticationID}", "ingestion"),
    ("ALGOLIA_DELETE_CONFIG", "DELETE", "/1/configs/{indexName}", "querySuggestions"),
    ("ALGOLIA_DELETE_DESTINATION", "DELETE", "/1/destinations/{destinationID}", "ingestion"),
    ("ALGOLIA_DELETE_INDEX", "DELETE", "/1/indexes/{indexName}", "search"),
    ("ALGOLIA_DELETE_OBJECTS", "POST", "/1/indexes/{indexName}/batch", "search"),
    (
        "ALGOLIA_DELETE_RECOMMEND_RULE",
        "DELETE",
        "/1/indexes/{indexName}/{model}/recommend/rules/{objectID}",
        "search",
    ),
    ("ALGOLIA_DELETE_RECORDS_BY_FILTER", "POST", "/1/indexes/{indexName}/deleteByQuery", "search"),
    ("ALGOLIA_DELETE_RULE", "DELETE", "/1/indexes/{indexName}/rules/{objectID}", "search"),
    ("ALGOLIA_DELETE_SOURCE", "DELETE", "/1/sources/{sourceID}", "ingestion"),
    ("ALGOLIA_DELETE_SYNONYM", "DELETE", "/1/indexes/{indexName}/synonyms/{objectID}", "search"),
    ("ALGOLIA_DELETE_TRANSFORMATION", "DELETE", "/1/transformations/{transformationID}", "ingestion"),
    ("ALGOLIA_DELETE_USER_PROFILE", "DELETE", "/1/profiles/personalization/{userToken}", "search"),
    ("ALGOLIA_DELETE_USER_TOKEN", "DELETE", "/1/usertokens/{userToken}", "insights"),
    ("ALGOLIA_DISABLE_TASK_V1", "POST", "/1/tasks/{taskID}/disable", "ingestion"),
    ("ALGOLIA_ENABLE_TASK_V1", "POST", "/1/tasks/{taskID}/enable", "ingestion"),
    ("ALGOLIA_EXECUTE_BATCH_ON_MULTIPLE_INDICES", "POST", "/1/indexes/*/batch", "search"),
    ("ALGOLIA_EXPORT_RULES", "POST", "/1/indexes/{indexName}/rules/search", "search"),
    ("ALGOLIA_FIND_OBJECT", "POST", "/1/indexes/{indexName}/query", "search"),
    ("ALGOLIA_GET_AB_TEST", "GET", "/2/abtests/{id}", "analytics"),
    ("ALGOLIA_GET_ADD_TO_CART_RATE", "GET", "/2/conversions/addToCartRate", "analytics"),
    ("ALGOLIA_GET_API_KEY", "GET", "/1/keys/{key}", "search"),
    ("ALGOLIA_GET_APP_TASK", "GET", "/1/task/{taskID}", "search"),
    ("ALGOLIA_GET_AUTHENTICATION", "GET", "/1/authentications/{authenticationID}", "ingestion"),
    ("ALGOLIA_GET_AVERAGE_CLICK_POSITION", "GET", "/2/clicks/averageClickPosition", "analytics"),
    ("ALGOLIA_GET_CLICK_POSITIONS", "GET", "/2/clicks/positions", "analytics"),
    ("ALGOLIA_GET_CLICK_THROUGH_RATE", "GET", "/2/clicks/clickThroughRate", "analytics"),
    ("ALGOLIA_GET_CONFIG", "GET", "/1/configs/{indexName}", "querySuggestions"),
    ("ALGOLIA_GET_CONFIG2", "GET", "/2/config", "personalization"),
    ("ALGOLIA_GET_CONVERSION_RATE", "GET", "/2/conversions/conversionRate", "analytics"),
    ("ALGOLIA_GET_DESTINATION", "GET", "/1/destinations/{destinationID}", "ingestion"),
    ("ALGOLIA_GET_DICTIONARY_LANGUAGES", "GET", "/1/dictionaries/*/languages", "search"),
    ("ALGOLIA_GET_DICTIONARY_SETTINGS", "GET", "/1/dictionaries/*/settings", "search"),
    ("ALGOLIA_GET_LOGS", "GET", "/1/logs", "search"),
    ("ALGOLIA_GET_NO_CLICK_RATE", "GET", "/2/searches/noClickRate", "analytics"),
    ("ALGOLIA_GET_NO_RESULTS_RATE", "GET", "/2/searches/noResultRate", "analytics"),
    ("ALGOLIA_GET_NO_RESULTS_SEARCHES", "GET", "/2/searches/noResults", "analytics"),
    ("ALGOLIA_GET_OBJECT_POSITION", "POST", "/1/indexes/{indexName}/query", "search"),
    ("ALGOLIA_GET_OBJECTS", "POST", "/1/indexes/*/objects", "search"),
    ("ALGOLIA_GET_PURCHASE_RATE", "GET", "/2/conversions/purchaseRate", "analytics"),
    (
        "ALGOLIA_GET_RECOMMEND_RULE",
        "GET",
        "/1/indexes/{indexName}/{model}/recommend/rules/{objectID}",
        "search",
    ),
    (
        "ALGOLIA_GET_RECOMMEND_TASK_STATUS",
        "GET",
        "/1/indexes/{indexName}/{model}/task/{taskID}",
        "search",
    ),
    ("ALGOLIA_GET_RECORD", "GET", "/1/indexes/{indexName}/{objectID}", "search"),
    ("ALGOLIA_GET_REVENUE", "GET", "/2/conversions/revenue", "analytics"),
    ("ALGOLIA_GET_RULE", "GET", "/1/indexes/{indexName}/rules/{objectID}", "search"),
    ("ALGOLIA_GET_SEARCHES_COUNT", "GET", "/2/searches/count", "analytics"),
    ("ALGOLIA_GET_SEARCHES_NO_CLICKS", "GET", "/2/searches/noClicks", "analytics"),
    ("ALGOLIA_GET_SETTINGS", "GET", "/1/indexes/{indexName}/settings", "search"),
    ("ALGOLIA_GET_SOURCE", "GET", "/1/sources/{sourceID}", "ingestion"),
    ("ALGOLIA_GET_SYNONYM", "GET", "/1/indexes/{indexName}/synonyms/{objectID}", "search"),
    ("ALGOLIA_GET_TASK_STATUS", "GET", "/1/indexes/{indexName}/task/{taskID}", "search"),
    ("ALGOLIA_GET_TASK_V1", "GET", "/1/tasks/{taskID}", "ingestion"),
    ("ALGOLIA_GET_TOP_COUNTRIES", "GET", "/2/countries", "analytics"),
    ("ALGOLIA_GET_TOP_FILTER_ATTRIBUTES", "GET", "/2/filters", "analytics"),
    ("ALGOLIA_GET_TOP_FILTER_FOR_ATTRIBUTE", "GET", "/2/filters/{attribute}", "analytics"),
    ("ALGOLIA_GET_TOP_FILTERS_NO_RESULTS", "GET", "/2/filters/noResults", "analytics"),
    ("ALGOLIA_GET_TOP_HITS", "GET", "/2/hits", "analytics"),
    ("ALGOLIA_GET_TOP_SEARCHES", "GET", "/2/searches", "analytics"),
    ("ALGOLIA_GET_TRANSFORMATION", "GET", "/1/transformations/{transformationID}", "ingestion"),
    ("ALGOLIA_GET_USAGE", "GET", "/1/usage/records", "usage"),
    ("ALGOLIA_GET_USAGE_FOR_INDEX", "GET", "/1/usage/indices/{indexName}", "usage"),
    ("ALGOLIA_GET_USERS", "GET", "/2/users", "personalization"),
    ("ALGOLIA_GET_USERS_COUNT", "GET", "/2/users/count", "analytics"),
    ("ALGOLIA_INDEX_EXISTS", "GET", "/1/indexes/{indexName}", "search"),
    ("ALGOLIA_INIT_INSIGHTS", "POST", "/1/events", "insights"),
    ("ALGOLIA_LIST_AB_TESTS", "GET", "/2/abtests", "analytics"),
    ("ALGOLIA_LIST_API_KEYS", "GET", "/1/keys", "search"),
    ("ALGOLIA_LIST_AUTHENTICATIONS", "GET", "/1/authentications", "ingestion"),
    ("ALGOLIA_LIST_DESTINATIONS", "GET", "/1/destinations", "ingestion"),
    ("ALGOLIA_LIST_INDICES", "GET", "/1/indexes", "search"),
    ("ALGOLIA_LIST_INGESTION_TASKS", "GET", "/2/tasks", "ingestion"),
    ("ALGOLIA_LIST_QS_CONFIGS", "GET", "/1/configs", "querySuggestions"),
    ("ALGOLIA_LIST_RUNS", "GET", "/1/runs", "ingestion"),
    ("ALGOLIA_LIST_SOURCES", "GET", "/1/sources", "ingestion"),
    ("ALGOLIA_LIST_TRANSFORMATIONS", "GET", "/1/transformations", "ingestion"),
    ("ALGOLIA_PARTIAL_UPDATE_OBJECTS", "POST", "/1/indexes/{indexName}/batch", "search"),
    ("ALGOLIA_PUSH_TASK", "POST", "/2/tasks/{taskID}/push", "ingestion"),
    ("ALGOLIA_REPLACE_ALL_RULES", "POST", "/1/indexes/{indexName}/rules/batch", "search"),
    ("ALGOLIA_REPLACE_TASK", "PUT", "/2/tasks/{taskID}", "ingestion"),
    ("ALGOLIA_RESTORE_API_KEY", "POST", "/1/keys/{key}/restore", "search"),
    ("ALGOLIA_RUN_TASK_V1", "POST", "/1/tasks/{taskID}/run", "ingestion"),
    ("ALGOLIA_SAVE_RULE", "PUT", "/1/indexes/{indexName}/rules/{objectID}", "search"),
    ("ALGOLIA_SAVE_SYNONYM", "PUT", "/1/indexes/{indexName}/synonyms/{objectID}", "search"),
    ("ALGOLIA_SAVE_SYNONYMS", "POST", "/1/indexes/{indexName}/synonyms/batch", "search"),
    ("ALGOLIA_SEARCH_AUTHENTICATIONS", "POST", "/1/authentications/search", "ingestion"),
    ("ALGOLIA_SEARCH_DESTINATIONS", "POST", "/1/destinations/search", "ingestion"),
    ("ALGOLIA_SEARCH_DICTIONARY_ENTRIES", "POST", "/1/dictionaries/{dictionaryName}/search", "search"),
    ("ALGOLIA_SEARCH_FACET_VALUES", "POST", "/1/indexes/{indexName}/facets/{facetName}/query", "search"),
    ("ALGOLIA_SEARCH_INDEX", "POST", "/1/indexes/{indexName}/query", "search"),
    ("ALGOLIA_SEARCH_MULTIPLE_INDICES", "POST", "/1/indexes/*/queries", "search"),
    (
        "ALGOLIA_SEARCH_RECOMMEND_RULES",
        "POST",
        "/1/indexes/{indexName}/{model}/recommend/rules/search",
        "search",
    ),
    ("ALGOLIA_SEARCH_SOURCES", "POST", "/1/sources/search", "ingestion"),
    ("ALGOLIA_SEARCH_SYNONYMS", "POST", "/1/indexes/{indexName}/synonyms/search", "search"),
    ("ALGOLIA_SEARCH_TASKS_V1", "POST", "/1/tasks/search", "ingestion"),
    ("ALGOLIA_SEARCH_TRANSFORMATIONS", "POST", "/1/transformations/search", "ingestion"),
    ("ALGOLIA_SET_DICTIONARY_SETTINGS", "PUT", "/1/dictionaries/*/settings", "search"),
    ("ALGOLIA_SET_PERSONALIZATION_STRATEGY", "PUT", "/1/strategies/personalization", "search"),
    ("ALGOLIA_SET_SETTINGS", "PUT", "/1/indexes/{indexName}/settings", "search"),
    ("ALGOLIA_STOP_AB_TEST", "POST", "/2/abtests/{id}/stop", "analytics"),
    ("ALGOLIA_TRY_TRANSFORMATION", "POST", "/1/transformations/try", "ingestion"),
    (
        "ALGOLIA_TRY_TRANSFORMATION_BEFORE_UPDATE",
        "POST",
        "/1/transformations/{transformationID}/try",
        "ingestion",
    ),
    ("ALGOLIA_UPDATE_API_KEY", "PUT", "/1/keys/{key}", "search"),
    ("ALGOLIA_UPDATE_AUTHENTICATION", "PATCH", "/1/authentications/{authenticationID}", "ingestion"),
    ("ALGOLIA_UPDATE_CONFIG", "PUT", "/1/configs/{indexName}", "querySuggestions"),
    ("ALGOLIA_UPDATE_DESTINATION", "PATCH", "/1/destinations/{destinationID}", "ingestion"),
    ("ALGOLIA_UPDATE_DICTIONARY_ENTRIES", "POST", "/1/dictionaries/{dictionaryName}/batch", "search"),
    ("ALGOLIA_UPDATE_RECORD_PARTIALLY", "POST", "/1/indexes/{indexName}/{objectID}/partial", "search"),
    ("ALGOLIA_UPDATE_SOURCE", "PATCH", "/1/sources/{sourceID}", "ingestion"),
    ("ALGOLIA_UPDATE_TASK", "PATCH", "/2/tasks/{taskID}", "ingestion"),
    ("ALGOLIA_UPDATE_TRANSFORMATION", "PATCH", "/1/transformations/{transformationID}", "ingestion"),
    ("ALGOLIA_VALIDATE_SOURCE", "POST", "/1/sources/validate", "ingestion"),
    ("ALGOLIA_VALIDATE_SOURCE_BEFORE_UPDATE", "POST", "/1/sources/{sourceID}/validate", "ingestion"),
]

MANUAL_ROUTES: dict[str, tuple[str, str, str]] = {
    slug: (method, path, host) for slug, method, path, host in RAW_ROUTES
}
