import type { EndpointRiskLevel } from 'corsair/core';

export type ActiveTrailMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';

export type ActiveTrailRoute = {
	key: string;
	group: string;
	name: string;
	method: ActiveTrailMethod;
	path: string;
	description: string;
	pathParams?: readonly string[];
	queryParams?: readonly string[];
	riskLevel: EndpointRiskLevel;
	irreversible?: boolean;
};

export const activeTrailRoutes = [
	{
		key: 'addGroupMember',
		group: 'groups',
		name: 'addGroupMember',
		method: 'POST',
		path: '/api/groups/{id}/members',
		description:
			'Tool to add a member to a group in ActiveTrail. Creates a new contact or adds an existing contact to the specified group. Supports comprehensive contact information including names, phone numbers, addresses, dates, and custom extension fields. The API will not return errors if the contact is already in the group (idempotent operation).',
		pathParams: ['group_id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'addMailinglistMember',
		group: 'mailingList',
		name: 'addMailinglistMember',
		method: 'POST',
		path: '/api/mailinglist/{id}/members',
		description:
			'Tool to add a member to a mailing list in ActiveTrail. Creates a new contact or adds an existing contact to the specified mailing list and groups. Either email or SMS must be provided.',
		pathParams: ['mailinglist_id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'contactGrowth',
		group: 'account',
		name: 'contactGrowth',
		method: 'GET',
		path: '/api/account/executivereport/contactgrowth',
		description:
			'Retrieves daily contact growth statistics showing active (subscribed) and inactive (unsubscribed) contact counts over a specified date range. Use this to analyze contact acquisition trends and measure the growth of your subscriber base over time. Returns time-series data with daily breakdowns.',
		pathParams: [],
		queryParams: ['FromDate', 'ToDate'],
		riskLevel: 'read' as const,
	},
	{
		key: 'createANewGroup',
		group: 'groups',
		name: 'createANewGroup',
		method: 'POST',
		path: '/api/groups',
		description:
			'Creates a new contact group in ActiveTrail for organizing and segmenting contacts. Groups are containers for contacts that allow you to: - Organize contacts by category, campaign, or segment - Target specific groups for email/SMS campaigns - Manage contact memberships independently The newly created group will be empty. Use the "Add Group Member" action to add contacts to this group. Returns the complete group details including the assigned group ID.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createCampaign',
		group: 'campaigns',
		name: 'createCampaign',
		method: 'POST',
		path: '/api/campaigns',
		description:
			'Create and return a new email campaign for specific groups. The campaign can be configured as an A/B split test, E-commerce campaign, or a regular campaign. Created in draft status unless is_sent is set to true.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createCampaignForContacts',
		group: 'campaigns',
		name: 'createCampaignForContacts',
		method: 'POST',
		path: '/api/campaigns/Contacts',
		description:
			'Tool to create and send a new campaign to specific contacts in ActiveTrail. Use when you need to create campaigns targeted at selected recipients by contact IDs or email addresses. Supports regular campaigns, A/B split campaigns, and e-commerce campaigns.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createContact',
		group: 'contacts',
		name: 'createContact',
		method: 'POST',
		path: '/api/contacts',
		description:
			'Creates a new contact in ActiveTrail with the provided information. At least one of email or sms must be provided as the primary identifier. All other fields are optional and can be used to enrich the contact profile. Important: Newly created contacts are not automatically assigned to any group. To enable email/SMS campaigns for this contact, you must add them to a group using a separate action after creation. Returns the complete contact record including the assigned contact ID.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createContentCategory',
		group: 'account',
		name: 'createContentCategory',
		method: 'POST',
		path: '/api/account/contentCategories',
		description:
			'Tool to create a new content category in ActiveTrail account. Use when you need to add a new category for organizing campaigns and templates.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createNewMailingList',
		group: 'mailingList',
		name: 'createNewMailingList',
		method: 'POST',
		path: '/api/mailinglist',
		description:
			'Tool to create a new mailing list in ActiveTrail. Use when you need to add a new mailing list to organize and manage contacts.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createOrder',
		group: 'commerce',
		name: 'createOrder',
		method: 'POST',
		path: '/api/commerce/Order',
		description:
			'Tool to create new orders in ActiveTrail commerce system. Use when you need to add order records with customer information, products, and transaction details. Accepts an array of order objects for batch creation.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createSegmentation',
		group: 'segmentation',
		name: 'createSegmentation',
		method: 'POST',
		path: '/api/segmentation',
		description:
			'Create a new contact segmentation in ActiveTrail. Segmentations are rule-based filters that define target audiences based on contact field values (e.g., email equals specific value, city contains text, etc.). Use this to create dynamic segments for campaign targeting, automation workflows, or contact organization. Requires a unique name and at least one base rule with field, operator, and values.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createSmartCodeSite',
		group: 'smartCodeSite',
		name: 'createSmartCodeSite',
		method: 'POST',
		path: '/api/smartcodesite',
		description:
			"Creates a new Smart Code tracking site in ActiveTrail. Smart Code is ActiveTrail's web analytics and visitor tracking solution that monitors visitor behavior on your website. Use this action to register a website for Smart Code tracking by providing a site name and domain(s).",
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createSmsCampaign',
		group: 'smsCampaign',
		name: 'createSmsCampaign',
		method: 'POST',
		path: '/api/smscampaign/Campaign',
		description:
			'Tool to create a new SMS campaign in ActiveTrail. Use when you need to send SMS messages to segments of your audience with customizable content, sender name, and scheduling options.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createSmsOperationalMessage',
		group: 'external',
		name: 'createSmsOperationalMessage',
		method: 'POST',
		path: '/api/external/operational/sms_message',
		description:
			'Tool to create a new operational SMS transactional message. Use when you need to create an SMS campaign for later use or editing.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createWebhook',
		group: 'webhooks',
		name: 'createWebhook',
		method: 'POST',
		path: '/api/webhooks',
		description:
			"Create a new webhook for event notifications in ActiveTrail. Webhooks enable real-time notifications for events like contact changes or campaign activities. After creating the webhook, use the 'Update Webhook Parameter' action to add custom parameters (headers, query params, body data) if needed.",
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'deleteAccountContentCategories',
		group: 'account',
		name: 'deleteAccountContentCategories',
		method: 'DELETE',
		path: '/api/account/contentCategories/{id}',
		description:
			'Tool to delete a specific content category by ID. Use when you need to remove a category from your ActiveTrail account.',
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteAMemberInAGroup',
		group: 'groups',
		name: 'deleteAMemberInAGroup',
		method: 'DELETE',
		path: '/api/groups/{group_id}/members/{contact_id}',
		description:
			'Tool to delete a group member by ID. Use when you need to remove a contact from a specific group in ActiveTrail.',
		pathParams: ['group_id', 'contact_id'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteAutomations',
		group: 'automations',
		name: 'deleteAutomations',
		method: 'DELETE',
		path: '/api/automations/{ids}',
		description:
			'Tool to delete one or more automations from Active Trail. Use when you need to remove automations by their IDs. Supports bulk deletion by providing comma-separated IDs.',
		pathParams: ['ids'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteCampaign',
		group: 'campaigns',
		name: 'deleteCampaign',
		method: 'DELETE',
		path: '/api/campaigns/{id}',
		description:
			'Tool to remove a campaign from ActiveTrail account. Use when you need to delete a campaign that is no longer needed.',
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteContact',
		group: 'contacts',
		name: 'deleteContact',
		method: 'DELETE',
		path: '/api/contacts/{id}',
		description:
			'Tool to permanently remove a contact from the ActiveTrail account by their unique contact ID. Use when you need to delete a specific contact. This operation is destructive and cannot be undone. Returns success status and optional message.',
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteGroupById',
		group: 'groups',
		name: 'deleteGroupById',
		method: 'DELETE',
		path: '/api/groups/{id}',
		description:
			'Tool to delete a group by ID. Use when you need to permanently remove a group from ActiveTrail. This is a destructive operation that cannot be undone.',
		pathParams: ['group_id'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteMailingList',
		group: 'external',
		name: 'deleteMailingList',
		method: 'DELETE',
		path: '/api/external/mailinglist/{mailinglistId}',
		description:
			'Tool to permanently remove a mailing list from the ActiveTrail account by its unique ID. Use when you need to delete a mailing list that is no longer needed. This operation is destructive and cannot be undone. Returns success status and confirmation message.',
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteSmartCodeSite',
		group: 'smartCodeSite',
		name: 'deleteSmartCodeSite',
		method: 'DELETE',
		path: '/api/smartcodesite/{id}',
		description:
			'Tool to remove a Smart Code site from ActiveTrail. Use when you need to permanently delete a Smart Code site identified by its unique ID.',
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteTemplate',
		group: 'templates',
		name: 'deleteTemplate',
		method: 'DELETE',
		path: '/api/templates/{id}',
		description:
			'Tool to remove a template from ActiveTrail account. Use when you need to delete a template that is no longer needed.',
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteTemplatesTemplateCategory',
		group: 'templates',
		name: 'deleteTemplatesTemplateCategory',
		method: 'DELETE',
		path: '/api/templates/TemplateCategory/{id}',
		description:
			'Tool to delete a template category by ID. Use when you need to remove a template category. Warning: Deleting a category will cascade-delete all templates within that category.',
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteWebhook',
		group: 'webhooks',
		name: 'deleteWebhook',
		method: 'DELETE',
		path: '/api/webhooks/{id}',
		description:
			'Tool to remove a webhook from ActiveTrail account by its ID. Use when you need to delete a webhook that is no longer needed.',
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteWebhooksParameters',
		group: 'webhooks',
		name: 'deleteWebhooksParameters',
		method: 'DELETE',
		path: '/api/webhooks/{webhook_id}/parameters/{id}',
		description:
			'Removes a specific parameter from a webhook configuration in ActiveTrail. Use this when you need to delete custom headers, query parameters, or body parameters that were previously added to a webhook. Requires both the webhook ID and the specific parameter ID to delete.',
		pathParams: ['webhook_id', 'parameter_id'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'getAccountBalance',
		group: 'account',
		name: 'getAccountBalance',
		method: 'GET',
		path: '/api/account/balance',
		description:
			'Tool to retrieve email and SMS credit balance for the account. Use when you need to check available email and SMS credits. #### Output | Parameter | Type | Required | Description | |-----------|------|----------|-------------| | `data` | string | Yes | Data from the action execution | | `error` | string | No | Error if any occurred during the execution of the action | | `successful` | boolean | Yes | Whether or not the action execution was successful or not |',
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getAccountContentCategories2',
		group: 'account',
		name: 'getAccountContentCategories2',
		method: 'GET',
		path: '/api/account/contentCategories/{id}',
		description:
			'Tool to retrieve specific category details by ID. Use when you need to get information about a content category from your ActiveTrail account.',
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getAccountIntegrationdata',
		group: 'account',
		name: 'getAccountIntegrationdata',
		method: 'GET',
		path: '/api/account/integrationdata/activecommerce',
		description:
			"Retrieves the account's ActiveCommerce integration configuration data including mailing list and group associations. This endpoint returns the integration settings that connect ActiveTrail with ActiveCommerce, showing which mailing list and group are configured for the integration. Use this when you need to verify ActiveCommerce integration setup or troubleshoot integration issues. #### Output | Parameter | Type | Required | Description | |-----------|------|----------|-------------| | `data` | string | Yes | Data from the action execution | | `error` | string | No | Error if any occurred during the execution of the action | | `successful` | boolean | Yes | Whether or not the action execution was successful or not |",
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getAccountMerge',
		group: 'account',
		name: 'getAccountMerge',
		method: 'GET',
		path: '/api/account/merge',
		description:
			'Check if the ActiveTrail account has any pending account merge operations. This action retrieves the current account merge status, indicating whether there are any account merges awaiting completion. Account merges are typically used when consolidating multiple ActiveTrail accounts into one. Returns information about pending merges including their status, source and target accounts, and creation dates. Use this when you need to: - Verify if any account merge operations are in progress - Monitor the status of account consolidation processes - Check for pending administrative merge tasks #### Output | Parameter | Type | Required | Description | |-----------|------|----------|-------------| | `data` | string | Yes | Data from the action execution | | `error` | string | No | Error if any occurred during the execution of the action | | `successful` | boolean | Yes | Whether or not the action execution was successful or not |',
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getAllCampaignReports',
		group: 'campaignReports',
		name: 'getAllCampaignReports',
		method: 'GET',
		path: '/api/campaignreports',
		description:
			'Tool to retrieve a full overview of all campaign reports with comprehensive metrics. Use when you need to get reports for all campaigns including send date, opened emails, number of clicks, CTO, bounces, unsubscribers, complaints, unopened and sent emails. Default behavior: Returns campaigns filtered by last update date within the previous 3 months when date parameters are not specified. Default limit is 20 records per page, maximum is 100.',
		pathParams: [],
		queryParams: ['Page', 'Limit'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getAllGroups',
		group: 'groups',
		name: 'getAllGroups',
		method: 'GET',
		path: '/api/groups',
		description:
			'Tool to retrieve the full list of account groups with pagination and filtering. Use when you need to get all groups or search for groups by name. Default limit is 100 groups per page.',
		pathParams: [],
		queryParams: ['SearchTerm', 'Page', 'Limit'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getAllSentCampaigns',
		group: 'campaignReports',
		name: 'getAllSentCampaigns',
		method: 'GET',
		path: '/api/campaigns',
		description:
			'Tool to retrieve campaigns with optional filtering by date, mailing list, and search criteria. Use when you need to get campaigns filtered by date range (default is last 3 months), limited to a specific number (default is 100), or filtered by mailing list.',
		pathParams: [],
		queryParams: ['Groupid', 'FromDate', 'ToDate', 'Page', 'Limit'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getAutomationLog',
		group: 'automations',
		name: 'getAutomationLog',
		method: 'GET',
		path: '/api/automationreports/{id}/logautomation',
		description:
			'Tool to track contacts through automation journey by retrieving detailed logs. Use when you need to see which contacts started a specific automation and their progress through each step of the workflow.',
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getAutomationReportsLogAutomationQueue',
		group: 'automations',
		name: 'getAutomationReportsLogAutomationQueue',
		method: 'GET',
		path: '/api/automationreports/{id}/logautomationqueue',
		description:
			'Tool to retrieve contacts that did not finish a specific automation. Use when you need to get the list of contacts remaining in the automation queue for a given automation ID.',
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getAutomationReportsSmsCampaignSummary',
		group: 'smsCampaignReport',
		name: 'getAutomationReportsSmsCampaignSummary',
		method: 'GET',
		path: '/api/automationreports/{id}/SMSCampaignSummaryReport',
		description:
			"Tool to retrieve SMS campaigns' summary reports for a specific automation. Use when you need to analyze SMS campaign performance including sent, delivered, failed, credits consumed, unsubscribe, and click metrics within an automation.",
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getAutomationReportsSummaryReport',
		group: 'smsCampaignReport',
		name: 'getAutomationReportsSummaryReport',
		method: 'GET',
		path: '/api/automationreports/{id}/SummaryReport',
		description:
			"Tool to retrieve email campaigns' summary reports for a specific automation. Use when you need to analyze email campaign performance metrics including opens, clicks, click-to-open rate, conversions, bounces, unsubscribes, and spam complaints within an automation for a given date range.",
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getAutomations',
		group: 'automations',
		name: 'getAutomations',
		method: 'GET',
		path: '/api/automations',
		description:
			'Tool to list account automations with filtering and pagination. Use when you need to retrieve automations from the ActiveTrail account. Supports filtering by state and pagination parameters.',
		pathParams: [],
		queryParams: ['StateType', 'Page', 'Limit'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getAutomationsDetails',
		group: 'automations',
		name: 'getAutomationsDetails',
		method: 'GET',
		path: '/api/automations/{id}/details',
		description:
			'Tool to retrieve detailed configuration of a specific automation excluding step-by-step execution details. Use when you need metadata about automation behavior, scheduling, reporting settings, and operational constraints.',
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getAutomationsEmailCampaignSteps',
		group: 'automations',
		name: 'getAutomationsEmailCampaignSteps',
		method: 'GET',
		path: '/api/automations/{id}/EmailCampaignSteps',
		description:
			"Tool to retrieve all email campaign steps in an automation workflow. Use when you need to get details about all 'send email' steps configured within a specific automation, including email content, scheduling, and tracking settings.",
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getAutomationsSmsCampaignSteps',
		group: 'automations',
		name: 'getAutomationsSmsCampaignSteps',
		method: 'GET',
		path: '/api/automations/{id}/SMSCampaignSteps',
		description:
			"Tool to retrieve all SMS campaign steps in an automation workflow. Use when you need to get details about all 'send SMS' steps configured within a specific automation, including SMS content, scheduling, and tracking settings.",
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getAutomationTriggerTypes',
		group: 'automations',
		name: 'getAutomationTriggerTypes',
		method: 'GET',
		path: '/api/automations/{id}/triggerInfo',
		description:
			'Tool to retrieve all available start trigger options for automations. Use when you need to get the list of trigger types that can initiate automation workflows in ActiveTrail. #### Output | Parameter | Type | Required | Description | |-----------|------|----------|-------------| | `data` | string | Yes | Data from the action execution | | `error` | string | No | Error if any occurred during the execution of the action | | `successful` | boolean | Yes | Whether or not the action execution was successful or not |',
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getCampaignBounces',
		group: 'campaignReports',
		name: 'getCampaignBounces',
		method: 'GET',
		path: '/api/campaignreports/{id}/bounces',
		description:
			'Tool to retrieve bounce details by domain for a specific campaign. Use when you need to analyze campaign bounce rates and identify problematic email domains. Defaults to campaigns updated in the last 3 months.',
		pathParams: ['id'],
		queryParams: ['BounceType'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getCampaignClicks',
		group: 'smsCampaign',
		name: 'getCampaignClicks',
		method: 'GET',
		path: '/api/campaignreports/{id}/clickdetails',
		description:
			"Retrieves detailed click-through data for all links in a campaign or optionally for a specific link. Returns comprehensive information including contact details (name, email), click timestamps, device information (browser, OS, device type), and click counts. Default date range: last 3 months from current date. Use this for aggregate click analysis across multiple links; for detailed analysis of a single link, consider using 'Get Click Details by Link ID' action instead. Returns an error if the campaign wasn't sent within the specified date range.",
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getCampaignDesign',
		group: 'campaigns',
		name: 'getCampaignDesign',
		method: 'GET',
		path: '/api/campaigns/{id}/design',
		description:
			'Tool to retrieve campaign design configuration including visual layout and HTML content. Use when you need to get the design details of a specific email campaign.',
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getCampaignDomainsReport',
		group: 'smsCampaignReport',
		name: 'getCampaignDomainsReport',
		method: 'GET',
		path: '/api/campaignreports/{id}/domains',
		description:
			'Tool to retrieve a report by domain for a specific campaign. Use when you need to analyze campaign performance grouped by recipient email domains, including sends, opens, clicks, bounces, and engagement metrics per domain. Defaults to campaigns updated in the last 3 months.',
		pathParams: ['campaign_id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getCampaignOpens',
		group: 'smsCampaign',
		name: 'getCampaignOpens',
		method: 'GET',
		path: '/api/campaignreports/{id}/opens',
		description:
			"Tool to retrieve contacts who opened a specific campaign email. Use when you need to identify which recipients opened your campaign, track open rates, and analyze campaign engagement. Default search covers campaigns updated in the last 3 months; if the campaign wasn't sent during the specified date range, an empty list is returned. Supports pagination and filtering by group.",
		pathParams: ['campaign_id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getCampaignReport',
		group: 'smsCampaignReport',
		name: 'getCampaignReport',
		method: 'GET',
		path: '/api/campaignreports/{id}',
		description:
			"Retrieves comprehensive performance metrics for a specific email campaign by its ID. Returns detailed statistics including send count, open rate, click rate, click-to-open rate (CTO), bounce rate, unsubscribe rate, spam complaints, and conversion data. Use this when you need detailed performance analytics for a single campaign. Default behavior: Returns data for campaigns updated in the last 3 months when date parameters are not specified. Note: Returns an error if the campaign wasn't sent/updated within the specified date range.",
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getCampaignReportsBounced',
		group: 'campaignReports',
		name: 'getCampaignReportsBounced',
		method: 'GET',
		path: '/api/campaignreports/{id}/bounced',
		description:
			"Tool to retrieve bounced email details filtered by bounce type for a specific campaign. Use when you need detailed information about which contacts' emails bounced and why, with the ability to filter by hard or soft bounces.",
		pathParams: ['id'],
		queryParams: ['BounceType'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getCampaignReportsComplaints',
		group: 'campaignReports',
		name: 'getCampaignReportsComplaints',
		method: 'GET',
		path: '/api/campaignreports/{id}/complaints',
		description:
			"Tool to retrieve contacts who reported a specific campaign as spam. Use when you need to identify which contacts flagged your campaign as unwanted. The default search window is the last 3 months; if the campaign wasn't sent during the specified dates, an empty list is returned.",
		pathParams: ['id'],
		queryParams: ['Groupid', 'FromDate', 'ToDate', 'Page', 'Limit'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getCampaignReportsEmailActivity',
		group: 'contacts',
		name: 'getCampaignReportsEmailActivity',
		method: 'GET',
		path: '/api/campaignreports/{id}/emailactivity',
		description:
			"Tool to retrieve all contacts' activity on a specific campaign. Use when you need comprehensive activity data including opens, clicks, bounces, and other engagement metrics for each contact in a campaign. By default, the search covers campaigns updated in the last 3 months; if the campaign wasn't sent in the specified date range, an error will be returned.",
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getCampaignReportsSent',
		group: 'campaignReports',
		name: 'getCampaignReportsSent',
		method: 'GET',
		path: '/api/campaignreports/{id}/sent',
		description:
			"Tool to retrieve contacts who received a specific campaign email. Use when you need to identify which recipients successfully received your campaign. The default search window is the last 3 months; if the campaign wasn't sent during the specified dates, an empty list is returned.",
		pathParams: ['id'],
		queryParams: ['Groupid', 'FromDate', 'ToDate', 'Page', 'Limit'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getCampaignReportsUnopened',
		group: 'campaignReports',
		name: 'getCampaignReportsUnopened',
		method: 'GET',
		path: '/api/campaignreports/{id}/unopened',
		description:
			"Tool to retrieve contacts who did not open a specific campaign. Use when you need to identify which recipients received but did not open your campaign email. The default search window is the last 3 months; if the campaign wasn't sent during the specified dates, an empty list is returned.",
		pathParams: ['id'],
		queryParams: ['Groupid', 'FromDate', 'ToDate', 'Page', 'Limit'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getCampaignScheduling',
		group: 'campaigns',
		name: 'getCampaignScheduling',
		method: 'GET',
		path: '/api/campaigns/{id}/scheduling',
		description:
			"Retrieves the scheduling configuration for a specific email campaign, including send status and scheduled datetime. Use this action when you need to check if a campaign is scheduled to send, when it's scheduled to send (in UTC), or verify the send status of a campaign. The response includes is_sent flag (whether campaign is dispatched) and scheduled_date_utc (planned send datetime). Campaign ID can be obtained from campaign list actions.",
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getCampaignSDetails',
		group: 'smsCampaign',
		name: 'getCampaignSDetails',
		method: 'GET',
		path: '/api/campaigns/{id}',
		description:
			'Tool to retrieve complete campaign information including send settings, design, template, and A/B test configuration. Use when you need comprehensive details about a specific email campaign.',
		pathParams: ['campaign_id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getCampaignsDetails',
		group: 'campaigns',
		name: 'getCampaignsDetails',
		method: 'GET',
		path: '/api/campaigns/{id}/details',
		description:
			'Tool to retrieve detailed campaign information including name, subject, and settings. Use when you need to get comprehensive details about a specific email campaign.',
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getCampaignsSegment',
		group: 'campaigns',
		name: 'getCampaignsSegment',
		method: 'GET',
		path: '/api/campaigns/{id}/segment',
		description:
			'Tool to retrieve campaign sending settings including target groups and sending restrictions. Use when you need to get the segmentation configuration for a specific campaign.',
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getCampaignsSentCampaigns',
		group: 'campaigns',
		name: 'getCampaignsSentCampaigns',
		method: 'GET',
		path: '/api/campaigns/SentCampaigns',
		description:
			'Tool to retrieve a list of all sent campaigns from ActiveTrail. Use when you need to view all campaigns that have been sent, including their details such as name, subject, send status, and delivery metrics. #### Output | Parameter | Type | Required | Description | |-----------|------|----------|-------------| | `data` | string | Yes | Data from the action execution | | `error` | string | No | Error if any occurred during the execution of the action | | `successful` | boolean | Yes | Whether or not the action execution was successful or not |',
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getCampaignTemplate',
		group: 'campaigns',
		name: 'getCampaignTemplate',
		method: 'GET',
		path: '/api/campaigns/{id}/template',
		description:
			"Retrieves template details (design, content, subject line, sender info) for a specific email campaign. Use this action when you need to: - View the template configuration used in a campaign - Get HTML/plain text content of a campaign template - Retrieve sender information (from name, from email, reply-to) - Access template metadata like category, creation/modification dates Note: Requires a valid campaign ID which can be obtained from the 'Get Sent Campaigns' action.",
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getCampaignUnsubscribed',
		group: 'campaignReports',
		name: 'getCampaignUnsubscribed',
		method: 'GET',
		path: '/api/campaignreports/{id}/unsubscribed',
		description:
			"Retrieves the list of contacts who unsubscribed from a specific email campaign. Use this action when you need to: - Identify which recipients opted out of receiving future communications from a campaign - Analyze unsubscribe patterns and reasons for a particular campaign - Track campaign unsubscribe metrics and contact details By default, searches campaigns updated within the last 3 months. If the campaign wasn't sent within the specified date range, an empty list is returned. Supports pagination for large unsubscribe lists.",
		pathParams: ['id'],
		queryParams: ['FromDate', 'ToDate', 'Page', 'Limit'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getCommerceSchema',
		group: 'commerce',
		name: 'getCommerceSchema',
		method: 'GET',
		path: '/api/commerce/schema',
		description:
			'Tool to retrieve order fields schema information from the ActiveTrail commerce API. Use when you need to get information about available order fields, their types, and custom names for commerce/order management. #### Output | Parameter | Type | Required | Description | |-----------|------|----------|-------------| | `data` | string | Yes | Data from the action execution | | `error` | string | No | Error if any occurred during the execution of the action | | `successful` | boolean | Yes | Whether or not the action execution was successful or not |',
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getContactActivity',
		group: 'contacts',
		name: 'getContactActivity',
		method: 'GET',
		path: '/api/contacts/{id}/activity',
		description:
			"Tool to retrieve contact's email engagement history including opens and clicks. Use when you need detailed activity data showing which campaigns were sent to a contact and their engagement metrics.",
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getContactDetails',
		group: 'contacts',
		name: 'getContactDetails',
		method: 'GET',
		path: '/api/contacts/{id}',
		description:
			'Tool to retrieve complete details of a specific contact by their ID. Use when you need full contact information including personal data, contact fields, subscription status, and all custom extended fields.',
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getContactFields',
		group: 'account',
		name: 'getContactFields',
		method: 'GET',
		path: '/api/account/contactFields',
		description:
			'Tool to retrieve account contact fields filtered by type. Use when you need to get contact field definitions from the ActiveTrail account.',
		pathParams: [],
		queryParams: ['FieldsType'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getContactGroups',
		group: 'contacts',
		name: 'getContactGroups',
		method: 'GET',
		path: '/api/contacts/{id}/groups',
		description:
			"Tool to retrieve all groups associated with a specific contact. Returns group details including group ID, name, member counts, and creation dates. Use when you need to list a contact's group memberships by contact ID.",
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getContactList',
		group: 'contacts',
		name: 'getContactList',
		method: 'GET',
		path: '/api/contacts',
		description:
			'Tool to retrieve account contacts filtered by status and date range. Use when you need to get a list of contacts filtered by customer status (active, unsubscribed, bounced, etc.) or by registration date. Default behavior: retrieves contacts modified within the last three months with a limit of 100 contacts per page.',
		pathParams: [],
		queryParams: [
			'CustomerStates',
			'SearchTerm',
			'FromDate',
			'ToDate',
			'Page',
			'Limit',
		],
		riskLevel: 'read' as const,
	},
	{
		key: 'getContactsErrors',
		group: 'contacts',
		name: 'getContactsErrors',
		method: 'GET',
		path: '/api/contacts/{id}/errors',
		description:
			"Tool to retrieve bounce and error history for a specific contact. Use when you need to understand delivery issues or bounce patterns for a contact's email address.",
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getContactsMailinglists',
		group: 'contacts',
		name: 'getContactsMailinglists',
		method: 'GET',
		path: '/api/contacts/{id}/mailinglists',
		description:
			"Tool to retrieve all mailing lists associated with a specific contact. Use when you need to list a contact's mailing list memberships by contact ID.",
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getContactsMerges',
		group: 'contacts',
		name: 'getContactsMerges',
		method: 'GET',
		path: '/api/contacts/merges',
		description:
			'Tool to retrieve contacts experiencing merge conflicts with filtering options. Use when you need to get the list of contacts with merge conflicts, filtered by status, date range, or limited to a specific number of conflicts.',
		pathParams: [],
		queryParams: ['StateType', 'FromDate', 'ToDate', 'Page', 'Limit'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getContactSmsStatistics',
		group: 'contacts',
		name: 'getContactSmsStatistics',
		method: 'GET',
		path: '/api/contacts/{id}/Statistics/SmsOperationMessage/{messageId}',
		description:
			'Tool to retrieve contact interaction statistics for a specific transactional SMS. Use when you need to see how a contact interacted with a transactional/operational SMS including delivery status, bounce information, and unsubscribe actions.',
		pathParams: ['contact_id', 'message_id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getContactsStatisticsCampaign',
		group: 'contacts',
		name: 'getContactsStatisticsCampaign',
		method: 'GET',
		path: '/api/contacts/{id}/Statistics/Campaign/{campaignId}',
		description:
			"Tool to retrieve contact's interaction statistics for a specific campaign. Use when you need to see how a specific contact engaged with a campaign including opens, clicks, bounces, unsubscribes, and spam complaints.",
		pathParams: ['id', 'campaign_id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getContactsSubscriptionAllContacts',
		group: 'contacts',
		name: 'getContactsSubscriptionAllContacts',
		method: 'GET',
		path: '/api/contacts/Subscription/AllContacts',
		description:
			"Tool to get contacts' subscription status and the source of their status (if known). Use when you need to retrieve all contacts with their subscription status information filtered by creation date. Defaults to three months back if date range is not specified.",
		pathParams: [],
		queryParams: ['FromDate', 'ToDate', 'Page', 'Limit'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getContactsSubscriptionCustomersStatus',
		group: 'contacts',
		name: 'getContactsSubscriptionCustomersStatus',
		method: 'GET',
		path: '/api/contacts/Subscription/CustomersStatus',
		description:
			'Get daily breakdown of contact status statistics over a date range. Returns counts of active, unsubscribed, bounced, quarantined, spam complaints, inactive, and user-requested removal contacts for each day in the specified period. Defaults to recent days when no date range is provided.',
		pathParams: [],
		queryParams: ['FromDate', 'ToDate', 'Page', 'Limit'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getContactsSubscriptionSubscribers',
		group: 'contacts',
		name: 'getContactsSubscriptionSubscribers',
		method: 'GET',
		path: '/api/contacts/Subscription/Subscribers',
		description:
			'Tool to retrieve all contacts who subscribed and the source of their subscription status. Use when you need to get a comprehensive list of subscribers. The search defaults to 3 months back if date range is not specified.',
		pathParams: [],
		queryParams: ['FromDate', 'ToDate', 'Page', 'Limit'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getContactsSubscriptionUnsubscribers',
		group: 'contacts',
		name: 'getContactsSubscriptionUnsubscribers',
		method: 'GET',
		path: '/api/contacts/Subscription/Unsubscribers',
		description:
			'Tool to retrieve all contacts who unsubscribed and the source of their unsubscription status. Use when you need to get a comprehensive list of unsubscribers. The search defaults to 3 months back if date range is not specified.',
		pathParams: [],
		queryParams: ['FromDate', 'ToDate', 'Page', 'Limit'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getContactsUnsubscribersSms',
		group: 'contacts',
		name: 'getContactsUnsubscribersSms',
		method: 'GET',
		path: '/api/contacts/unsubscribers/sms',
		description:
			'Tool to retrieve all contacts who unsubscribed from receiving SMS messages. Use when you need to get a list of SMS unsubscribers with optional filtering by date range and pagination support.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getContactsWithSmsState',
		group: 'contacts',
		name: 'getContactsWithSmsState',
		method: 'GET',
		path: '/api/contacts/GetWithSmsState',
		description:
			"Tool to retrieve account's contacts list with SMS subscription state. Use when you need to get contacts filtered by customer status (active, unsubscribed, bounced, etc.) and by state change date range, with default filtering to three months back.",
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getContentCategories',
		group: 'account',
		name: 'getContentCategories',
		method: 'GET',
		path: '/api/account/contentCategories',
		description:
			'Tool to retrieve all content categories from the ActiveTrail account. Use when you need to get the list of categories used for organizing campaigns and templates. #### Output | Parameter | Type | Required | Description | |-----------|------|----------|-------------| | `data` | string | Yes | Data from the action execution | | `error` | string | No | Error if any occurred during the execution of the action | | `successful` | boolean | Yes | Whether or not the action execution was successful or not |',
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getCustomerStatsForTransactionalMessage',
		group: 'contacts',
		name: 'getCustomerStatsForTransactionalMessage',
		method: 'GET',
		path: '/api/contacts/{id}/Statistics/OperationMessage/{messageId}',
		description:
			'Tool to retrieve customer interaction statistics for a specific transactional message. Use when you need to see how a contact engaged with a transactional/operational message including delivery status, opens, clicks, and other interaction metrics.',
		pathParams: ['contact_id', 'transactional_id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getExecutiveReport',
		group: 'account',
		name: 'getExecutiveReport',
		method: 'GET',
		path: '/api/account/executivereport',
		description:
			'Retrieve executive performance report for the ActiveTrail account, providing email marketing metrics over the past 12 months. Returns monthly statistics including emails sent, bounce rates, open rates, click rates, click-to-open rates, complaint rates, and unsubscribe rates for both marketing campaigns and transactional emails. Use this to analyze overall account performance trends and generate summary statistics. #### Output | Parameter | Type | Required | Description | |-----------|------|----------|-------------| | `data` | string | Yes | Data from the action execution | | `error` | string | No | Error if any occurred during the execution of the action | | `successful` | boolean | Yes | Whether or not the action execution was successful or not |',
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getExternalSchema',
		group: 'external',
		name: 'getExternalSchema',
		method: 'GET',
		path: '/api/external/schema',
		description:
			'Tool to retrieve contact field schema information for the account. Use when you need to get the structure and metadata of all available contact fields. #### Output | Parameter | Type | Required | Description | |-----------|------|----------|-------------| | `data` | string | Yes | Data from the action execution | | `error` | string | No | Error if any occurred during the execution of the action | | `successful` | boolean | Yes | Whether or not the action execution was successful or not |',
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getGroup',
		group: 'groups',
		name: 'getGroup',
		method: 'GET',
		path: '/api/groups/{id}',
		description:
			'Tool to retrieve detailed information about a specific group by its unique identifier. Use when you need to fetch group details including name, contact counters, and timestamps.',
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getGroupContentsById',
		group: 'groups',
		name: 'getGroupContentsById',
		method: 'GET',
		path: '/api/groups/{id}/members',
		description:
			'Tool to retrieve all group members by group ID with pagination and filtering. Use when you need to get complete information about contacts in a specific group. Returns up to 100 contacts per page with optional filtering by status and date range.',
		pathParams: ['group_id'],
		queryParams: [
			'CustomerStates',
			'SearchTerm',
			'FromDate',
			'ToDate',
			'Page',
			'Limit',
		],
		riskLevel: 'read' as const,
	},
	{
		key: 'getGroupsEvents',
		group: 'groups',
		name: 'getGroupsEvents',
		method: 'GET',
		path: '/api/groups/{id}/events',
		description:
			'Tool to retrieve all events for a specific group with optional filtering by event type, event date, and subscriber creation date. Use when you need to analyze group engagement metrics like opens, clicks, and unsubscribes. Default date range is 3 months back if not specified.',
		pathParams: ['id'],
		queryParams: [
			'EventType',
			'CreatedFromDate',
			'CreatedToDate',
			'EventFromDate',
			'EventToDate',
		],
		riskLevel: 'read' as const,
	},
	{
		key: 'getLandingPages',
		group: 'landingpage',
		name: 'getLandingPages',
		method: 'GET',
		path: '/api/landingpage',
		description:
			'Tool to retrieve landing pages from the ActiveTrail account with pagination support. Use when you need to get all landing pages or fetch paginated results.',
		pathParams: [],
		queryParams: ['Page', 'Limit'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getMailingList',
		group: 'mailingList',
		name: 'getMailingList',
		method: 'GET',
		path: '/api/mailinglist/{id}',
		description:
			'Tool to retrieve basic information about a specific mailing list by its unique identifier. Returns the mailing list ID and name. Use when you need to verify a mailing list exists or get its name by ID.',
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getMailingListMembers',
		group: 'mailingList',
		name: 'getMailingListMembers',
		method: 'GET',
		path: '/api/mailinglist/{id}/members',
		description:
			'Tool to retrieve all members belonging to a specific mailing list. Use when you need to get contacts from a mailing list, with optional filtering by contact status and state change date range.',
		pathParams: ['id'],
		queryParams: ['CustomerStates', 'FromDate', 'ToDate', 'Page', 'Limit'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getMailingLists',
		group: 'mailingList',
		name: 'getMailingLists',
		method: 'GET',
		path: '/api/mailinglist',
		description:
			'Tool to retrieve all mailing lists from the ActiveTrail account. Use when you need to get the list of mailing lists associated with the account. #### Output | Parameter | Type | Required | Description | |-----------|------|----------|-------------| | `data` | string | Yes | Data from the action execution | | `error` | string | No | Error if any occurred during the execution of the action | | `successful` | boolean | Yes | Whether or not the action execution was successful or not |',
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getOrder',
		group: 'commerce',
		name: 'getOrder',
		method: 'GET',
		path: '/api/commerce/Order/{orderId}',
		description:
			'Tool to retrieve complete details of a specific order from ActiveTrail commerce system. Use when you need to fetch order information including customer details, financial data, products, and shipping information.',
		pathParams: ['order_id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getPushCampaignOpens',
		group: 'smsCampaign',
		name: 'getPushCampaignOpens',
		method: 'GET',
		path: '/api/Pushcampaignreport/{id}/Opens',
		description:
			'Retrieves a list of contacts who opened a specific push notification campaign, including contact details and when they opened the notification. Use this action to: - Track engagement metrics for push campaigns - Identify which recipients interacted with your push notifications - Filter opens by date range, send type, or search for specific contacts Note: The campaign must have been sent within the date range (defaults to last 3 months from current date if not specified). Results are paginated for campaigns with many opens.',
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getPushCampaignReportDelivered',
		group: 'pushCampaignReport',
		name: 'getPushCampaignReportDelivered',
		method: 'GET',
		path: '/api/Pushcampaignreport/{id}/Delivered',
		description:
			'Tool to retrieve contacts who successfully received a specific push notification campaign. Use when you need to identify which recipients had the push campaign delivered to their devices. The campaign must have been sent within the specified date range (defaults to last 3 months); if not sent during these dates, an empty list is returned.',
		pathParams: ['id'],
		queryParams: [
			'SendType',
			'SearchTerm',
			'FromDate',
			'ToDate',
			'Page',
			'Limit',
		],
		riskLevel: 'read' as const,
	},
	{
		key: 'getPushCampaignReportFailed',
		group: 'pushCampaignReport',
		name: 'getPushCampaignReportFailed',
		method: 'GET',
		path: '/api/Pushcampaignreport/{id}/Failed',
		description:
			'Tool to retrieve the failed delivery report for a specific push campaign. Use when you need to see which contacts experienced delivery failures and why. The campaign must be sent in the specified date range (defaults to last 3 months).',
		pathParams: ['id'],
		queryParams: [
			'SendType',
			'SearchTerm',
			'FromDate',
			'ToDate',
			'Page',
			'Limit',
		],
		riskLevel: 'read' as const,
	},
	{
		key: 'getPushCampaignReports',
		group: 'campaignReports',
		name: 'getPushCampaignReports',
		method: 'GET',
		path: '/api/Pushcampaignreport',
		description:
			'Retrieves push notification campaign performance metrics and reports filtered by date range, send type, or search term. Returns analytics including sent count, delivered count, opened count, clicked count, open rate, click rate, and delivery status for each campaign. Default behavior: Returns the last 20 campaigns from the last 3 months when no parameters are specified.',
		pathParams: [],
		queryParams: ['Page', 'Limit'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getPushCampaignReportSent',
		group: 'pushCampaignReport',
		name: 'getPushCampaignReportSent',
		method: 'GET',
		path: '/api/Pushcampaignreport/{id}/Sent',
		description:
			'Tool to retrieve the list of contacts who were sent a specific push notification campaign, including contact details, device types, and sent timestamps. Use when you need to see the complete list of recipients for a push campaign with their delivery information. Supports filtering by date range (defaults to last 3 months), send type, and search terms. Returns paginated results with contact details for each recipient.',
		pathParams: ['id'],
		queryParams: [
			'SendType',
			'SearchTerm',
			'FromDate',
			'ToDate',
			'Page',
			'Limit',
		],
		riskLevel: 'read' as const,
	},
	{
		key: 'getPushCampaignReportSummary',
		group: 'smsCampaignReport',
		name: 'getPushCampaignReportSummary',
		method: 'GET',
		path: '/api/Pushcampaignreport/GetSummary',
		description:
			'Tool to retrieve aggregated summary statistics for push notification campaigns filtered by date range. Returns total counts across all campaigns including total sent, opens, clicks, clickers, unsubscribes, failed deliveries, and total devices. Use this when you need overall push campaign performance metrics rather than individual campaign details. Default behavior: Returns aggregate statistics for campaigns from the last 3 months when date parameters are not specified.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getPushCampaigns',
		group: 'campaigns',
		name: 'getPushCampaigns',
		method: 'GET',
		path: '/api/pushcampaign/Campaign',
		description:
			'Tool to retrieve push notification campaigns with optional filtering by date, campaign ID, and search criteria. Use when you need to get push campaigns filtered by date range (default is last 6 months and last 20 campaigns), or filtered by specific campaign ID or search term.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getSegmentationRuleFieldTypes',
		group: 'segmentation',
		name: 'getSegmentationRuleFieldTypes',
		method: 'GET',
		path: '/api/segmentation/ruleFieldTypes',
		description:
			'Retrieve a reference dictionary of all available field types that can be used in segmentation rules for ActiveTrail automation. Returns field type definitions including their identifiers, names, data types, and descriptions. This endpoint provides the foundational metadata needed to understand which contact fields (email, phone, custom fields, behavioral data, etc.) can be evaluated when constructing segmentation conditions in marketing automations. Use this when you need to discover what field types are available before building or validating segmentation rules. #### Output | Parameter | Type | Required | Description | |-----------|------|----------|-------------| | `data` | string | Yes | Data from the action execution | | `error` | string | No | Error if any occurred during the execution of the action | | `successful` | boolean | Yes | Whether or not the action execution was successful or not |',
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getSegmentationRuleOperations',
		group: 'segmentation',
		name: 'getSegmentationRuleOperations',
		method: 'GET',
		path: '/api/segmentation/ruleOperations',
		description:
			'Retrieves available rule operations for segmentation by field type. Returns operations categorized by field types (Info, Date, Action, Numeric, etc.) with their corresponding operation types (Is, IsNot, Contain, GreaterThan, etc.). Use this to understand which operations are valid when building segmentation rules based on field types. #### Output | Parameter | Type | Required | Description | |-----------|------|----------|-------------| | `data` | string | Yes | Data from the action execution | | `error` | string | No | Error if any occurred during the execution of the action | | `successful` | boolean | Yes | Whether or not the action execution was successful or not |',
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getSegmentationRuleTypes',
		group: 'segmentation',
		name: 'getSegmentationRuleTypes',
		method: 'GET',
		path: '/api/segmentation/ruleTypes',
		description:
			'Tool to retrieve available segmentation rule types for automation. Returns a list of rule type names that can be used when creating or editing automation segmentations. Use this to discover what types of rules are available (e.g., Info, Numeric, Date, Group, Action, Order-related, Cart, Catalog, etc.). #### Output | Parameter | Type | Required | Description | |-----------|------|----------|-------------| | `data` | string | Yes | Data from the action execution | | `error` | string | No | Error if any occurred during the execution of the action | | `successful` | boolean | Yes | Whether or not the action execution was successful or not |',
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getSegmentationRuleTypesMapping',
		group: 'segmentation',
		name: 'getSegmentationRuleTypesMapping',
		method: 'GET',
		path: '/api/segmentation/ruleTypesMapping',
		description:
			"Tool to retrieve the complete mapping of segmentation rule types with their associated field types and operations from ActiveTrail. Use this when building segmentation rules to understand which field types and operations are available for each rule type (e.g., Info rules support Email fields with 'Is' operation). #### Output | Parameter | Type | Required | Description | |-----------|------|----------|-------------| | `data` | string | Yes | Data from the action execution | | `error` | string | No | Error if any occurred during the execution of the action | | `successful` | boolean | Yes | Whether or not the action execution was successful or not |",
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getSegmentations',
		group: 'segmentation',
		name: 'getSegmentations',
		method: 'GET',
		path: '/api/segmentation',
		description:
			'Retrieve all contact segmentations from your ActiveTrail account. Segmentations are rule-based filters that define target audiences for campaigns and automations (e.g., contacts who opened specific campaigns, belong to certain groups, or match demographic criteria). Use this to list all configured segmentations and their IDs for use in campaign targeting or automation workflows. #### Output | Parameter | Type | Required | Description | |-----------|------|----------|-------------| | `data` | string | Yes | Data from the action execution | | `error` | string | No | Error if any occurred during the execution of the action | | `successful` | boolean | Yes | Whether or not the action execution was successful or not |',
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getSendingProfiles',
		group: 'external',
		name: 'getSendingProfiles',
		method: 'GET',
		path: '/api/account/sendingprofiles',
		description:
			'Tool to retrieve account email sending profiles. Use when you need to get sending profile configurations including sender names, email addresses, and reply-to settings. #### Output | Parameter | Type | Required | Description | |-----------|------|----------|-------------| | `data` | string | Yes | Data from the action execution | | `error` | string | No | Error if any occurred during the execution of the action | | `successful` | boolean | Yes | Whether or not the action execution was successful or not |',
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getSignupForms',
		group: 'signupForms',
		name: 'getSignupForms',
		method: 'GET',
		path: '/api/signupforms',
		description:
			'Tool to retrieve all signup forms from the ActiveTrail account. Use when you need to get the list of signup forms associated with the account. #### Output | Parameter | Type | Required | Description | |-----------|------|----------|-------------| | `data` | string | Yes | Data from the action execution | | `error` | string | No | Error if any occurred during the execution of the action | | `successful` | boolean | Yes | Whether or not the action execution was successful or not |',
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getSmartCodeSites',
		group: 'smartCodeSite',
		name: 'getSmartCodeSites',
		method: 'GET',
		path: '/api/smartcodesite',
		description:
			"Retrieves all Smart Code tracking sites configured in the ActiveTrail account. Smart Code is ActiveTrail's web analytics and visitor tracking solution. Use this action to list all registered websites with Smart Code tracking, including their IDs, names, and associated domains. #### Output | Parameter | Type | Required | Description | |-----------|------|----------|-------------| | `data` | string | Yes | Data from the action execution | | `error` | string | No | Error if any occurred during the execution of the action | | `successful` | boolean | Yes | Whether or not the action execution was successful or not |",
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getSmsCampaign',
		group: 'smsCampaign',
		name: 'getSmsCampaign',
		method: 'GET',
		path: '/api/smscampaign/Campaign/{id}',
		description:
			'Tool to retrieve detailed information about a specific SMS campaign by its unique identifier. Use when you need to fetch campaign details including message content, sender, status, and delivery metrics.',
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getSmsCampaignClickers',
		group: 'smsCampaign',
		name: 'getSmsCampaignClickers',
		method: 'GET',
		path: '/api/smscampaignreport/{id}/Clickers',
		description:
			'Retrieve contacts who clicked links in an SMS campaign with detailed click analytics. Returns contact information (name, email, phone), click timestamps, link details, and click counts. Supports filtering by specific links, date ranges, and contact search. Note: If the SMS was sent using "add numbers manually" instead of groups/mailing lists, you\'ll receive click counts but mobile numbers may not be available. Default search window is 3 months from today.',
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getSmsCampaignDelivered',
		group: 'smsCampaignReport',
		name: 'getSmsCampaignDelivered',
		method: 'GET',
		path: '/api/smscampaignreport/{id}/Delivered',
		description:
			'Tool to retrieve delivery confirmations for a specific SMS campaign. Use when you need to see which contacts successfully received the SMS message. The campaign must be sent in the specified date range (defaults to last 3 months). Note: If SMS was sent using manual number entry instead of a group, only the delivery count is returned without specific mobile numbers.',
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getSmsCampaignEstimate',
		group: 'smsCampaign',
		name: 'getSmsCampaignEstimate',
		method: 'GET',
		path: '/api/smscampaign/Campaign/{id}/estimate',
		description:
			'Tool to calculate the estimated number of messages for a given SMS campaign. Use when you need to get message count estimates for campaigns that have not been sent yet. Cannot be used for already-sent campaigns.',
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getSmsCampaignReport',
		group: 'smsCampaignReport',
		name: 'getSmsCampaignReport',
		method: 'GET',
		path: '/api/smscampaignreport/{id}',
		description:
			"Tool to retrieve summary report for a specific SMS campaign by ID. Use when you need detailed metrics about an SMS campaign's performance including sent count, delivery rate, clicks, and errors.",
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getSmsCampaignReportClicks',
		group: 'smsCampaignReport',
		name: 'getSmsCampaignReportClicks',
		method: 'GET',
		path: '/api/smscampaignreport/{id}/Clicks',
		description:
			"Tool to retrieve detailed click event data for links in SMS campaigns. Returns individual click records (not unique clickers) with contact information, timestamps, link details, and device/browser information. Use when you need granular click-level analytics for SMS campaign links. Note: By default, searches for clicks within the last 3 months. If the campaign wasn't sent in the specified date range, no data will be returned. If SMS recipients were added manually (not from a group), you may get click counts but not all contact details.",
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getSmsCampaignReportFailed',
		group: 'smsCampaignReport',
		name: 'getSmsCampaignReportFailed',
		method: 'GET',
		path: '/api/smscampaignreport/{id}/Failed',
		description:
			'Tool to retrieve the failed delivery report for a specific SMS campaign. Use when you need to see which contacts experienced delivery failures and why. The campaign must be sent in the specified date range (defaults to last 3 months). Note: If SMS was sent using manual number entry instead of a group, only the failure count is returned without specific mobile numbers.',
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getSmsCampaignReports',
		group: 'smsCampaign',
		name: 'getSmsCampaignReports',
		method: 'GET',
		path: '/api/smscampaignreport',
		description:
			'Tool to retrieve SMS campaign performance metrics and reports with filtering options. Use when you need to access SMS campaign analytics including sent, delivered, failed, clicks, and engagement statistics. Returns the last 20 campaigns from the last 6 months by default when no date range or filters are specified.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getSmsCampaignReportSent',
		group: 'smsCampaignReport',
		name: 'getSmsCampaignReportSent',
		method: 'GET',
		path: '/api/smscampaignreport/{id}/Sent',
		description:
			'Tool to retrieve all contacts that an SMS campaign was sent to. Use when you need to see the list of recipients for a specific SMS campaign. The campaign must be sent in the specified date range (defaults to last 3 months). Note: If SMS was sent using manual number entry instead of a group, only the contact count is returned without specific mobile numbers.',
		pathParams: ['id'],
		queryParams: [
			'SendType',
			'SearchTerm',
			'RowsAffected',
			'PreviousRowCount',
			'FromDate',
			'ToDate',
			'Page',
			'Limit',
		],
		riskLevel: 'read' as const,
	},
	{
		key: 'getSmsCampaignReportSummary',
		group: 'smsCampaignReport',
		name: 'getSmsCampaignReportSummary',
		method: 'GET',
		path: '/api/smscampaignreport/GetSummary',
		description:
			'Retrieve aggregate summary metrics for SMS campaigns across a filtered date range. Returns total counts for sent messages, failed deliveries, clicks, unique clicks, unsubscribes, and credits consumed. Use this to get high-level performance statistics across all SMS campaigns in a given period. Default behavior: Returns aggregate metrics for the last 3 months when date parameters are not specified.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getSmsCampaignReportUnsubscribed',
		group: 'smsCampaignReport',
		name: 'getSmsCampaignReportUnsubscribed',
		method: 'GET',
		path: '/api/smscampaignreport/{id}/Unsubscribed',
		description:
			"Tool to retrieve contacts who unsubscribed from a specific SMS campaign. Use when you need to identify recipients who opted out of receiving future SMS messages. Note: For manually added numbers, only the count is returned, not individual phone numbers. Default search range is last 3 months; if campaign wasn't sent in the given range, no information will be returned.",
		pathParams: ['id'],
		queryParams: [
			'SendType',
			'SearchTerm',
			'RowsAffected',
			'PreviousRowCount',
			'FromDate',
			'ToDate',
			'Page',
			'Limit',
		],
		riskLevel: 'read' as const,
	},
	{
		key: 'getSmsSendingProfiles',
		group: 'external',
		name: 'getSmsSendingProfiles',
		method: 'GET',
		path: '/api/account/sms-sendingprofiles',
		description:
			'Tool to retrieve SMS sending profiles configured for the account. Use when you need to get SMS sender profile configurations including sender names and phone numbers. #### Output | Parameter | Type | Required | Description | |-----------|------|----------|-------------| | `data` | string | Yes | Data from the action execution | | `error` | string | No | Error if any occurred during the execution of the action | | `successful` | boolean | Yes | Whether or not the action execution was successful or not |',
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getTemplate',
		group: 'campaigns',
		name: 'getTemplate',
		method: 'GET',
		path: '/api/templates/{id}',
		description:
			"Tool to retrieve detailed information about a specific template from the account's saved templates. Use when you need to fetch template details including name, subject, content, category, and encoding settings.",
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getTemplateContent',
		group: 'templates',
		name: 'getTemplateContent',
		method: 'GET',
		path: '/api/templates/{id}/content',
		description:
			'Tool to retrieve HTML content of a specific template. Use when you need to get the HTML markup or design content of a template by its ID.',
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getTemplates',
		group: 'templates',
		name: 'getTemplates',
		method: 'GET',
		path: '/api/templates',
		description:
			'Tool to retrieve saved templates from the ActiveTrail account. Use when you need to list all templates or search for templates by name. Supports pagination and filtering.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getTemplatesTemplateCategory',
		group: 'templates',
		name: 'getTemplatesTemplateCategory',
		method: 'GET',
		path: '/api/templates/TemplateCategory',
		description:
			"Tool to retrieve all template categories from 'my templates' section. Use when you need to get the list of categories for organizing email templates. #### Output | Parameter | Type | Required | Description | |-----------|------|----------|-------------| | `data` | string | Yes | Data from the action execution | | `error` | string | No | Error if any occurred during the execution of the action | | `successful` | boolean | Yes | Whether or not the action execution was successful or not |",
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getTransactionalMessagesClassification',
		group: 'operationalMessage',
		name: 'getTransactionalMessagesClassification',
		method: 'GET',
		path: '/api/OperationalMessage/Classification',
		description:
			'Tool to retrieve all classification options for operational/transactional messages. Use when you need to get available classifications for categorizing and filtering transactional message reports. #### Output | Parameter | Type | Required | Description | |-----------|------|----------|-------------| | `data` | string | Yes | Data from the action execution | | `error` | string | No | Error if any occurred during the execution of the action | | `successful` | boolean | Yes | Whether or not the action execution was successful or not |',
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getTransactionalSmsMessage',
		group: 'smsCampaign',
		name: 'getTransactionalSmsMessage',
		method: 'GET',
		path: '/api/smscampaign/OperationalMessage/{id}',
		description:
			'Tool to retrieve detailed information about a specific transactional SMS message by its unique identifier. Use when you need to fetch SMS message content, delivery statistics, and metadata for operational SMS messages.',
		pathParams: ['transactional_sms_id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getTwoWaySmsReplies',
		group: 'account',
		name: 'getTwoWaySmsReplies',
		method: 'GET',
		path: '/api/2waysms/getreplies',
		description:
			'Tool to retrieve virtual number SMS replies with filtering options. Use when you need to fetch two-way SMS responses for campaigns with optional filtering by search term, campaign ID, or date range.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getUpdateActions',
		group: 'automations',
		name: 'getUpdateActions',
		method: 'GET',
		path: '/api/automations/GetUpdateActions',
		description:
			'Retrieves all available update action types that can be applied to contacts within automation workflows. Each action type includes its ID, name, description, type category, and required parameters. Use this to discover what contact update operations are available when building or modifying automation workflows (e.g., updating contact fields, changing status, adding tags, etc.). #### Output | Parameter | Type | Required | Description | |-----------|------|----------|-------------| | `data` | string | Yes | Data from the action execution | | `error` | string | No | Error if any occurred during the execution of the action | | `successful` | boolean | Yes | Whether or not the action execution was successful or not |',
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getUserSocialAccountsGet',
		group: 'userSocial',
		name: 'getUserSocialAccountsGet',
		method: 'GET',
		path: '/api/user-social/accounts/get',
		description:
			'Retrieve social media accounts (Facebook, Instagram, etc.) connected to the ActiveTrail account. Returns a list of connected social media accounts with details like platform, username, status, and connection date. Note: Social media integration is only available for ActiveTrail Plus plan customers. #### Output | Parameter | Type | Required | Description | |-----------|------|----------|-------------| | `data` | string | Yes | Data from the action execution | | `error` | string | No | Error if any occurred during the execution of the action | | `successful` | boolean | Yes | Whether or not the action execution was successful or not |',
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getWebhook',
		group: 'webhooks',
		name: 'getWebhook',
		method: 'GET',
		path: '/api/webhooks/{id}',
		description:
			'Tool to retrieve detailed information about a specific webhook by its unique identifier. Use when you need to fetch complete webhook configuration including event type, target URL, state, and associated parameters.',
		pathParams: ['webhook_id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getWebhooks',
		group: 'webhooks',
		name: 'getWebhooks',
		method: 'GET',
		path: '/api/webhooks',
		description:
			'Tool to list account webhooks with optional filtering. Use when you need to retrieve webhooks configured for the ActiveTrail account with filtering by event type, state, or target type.',
		pathParams: [],
		queryParams: ['EventType', 'StateType', 'TargetType', 'IsIgnoreParameters'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getWebhooksParameters',
		group: 'webhooks',
		name: 'getWebhooksParameters',
		method: 'GET',
		path: '/api/webhooks/{id}/parameters',
		description:
			'Retrieves custom parameters configured for a specific webhook. Parameters define additional data (headers, query parameters, or body fields) that ActiveTrail includes when calling the webhook URL. Use this to inspect webhook configuration details including parameter keys, values, types, and dynamic field mappings.',
		pathParams: ['webhook_id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'importNewContacts',
		group: 'contacts',
		name: 'importNewContacts',
		method: 'POST',
		path: '/api/contacts/Import',
		description:
			'Tool to import new contacts into a group in ActiveTrail. Use when you need to bulk import contacts with customer information (limited to 1000 contacts per call). Returns success count and any errors for failed contact imports.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'listSmsCampaigns',
		group: 'campaigns',
		name: 'listSmsCampaigns',
		method: 'GET',
		path: '/api/smscampaign/Campaign',
		description:
			'Tool to retrieve SMS campaigns with optional filtering by date, search term, and type. Use when you need to get SMS campaigns filtered by date range (default is last 3 months) or other criteria. Returns up to 20 campaigns per page by default.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'listTransactionalSmsMessages',
		group: 'contacts',
		name: 'listTransactionalSmsMessages',
		method: 'GET',
		path: '/api/smscampaign/OperationalMessage',
		description:
			'Tool to retrieve all SMS transactional messages with pagination support. Use when you need to fetch the list of operational SMS campaigns configured in the account.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'postTemplatesCampaign',
		group: 'templates',
		name: 'postTemplatesCampaign',
		method: 'POST',
		path: '/api/templates/{Id}/campaign',
		description:
			"Creates a new email campaign from an existing template. The campaign will be created in draft status. Prerequisites: - A valid template ID (obtain from 'Get Templates' action) - A valid sending profile ID (obtain from 'Get Sending Profiles' action) Use this when you need to quickly create a campaign using a pre-designed template rather than building from scratch.",
		pathParams: ['Id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'postTemplatesTemplateCategory',
		group: 'templates',
		name: 'postTemplatesTemplateCategory',
		method: 'POST',
		path: '/api/templates/TemplateCategory',
		description:
			'Tool to create a new template category in ActiveTrail. Use when you need to add a new category for organizing email templates.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'postWebhooksParameters',
		group: 'webhooks',
		name: 'postWebhooksParameters',
		method: 'POST',
		path: '/api/webhooks/{id}/parameters',
		description:
			'Tool to add a new parameter to an existing webhook in your ActiveTrail account. Use when you need to configure additional parameters for webhook events, such as authentication headers, custom query parameters, or body fields. Each parameter can have either a static value or dynamically pull from contact fields.',
		pathParams: ['webhook_id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'postWebhooksTest2',
		group: 'webhooks',
		name: 'postWebhooksTest2',
		method: 'POST',
		path: '/api/webhooks/Test',
		description:
			'Tool to send a test webhook request with configurable URL and parameters. Use when you need to validate webhook configurations by sending a test request to a specified URL with custom event types, parameters, and target types.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'putAccountContentCategories',
		group: 'account',
		name: 'putAccountContentCategories',
		method: 'PUT',
		path: '/api/account/contentCategories/{id}',
		description:
			'Tool to update a specific content category by ID. Use when you need to modify the name or display order of a category in your ActiveTrail account.',
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'putCampaignsSegment',
		group: 'campaigns',
		name: 'putCampaignsSegment',
		method: 'PUT',
		path: '/api/campaigns/{id}/segment',
		description:
			'Tool to update campaign sending settings including groups and sending restrictions. Use when you need to modify which groups receive a campaign. Note: Only campaigns in draft mode can be updated.',
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'removeAContactFromAMailingList',
		group: 'mailingList',
		name: 'removeAContactFromAMailingList',
		method: 'DELETE',
		path: '/api/mailinglist/{mailinglist_id}/members/{contact_id}',
		description:
			"Removes a specific contact from a mailing list in ActiveTrail. Use this action to unsubscribe or remove a contact from a particular mailing list without deleting the contact from your account entirely. The contact will no longer receive campaigns sent to this specific mailing list, but will remain in other lists they belong to. Note: This is a destructive operation that cannot be undone via API. To re-add the contact to the list, use the 'Import New Contacts' action.",
		pathParams: ['mailinglist_id', 'contact_id'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'removeExternalContactFromGroup',
		group: 'external',
		name: 'removeExternalContactFromGroup',
		method: 'DELETE',
		path: '/api/external/group/{groupId}',
		description:
			'Tool to remove contacts from a group via external ID. Use when you need to delete external contacts from a specific group in ActiveTrail. Limited to 1000 contacts per call.',
		pathParams: ['group_id'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'sendOperationalMessage',
		group: 'external',
		name: 'sendOperationalMessage',
		method: 'POST',
		path: '/api/external/operational/message',
		description:
			"Create and send a new operational message via the external API (limited to 500 messages per request). Recipients will be created as contacts if they don't already exist.",
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'sendOperationalMessageEmail',
		group: 'external',
		name: 'sendOperationalMessageEmail',
		method: 'POST',
		path: '/api/OperationalMessage/Message',
		description:
			'Send an email operational message to individual emails (limited to 500). Supports dynamic text replacement via email_package key-value pairs.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'testWebhook',
		group: 'webhooks',
		name: 'testWebhook',
		method: 'POST',
		path: '/api/webhooks/{id}/test',
		description:
			"Send a test request to a configured webhook to verify it's working correctly. This action triggers a test event for the specified webhook without waiting for actual events to occur. Use this to validate that the webhook URL is reachable, properly configured, and able to receive notifications from ActiveTrail. The webhook must already exist in your ActiveTrail account.",
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateCampaign',
		group: 'smsCampaign',
		name: 'updateCampaign',
		method: 'PUT',
		path: '/api/smscampaign/Campaign/{id}',
		description:
			'Tool to update draft campaigns in ActiveTrail. Use when you need to modify campaign properties such as name, subject, content, or design settings. IMPORTANT: Only campaigns in draft mode can be updated - campaigns that have been sent or are scheduled cannot be modified.',
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateCampaignDesign',
		group: 'campaigns',
		name: 'updateCampaignDesign',
		method: 'PUT',
		path: '/api/campaigns/{id}/design',
		description:
			"Tool to update the design and HTML content of an email campaign in ActiveTrail. Use when you need to modify a campaign's visual layout, HTML content, or encoding settings. Important: Only campaigns in draft mode can be updated through this endpoint.",
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateCampaignScheduling',
		group: 'campaigns',
		name: 'updateCampaignScheduling',
		method: 'PUT',
		path: '/api/campaigns/{id}/scheduling',
		description:
			'Tool to configure send schedule for draft campaigns. Use when you need to update the scheduling configuration of a campaign. Only campaigns in draft mode can be updated.',
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateCampaignSDetails',
		group: 'campaigns',
		name: 'updateCampaignSDetails',
		method: 'PUT',
		path: '/api/campaigns/{id}/details',
		description:
			"Updates an email campaign's core details including name, subject line, sender profile, category, and delivery settings. Important: Only campaigns in DRAFT status can be updated. Attempting to update sent or scheduled campaigns will fail. Use 'Get Campaign by ID' first to verify the campaign is in draft mode before updating.",
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateCampaignTemplate',
		group: 'campaigns',
		name: 'updateCampaignTemplate',
		method: 'PUT',
		path: '/api/campaigns/{id}/template',
		description:
			'Tool to update the template associated with an email campaign in ActiveTrail. Use when you need to assign or change a template for a campaign. Important: Only campaigns in draft mode can be updated through this endpoint.',
		pathParams: ['campaign_id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateContact',
		group: 'external',
		name: 'updateContact',
		method: 'PUT',
		path: '/api/external/contact/{externalId}',
		description:
			"Tool to update an existing contact's information by ID. Use when you need to modify contact details such as name, email, phone, address, or custom fields. Only the fields you include in the request will be updated; other fields remain unchanged.",
		pathParams: ['id'],
		queryParams: ['externalName'],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateGroup',
		group: 'groups',
		name: 'updateGroup',
		method: 'PUT',
		path: '/api/groups/{id}',
		description:
			"Updates an existing group in ActiveTrail by its ID. Primary use case: Rename a group by updating its name field. Important notes: - Only the 'name' field is reliably updateable via this endpoint - The API typically returns HTTP 204 (No Content) on success - Group must exist or will return 404 error Use 'Get All Groups' or 'Get Group by ID' actions to find the group ID first.",
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateOrder',
		group: 'commerce',
		name: 'updateOrder',
		method: 'PUT',
		path: '/api/commerce/Order/{orderId}',
		description:
			'Updates an existing order in the ActiveTrail commerce system. Use this action to modify order details including customer information (name, email, phone), shipping address, order status, pricing (amounts, tax, currency), or product items. You must provide the existing order_id - this action cannot create new orders. Common use cases: - Update order status (e.g., from "pending" to "shipped") - Modify customer contact information - Adjust pricing or add/remove items - Update shipping addresses - Change order metadata (dates, custom fields)',
		pathParams: ['order_id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateSegmentation',
		group: 'segmentation',
		name: 'updateSegmentation',
		method: 'PUT',
		path: '/api/segmentation/{id}',
		description:
			"Tool to update an existing segmentation's name and/or rules by its ID. Use when you need to modify segmentation criteria or rename a segment. Segmentations are rule-based filters that define target audiences based on contact attributes, behaviors, or campaign interactions.",
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateSmartCodeSite',
		group: 'smartCodeSite',
		name: 'updateSmartCodeSite',
		method: 'PUT',
		path: '/api/smartcodesite/{id}',
		description:
			"Updates an existing Smart Code tracking site in ActiveTrail. Use this action to modify a site's name and domain configuration. Both name and domains must be provided in the update request (the API does not support partial updates).",
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateSmsOperationalMessage',
		group: 'smsCampaign',
		name: 'updateSmsOperationalMessage',
		method: 'PUT',
		path: '/api/smscampaign/OperationalMessage/{id}',
		description:
			'Tool to update an operational SMS transactional message by ID. Use when you need to modify the name, sender, or content of an existing SMS campaign. Important: You cannot update a campaign that has already been sent.',
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateTemplate',
		group: 'templates',
		name: 'updateTemplate',
		method: 'PUT',
		path: '/api/templates/{id}',
		description:
			"Tool to update an existing email template in ActiveTrail account. Use this action to modify template properties including: - Template name and subject line - HTML content/body - Editor type and display settings - Template categorization - Character encoding settings All fields except 'id' are optional - only provide the fields you want to update. The template will be updated with the new values while preserving any fields not specified. Note: To update only the HTML content of a template, consider using the 'Update Template Content' action instead.",
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateTemplateCategory',
		group: 'templates',
		name: 'updateTemplateCategory',
		method: 'PUT',
		path: '/api/templates/TemplateCategory/{id}',
		description:
			'Tool to update an existing template category in ActiveTrail. Use when you need to modify the name of a template category used for organizing email templates.',
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateTemplateContent',
		group: 'templates',
		name: 'updateTemplateContent',
		method: 'PUT',
		path: '/api/templates/{Id}/content',
		description:
			'Tool to update the HTML content of an email template in ActiveTrail. Use when you need to modify the design or layout of an existing template.',
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateWebhook',
		group: 'webhooks',
		name: 'updateWebhook',
		method: 'PUT',
		path: '/api/webhooks/{id}',
		description:
			'Tool to update an existing webhook configuration in ActiveTrail. Use when you need to modify webhook properties such as name, URL, event type, format, or active status.',
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateWebhookParameter',
		group: 'webhooks',
		name: 'updateWebhookParameter',
		method: 'PUT',
		path: '/api/webhooks/{id}/parameters/{parameterid}',
		description:
			'Tool to update an existing webhook parameter in your ActiveTrail account. Use when you need to modify parameter properties such as key, value, type, or field mappings for webhook events.',
		pathParams: ['webhook_id', 'parameter_id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
] as const;

export type ActiveTrailRoutes = typeof activeTrailRoutes;
