import type { EndpointRiskLevel } from 'corsair/core';

export type SupabaseMethod =
	| 'GET'
	| 'POST'
	| 'PUT'
	| 'PATCH'
	| 'DELETE'
	| 'HEAD'
	| 'OPTIONS';

export type SupabaseOperationKind =
	| 'management'
	| 'project'
	| 'oauthAuthorizeUrl'
	| 'listTables'
	| 'getTableSchemas'
	| 'selectFromTable';

export type SupabaseOperation = {
	key: string;
	group: string;
	name: string;
	method: SupabaseMethod;
	path: string;
	description: string;
	pathParams?: readonly string[];
	riskLevel: EndpointRiskLevel;
	irreversible?: boolean;
	kind?: SupabaseOperationKind;
	mediaType?: string;
	defaultQuery?: Record<string, unknown>;
};

export const supabaseOperations = [
	{
		key: 'activateVanitySubdomain',
		group: 'domains',
		name: 'activateVanitySubdomain',
		method: 'POST',
		path: '/v1/projects/{ref}/vanity-subdomain/activate',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Activate a vanity subdomain for a project',
	},
	{
		key: 'applyMigration',
		group: 'database',
		name: 'applyMigration',
		method: 'POST',
		path: '/v1/projects/{ref}/database/migrations',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Apply a database migration',
	},
	{
		key: 'authorizeUserThroughOauth',
		group: 'oauth',
		name: 'authorizeUserThroughOauth',
		method: 'GET',
		path: '/v1/oauth/authorize',
		kind: 'oauthAuthorizeUrl',
		riskLevel: 'read',
		description: 'Generate a Supabase OAuth authorization URL',
	},
	{
		key: 'activateCustomHostname',
		group: 'domains',
		name: 'activateCustomHostname',
		method: 'POST',
		path: '/v1/projects/{ref}/custom-hostname/activate',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Activate a configured custom hostname',
	},
	{
		key: 'getProjectCustomHostnameConfig',
		group: 'domains',
		name: 'getProjectCustomHostnameConfig',
		method: 'GET',
		path: '/v1/projects/{ref}/custom-hostname',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get a project custom hostname configuration',
	},
	{
		key: 'updateProjectNetworkRestrictions',
		group: 'projects',
		name: 'updateProjectNetworkRestrictions',
		method: 'POST',
		path: '/v1/projects/{ref}/network-restrictions/apply',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Apply project network restrictions',
	},
	{
		key: 'createBulkSecrets',
		group: 'secrets',
		name: 'createBulkSecrets',
		method: 'POST',
		path: '/v1/projects/{ref}/secrets',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Create multiple project secrets',
	},
	{
		key: 'deleteSecrets',
		group: 'secrets',
		name: 'deleteSecrets',
		method: 'DELETE',
		path: '/v1/projects/{ref}/secrets',
		pathParams: ['ref'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Delete multiple project secrets',
	},
	{
		key: 'updateFunctions',
		group: 'edgeFunctions',
		name: 'updateFunctions',
		method: 'PUT',
		path: '/v1/projects/{ref}/functions',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Bulk update Edge Functions',
	},
	{
		key: 'checkVanitySubdomainAvailability',
		group: 'domains',
		name: 'checkVanitySubdomainAvailability',
		method: 'POST',
		path: '/v1/projects/{ref}/vanity-subdomain/check-availability',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Check vanity subdomain availability',
	},
	{
		key: 'countActionRuns',
		group: 'environments',
		name: 'countActionRuns',
		method: 'HEAD',
		path: '/v1/projects/{ref}/actions',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Count action runs',
	},
	{
		key: 'createLoginRole',
		group: 'database',
		name: 'createLoginRole',
		method: 'POST',
		path: '/v1/projects/{ref}/cli/login-role',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Create a CLI login role',
	},
	{
		key: 'createSsoProvider',
		group: 'auth',
		name: 'createSsoProvider',
		method: 'POST',
		path: '/v1/projects/{ref}/config/auth/sso/providers',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Create an SSO provider',
	},
	{
		key: 'createDatabaseBranch',
		group: 'environments',
		name: 'createDatabaseBranch',
		method: 'POST',
		path: '/v1/projects/{ref}/branches',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Create a database branch',
	},
	{
		key: 'createFunction',
		group: 'edgeFunctions',
		name: 'createFunction',
		method: 'POST',
		path: '/v1/projects/{ref}/functions',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Create an Edge Function',
	},
	{
		key: 'createThirdPartyAuthIntegration',
		group: 'auth',
		name: 'createThirdPartyAuthIntegration',
		method: 'POST',
		path: '/v1/projects/{ref}/config/auth/third-party-auth',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Create a third-party auth integration',
	},
	{
		key: 'createOrganization',
		group: 'organizations',
		name: 'createOrganization',
		method: 'POST',
		path: '/v1/organizations',
		riskLevel: 'write',
		description: 'Create an organization',
	},
	{
		key: 'createProject',
		group: 'projects',
		name: 'createProject',
		method: 'POST',
		path: '/v1/projects',
		riskLevel: 'write',
		description: 'Create a project',
	},
	{
		key: 'createApiKey',
		group: 'secrets',
		name: 'createApiKey',
		method: 'POST',
		path: '/v1/projects/{ref}/api-keys',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Create a project API key',
	},
	{
		key: 'createProjectSigningKey',
		group: 'auth',
		name: 'createProjectSigningKey',
		method: 'POST',
		path: '/v1/projects/{ref}/config/auth/signing-keys',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Create a project signing key',
	},
	{
		key: 'deleteLoginRoles',
		group: 'database',
		name: 'deleteLoginRoles',
		method: 'DELETE',
		path: '/v1/projects/{ref}/cli/login-role',
		pathParams: ['ref'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Delete CLI login roles',
	},
	{
		key: 'deleteApiKey',
		group: 'secrets',
		name: 'deleteApiKey',
		method: 'DELETE',
		path: '/v1/projects/{ref}/api-keys/{id}',
		pathParams: ['ref', 'id'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Delete a project API key',
	},
	{
		key: 'deleteFunction',
		group: 'edgeFunctions',
		name: 'deleteFunction',
		method: 'DELETE',
		path: '/v1/projects/{ref}/functions/{functionSlug}',
		pathParams: ['ref', 'functionSlug'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Delete an Edge Function',
	},
	{
		key: 'deleteDatabaseBranch',
		group: 'environments',
		name: 'deleteDatabaseBranch',
		method: 'DELETE',
		path: '/v1/branches/{branchId}',
		pathParams: ['branchId'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Delete a database branch',
	},
	{
		key: 'deleteCustomHostnameConfig',
		group: 'domains',
		name: 'deleteCustomHostnameConfig',
		method: 'DELETE',
		path: '/v1/projects/{ref}/custom-hostname',
		pathParams: ['ref'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Delete custom hostname configuration',
	},
	{
		key: 'deleteProject',
		group: 'projects',
		name: 'deleteProject',
		method: 'DELETE',
		path: '/v1/projects/{ref}',
		pathParams: ['ref'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Delete a project',
	},
	{
		key: 'deleteThirdPartyAuthIntegration',
		group: 'auth',
		name: 'deleteThirdPartyAuthIntegration',
		method: 'DELETE',
		path: '/v1/projects/{ref}/config/auth/third-party-auth/{tpaId}',
		pathParams: ['ref', 'tpaId'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Delete a third-party auth integration',
	},
	{
		key: 'deleteProjectVanitySubdomain',
		group: 'domains',
		name: 'deleteProjectVanitySubdomain',
		method: 'DELETE',
		path: '/v1/projects/{ref}/vanity-subdomain',
		pathParams: ['ref'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Delete a project vanity subdomain',
	},
	{
		key: 'deployFunction',
		group: 'edgeFunctions',
		name: 'deployFunction',
		method: 'POST',
		path: '/v1/projects/{ref}/functions/deploy',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Deploy an Edge Function',
	},
	{
		key: 'disablePreviewBranching',
		group: 'environments',
		name: 'disablePreviewBranching',
		method: 'DELETE',
		path: '/v1/projects/{ref}/branches',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Disable preview branching',
	},
	{
		key: 'disableProjectReadonly',
		group: 'database',
		name: 'disableProjectReadonly',
		method: 'POST',
		path: '/v1/projects/{ref}/readonly/temporary-disable',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Temporarily disable project read-only mode',
	},
	{
		key: 'enableDatabaseWebhooks',
		group: 'database',
		name: 'enableDatabaseWebhooks',
		method: 'POST',
		path: '/v1/projects/{ref}/database/webhooks/enable',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Enable database webhooks',
	},
	{
		key: 'exchangeOauthToken',
		group: 'oauth',
		name: 'exchangeOauthToken',
		method: 'POST',
		path: '/v1/oauth/token',
		riskLevel: 'write',
		mediaType: 'application/x-www-form-urlencoded',
		description: 'Exchange an OAuth authorization code or refresh token',
	},
	{
		key: 'runSqlQuery',
		group: 'database',
		name: 'runSqlQuery',
		method: 'POST',
		path: '/v1/projects/{ref}/database/query',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Execute a project database query',
	},
	{
		key: 'runReadOnlyQuery',
		group: 'database',
		name: 'runReadOnlyQuery',
		method: 'POST',
		path: '/v1/projects/{ref}/database/query/read-only',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Execute a read-only database query',
	},
	{
		key: 'generateTypescriptTypes',
		group: 'database',
		name: 'generateTypescriptTypes',
		method: 'GET',
		path: '/v1/projects/{ref}/types/typescript',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Generate TypeScript database types',
	},
	{
		key: 'getHealth',
		group: 'projects',
		name: 'getHealth',
		method: 'GET',
		path: '/v1/projects/{ref}/health',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get project API health status',
	},
	{
		key: 'getAvailableRegions',
		group: 'projects',
		name: 'getAvailableRegions',
		method: 'GET',
		path: '/v1/projects/available-regions',
		riskLevel: 'read',
		description: 'Get available project regions',
	},
	{
		key: 'getDatabaseMetadata',
		group: 'database',
		name: 'getDatabaseMetadata',
		method: 'GET',
		path: '/v1/projects/{ref}/database/context',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get database metadata',
	},
	{
		key: 'getJitAccessConfig',
		group: 'database',
		name: 'getJitAccessConfig',
		method: 'GET',
		path: '/v1/projects/{ref}/jit-access',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get JIT access config',
	},
	{
		key: 'getProjectUpgradeEligibility',
		group: 'projects',
		name: 'getProjectUpgradeEligibility',
		method: 'GET',
		path: '/v1/projects/{ref}/upgrade/eligibility',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get project upgrade eligibility',
	},
	{
		key: 'getSecurityAdvisors',
		group: 'advisors',
		name: 'getSecurityAdvisors',
		method: 'GET',
		path: '/v1/projects/{ref}/advisors/security',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get security advisors',
	},
	{
		key: 'getResumableUploadBaseOptions',
		group: 'storage',
		name: 'getResumableUploadBaseOptions',
		method: 'OPTIONS',
		path: '/storage/v1/upload/resumable',
		kind: 'project',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get TUS resumable upload base options',
	},
	{
		key: 'getResumableUploadOptions',
		group: 'storage',
		name: 'getResumableUploadOptions',
		method: 'OPTIONS',
		path: '/storage/v1/upload/resumable/{uploadId}',
		kind: 'project',
		pathParams: ['ref', 'uploadId'],
		riskLevel: 'read',
		description: 'Get TUS resumable upload options',
	},
	{
		key: 'getTableSchemas',
		group: 'database',
		name: 'getTableSchemas',
		method: 'POST',
		path: '/v1/projects/{ref}/database/query/read-only',
		kind: 'getTableSchemas',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get database table schemas',
	},
	{
		key: 'getSsoProvider',
		group: 'auth',
		name: 'getSsoProvider',
		method: 'GET',
		path: '/v1/projects/{ref}/config/auth/sso/providers/{providerId}',
		pathParams: ['ref', 'providerId'],
		riskLevel: 'read',
		description: 'Get an SSO provider',
	},
	{
		key: 'getBranch',
		group: 'environments',
		name: 'getBranch',
		method: 'GET',
		path: '/v1/projects/{ref}/branches/{name}',
		pathParams: ['ref', 'name'],
		riskLevel: 'read',
		description: 'Get a database branch by name',
	},
	{
		key: 'getMigration',
		group: 'database',
		name: 'getMigration',
		method: 'GET',
		path: '/v1/projects/{ref}/database/migrations/{version}',
		pathParams: ['ref', 'version'],
		riskLevel: 'read',
		description: 'Get a migration',
	},
	{
		key: 'getSqlSnippet',
		group: 'database',
		name: 'getSqlSnippet',
		method: 'GET',
		path: '/v1/snippets/{id}',
		pathParams: ['id'],
		riskLevel: 'read',
		description: 'Get a SQL snippet',
	},
	{
		key: 'getThirdPartyIntegration',
		group: 'auth',
		name: 'getThirdPartyIntegration',
		method: 'GET',
		path: '/v1/projects/{ref}/config/auth/third-party-auth/{tpaId}',
		pathParams: ['ref', 'tpaId'],
		riskLevel: 'read',
		description: 'Get a third-party auth integration',
	},
	{
		key: 'getActionRunLogs',
		group: 'environments',
		name: 'getActionRunLogs',
		method: 'GET',
		path: '/v1/projects/{ref}/actions/{runId}/logs',
		pathParams: ['ref', 'runId'],
		riskLevel: 'read',
		description: 'Get action run logs',
	},
	{
		key: 'getActionRun',
		group: 'environments',
		name: 'getActionRun',
		method: 'GET',
		path: '/v1/projects/{ref}/actions/{runId}',
		pathParams: ['ref', 'runId'],
		riskLevel: 'read',
		description: 'Get action run status',
	},
	{
		key: 'getVanitySubdomainConfig',
		group: 'domains',
		name: 'getVanitySubdomainConfig',
		method: 'GET',
		path: '/v1/projects/{ref}/vanity-subdomain',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get current vanity subdomain config',
	},
	{
		key: 'getDatabaseBranchConfig',
		group: 'environments',
		name: 'getDatabaseBranchConfig',
		method: 'GET',
		path: '/v1/branches/{branchId}',
		pathParams: ['branchId'],
		riskLevel: 'read',
		description: 'Get database branch config',
	},
	{
		key: 'getOrganization',
		group: 'organizations',
		name: 'getOrganization',
		method: 'GET',
		path: '/v1/organizations/{slug}',
		pathParams: ['slug'],
		riskLevel: 'read',
		description: 'Get organization information',
	},
	{
		key: 'getLegacySigningKey',
		group: 'auth',
		name: 'getLegacySigningKey',
		method: 'GET',
		path: '/v1/projects/{ref}/config/auth/signing-keys/legacy',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get legacy signing key',
	},
	{
		key: 'getPerformanceAdvisors',
		group: 'advisors',
		name: 'getPerformanceAdvisors',
		method: 'GET',
		path: '/v1/projects/{ref}/advisors/performance',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get performance advisors',
	},
	{
		key: 'getProject',
		group: 'projects',
		name: 'getProject',
		method: 'GET',
		path: '/v1/projects/{ref}',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get a project',
	},
	{
		key: 'getProjectApiKey',
		group: 'secrets',
		name: 'getProjectApiKey',
		method: 'GET',
		path: '/v1/projects/{ref}/api-keys/{id}',
		pathParams: ['ref', 'id'],
		riskLevel: 'read',
		defaultQuery: { reveal: false },
		description: 'Get a project API key',
	},
	{
		key: 'getProjectApiKeys',
		group: 'secrets',
		name: 'getProjectApiKeys',
		method: 'GET',
		path: '/v1/projects/{ref}/api-keys',
		pathParams: ['ref'],
		riskLevel: 'read',
		defaultQuery: { reveal: false },
		description: 'Get project API keys',
	},
	{
		key: 'getProjectPgbouncerConfig',
		group: 'database',
		name: 'getProjectPgbouncerConfig',
		method: 'GET',
		path: '/v1/projects/{ref}/config/database/pgbouncer',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get project PgBouncer config',
	},
	{
		key: 'getProjectSslEnforcementConfig',
		group: 'database',
		name: 'getProjectSslEnforcementConfig',
		method: 'GET',
		path: '/v1/projects/{ref}/ssl-enforcement',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get project SSL enforcement config',
	},
	{
		key: 'getProjectSupavisorConfig',
		group: 'database',
		name: 'getProjectSupavisorConfig',
		method: 'GET',
		path: '/v1/projects/{ref}/config/database/pooler',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get project Supavisor config',
	},
	{
		key: 'getProjectLegacyApiKeys',
		group: 'secrets',
		name: 'getProjectLegacyApiKeys',
		method: 'GET',
		path: '/v1/projects/{ref}/api-keys/legacy',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get project legacy API keys status',
	},
	{
		key: 'getProjectLogs',
		group: 'analytics',
		name: 'getProjectLogs',
		method: 'GET',
		path: '/v1/projects/{ref}/analytics/endpoints/logs.all',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get project logs',
	},
	{
		key: 'getProjectNetworkRestrictions',
		group: 'projects',
		name: 'getProjectNetworkRestrictions',
		method: 'GET',
		path: '/v1/projects/{ref}/network-restrictions',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get project network restrictions',
	},
	{
		key: 'getProjectPgsodiumConfig',
		group: 'secrets',
		name: 'getProjectPgsodiumConfig',
		method: 'GET',
		path: '/v1/projects/{ref}/pgsodium',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get project pgsodium config',
	},
	{
		key: 'getProjectPostgresConfig',
		group: 'database',
		name: 'getProjectPostgresConfig',
		method: 'GET',
		path: '/v1/projects/{ref}/config/database/postgres',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get project postgres config',
	},
	{
		key: 'getProjectSigningKeys',
		group: 'auth',
		name: 'getProjectSigningKeys',
		method: 'GET',
		path: '/v1/projects/{ref}/config/auth/signing-keys',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get project signing keys',
	},
	{
		key: 'getProjectUpgradeStatus',
		group: 'projects',
		name: 'getProjectUpgradeStatus',
		method: 'GET',
		path: '/v1/projects/{ref}/upgrade/status',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get project upgrade status',
	},
	{
		key: 'getProjectPostgrestConfig',
		group: 'rest',
		name: 'getProjectPostgrestConfig',
		method: 'GET',
		path: '/v1/projects/{ref}/postgrest',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get project PostgREST config',
	},
	{
		key: 'getProjectAuthConfig',
		group: 'auth',
		name: 'getProjectAuthConfig',
		method: 'GET',
		path: '/v1/projects/{ref}/config/auth',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get project auth config',
	},
	{
		key: 'getProjectReadonlyModeStatus',
		group: 'database',
		name: 'getProjectReadonlyModeStatus',
		method: 'GET',
		path: '/v1/projects/{ref}/readonly',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get project read-only mode status',
	},
	{
		key: 'getProjectServiceHealthStatus',
		group: 'projects',
		name: 'getProjectServiceHealthStatus',
		method: 'GET',
		path: '/v1/projects/{ref}/health',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get project service health status',
	},
	{
		key: 'invokeEdgeFunction',
		group: 'edgeFunctions',
		name: 'invokeEdgeFunction',
		method: 'POST',
		path: '/functions/v1/{functionSlug}',
		kind: 'project',
		pathParams: ['ref', 'functionSlug'],
		riskLevel: 'write',
		description: 'Invoke an Edge Function',
	},
	{
		key: 'listTables',
		group: 'database',
		name: 'listTables',
		method: 'POST',
		path: '/v1/projects/{ref}/database/query/read-only',
		kind: 'listTables',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'List database tables',
	},
	{
		key: 'listSqlSnippets',
		group: 'database',
		name: 'listSqlSnippets',
		method: 'GET',
		path: '/v1/snippets',
		riskLevel: 'read',
		description: 'List SQL snippets',
	},
	{
		key: 'listSsoProviders',
		group: 'auth',
		name: 'listSsoProviders',
		method: 'GET',
		path: '/v1/projects/{ref}/config/auth/sso/providers',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'List SSO providers',
	},
	{
		key: 'listBuckets',
		group: 'storage',
		name: 'listBuckets',
		method: 'GET',
		path: '/v1/projects/{ref}/storage/buckets',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'List storage buckets',
	},
	{
		key: 'listDatabaseBranches',
		group: 'environments',
		name: 'listDatabaseBranches',
		method: 'GET',
		path: '/v1/projects/{ref}/branches',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'List database branches',
	},
	{
		key: 'listFunctions',
		group: 'edgeFunctions',
		name: 'listFunctions',
		method: 'GET',
		path: '/v1/projects/{ref}/functions',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'List Edge Functions',
	},
	{
		key: 'listAllOrganizations',
		group: 'organizations',
		name: 'listAllOrganizations',
		method: 'GET',
		path: '/v1/organizations',
		riskLevel: 'read',
		description: 'List organizations',
	},
	{
		key: 'listAllProjects',
		group: 'projects',
		name: 'listAllProjects',
		method: 'GET',
		path: '/v1/projects',
		riskLevel: 'read',
		description: 'List projects',
	},
	{
		key: 'listSecrets',
		group: 'secrets',
		name: 'listSecrets',
		method: 'GET',
		path: '/v1/projects/{ref}/secrets',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'List project secrets',
	},
	{
		key: 'listOrganizationMembers',
		group: 'organizations',
		name: 'listOrganizationMembers',
		method: 'GET',
		path: '/v1/organizations/{slug}/members',
		pathParams: ['slug'],
		riskLevel: 'read',
		description: 'List organization members',
	},
	{
		key: 'listMigrationHistory',
		group: 'database',
		name: 'listMigrationHistory',
		method: 'GET',
		path: '/v1/projects/{ref}/database/migrations',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'List migration history',
	},
	{
		key: 'listBackups',
		group: 'database',
		name: 'listBackups',
		method: 'GET',
		path: '/v1/projects/{ref}/database/backups',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'List project database backups',
	},
	{
		key: 'listThirdPartyAuthIntegrations',
		group: 'auth',
		name: 'listThirdPartyAuthIntegrations',
		method: 'GET',
		path: '/v1/projects/{ref}/config/auth/third-party-auth',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'List third-party auth integrations',
	},
	{
		key: 'handleResumableUploadSignOptionsWithId',
		group: 'storage',
		name: 'handleResumableUploadSignOptionsWithId',
		method: 'OPTIONS',
		path: '/storage/v1/upload/resumable/sign/{uploadId}',
		kind: 'project',
		pathParams: ['ref', 'uploadId'],
		riskLevel: 'read',
		description: 'Handle TUS resumable upload sign options with ID',
	},
	{
		key: 'handleResumableUploadSignOptions',
		group: 'storage',
		name: 'handleResumableUploadSignOptions',
		method: 'OPTIONS',
		path: '/storage/v1/upload/resumable/sign',
		kind: 'project',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Handle TUS resumable upload sign options',
	},
	{
		key: 'patchMigration',
		group: 'database',
		name: 'patchMigration',
		method: 'PATCH',
		path: '/v1/projects/{ref}/database/migrations/{version}',
		pathParams: ['ref', 'version'],
		riskLevel: 'write',
		description: 'Patch a migration',
	},
	{
		key: 'patchNetworkRestrictions',
		group: 'projects',
		name: 'patchNetworkRestrictions',
		method: 'PATCH',
		path: '/v1/projects/{ref}/network-restrictions',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Patch project network restrictions',
	},
	{
		key: 'pushBranch',
		group: 'environments',
		name: 'pushBranch',
		method: 'POST',
		path: '/v1/branches/{branchId}/push',
		pathParams: ['branchId'],
		riskLevel: 'write',
		description: 'Push a database branch',
	},
	{
		key: 'deleteSsoProvider',
		group: 'auth',
		name: 'deleteSsoProvider',
		method: 'DELETE',
		path: '/v1/projects/{ref}/config/auth/sso/providers/{providerId}',
		pathParams: ['ref', 'providerId'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Remove an SSO provider',
	},
	{
		key: 'removeNetworkBans',
		group: 'projects',
		name: 'removeNetworkBans',
		method: 'DELETE',
		path: '/v1/projects/{ref}/network-bans',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Remove project network bans',
	},
	{
		key: 'removeReadReplica',
		group: 'database',
		name: 'removeReadReplica',
		method: 'POST',
		path: '/v1/projects/{ref}/read-replicas/remove',
		pathParams: ['ref'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Remove a read replica',
	},
	{
		key: 'resetDatabaseBranch',
		group: 'environments',
		name: 'resetDatabaseBranch',
		method: 'POST',
		path: '/v1/branches/{branchId}/reset',
		pathParams: ['branchId'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Reset a database branch',
	},
	{
		key: 'restorePitrBackup',
		group: 'database',
		name: 'restorePitrBackup',
		method: 'POST',
		path: '/v1/projects/{ref}/database/backups/restore-pitr',
		pathParams: ['ref'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Restore database PITR backup',
	},
	{
		key: 'getFunction',
		group: 'edgeFunctions',
		name: 'getFunction',
		method: 'GET',
		path: '/v1/projects/{ref}/functions/{functionSlug}',
		pathParams: ['ref', 'functionSlug'],
		riskLevel: 'read',
		description: 'Retrieve an Edge Function',
	},
	{
		key: 'getFunctionBody',
		group: 'edgeFunctions',
		name: 'getFunctionBody',
		method: 'GET',
		path: '/v1/projects/{ref}/functions/{functionSlug}/body',
		pathParams: ['ref', 'functionSlug'],
		riskLevel: 'read',
		description: 'Retrieve an Edge Function body',
	},
	{
		key: 'getProjectNetworkBans',
		group: 'projects',
		name: 'getProjectNetworkBans',
		method: 'POST',
		path: '/v1/projects/{ref}/network-bans/retrieve',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Retrieve project network bans',
	},
	{
		key: 'verifyCustomHostnameDns',
		group: 'domains',
		name: 'verifyCustomHostnameDns',
		method: 'POST',
		path: '/v1/projects/{ref}/custom-hostname/reverify',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Reverify custom hostname DNS',
	},
	{
		key: 'selectFromTable',
		group: 'database',
		name: 'selectFromTable',
		method: 'POST',
		path: '/v1/projects/{ref}/database/query/read-only',
		kind: 'selectFromTable',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Select rows from a database table',
	},
	{
		key: 'createReadReplica',
		group: 'database',
		name: 'createReadReplica',
		method: 'POST',
		path: '/v1/projects/{ref}/read-replicas/setup',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Set up a read replica',
	},
	{
		key: 'updateJitAccessConfig',
		group: 'database',
		name: 'updateJitAccessConfig',
		method: 'PUT',
		path: '/v1/projects/{ref}/jit-access',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Update JIT access config',
	},
	{
		key: 'updateSslEnforcementConfig',
		group: 'database',
		name: 'updateSslEnforcementConfig',
		method: 'PUT',
		path: '/v1/projects/{ref}/ssl-enforcement',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Update SSL enforcement config',
	},
	{
		key: 'updateFunction',
		group: 'edgeFunctions',
		name: 'updateFunction',
		method: 'PATCH',
		path: '/v1/projects/{ref}/functions/{functionSlug}',
		pathParams: ['ref', 'functionSlug'],
		riskLevel: 'write',
		description: 'Update an Edge Function',
	},
	{
		key: 'updateProject',
		group: 'projects',
		name: 'updateProject',
		method: 'PATCH',
		path: '/v1/projects/{ref}',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Update a project',
	},
	{
		key: 'updateApiKey',
		group: 'secrets',
		name: 'updateApiKey',
		method: 'PATCH',
		path: '/v1/projects/{ref}/api-keys/{id}',
		pathParams: ['ref', 'id'],
		riskLevel: 'write',
		description: 'Update a project API key',
	},
	{
		key: 'updateSsoProvider',
		group: 'auth',
		name: 'updateSsoProvider',
		method: 'PUT',
		path: '/v1/projects/{ref}/config/auth/sso/providers/{providerId}',
		pathParams: ['ref', 'providerId'],
		riskLevel: 'write',
		description: 'Update an SSO provider',
	},
	{
		key: 'updateDatabaseBranchConfig',
		group: 'environments',
		name: 'updateDatabaseBranchConfig',
		method: 'PATCH',
		path: '/v1/branches/{branchId}',
		pathParams: ['branchId'],
		riskLevel: 'write',
		description: 'Update database branch config',
	},
	{
		key: 'updateDatabasePassword',
		group: 'database',
		name: 'updateDatabasePassword',
		method: 'PATCH',
		path: '/v1/projects/{ref}/database/password',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Update database password',
	},
	{
		key: 'updateProjectSupavisorConfig',
		group: 'database',
		name: 'updateProjectSupavisorConfig',
		method: 'PATCH',
		path: '/v1/projects/{ref}/config/database/pooler',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Update project Supavisor config',
	},
	{
		key: 'updatePgsodiumConfig',
		group: 'secrets',
		name: 'updatePgsodiumConfig',
		method: 'PUT',
		path: '/v1/projects/{ref}/pgsodium',
		pathParams: ['ref'],
		riskLevel: 'destructive',
		description: 'Update pgsodium root key',
	},
	{
		key: 'updateProjectLegacyApiKeys',
		group: 'secrets',
		name: 'updateProjectLegacyApiKeys',
		method: 'PUT',
		path: '/v1/projects/{ref}/api-keys/legacy',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Update project legacy API keys',
	},
	{
		key: 'updateProjectPostgrestConfig',
		group: 'rest',
		name: 'updateProjectPostgrestConfig',
		method: 'PATCH',
		path: '/v1/projects/{ref}/postgrest',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Update project PostgREST config',
	},
	{
		key: 'updateProjectAuthConfig',
		group: 'auth',
		name: 'updateProjectAuthConfig',
		method: 'PATCH',
		path: '/v1/projects/{ref}/config/auth',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Update project auth config',
	},
	{
		key: 'updateProjectCustomHostname',
		group: 'domains',
		name: 'updateProjectCustomHostname',
		method: 'POST',
		path: '/v1/projects/{ref}/custom-hostname/initialize',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Update project custom hostname',
	},
	{
		key: 'updateProjectPostgresConfig',
		group: 'database',
		name: 'updateProjectPostgresConfig',
		method: 'PUT',
		path: '/v1/projects/{ref}/config/database/postgres',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Update project postgres config',
	},
	{
		key: 'upgradeProjectPostgresVersion',
		group: 'projects',
		name: 'upgradeProjectPostgresVersion',
		method: 'POST',
		path: '/v1/projects/{ref}/upgrade',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Upgrade project PostgreSQL version',
	},
	{
		key: 'upsertMigration',
		group: 'database',
		name: 'upsertMigration',
		method: 'PUT',
		path: '/v1/projects/{ref}/database/migrations',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Upsert a migration',
	},
] as const satisfies readonly SupabaseOperation[];
