import type { NeonOperation } from '../endpoints/operation-types';

export const authOperations = [
	{
		key: 'getAuthDetails',
		group: 'auth',
		name: 'getAuthDetails',
		method: 'GET',
		path: '/auth',
		riskLevel: 'read',
		description: 'Retrieve details about the current API credentials',
	},
	{
		key: 'createNeonAuth',
		group: 'auth',
		name: 'createNeonAuth',
		method: 'POST',
		path: '/projects/{project_id}/branches/{branch_id}/auth',
		pathParams: ['project_id', 'branch_id'],
		riskLevel: 'write',
		description: 'Enable Neon Auth for the branch',
	},
	{
		key: 'disableNeonAuth',
		group: 'auth',
		name: 'disableNeonAuth',
		method: 'DELETE',
		path: '/projects/{project_id}/branches/{branch_id}/auth',
		pathParams: ['project_id', 'branch_id'],
		riskLevel: 'destructive',
		description: 'Disable Neon Auth for the branch',
	},
	{
		key: 'listBranchNeonAuthTrustedDomains',
		group: 'auth',
		name: 'listBranchNeonAuthTrustedDomains',
		method: 'GET',
		path: '/projects/{project_id}/branches/{branch_id}/auth/domains',
		pathParams: ['project_id', 'branch_id'],
		riskLevel: 'read',
		description: 'List domains in redirect_uri whitelist',
	},
	{
		key: 'deleteBranchNeonAuthTrustedDomain',
		group: 'auth',
		name: 'deleteBranchNeonAuthTrustedDomain',
		method: 'DELETE',
		path: '/projects/{project_id}/branches/{branch_id}/auth/domains',
		pathParams: ['project_id', 'branch_id'],
		riskLevel: 'destructive',
		description: 'Delete domain from redirect_uri whitelist',
	},
	{
		key: 'deleteNeonAuthDomainFromRedirectURIWhitelist',
		group: 'auth',
		name: 'deleteNeonAuthDomainFromRedirectURIWhitelist',
		method: 'DELETE',
		path: '/projects/{project_id}/auth/domains',
		pathParams: ['project_id'],
		riskLevel: 'destructive',
		description:
			'Delete trusted redirect URI domain (deprecated project-level route)',
	},
	{
		key: 'createNeonAuthProviderSDKKeys',
		group: 'auth',
		name: 'createNeonAuthProviderSDKKeys',
		method: 'POST',
		path: '/projects/auth/keys',
		riskLevel: 'write',
		description: 'Create Auth Provider SDK keys',
	},
	{
		key: 'createBranchNeonAuthNewUser',
		group: 'auth',
		name: 'createBranchNeonAuthNewUser',
		method: 'POST',
		path: '/projects/{project_id}/branches/{branch_id}/auth/users',
		pathParams: ['project_id', 'branch_id'],
		riskLevel: 'write',
		description: 'Create new auth user',
	},
	{
		key: 'deleteBranchNeonAuthUser',
		group: 'auth',
		name: 'deleteBranchNeonAuthUser',
		method: 'DELETE',
		path: '/projects/{project_id}/branches/{branch_id}/auth/users/{auth_user_id}',
		pathParams: ['project_id', 'branch_id', 'auth_user_id'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Delete auth user',
	},
	{
		key: 'listNeonAuthOauthProviders',
		group: 'auth',
		name: 'listNeonAuthOauthProviders',
		method: 'GET',
		path: '/projects/{project_id}/auth/oauth_providers',
		pathParams: ['project_id'],
		riskLevel: 'read',
		description: 'List OAuth providers (deprecated project-level route)',
	},
	{
		key: 'listBranchNeonAuthOauthProviders',
		group: 'auth',
		name: 'listBranchNeonAuthOauthProviders',
		method: 'GET',
		path: '/projects/{project_id}/branches/{branch_id}/auth/oauth_providers',
		pathParams: ['project_id', 'branch_id'],
		riskLevel: 'read',
		description: 'List OAuth providers for the branch',
	},
	{
		key: 'updateNeonAuthOauthProvider',
		group: 'auth',
		name: 'updateNeonAuthOauthProvider',
		method: 'PATCH',
		path: '/projects/{project_id}/auth/oauth_providers/{oauth_provider_id}',
		pathParams: ['project_id', 'oauth_provider_id'],
		riskLevel: 'write',
		description: 'Update OAuth provider (deprecated project-level route)',
	},
	{
		key: 'deleteBranchNeonAuthOauthProvider',
		group: 'auth',
		name: 'deleteBranchNeonAuthOauthProvider',
		method: 'DELETE',
		path: '/projects/{project_id}/branches/{branch_id}/auth/oauth_providers/{oauth_provider_id}',
		pathParams: ['project_id', 'branch_id', 'oauth_provider_id'],
		riskLevel: 'destructive',
		description: 'Delete OAuth provider',
	},
	{
		key: 'getNeonAuthEmailProvider',
		group: 'auth',
		name: 'getNeonAuthEmailProvider',
		method: 'GET',
		path: '/projects/{project_id}/branches/{branch_id}/auth/email_provider',
		pathParams: ['project_id', 'branch_id'],
		riskLevel: 'read',
		description: 'Retrieve email provider configuration',
	},
	{
		key: 'updateNeonAuthEmailProvider',
		group: 'auth',
		name: 'updateNeonAuthEmailProvider',
		method: 'PATCH',
		path: '/projects/{project_id}/branches/{branch_id}/auth/email_provider',
		pathParams: ['project_id', 'branch_id'],
		riskLevel: 'write',
		description: 'Update email provider configuration',
	},
	{
		key: 'sendNeonAuthTestEmail',
		group: 'auth',
		name: 'sendNeonAuthTestEmail',
		method: 'POST',
		path: '/projects/{project_id}/branches/{branch_id}/auth/send_test_email',
		pathParams: ['project_id', 'branch_id'],
		riskLevel: 'write',
		description: 'Send test email',
	},
	{
		key: 'getNeonAuthAllowLocalhost',
		group: 'auth',
		name: 'getNeonAuthAllowLocalhost',
		method: 'GET',
		path: '/projects/{project_id}/branches/{branch_id}/auth/allow_localhost',
		pathParams: ['project_id', 'branch_id'],
		riskLevel: 'read',
		description: 'Retrieve localhost allow setting',
	},
	{
		key: 'updateNeonAuthAllowLocalhost',
		group: 'auth',
		name: 'updateNeonAuthAllowLocalhost',
		method: 'PATCH',
		path: '/projects/{project_id}/branches/{branch_id}/auth/allow_localhost',
		pathParams: ['project_id', 'branch_id'],
		riskLevel: 'write',
		description: 'Update localhost allow setting',
	},
] as const satisfies readonly NeonOperation[];
