import type { NeonOperation } from '../endpoints/operation-types';

export const branchesOperations = [
	{
		key: 'createProjectBranch',
		group: 'branches',
		name: 'createProjectBranch',
		method: 'POST',
		path: '/projects/{project_id}/branches',
		pathParams: ['project_id'],
		riskLevel: 'write',
		description: 'Create branch',
	},
	{
		key: 'listProjectBranches',
		group: 'branches',
		name: 'listProjectBranches',
		method: 'GET',
		path: '/projects/{project_id}/branches',
		pathParams: ['project_id'],
		riskLevel: 'read',
		description: 'List branches',
	},
	{
		key: 'countProjectBranches',
		group: 'branches',
		name: 'countProjectBranches',
		method: 'GET',
		path: '/projects/{project_id}/branches/count',
		pathParams: ['project_id'],
		riskLevel: 'read',
		description: 'Retrieve number of branches',
	},
	{
		key: 'getProjectBranch',
		group: 'branches',
		name: 'getProjectBranch',
		method: 'GET',
		path: '/projects/{project_id}/branches/{branch_id}',
		pathParams: ['project_id', 'branch_id'],
		riskLevel: 'read',
		description: 'Retrieve branch details',
	},
	{
		key: 'updateProjectBranch',
		group: 'branches',
		name: 'updateProjectBranch',
		method: 'PATCH',
		path: '/projects/{project_id}/branches/{branch_id}',
		pathParams: ['project_id', 'branch_id'],
		riskLevel: 'write',
		description: 'Update branch',
	},
	{
		key: 'deleteProjectBranch',
		group: 'branches',
		name: 'deleteProjectBranch',
		method: 'DELETE',
		path: '/projects/{project_id}/branches/{branch_id}',
		pathParams: ['project_id', 'branch_id'],
		riskLevel: 'destructive',
		description: 'Delete branch',
	},
	{
		key: 'restoreProjectBranch',
		group: 'branches',
		name: 'restoreProjectBranch',
		method: 'POST',
		path: '/projects/{project_id}/branches/{branch_id}/restore',
		pathParams: ['project_id', 'branch_id'],
		riskLevel: 'write',
		description: 'Restore branch to a historical state',
	},
	{
		key: 'finalizeRestoreBranch',
		group: 'branches',
		name: 'finalizeRestoreBranch',
		method: 'POST',
		path: '/projects/{project_id}/branches/{branch_id}/finalize_restore',
		pathParams: ['project_id', 'branch_id'],
		riskLevel: 'write',
		description: 'Finalize branch restore from snapshot',
	},
	{
		key: 'setDefaultProjectBranch',
		group: 'branches',
		name: 'setDefaultProjectBranch',
		method: 'POST',
		path: '/projects/{project_id}/branches/{branch_id}/set_as_default',
		pathParams: ['project_id', 'branch_id'],
		riskLevel: 'write',
		description: 'Set branch as default',
	},
	{
		key: 'getProjectBranchSchema',
		group: 'branches',
		name: 'getProjectBranchSchema',
		method: 'GET',
		path: '/projects/{project_id}/branches/{branch_id}/schema',
		pathParams: ['project_id', 'branch_id'],
		riskLevel: 'read',
		description: 'Retrieve database schema',
	},
	{
		key: 'getProjectBranchSchemaComparison',
		group: 'branches',
		name: 'getProjectBranchSchemaComparison',
		method: 'GET',
		path: '/projects/{project_id}/branches/{branch_id}/compare_schema',
		pathParams: ['project_id', 'branch_id'],
		riskLevel: 'read',
		description: 'Compare database schema',
	},
	{
		key: 'createProjectBranchAnonymized',
		group: 'branches',
		name: 'createProjectBranchAnonymized',
		method: 'POST',
		path: '/projects/{project_id}/branch_anonymized',
		pathParams: ['project_id'],
		riskLevel: 'write',
		description: 'Create anonymized branch',
	},
	{
		key: 'getAnonymizedBranchStatus',
		group: 'branches',
		name: 'getAnonymizedBranchStatus',
		method: 'GET',
		path: '/projects/{project_id}/branches/{branch_id}/anonymized_status',
		pathParams: ['project_id', 'branch_id'],
		riskLevel: 'read',
		description: 'Retrieve anonymized branch status',
	},
	{
		key: 'startAnonymization',
		group: 'branches',
		name: 'startAnonymization',
		method: 'POST',
		path: '/projects/{project_id}/branches/{branch_id}/anonymize',
		pathParams: ['project_id', 'branch_id'],
		riskLevel: 'write',
		description: 'Start anonymization',
	},
	{
		key: 'getMaskingRules',
		group: 'branches',
		name: 'getMaskingRules',
		method: 'GET',
		path: '/projects/{project_id}/branches/{branch_id}/masking_rules',
		pathParams: ['project_id', 'branch_id'],
		riskLevel: 'read',
		description: 'Retrieve masking rules',
	},
	{
		key: 'updateMaskingRules',
		group: 'branches',
		name: 'updateMaskingRules',
		method: 'PATCH',
		path: '/projects/{project_id}/branches/{branch_id}/masking_rules',
		pathParams: ['project_id', 'branch_id'],
		riskLevel: 'write',
		description: 'Update masking rules',
	},
	{
		key: 'listProjectBranchEndpoints',
		group: 'branches',
		name: 'listProjectBranchEndpoints',
		method: 'GET',
		path: '/projects/{project_id}/branches/{branch_id}/endpoints',
		pathParams: ['project_id', 'branch_id'],
		riskLevel: 'read',
		description: 'List compute endpoints for the branch',
	},
] as const satisfies readonly NeonOperation[];
