import type { NeonOperation } from '../endpoints/operation-types';

export const computeEndpointsOperations = [
	{
		key: 'createProjectEndpoint',
		group: 'computeEndpoints',
		name: 'createProjectEndpoint',
		method: 'POST',
		path: '/projects/{project_id}/endpoints',
		pathParams: ['project_id'],
		riskLevel: 'write',
		description: 'Create compute endpoint',
	},
	{
		key: 'listProjectEndpoints',
		group: 'computeEndpoints',
		name: 'listProjectEndpoints',
		method: 'GET',
		path: '/projects/{project_id}/endpoints',
		pathParams: ['project_id'],
		riskLevel: 'read',
		description: 'List compute endpoints',
	},
	{
		key: 'getProjectEndpoint',
		group: 'computeEndpoints',
		name: 'getProjectEndpoint',
		method: 'GET',
		path: '/projects/{project_id}/endpoints/{endpoint_id}',
		pathParams: ['project_id', 'endpoint_id'],
		riskLevel: 'read',
		description: 'Retrieve compute endpoint details',
	},
	{
		key: 'updateProjectEndpoint',
		group: 'computeEndpoints',
		name: 'updateProjectEndpoint',
		method: 'PATCH',
		path: '/projects/{project_id}/endpoints/{endpoint_id}',
		pathParams: ['project_id', 'endpoint_id'],
		riskLevel: 'write',
		description: 'Update compute endpoint',
	},
	{
		key: 'deleteProjectEndpoint',
		group: 'computeEndpoints',
		name: 'deleteProjectEndpoint',
		method: 'DELETE',
		path: '/projects/{project_id}/endpoints/{endpoint_id}',
		pathParams: ['project_id', 'endpoint_id'],
		riskLevel: 'destructive',
		description: 'Delete compute endpoint',
	},
	{
		key: 'startProjectEndpoint',
		group: 'computeEndpoints',
		name: 'startProjectEndpoint',
		method: 'POST',
		path: '/projects/{project_id}/endpoints/{endpoint_id}/start',
		pathParams: ['project_id', 'endpoint_id'],
		riskLevel: 'write',
		description: 'Start compute endpoint',
	},
	{
		key: 'suspendProjectEndpoint',
		group: 'computeEndpoints',
		name: 'suspendProjectEndpoint',
		method: 'POST',
		path: '/projects/{project_id}/endpoints/{endpoint_id}/suspend',
		pathParams: ['project_id', 'endpoint_id'],
		riskLevel: 'write',
		description: 'Suspend compute endpoint',
	},
	{
		key: 'restartProjectEndpoint',
		group: 'computeEndpoints',
		name: 'restartProjectEndpoint',
		method: 'POST',
		path: '/projects/{project_id}/endpoints/{endpoint_id}/restart',
		pathParams: ['project_id', 'endpoint_id'],
		riskLevel: 'write',
		description: 'Restart compute endpoint',
	},
] as const satisfies readonly NeonOperation[];
