import type { NeonOperation } from '../endpoints/operation-types';

export const databasesOperations = [
	{
		key: 'listProjectBranchDatabases',
		group: 'databases',
		name: 'listProjectBranchDatabases',
		method: 'GET',
		path: '/projects/{project_id}/branches/{branch_id}/databases',
		pathParams: ['project_id', 'branch_id'],
		riskLevel: 'read',
		description: 'List databases',
	},
	{
		key: 'createProjectBranchDatabase',
		group: 'databases',
		name: 'createProjectBranchDatabase',
		method: 'POST',
		path: '/projects/{project_id}/branches/{branch_id}/databases',
		pathParams: ['project_id', 'branch_id'],
		riskLevel: 'write',
		description: 'Create database',
	},
	{
		key: 'getProjectBranchDatabase',
		group: 'databases',
		name: 'getProjectBranchDatabase',
		method: 'GET',
		path: '/projects/{project_id}/branches/{branch_id}/databases/{database_name}',
		pathParams: ['project_id', 'branch_id', 'database_name'],
		riskLevel: 'read',
		description: 'Retrieve database details',
	},
	{
		key: 'updateProjectBranchDatabase',
		group: 'databases',
		name: 'updateProjectBranchDatabase',
		method: 'PATCH',
		path: '/projects/{project_id}/branches/{branch_id}/databases/{database_name}',
		pathParams: ['project_id', 'branch_id', 'database_name'],
		riskLevel: 'write',
		description: 'Update database',
	},
	{
		key: 'deleteProjectBranchDatabase',
		group: 'databases',
		name: 'deleteProjectBranchDatabase',
		method: 'DELETE',
		path: '/projects/{project_id}/branches/{branch_id}/databases/{database_name}',
		pathParams: ['project_id', 'branch_id', 'database_name'],
		riskLevel: 'destructive',
		description: 'Delete database',
	},
] as const satisfies readonly NeonOperation[];
