import type { NeonOperation } from '../endpoints/operation-types';

export const organizationsOperations = [
	{
		key: 'getOrganization',
		group: 'organizations',
		name: 'getOrganization',
		method: 'GET',
		path: '/organizations/{org_id}',
		pathParams: ['org_id'],
		riskLevel: 'read',
		description: 'Retrieve organization details',
	},
	{
		key: 'listOrgApiKeys',
		group: 'organizations',
		name: 'listOrgApiKeys',
		method: 'GET',
		path: '/organizations/{org_id}/api_keys',
		pathParams: ['org_id'],
		riskLevel: 'read',
		description: 'List organization API keys',
	},
	{
		key: 'createOrgApiKey',
		group: 'organizations',
		name: 'createOrgApiKey',
		method: 'POST',
		path: '/organizations/{org_id}/api_keys',
		pathParams: ['org_id'],
		riskLevel: 'write',
		description: 'Create organization API key',
	},
	{
		key: 'revokeOrgApiKey',
		group: 'organizations',
		name: 'revokeOrgApiKey',
		method: 'DELETE',
		path: '/organizations/{org_id}/api_keys/{key_id}',
		pathParams: ['org_id', 'key_id'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Revoke organization API key',
	},
	{
		key: 'getOrganizationMembers',
		group: 'organizations',
		name: 'getOrganizationMembers',
		method: 'GET',
		path: '/organizations/{org_id}/members',
		pathParams: ['org_id'],
		riskLevel: 'read',
		description: 'List organization members',
	},
	{
		key: 'getOrganizationMember',
		group: 'organizations',
		name: 'getOrganizationMember',
		method: 'GET',
		path: '/organizations/{org_id}/members/{member_id}',
		pathParams: ['org_id', 'member_id'],
		riskLevel: 'read',
		description: 'Retrieve organization member details',
	},
	{
		key: 'updateOrganizationMember',
		group: 'organizations',
		name: 'updateOrganizationMember',
		method: 'PATCH',
		path: '/organizations/{org_id}/members/{member_id}',
		pathParams: ['org_id', 'member_id'],
		riskLevel: 'write',
		description: 'Update role for organization member',
	},
	{
		key: 'removeOrganizationMember',
		group: 'organizations',
		name: 'removeOrganizationMember',
		method: 'DELETE',
		path: '/organizations/{org_id}/members/{member_id}',
		pathParams: ['org_id', 'member_id'],
		riskLevel: 'destructive',
		description: 'Remove organization member',
	},
	{
		key: 'getOrganizationInvitations',
		group: 'organizations',
		name: 'getOrganizationInvitations',
		method: 'GET',
		path: '/organizations/{org_id}/invitations',
		pathParams: ['org_id'],
		riskLevel: 'read',
		description: 'List organization invitations',
	},
	{
		key: 'createOrganizationInvitations',
		group: 'organizations',
		name: 'createOrganizationInvitations',
		method: 'POST',
		path: '/organizations/{org_id}/invitations',
		pathParams: ['org_id'],
		riskLevel: 'write',
		description: 'Create organization invitations',
	},
	{
		key: 'transferProjectsFromOrgToOrg',
		group: 'organizations',
		name: 'transferProjectsFromOrgToOrg',
		method: 'POST',
		path: '/organizations/{source_org_id}/projects/transfer',
		pathParams: ['source_org_id'],
		riskLevel: 'write',
		description: 'Transfer projects between organizations',
	},
	{
		key: 'transferProjectsFromUserToOrg',
		group: 'organizations',
		name: 'transferProjectsFromUserToOrg',
		method: 'POST',
		path: '/users/me/projects/transfer',
		riskLevel: 'write',
		description:
			'Transfer projects from personal account to organization (deprecated)',
	},
] as const satisfies readonly NeonOperation[];
