import type { NeonOperation } from '../endpoints/operation-types';

export const projectsOperations = [
	{
		key: 'listProjects',
		group: 'projects',
		name: 'listProjects',
		method: 'GET',
		path: '/projects',
		riskLevel: 'read',
		description: 'List projects',
	},
	{
		key: 'createProject',
		group: 'projects',
		name: 'createProject',
		method: 'POST',
		path: '/projects',
		riskLevel: 'write',
		description: 'Create project',
	},
	{
		key: 'listSharedProjects',
		group: 'projects',
		name: 'listSharedProjects',
		method: 'GET',
		path: '/projects/shared',
		riskLevel: 'read',
		description: 'List shared projects',
	},
	{
		key: 'getProject',
		group: 'projects',
		name: 'getProject',
		method: 'GET',
		path: '/projects/{project_id}',
		pathParams: ['project_id'],
		riskLevel: 'read',
		description: 'Retrieve project details',
	},
	{
		key: 'updateProject',
		group: 'projects',
		name: 'updateProject',
		method: 'PATCH',
		path: '/projects/{project_id}',
		pathParams: ['project_id'],
		riskLevel: 'write',
		description: 'Update project',
	},
	{
		key: 'deleteProject',
		group: 'projects',
		name: 'deleteProject',
		method: 'DELETE',
		path: '/projects/{project_id}',
		pathParams: ['project_id'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Delete project',
	},
	{
		key: 'listProjectOperations',
		group: 'projects',
		name: 'listProjectOperations',
		method: 'GET',
		path: '/projects/{project_id}/operations',
		pathParams: ['project_id'],
		riskLevel: 'read',
		description: 'List operations',
	},
	{
		key: 'getProjectOperation',
		group: 'projects',
		name: 'getProjectOperation',
		method: 'GET',
		path: '/projects/{project_id}/operations/{operation_id}',
		pathParams: ['project_id', 'operation_id'],
		riskLevel: 'read',
		description: 'Retrieve operation details',
	},
	{
		key: 'listProjectPermissions',
		group: 'projects',
		name: 'listProjectPermissions',
		method: 'GET',
		path: '/projects/{project_id}/permissions',
		pathParams: ['project_id'],
		riskLevel: 'read',
		description: 'List project access',
	},
	{
		key: 'grantPermissionToProject',
		group: 'projects',
		name: 'grantPermissionToProject',
		method: 'POST',
		path: '/projects/{project_id}/permissions',
		pathParams: ['project_id'],
		riskLevel: 'write',
		description: 'Grant project access',
	},
	{
		key: 'revokePermissionFromProject',
		group: 'projects',
		name: 'revokePermissionFromProject',
		method: 'DELETE',
		path: '/projects/{project_id}/permissions/{permission_id}',
		pathParams: ['project_id', 'permission_id'],
		riskLevel: 'destructive',
		description: 'Revoke project access',
	},
	{
		key: 'getConnectionURI',
		group: 'projects',
		name: 'getConnectionURI',
		method: 'GET',
		path: '/projects/{project_id}/connection_uri',
		pathParams: ['project_id'],
		riskLevel: 'read',
		description: 'Retrieve database connection URI',
	},
	{
		key: 'getAvailablePreloadLibraries',
		group: 'projects',
		name: 'getAvailablePreloadLibraries',
		method: 'GET',
		path: '/projects/{project_id}/available_preload_libraries',
		pathParams: ['project_id'],
		riskLevel: 'read',
		description: 'List available shared preload libraries',
	},
	{
		key: 'createProjectTransferRequest',
		group: 'projects',
		name: 'createProjectTransferRequest',
		method: 'POST',
		path: '/projects/{project_id}/transfer_requests',
		pathParams: ['project_id'],
		riskLevel: 'write',
		description: 'Create a project transfer request',
	},
	{
		key: 'acceptProjectTransferRequest',
		group: 'projects',
		name: 'acceptProjectTransferRequest',
		method: 'PUT',
		path: '/projects/{project_id}/transfer_requests/{request_id}',
		pathParams: ['project_id', 'request_id'],
		riskLevel: 'write',
		description: 'Accept a project transfer request',
	},
	{
		key: 'getProjectJWKS',
		group: 'projects',
		name: 'getProjectJWKS',
		method: 'GET',
		path: '/projects/{project_id}/jwks',
		pathParams: ['project_id'],
		riskLevel: 'read',
		description: 'List JWKS URLs',
	},
	{
		key: 'addProjectJWKS',
		group: 'projects',
		name: 'addProjectJWKS',
		method: 'POST',
		path: '/projects/{project_id}/jwks',
		pathParams: ['project_id'],
		riskLevel: 'write',
		description: 'Add JWKS URL',
	},
	{
		key: 'deleteProjectJWKS',
		group: 'projects',
		name: 'deleteProjectJWKS',
		method: 'DELETE',
		path: '/projects/{project_id}/jwks/{jwks_id}',
		pathParams: ['project_id', 'jwks_id'],
		riskLevel: 'destructive',
		description: 'Delete JWKS URL',
	},
] as const satisfies readonly NeonOperation[];
