import type { NeonOperation } from '../endpoints/operation-types';

export const rolesOperations = [
	{
		key: 'listProjectBranchRoles',
		group: 'roles',
		name: 'listProjectBranchRoles',
		method: 'GET',
		path: '/projects/{project_id}/branches/{branch_id}/roles',
		pathParams: ['project_id', 'branch_id'],
		riskLevel: 'read',
		description: 'List roles',
	},
	{
		key: 'createProjectBranchRole',
		group: 'roles',
		name: 'createProjectBranchRole',
		method: 'POST',
		path: '/projects/{project_id}/branches/{branch_id}/roles',
		pathParams: ['project_id', 'branch_id'],
		riskLevel: 'write',
		description: 'Create role',
	},
	{
		key: 'getProjectBranchRole',
		group: 'roles',
		name: 'getProjectBranchRole',
		method: 'GET',
		path: '/projects/{project_id}/branches/{branch_id}/roles/{role_name}',
		pathParams: ['project_id', 'branch_id', 'role_name'],
		riskLevel: 'read',
		description: 'Retrieve role details',
	},
	{
		key: 'deleteProjectBranchRole',
		group: 'roles',
		name: 'deleteProjectBranchRole',
		method: 'DELETE',
		path: '/projects/{project_id}/branches/{branch_id}/roles/{role_name}',
		pathParams: ['project_id', 'branch_id', 'role_name'],
		riskLevel: 'destructive',
		description: 'Delete role',
	},
	{
		key: 'getProjectBranchRolePassword',
		group: 'roles',
		name: 'getProjectBranchRolePassword',
		method: 'GET',
		path: '/projects/{project_id}/branches/{branch_id}/roles/{role_name}/reveal_password',
		pathParams: ['project_id', 'branch_id', 'role_name'],
		riskLevel: 'read',
		description: 'Retrieve role password',
	},
	{
		key: 'resetProjectBranchRolePassword',
		group: 'roles',
		name: 'resetProjectBranchRolePassword',
		method: 'POST',
		path: '/projects/{project_id}/branches/{branch_id}/roles/{role_name}/reset_password',
		pathParams: ['project_id', 'branch_id', 'role_name'],
		riskLevel: 'write',
		description: 'Reset role password',
	},
] as const satisfies readonly NeonOperation[];
