import type { NeonOperation } from '../endpoints/operation-types';

export const snapshotsOperations = [
	{
		key: 'createSnapshot',
		group: 'snapshots',
		name: 'createSnapshot',
		method: 'POST',
		path: '/projects/{project_id}/branches/{branch_id}/snapshot',
		pathParams: ['project_id', 'branch_id'],
		riskLevel: 'write',
		description: 'Create snapshot',
	},
	{
		key: 'listSnapshots',
		group: 'snapshots',
		name: 'listSnapshots',
		method: 'GET',
		path: '/projects/{project_id}/snapshots',
		pathParams: ['project_id'],
		riskLevel: 'read',
		description: 'List project snapshots',
	},
	{
		key: 'updateSnapshot',
		group: 'snapshots',
		name: 'updateSnapshot',
		method: 'PATCH',
		path: '/projects/{project_id}/snapshots/{snapshot_id}',
		pathParams: ['project_id', 'snapshot_id'],
		riskLevel: 'write',
		description: 'Update snapshot',
	},
	{
		key: 'deleteSnapshot',
		group: 'snapshots',
		name: 'deleteSnapshot',
		method: 'DELETE',
		path: '/projects/{project_id}/snapshots/{snapshot_id}',
		pathParams: ['project_id', 'snapshot_id'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Delete snapshot',
	},
	{
		key: 'restoreSnapshot',
		group: 'snapshots',
		name: 'restoreSnapshot',
		method: 'POST',
		path: '/projects/{project_id}/snapshots/{snapshot_id}/restore',
		pathParams: ['project_id', 'snapshot_id'],
		riskLevel: 'write',
		description: 'Restore snapshot',
	},
	{
		key: 'getSnapshotSchedule',
		group: 'snapshots',
		name: 'getSnapshotSchedule',
		method: 'GET',
		path: '/projects/{project_id}/branches/{branch_id}/backup_schedule',
		pathParams: ['project_id', 'branch_id'],
		riskLevel: 'read',
		description: 'Retrieve backup schedule',
	},
] as const satisfies readonly NeonOperation[];
