import type { NeonOperation } from '../endpoints/operation-types';

export const vpcOperations = [
	{
		key: 'listOrganizationVPCEndpointsAllRegions',
		group: 'vpc',
		name: 'listOrganizationVPCEndpointsAllRegions',
		method: 'GET',
		path: '/organizations/{org_id}/vpc/vpc_endpoints',
		pathParams: ['org_id'],
		riskLevel: 'read',
		description: 'List VPC endpoints across all regions',
	},
	{
		key: 'listOrganizationVPCEndpoints',
		group: 'vpc',
		name: 'listOrganizationVPCEndpoints',
		method: 'GET',
		path: '/organizations/{org_id}/vpc/region/{region_id}/vpc_endpoints',
		pathParams: ['org_id', 'region_id'],
		riskLevel: 'read',
		description: 'List VPC endpoints',
	},
	{
		key: 'getOrganizationVPCEndpointDetails',
		group: 'vpc',
		name: 'getOrganizationVPCEndpointDetails',
		method: 'GET',
		path: '/organizations/{org_id}/vpc/region/{region_id}/vpc_endpoints/{vpc_endpoint_id}',
		pathParams: ['org_id', 'region_id', 'vpc_endpoint_id'],
		riskLevel: 'read',
		description: 'Retrieve VPC endpoint details',
	},
	{
		key: 'assignOrganizationVPCEndpoint',
		group: 'vpc',
		name: 'assignOrganizationVPCEndpoint',
		method: 'POST',
		path: '/organizations/{org_id}/vpc/region/{region_id}/vpc_endpoints/{vpc_endpoint_id}',
		pathParams: ['org_id', 'region_id', 'vpc_endpoint_id'],
		riskLevel: 'write',
		description: 'Assign or update VPC endpoint',
	},
	{
		key: 'deleteOrganizationVPCEndpoint',
		group: 'vpc',
		name: 'deleteOrganizationVPCEndpoint',
		method: 'DELETE',
		path: '/organizations/{org_id}/vpc/region/{region_id}/vpc_endpoints/{vpc_endpoint_id}',
		pathParams: ['org_id', 'region_id', 'vpc_endpoint_id'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Delete VPC endpoint',
	},
	{
		key: 'listProjectVPCEndpoints',
		group: 'vpc',
		name: 'listProjectVPCEndpoints',
		method: 'GET',
		path: '/projects/{project_id}/vpc_endpoints',
		pathParams: ['project_id'],
		riskLevel: 'read',
		description: 'List VPC endpoint restrictions',
	},
	{
		key: 'assignProjectVPCEndpoint',
		group: 'vpc',
		name: 'assignProjectVPCEndpoint',
		method: 'POST',
		path: '/projects/{project_id}/vpc_endpoints/{vpc_endpoint_id}',
		pathParams: ['project_id', 'vpc_endpoint_id'],
		riskLevel: 'write',
		description: 'Set VPC endpoint restriction',
	},
	{
		key: 'deleteProjectVPCEndpoint',
		group: 'vpc',
		name: 'deleteProjectVPCEndpoint',
		method: 'DELETE',
		path: '/projects/{project_id}/vpc_endpoints/{vpc_endpoint_id}',
		pathParams: ['project_id', 'vpc_endpoint_id'],
		riskLevel: 'destructive',
		description: 'Delete VPC endpoint restriction',
	},
] as const satisfies readonly NeonOperation[];
