"""Anchor Browser Composio slug -> (method, path) mappings for all 64 operations."""

from __future__ import annotations

MANUAL_ROUTES: dict[str, tuple[str, str]] = {
    "ANCHOR_BROWSER_CLICK_MOUSE": ("POST", "/sessions/{sessionId}/mouse/click"),
    "ANCHOR_BROWSER_COPY_SELECTED_TEXT": ("POST", "/sessions/{sessionId}/copy"),
    "ANCHOR_BROWSER_CREATE_INTEGRATION": ("POST", "/integrations"),
    "ANCHOR_BROWSER_CREATE_OR_UPDATE_TASK_DRAFT": ("POST", "/task/{taskId}/draft"),
    "ANCHOR_BROWSER_CREATE_PROFILE": ("POST", "/profiles"),
    "ANCHOR_BROWSER_CREATE_TASK": ("POST", "/task"),
    "ANCHOR_BROWSER_DELETE_EXTENSION": ("DELETE", "/extensions/{id}"),
    "ANCHOR_BROWSER_DELETE_INTEGRATION": ("DELETE", "/integrations/{integrationId}"),
    "ANCHOR_BROWSER_DELETE_PROFILE": ("DELETE", "/profiles/{name}"),
    "ANCHOR_BROWSER_DELETE_TASK": ("DELETE", "/task/{taskId}"),
    "ANCHOR_BROWSER_DELETE_TASK_VERSION": ("DELETE", "/task/{taskId}/{taskVersion}"),
    "ANCHOR_BROWSER_DEPLOY_TASK": ("POST", "/task/{taskId}/deploy"),
    "ANCHOR_BROWSER_DOUBLE_CLICK_MOUSE": ("POST", "/sessions/{sessionId}/mouse/doubleClick"),
    "ANCHOR_BROWSER_DRAG_AND_DROP": ("POST", "/sessions/{sessionId}/drag-and-drop"),
    "ANCHOR_BROWSER_END_ALL_SESSIONS": ("DELETE", "/sessions/all"),
    "ANCHOR_BROWSER_END_BROWSER_SESSION": ("DELETE", "/sessions/{session_id}"),
    "ANCHOR_BROWSER_GET_BATCH_SESSION_STATUS": ("GET", "/batch-sessions/{batch_id}"),
    "ANCHOR_BROWSER_GET_BROWSER_SESSION": ("GET", "/sessions/{session_id}"),
    "ANCHOR_BROWSER_GET_CLIPBOARD_CONTENT": ("GET", "/sessions/{sessionId}/clipboard"),
    "ANCHOR_BROWSER_GET_LATEST_TASK_VERSION": ("GET", "/task/{taskId}/latest"),
    "ANCHOR_BROWSER_GET_PROFILE2": ("GET", "/profiles/{name}"),
    "ANCHOR_BROWSER_GET_SESSION_PAGES": ("GET", "/sessions/{session_id}/pages"),
    "ANCHOR_BROWSER_GET_TASK_DRAFT": ("GET", "/task/{taskId}/draft"),
    "ANCHOR_BROWSER_GET_TASK_EXECUTION_RESULT": (
        "GET",
        "/task/{taskId}/executions/{executionId}",
    ),
    "ANCHOR_BROWSER_GET_TASK_METADATA": ("GET", "/task/{taskId}"),
    "ANCHOR_BROWSER_GET_TASK_VERSION": ("GET", "/task/{taskId}/{taskVersion}"),
    "ANCHOR_BROWSER_GET_WEBPAGE_CONTENT": ("POST", "/tools/fetch/webpage"),
    "ANCHOR_BROWSER_LIST_AGENT_RESOURCES": ("GET", "/sessions/{sessionId}/agent/files"),
    "ANCHOR_BROWSER_LIST_EXTENSIONS": ("GET", "/extensions"),
    "ANCHOR_BROWSER_LIST_INTEGRATIONS": ("GET", "/integrations"),
    "ANCHOR_BROWSER_LIST_PROFILES": ("GET", "/profiles"),
    "ANCHOR_BROWSER_LIST_SESSION_DOWNLOADS": ("GET", "/sessions/{session_id}/downloads"),
    "ANCHOR_BROWSER_LIST_SESSION_RECORDINGS": ("GET", "/sessions/{session_id}/recordings"),
    "ANCHOR_BROWSER_LIST_SESSIONS": ("GET", "/sessions"),
    "ANCHOR_BROWSER_LIST_TASK_EXECUTIONS": ("GET", "/task/{taskId}/executions"),
    "ANCHOR_BROWSER_LIST_TASKS": ("GET", "/task"),
    "ANCHOR_BROWSER_LIST_TASK_VERSIONS": ("GET", "/task/{taskId}/versions"),
    "ANCHOR_BROWSER_MOVE_MOUSE": ("POST", "/sessions/{sessionId}/mouse/move"),
    "ANCHOR_BROWSER_NAVIGATE_TO_URL": ("POST", "/sessions/{sessionId}/goto"),
    "ANCHOR_BROWSER_PASTE_TEXT": ("POST", "/sessions/{sessionId}/paste"),
    "ANCHOR_BROWSER_PAUSE_AGENT": ("POST", "/sessions/{session_id}/agent/pause"),
    "ANCHOR_BROWSER_PAUSE_SESSION_RECORDING": (
        "POST",
        "/sessions/{session_id}/recordings/pause",
    ),
    "ANCHOR_BROWSER_PERFORM_KEYBOARD_SHORTCUT": (
        "POST",
        "/sessions/{sessionId}/keyboard/shortcut",
    ),
    "ANCHOR_BROWSER_PERFORM_WEB_TASK": ("POST", "/tools/perform-web-task"),
    "ANCHOR_BROWSER_PRESS_MOUSE_BUTTON": ("POST", "/sessions/{sessionId}/mouse/down"),
    "ANCHOR_BROWSER_PUBLISH_TASK_VERSION": ("POST", "/task/{taskId}/{taskVersion}"),
    "ANCHOR_BROWSER_RELEASE_MOUSE_BUTTON": ("POST", "/sessions/{sessionId}/mouse/up"),
    "ANCHOR_BROWSER_RESUME_AGENT": ("POST", "/sessions/{session_id}/agent/resume"),
    "ANCHOR_BROWSER_RESUME_SESSION_RECORDING": (
        "POST",
        "/sessions/{session_id}/recordings/resume",
    ),
    "ANCHOR_BROWSER_RUN_TASK": ("POST", "/task/run"),
    "ANCHOR_BROWSER_RUN_TASK_BY_NAME": ("POST", "/task/run/{taskName}"),
    "ANCHOR_BROWSER_SCREENSHOT_WEBPAGE": ("POST", "/tools/screenshot"),
    "ANCHOR_BROWSER_SCROLL_SESSION": ("POST", "/sessions/{sessionId}/scroll"),
    "ANCHOR_BROWSER_SET_CLIPBOARD_CONTENT": ("POST", "/sessions/{sessionId}/clipboard"),
    "ANCHOR_BROWSER_SIGNAL_EVENT": ("POST", "/events/{event_name}"),
    "ANCHOR_BROWSER_START_BROWSER_SESSION": ("POST", "/sessions"),
    "ANCHOR_BROWSER_TAKE_SCREENSHOT": ("GET", "/sessions/{sessionId}/screenshot"),
    "ANCHOR_BROWSER_TYPE_TEXT": ("POST", "/sessions/{sessionId}/keyboard/type"),
    "ANCHOR_BROWSER_UPDATE_PROFILE": ("POST", "/profiles"),
    "ANCHOR_BROWSER_UPDATE_TASK_METADATA": ("PUT", "/task/{taskId}"),
    "ANCHOR_BROWSER_UPLOAD_EXTENSION": ("POST", "/extensions"),
    "ANCHOR_BROWSER_UPLOAD_FILE": ("POST", "/sessions/{sessionId}/agent/files"),
    "ANCHOR_BROWSER_UPLOAD_FILES_TO_SESSION": ("POST", "/sessions/{sessionId}/uploads"),
    "ANCHOR_BROWSER_WAIT_FOR_EVENT": ("POST", "/events/{event_name}/wait"),
}
# Total: 64 routes
