import { z } from 'zod';

/**
 * A sandbox session where code is executed and files are managed.
 */
export const CodeInterpreterSession = z.object({
	id: z.string(),
	status: z.enum(['active', 'idle', 'terminated']),
	language: z.string().optional(),
	created_at: z.coerce.date().nullable().optional(),
	updated_at: z.coerce.date().nullable().optional(),
});
export type CodeInterpreterSession = z.infer<typeof CodeInterpreterSession>;

/**
 * A file uploaded to or generated by the sandbox.
 */
export const CodeInterpreterFile = z.object({
	id: z.string(),
	name: z.string(),
	size: z.number().optional(),
	mime_type: z.string().optional(),
	session_id: z.string().optional(),
	created_at: z.coerce.date().nullable().optional(),
});
export type CodeInterpreterFile = z.infer<typeof CodeInterpreterFile>;

/**
 * Result of a code execution within the sandbox.
 */
export const CodeInterpreterExecution = z.object({
	id: z.string().optional(),
	exit_code: z.number(),
	stdout: z.string().optional(),
	stderr: z.string().optional(),
	logs: z.string().optional(),
	output_files: z.array(z.object({
		id: z.string(),
		name: z.string(),
	})).optional(),
	session_id: z.string().optional(),
	created_at: z.coerce.date().nullable().optional(),
});
export type CodeInterpreterExecution = z.infer<typeof CodeInterpreterExecution>;
