import { randomBytes, createCipheriv, createDecipheriv, scrypt } from 'crypto';
import { promisify } from 'util';
import { writeFileSync, readFileSync, existsSync } from 'fs';
import { resolve } from 'path';

const scryptAsync = promisify(scrypt);

const ALGORITHM = 'aes-256-gcm';
const IV_LENGTH = 12;
const AUTH_TAG_LENGTH = 16;
const SALT_LENGTH = 16;
const KEY_LENGTH = 32;

function generateDEK(): string {
	return randomBytes(KEY_LENGTH).toString('base64');
}

async function encryptDEK(dek: string, kek: string): Promise<string> {
	const salt = randomBytes(SALT_LENGTH);
	const derivedKey = (await scryptAsync(kek, salt, KEY_LENGTH)) as Buffer;
	const iv = randomBytes(IV_LENGTH);
	const cipher = createCipheriv(ALGORITHM, derivedKey, iv, { authTagLength: AUTH_TAG_LENGTH });
	const encrypted = Buffer.concat([cipher.update(dek, 'utf8'), cipher.final()]);
	const authTag = cipher.getAuthTag();
	return [salt.toString('base64'), iv.toString('base64'), authTag.toString('base64'), encrypted.toString('base64')].join(':');
}

function encryptWithDEK(data: string, dek: string): string {
	const key = Buffer.from(dek, 'base64');
	const iv = randomBytes(IV_LENGTH);
	const cipher = createCipheriv(ALGORITHM, key, iv, { authTagLength: AUTH_TAG_LENGTH });
	const encrypted = Buffer.concat([cipher.update(data, 'utf8'), cipher.final()]);
	const authTag = cipher.getAuthTag();
	return [iv.toString('base64'), authTag.toString('base64'), encrypted.toString('base64')].join(':');
}

function escapeSql(str: string): string {
	return str.replace(/'/g, "''");
}

async function main() {
	const envPath = resolve(process.cwd(), 'demo/testing/.env');
	const envContent = readFileSync(envPath, 'utf-8');
	const env: Record<string, string> = {};
	for (const line of envContent.split('\n')) {
		const trimmed = line.trim();
		if (!trimmed || trimmed.startsWith('#')) continue;
		const eqIdx = trimmed.indexOf('=');
		if (eqIdx > 0) {
			env[trimmed.slice(0, eqIdx)] = trimmed.slice(eqIdx + 1);
		}
	}

	const kek = env.CORSAIR_KEK;
	const clientId = env.GOOGLE_CLIENT_ID;
	const clientSecret = env.GOOGLE_CLIENT_SECRET;
	const accessToken = env.GOOGLE_ACCESS_TOKEN;
	const refreshToken = env.GOOGLE_REFRESH_TOKEN;

	if (!kek || kek === 'corsair-googlemeet-test-kek-32-chars-minimum') {
		console.error('ERROR: Set CORSAIR_KEK in demo/testing/.env to a real value (at least 32 chars)');
		process.exit(1);
	}
	if (!clientId || clientId === 'your-client-id-here') {
		console.error('ERROR: Set GOOGLE_CLIENT_ID in demo/testing/.env');
		process.exit(1);
	}
	if (!clientSecret || clientSecret === 'your-client-secret-here') {
		console.error('ERROR: Set GOOGLE_CLIENT_SECRET in demo/testing/.env');
		process.exit(1);
	}
	if (!accessToken || accessToken === 'your-access-token-here') {
		console.error('ERROR: Set GOOGLE_ACCESS_TOKEN in demo/testing/.env');
		process.exit(1);
	}
	if (!refreshToken || refreshToken === 'your-refresh-token-here') {
		console.error('ERROR: Set GOOGLE_REFRESH_TOKEN in demo/testing/.env');
		process.exit(1);
	}

	console.log('Generating encryption keys...');

	const integrationDek = generateDEK();
	const accountDek = generateDEK();

	const encryptedIntegrationDek = await encryptDEK(integrationDek, kek);
	const encryptedAccountDek = await encryptDEK(accountDek, kek);

	const now = Math.floor(Date.now() / 1000);
	const integrationId = crypto.randomUUID();
	const accountId = crypto.randomUUID();

	const integrationConfig = {
		client_id: encryptWithDEK(clientId, integrationDek),
		client_secret: encryptWithDEK(clientSecret, integrationDek),
		redirect_url: encryptWithDEK('http://localhost:3001/api/connect/callback', integrationDek),
	};

	const expiresAt = String(Math.floor(Date.now() / 1000) + 3600);
	const accountConfig = {
		access_token: encryptWithDEK(accessToken, accountDek),
		refresh_token: encryptWithDEK(refreshToken, accountDek),
		expires_at: encryptWithDEK(expiresAt, accountDek),
		scope: encryptWithDEK('https://www.googleapis.com/auth/meetings.space.created https://www.googleapis.com/auth/meetings.space.readonly', accountDek),
		webhook_signature: encryptWithDEK('', accountDek),
	};

	const sql = `-- Google Meet plugin setup for Corsair testing
-- Generated by setup-googlemeet-db.ts

INSERT OR REPLACE INTO corsair_integrations (id, created_at, updated_at, name, config, dek)
VALUES (
  '${integrationId}',
  ${now},
  ${now},
  'googlemeet',
  '${escapeSql(JSON.stringify(integrationConfig))}',
  '${escapeSql(encryptedIntegrationDek)}'
);

INSERT OR REPLACE INTO corsair_accounts (id, created_at, updated_at, tenant_id, integration_id, config, dek)
VALUES (
  '${accountId}',
  ${now},
  ${now},
  'default',
  '${integrationId}',
  '${escapeSql(JSON.stringify(accountConfig))}',
  '${escapeSql(encryptedAccountDek)}'
);

-- Verify: Run this to check the rows exist
-- SELECT id, name FROM corsair_integrations WHERE name = 'googlemeet';
-- SELECT id, tenant_id, integration_id FROM corsair_accounts WHERE integration_id = '${integrationId}';
`;

	const sqlPath = resolve(process.cwd(), 'demo/testing/setup-googlemeet.sql');
	writeFileSync(sqlPath, sql);
	console.log(`SQL file written to: ${sqlPath}`);

	const pyScript = `import sqlite3
import sys

db_path = sys.argv[1] if len(sys.argv) > 1 else 'corsair.db'
sql_path = sys.argv[2] if len(sys.argv) > 2 else 'setup-googlemeet.sql'

print(f'Opening database: {db_path}')
conn = sqlite3.connect(db_path)
cursor = conn.cursor()

# Read and execute the SQL file
with open(sql_path, 'r') as f:
    sql_content = f.read()

# Split by semicolons and execute each statement
for statement in sql_content.split(';'):
    statement = statement.strip()
    if statement and not statement.startswith('--'):
        cursor.execute(statement)

conn.commit()

# Verify
cursor.execute("SELECT id, name FROM corsair_integrations WHERE name = 'googlemeet'")
integrations = cursor.fetchall()
print(f'\\nIntegration rows: {len(integrations)}')
for row in integrations:
    print(f'  id={row[0]}, name={row[1]}')

cursor.execute("SELECT id, tenant_id FROM corsair_accounts WHERE integration_id IN (SELECT id FROM corsair_integrations WHERE name = 'googlemeet')")
accounts = cursor.fetchall()
print(f'\\nAccount rows: {len(accounts)}')
for row in accounts:
    print(f'  id={row[0]}, tenant_id={row[1]}')

conn.close()
print('\\nDone! Google Meet plugin is ready to test.')
`;

	const pyPath = resolve(process.cwd(), 'demo/testing/setup-db.py');
	writeFileSync(pyPath, pyScript);
	console.log(`Python script written to: ${pyPath}`);
	console.log('');
	console.log('Next steps:');
	console.log(`  cd demo/testing`);
	console.log(`  python setup-db.py corsair.db setup-googlemeet.sql`);
	console.log(`  pnpm run test`);
}

main().catch(console.error);
