/* eslint-disable */
import { boolean, integer, jsonb, pgTable, text, timestamp } from 'drizzle-orm/pg-core';

// This file is generated by Corsair. Do not edit by hand.

export const github_issues = pgTable('github_issues', {
		id: text('id').primaryKey(),
		createdAt: timestamp('createdAt', { withTimezone: true }).notNull().defaultNow(),
		updatedAt: timestamp('updatedAt', { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
		number: integer('number').notNull(),
		title: text('title').notNull(),
		body: text('body').notNull(),
		state: text('state').notNull(),
		repo: text('repo').notNull(),
		author: text('author').notNull(),
		created_at: text('created_at').notNull(),
		updated_at: text('updated_at').notNull(),
		closed_at: text('closed_at').notNull(),
});

export const github_pull_requests = pgTable('github_pull_requests', {
		id: text('id').primaryKey(),
		createdAt: timestamp('createdAt', { withTimezone: true }).notNull().defaultNow(),
		updatedAt: timestamp('updatedAt', { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
		number: integer('number').notNull(),
		title: text('title').notNull(),
		body: text('body').notNull(),
		state: text('state').notNull(),
		repo: text('repo').notNull(),
		author: text('author').notNull(),
		head: text('head').notNull(),
		base: text('base').notNull(),
		created_at: text('created_at').notNull(),
		updated_at: text('updated_at').notNull(),
		merged_at: text('merged_at').notNull(),
});

export const github_repositories = pgTable('github_repositories', {
		id: text('id').primaryKey(),
		createdAt: timestamp('createdAt', { withTimezone: true }).notNull().defaultNow(),
		updatedAt: timestamp('updatedAt', { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
		name: text('name').notNull(),
		full_name: text('full_name').notNull(),
		description: text('description').notNull(),
		private: boolean('private').notNull(),
		owner: text('owner').notNull(),
		url: text('url').notNull(),
		created_at: text('created_at').notNull(),
		updated_at: text('updated_at').notNull(),
});

export const github_commits = pgTable('github_commits', {
		id: text('id').primaryKey(),
		createdAt: timestamp('createdAt', { withTimezone: true }).notNull().defaultNow(),
		updatedAt: timestamp('updatedAt', { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
		sha: text('sha').notNull(),
		message: text('message').notNull(),
		author: text('author').notNull(),
		repo: text('repo').notNull(),
		created_at: text('created_at').notNull(),
});

export const linear_issues = pgTable('linear_issues', {
		id: text('id').primaryKey(),
		createdAt: timestamp('createdAt', { withTimezone: true }).notNull().defaultNow(),
		updatedAt: timestamp('updatedAt', { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
		title: text('title').notNull(),
		description: text('description').notNull(),
		priority: integer('priority').notNull(),
		state_id: text('state_id').notNull(),
		team_id: text('team_id').notNull(),
		assignee_id: text('assignee_id').notNull(),
		creator_id: text('creator_id').notNull(),
		number: integer('number').notNull(),
		url: text('url').notNull(),
		created_at: text('created_at').notNull(),
		updated_at: text('updated_at').notNull(),
});

export const linear_teams = pgTable('linear_teams', {
		id: text('id').primaryKey(),
		createdAt: timestamp('createdAt', { withTimezone: true }).notNull().defaultNow(),
		updatedAt: timestamp('updatedAt', { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
		name: text('name').notNull(),
		key: text('key').notNull(),
});

export const linear_projects = pgTable('linear_projects', {
		id: text('id').primaryKey(),
		createdAt: timestamp('createdAt', { withTimezone: true }).notNull().defaultNow(),
		updatedAt: timestamp('updatedAt', { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
		name: text('name').notNull(),
		description: text('description').notNull(),
		state: text('state').notNull(),
		progress: integer('progress').notNull(),
});

export const linear_comments = pgTable('linear_comments', {
		id: text('id').primaryKey(),
		createdAt: timestamp('createdAt', { withTimezone: true }).notNull().defaultNow(),
		updatedAt: timestamp('updatedAt', { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
		issue_id: text('issue_id').notNull(),
		body: text('body').notNull(),
		user_id: text('user_id').notNull(),
		created_at: text('created_at').notNull(),
		updated_at: text('updated_at').notNull(),
});

export const gmail_messages = pgTable('gmail_messages', {
		id: text('id').primaryKey(),
		createdAt: timestamp('createdAt', { withTimezone: true }).notNull().defaultNow(),
		updatedAt: timestamp('updatedAt', { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
		thread_id: text('thread_id').notNull(),
		subject: text('subject').notNull(),
		from: text('from').notNull(),
		to: text('to').notNull(),
		body: text('body').notNull(),
		date: text('date').notNull(),
		label_ids: text('label_ids').notNull(),
});

export const gmail_threads = pgTable('gmail_threads', {
		id: text('id').primaryKey(),
		createdAt: timestamp('createdAt', { withTimezone: true }).notNull().defaultNow(),
		updatedAt: timestamp('updatedAt', { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
		history_id: text('history_id').notNull(),
		snippet: text('snippet').notNull(),
});

export const gmail_labels = pgTable('gmail_labels', {
		id: text('id').primaryKey(),
		createdAt: timestamp('createdAt', { withTimezone: true }).notNull().defaultNow(),
		updatedAt: timestamp('updatedAt', { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
		name: text('name').notNull(),
		type: text('type').notNull(),
		color: text('color').notNull(),
});

export const gmail_drafts = pgTable('gmail_drafts', {
		id: text('id').primaryKey(),
		createdAt: timestamp('createdAt', { withTimezone: true }).notNull().defaultNow(),
		updatedAt: timestamp('updatedAt', { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
		message_id: text('message_id').notNull(),
		subject: text('subject').notNull(),
		to: text('to').notNull(),
		body: text('body').notNull(),
});

