import {
	BannerbearAccount,
	BannerbearAnimatedGif,
	BannerbearCollection,
	BannerbearEffect,
	BannerbearFont,
	BannerbearImage,
	BannerbearPdfJoin,
	BannerbearProject,
	BannerbearScreenshot,
	BannerbearSignedBase,
	BannerbearTemplate,
	BannerbearTemplateModification,
	BannerbearTemplateSet,
	BannerbearVideo,
	BannerbearVideoTemplate,
	BannerbearWebhookObj,
	BannerbearWorkflow,
	BannerbearWorkflowRun,
} from './database';

export const BannerbearSchema = {
	version: '1.0.0',
	entities: {
		account: BannerbearAccount,
		project: BannerbearProject,
		template: BannerbearTemplate,
		templateModification: BannerbearTemplateModification,
		image: BannerbearImage,
		video: BannerbearVideo,
		animatedGif: BannerbearAnimatedGif,
		collection: BannerbearCollection,
		screenshot: BannerbearScreenshot,
		templateSet: BannerbearTemplateSet,
		videoTemplate: BannerbearVideoTemplate,
		workflow: BannerbearWorkflow,
		workflowRun: BannerbearWorkflowRun,
		webhookObj: BannerbearWebhookObj,
		signedBase: BannerbearSignedBase,
		font: BannerbearFont,
		effect: BannerbearEffect,
		pdfJoin: BannerbearPdfJoin,
	},
} as const;
