import type { SupabaseOperation } from '../operation-types';

export const databaseOperations = [
	{
		key: 'applyMigration',
		group: 'database',
		name: 'applyMigration',
		method: 'POST',
		path: '/v1/projects/{ref}/database/migrations',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Apply a database migration',
	},
	{
		key: 'createLoginRole',
		group: 'database',
		name: 'createLoginRole',
		method: 'POST',
		path: '/v1/projects/{ref}/cli/login-role',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Create a CLI login role',
	},
	{
		key: 'deleteLoginRoles',
		group: 'database',
		name: 'deleteLoginRoles',
		method: 'DELETE',
		path: '/v1/projects/{ref}/cli/login-role',
		pathParams: ['ref'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Delete CLI login roles',
	},
	{
		key: 'disableProjectReadonly',
		group: 'database',
		name: 'disableProjectReadonly',
		method: 'POST',
		path: '/v1/projects/{ref}/readonly/temporary-disable',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Temporarily disable project read-only mode',
	},
	{
		key: 'enableDatabaseWebhooks',
		group: 'database',
		name: 'enableDatabaseWebhooks',
		method: 'POST',
		path: '/v1/projects/{ref}/database/webhooks/enable',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Enable database webhooks',
	},
	{
		key: 'runSqlQuery',
		group: 'database',
		name: 'runSqlQuery',
		method: 'POST',
		path: '/v1/projects/{ref}/database/query',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Execute a project database query',
	},
	{
		key: 'runReadOnlyQuery',
		group: 'database',
		name: 'runReadOnlyQuery',
		method: 'POST',
		path: '/v1/projects/{ref}/database/query/read-only',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Execute a read-only database query',
	},
	{
		key: 'generateTypescriptTypes',
		group: 'database',
		name: 'generateTypescriptTypes',
		method: 'GET',
		path: '/v1/projects/{ref}/types/typescript',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Generate TypeScript database types',
	},
	{
		key: 'getDatabaseMetadata',
		group: 'database',
		name: 'getDatabaseMetadata',
		method: 'GET',
		path: '/v1/projects/{ref}/database/context',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get database metadata',
	},
	{
		key: 'getJitAccessConfig',
		group: 'database',
		name: 'getJitAccessConfig',
		method: 'GET',
		path: '/v1/projects/{ref}/jit-access',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get JIT access config',
	},
	{
		key: 'getTableSchemas',
		group: 'database',
		name: 'getTableSchemas',
		method: 'POST',
		path: '/v1/projects/{ref}/database/query/read-only',
		kind: 'getTableSchemas',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get database table schemas',
	},
	{
		key: 'getMigration',
		group: 'database',
		name: 'getMigration',
		method: 'GET',
		path: '/v1/projects/{ref}/database/migrations/{version}',
		pathParams: ['ref', 'version'],
		riskLevel: 'read',
		description: 'Get a migration',
	},
	{
		key: 'getSqlSnippet',
		group: 'database',
		name: 'getSqlSnippet',
		method: 'GET',
		path: '/v1/snippets/{id}',
		pathParams: ['id'],
		riskLevel: 'read',
		description: 'Get a SQL snippet',
	},
	{
		key: 'getProjectPgbouncerConfig',
		group: 'database',
		name: 'getProjectPgbouncerConfig',
		method: 'GET',
		path: '/v1/projects/{ref}/config/database/pgbouncer',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get project PgBouncer config',
	},
	{
		key: 'getProjectSslEnforcementConfig',
		group: 'database',
		name: 'getProjectSslEnforcementConfig',
		method: 'GET',
		path: '/v1/projects/{ref}/ssl-enforcement',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get project SSL enforcement config',
	},
	{
		key: 'getProjectSupavisorConfig',
		group: 'database',
		name: 'getProjectSupavisorConfig',
		method: 'GET',
		path: '/v1/projects/{ref}/config/database/pooler',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get project Supavisor config',
	},
	{
		key: 'getProjectPostgresConfig',
		group: 'database',
		name: 'getProjectPostgresConfig',
		method: 'GET',
		path: '/v1/projects/{ref}/config/database/postgres',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get project postgres config',
	},
	{
		key: 'getProjectReadonlyModeStatus',
		group: 'database',
		name: 'getProjectReadonlyModeStatus',
		method: 'GET',
		path: '/v1/projects/{ref}/readonly',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get project read-only mode status',
	},
	{
		key: 'listTables',
		group: 'database',
		name: 'listTables',
		method: 'POST',
		path: '/v1/projects/{ref}/database/query/read-only',
		kind: 'listTables',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'List database tables',
	},
	{
		key: 'listSqlSnippets',
		group: 'database',
		name: 'listSqlSnippets',
		method: 'GET',
		path: '/v1/snippets',
		riskLevel: 'read',
		description: 'List SQL snippets',
	},
	{
		key: 'listMigrationHistory',
		group: 'database',
		name: 'listMigrationHistory',
		method: 'GET',
		path: '/v1/projects/{ref}/database/migrations',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'List migration history',
	},
	{
		key: 'listBackups',
		group: 'database',
		name: 'listBackups',
		method: 'GET',
		path: '/v1/projects/{ref}/database/backups',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'List project database backups',
	},
	{
		key: 'patchMigration',
		group: 'database',
		name: 'patchMigration',
		method: 'PATCH',
		path: '/v1/projects/{ref}/database/migrations/{version}',
		pathParams: ['ref', 'version'],
		riskLevel: 'write',
		description: 'Patch a migration',
	},
	{
		key: 'removeReadReplica',
		group: 'database',
		name: 'removeReadReplica',
		method: 'POST',
		path: '/v1/projects/{ref}/read-replicas/remove',
		pathParams: ['ref'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Remove a read replica',
	},
	{
		key: 'restorePitrBackup',
		group: 'database',
		name: 'restorePitrBackup',
		method: 'POST',
		path: '/v1/projects/{ref}/database/backups/restore-pitr',
		pathParams: ['ref'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Restore database PITR backup',
	},
	{
		key: 'selectFromTable',
		group: 'database',
		name: 'selectFromTable',
		method: 'POST',
		path: '/v1/projects/{ref}/database/query/read-only',
		kind: 'selectFromTable',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Select rows from a database table',
	},
	{
		key: 'createReadReplica',
		group: 'database',
		name: 'createReadReplica',
		method: 'POST',
		path: '/v1/projects/{ref}/read-replicas/setup',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Set up a read replica',
	},
	{
		key: 'updateJitAccessConfig',
		group: 'database',
		name: 'updateJitAccessConfig',
		method: 'PUT',
		path: '/v1/projects/{ref}/jit-access',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Update JIT access config',
	},
	{
		key: 'updateSslEnforcementConfig',
		group: 'database',
		name: 'updateSslEnforcementConfig',
		method: 'PUT',
		path: '/v1/projects/{ref}/ssl-enforcement',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Update SSL enforcement config',
	},
	{
		key: 'updateDatabasePassword',
		group: 'database',
		name: 'updateDatabasePassword',
		method: 'PATCH',
		path: '/v1/projects/{ref}/database/password',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Update database password',
	},
	{
		key: 'updateProjectSupavisorConfig',
		group: 'database',
		name: 'updateProjectSupavisorConfig',
		method: 'PATCH',
		path: '/v1/projects/{ref}/config/database/pooler',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Update project Supavisor config',
	},
	{
		key: 'updateProjectPostgresConfig',
		group: 'database',
		name: 'updateProjectPostgresConfig',
		method: 'PUT',
		path: '/v1/projects/{ref}/config/database/postgres',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Update project postgres config',
	},
	{
		key: 'upsertMigration',
		group: 'database',
		name: 'upsertMigration',
		method: 'PUT',
		path: '/v1/projects/{ref}/database/migrations',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Upsert a migration',
	},
] as const satisfies readonly SupabaseOperation[];
