import type { SupabaseOperation } from '../operation-types';

export const domainsOperations = [
	{
		key: 'activateVanitySubdomain',
		group: 'domains',
		name: 'activateVanitySubdomain',
		method: 'POST',
		path: '/v1/projects/{ref}/vanity-subdomain/activate',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Activate a vanity subdomain for a project',
	},
	{
		key: 'activateCustomHostname',
		group: 'domains',
		name: 'activateCustomHostname',
		method: 'POST',
		path: '/v1/projects/{ref}/custom-hostname/activate',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Activate a configured custom hostname',
	},
	{
		key: 'getProjectCustomHostnameConfig',
		group: 'domains',
		name: 'getProjectCustomHostnameConfig',
		method: 'GET',
		path: '/v1/projects/{ref}/custom-hostname',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get a project custom hostname configuration',
	},
	{
		key: 'checkVanitySubdomainAvailability',
		group: 'domains',
		name: 'checkVanitySubdomainAvailability',
		method: 'POST',
		path: '/v1/projects/{ref}/vanity-subdomain/check-availability',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Check vanity subdomain availability',
	},
	{
		key: 'deleteCustomHostnameConfig',
		group: 'domains',
		name: 'deleteCustomHostnameConfig',
		method: 'DELETE',
		path: '/v1/projects/{ref}/custom-hostname',
		pathParams: ['ref'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Delete custom hostname configuration',
	},
	{
		key: 'deleteProjectVanitySubdomain',
		group: 'domains',
		name: 'deleteProjectVanitySubdomain',
		method: 'DELETE',
		path: '/v1/projects/{ref}/vanity-subdomain',
		pathParams: ['ref'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Delete a project vanity subdomain',
	},
	{
		key: 'getVanitySubdomainConfig',
		group: 'domains',
		name: 'getVanitySubdomainConfig',
		method: 'GET',
		path: '/v1/projects/{ref}/vanity-subdomain',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get current vanity subdomain config',
	},
	{
		key: 'verifyCustomHostnameDns',
		group: 'domains',
		name: 'verifyCustomHostnameDns',
		method: 'POST',
		path: '/v1/projects/{ref}/custom-hostname/reverify',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Reverify custom hostname DNS',
	},
	{
		key: 'updateProjectCustomHostname',
		group: 'domains',
		name: 'updateProjectCustomHostname',
		method: 'POST',
		path: '/v1/projects/{ref}/custom-hostname/initialize',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Update project custom hostname',
	},
] as const satisfies readonly SupabaseOperation[];
