import type { SupabaseOperation } from '../operation-types';

export const environmentsOperations = [
	{
		key: 'countActionRuns',
		group: 'environments',
		name: 'countActionRuns',
		method: 'HEAD',
		path: '/v1/projects/{ref}/actions',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Count action runs',
	},
	{
		key: 'createDatabaseBranch',
		group: 'environments',
		name: 'createDatabaseBranch',
		method: 'POST',
		path: '/v1/projects/{ref}/branches',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Create a database branch',
	},
	{
		key: 'deleteDatabaseBranch',
		group: 'environments',
		name: 'deleteDatabaseBranch',
		method: 'DELETE',
		path: '/v1/branches/{branchId}',
		pathParams: ['branchId'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Delete a database branch',
	},
	{
		key: 'disablePreviewBranching',
		group: 'environments',
		name: 'disablePreviewBranching',
		method: 'DELETE',
		path: '/v1/projects/{ref}/branches',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Disable preview branching',
	},
	{
		key: 'getBranch',
		group: 'environments',
		name: 'getBranch',
		method: 'GET',
		path: '/v1/projects/{ref}/branches/{name}',
		pathParams: ['ref', 'name'],
		riskLevel: 'read',
		description: 'Get a database branch by name',
	},
	{
		key: 'getActionRunLogs',
		group: 'environments',
		name: 'getActionRunLogs',
		method: 'GET',
		path: '/v1/projects/{ref}/actions/{runId}/logs',
		pathParams: ['ref', 'runId'],
		riskLevel: 'read',
		description: 'Get action run logs',
	},
	{
		key: 'getActionRun',
		group: 'environments',
		name: 'getActionRun',
		method: 'GET',
		path: '/v1/projects/{ref}/actions/{runId}',
		pathParams: ['ref', 'runId'],
		riskLevel: 'read',
		description: 'Get action run status',
	},
	{
		key: 'getDatabaseBranchConfig',
		group: 'environments',
		name: 'getDatabaseBranchConfig',
		method: 'GET',
		path: '/v1/branches/{branchId}',
		pathParams: ['branchId'],
		riskLevel: 'read',
		description: 'Get database branch config',
	},
	{
		key: 'listDatabaseBranches',
		group: 'environments',
		name: 'listDatabaseBranches',
		method: 'GET',
		path: '/v1/projects/{ref}/branches',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'List database branches',
	},
	{
		key: 'pushBranch',
		group: 'environments',
		name: 'pushBranch',
		method: 'POST',
		path: '/v1/branches/{branchId}/push',
		pathParams: ['branchId'],
		riskLevel: 'write',
		description: 'Push a database branch',
	},
	{
		key: 'resetDatabaseBranch',
		group: 'environments',
		name: 'resetDatabaseBranch',
		method: 'POST',
		path: '/v1/branches/{branchId}/reset',
		pathParams: ['branchId'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Reset a database branch',
	},
	{
		key: 'updateDatabaseBranchConfig',
		group: 'environments',
		name: 'updateDatabaseBranchConfig',
		method: 'PATCH',
		path: '/v1/branches/{branchId}',
		pathParams: ['branchId'],
		riskLevel: 'write',
		description: 'Update database branch config',
	},
] as const satisfies readonly SupabaseOperation[];
