import { z } from 'zod';

export const StravaActivity = z.object({
	id: z.number(),
	name: z.string().optional(),
	sport_type: z.string().optional(),
	start_date: z.string().optional(),
	start_date_local: z.string().optional(),
	elapsed_time: z.number().optional(),
	moving_time: z.number().optional(),
	distance: z.number().optional(),
	total_elevation_gain: z.number().optional(),
	timezone: z.string().optional(),
	description: z.string().nullable().optional(),
	calories: z.number().optional(),
	athlete: z.object({ id: z.number() }).optional(),
	gear_id: z.string().nullable().optional(),
	commute: z.boolean().optional(),
	trainer: z.boolean().optional(),
	manual: z.boolean().optional(),
	private: z.boolean().optional(),
	resource_state: z.number().optional(),
	kudos_count: z.number().optional(),
	comment_count: z.number().optional(),
	athlete_count: z.number().optional(),
	photo_count: z.number().optional(),
	average_speed: z.number().optional(),
	max_speed: z.number().optional(),
	average_heartrate: z.number().optional(),
	max_heartrate: z.number().optional(),
	average_watts: z.number().optional(),
	max_watts: z.number().optional(),
	kilojoules: z.number().optional(),
	device_watts: z.boolean().optional(),
	has_heartrate: z.boolean().optional(),
	elev_high: z.number().optional(),
	elev_low: z.number().optional(),
	pr_count: z.number().optional(),
	suffer_score: z.number().nullable().optional(),
	workout_type: z.number().nullable().optional(),
	upload_id: z.number().nullable().optional(),
	external_id: z.string().nullable().optional(),
	has_kudoed: z.boolean().optional(),
	average_cadence: z.number().optional(),
	device_name: z.string().optional(),
});

export const StravaAthlete = z.object({
	id: z.number(),
	username: z.string().nullable().optional(),
	firstname: z.string().optional(),
	lastname: z.string().optional(),
	city: z.string().nullable().optional(),
	state: z.string().nullable().optional(),
	country: z.string().nullable().optional(),
	sex: z.string().nullable().optional(),
	premium: z.boolean().optional(),
	summit: z.boolean().optional(),
	created_at: z.string().optional(),
	updated_at: z.string().optional(),
	follower_count: z.number().optional(),
	friend_count: z.number().optional(),
	measurement_preference: z.string().optional(),
	ftp: z.number().nullable().optional(),
	weight: z.number().nullable().optional(),
	profile: z.string().optional(),
	profile_medium: z.string().optional(),
	resource_state: z.number().optional(),
});

export const StravaSegment = z.object({
	id: z.number(),
	name: z.string().optional(),
	activity_type: z.string().optional(),
	distance: z.number().optional(),
	average_grade: z.number().optional(),
	maximum_grade: z.number().optional(),
	elevation_high: z.number().optional(),
	elevation_low: z.number().optional(),
	start_latlng: z.array(z.number()).optional(),
	end_latlng: z.array(z.number()).optional(),
	climb_category: z.number().optional(),
	city: z.string().nullable().optional(),
	state: z.string().nullable().optional(),
	country: z.string().nullable().optional(),
	private: z.boolean().optional(),
	starred: z.boolean().optional(),
	created_at: z.string().optional(),
	updated_at: z.string().optional(),
	total_elevation_gain: z.number().optional(),
	effort_count: z.number().optional(),
	athlete_count: z.number().optional(),
	hazardous: z.boolean().optional(),
	star_count: z.number().optional(),
});

export const StravaSegmentEffort = z.object({
	id: z.number(),
	activity_id: z.number().optional(),
	athlete_id: z.number().optional(),
	name: z.string().optional(),
	elapsed_time: z.number().optional(),
	moving_time: z.number().optional(),
	start_date: z.string().optional(),
	start_date_local: z.string().optional(),
	distance: z.number().optional(),
	start_index: z.number().optional(),
	end_index: z.number().optional(),
	kom_rank: z.number().nullable().optional(),
	pr_rank: z.number().nullable().optional(),
	device_watts: z.boolean().optional(),
	average_watts: z.number().optional(),
	average_heartrate: z.number().optional(),
	max_heartrate: z.number().optional(),
	average_cadence: z.number().optional(),
	resource_state: z.number().optional(),
});

export const StravaRoute = z.object({
	id: z.number(),
	description: z.string().nullable().optional(),
	distance: z.number().optional(),
	elevation_gain: z.number().optional(),
	name: z.string().optional(),
	private: z.boolean().optional(),
	starred: z.boolean().optional(),
	timestamp: z.number().optional(),
	type: z.number().optional(),
	sub_type: z.number().optional(),
	created_at: z.string().optional(),
	updated_at: z.string().optional(),
	estimated_moving_time: z.number().optional(),
});

export const StravaClub = z.object({
	id: z.number(),
	name: z.string().optional(),
	profile: z.string().optional(),
	profile_medium: z.string().optional(),
	description: z.string().nullable().optional(),
	club_type: z.string().optional(),
	sport_type: z.string().optional(),
	city: z.string().nullable().optional(),
	state: z.string().nullable().optional(),
	country: z.string().nullable().optional(),
	private: z.boolean().optional(),
	member_count: z.number().optional(),
	featured: z.boolean().optional(),
	verified: z.boolean().optional(),
	url: z.string().optional(),
});

export const StravaLap = z.object({
	id: z.number(),
	average_cadence: z.number().optional(),
	average_speed: z.number().optional(),
	average_heartrate: z.number().optional(),
	average_watts: z.number().optional(),
	device_watts: z.boolean().optional(),
	distance: z.number().optional(),
	elapsed_time: z.number().optional(),
	end_index: z.number().optional(),
	lap_index: z.number().optional(),
	max_speed: z.number().optional(),
	max_heartrate: z.number().optional(),
	moving_time: z.number().optional(),
	name: z.string().optional(),
	pace_zone: z.number().optional(),
	resource_state: z.number().optional(),
	split: z.number().optional(),
	start_date: z.string().optional(),
	start_date_local: z.string().optional(),
	start_index: z.number().optional(),
	total_elevation_gain: z.number().optional(),
});

export const StravaGear = z.object({
	id: z.string(),
	primary: z.boolean().optional(),
	name: z.string().optional(),
	distance: z.number().optional(),
	brand_name: z.string().nullable().optional(),
	model_name: z.string().nullable().optional(),
	frame_type: z.number().nullable().optional(),
	description: z.string().nullable().optional(),
	athlete_id: z.number().optional(),
	resource_state: z.number().optional(),
	retired: z.boolean().optional(),
	converted_distance: z.number().optional(),
	notification_distance: z.number().optional(),
});

export const StravaUpload = z.object({
	id: z.number(),
	external_id: z.string().nullable().optional(),
	error: z.string().nullable().optional(),
	status: z.string().optional(),
	activity_id: z.number().nullable().optional(),
});

export type StravaActivity = z.infer<typeof StravaActivity>;
export type StravaAthlete = z.infer<typeof StravaAthlete>;
export type StravaSegment = z.infer<typeof StravaSegment>;
export type StravaSegmentEffort = z.infer<typeof StravaSegmentEffort>;
export type StravaRoute = z.infer<typeof StravaRoute>;
export type StravaClub = z.infer<typeof StravaClub>;
export type StravaLap = z.infer<typeof StravaLap>;
export type StravaGear = z.infer<typeof StravaGear>;
export type StravaUpload = z.infer<typeof StravaUpload>;
