import { z } from 'zod';
import type { CanvasOperationName } from './operations';
import { canvasOperations } from './operations';

export type CanvasRequestInput = {
	/** Path parameters as key-value pairs (e.g. { course_id: '123', assignment_id: '456' }) */
	pathParams?: Record<string, string>;
	/** Query string parameters */
	query?: Record<string, string | number | boolean | string[] | undefined>;
	/** Request body for POST/PUT/PATCH */
	body?: Record<string, unknown>;
};

export type CanvasResponse = unknown;

export type CanvasEndpointInputs = {
	[K in CanvasOperationName]: CanvasRequestInput;
};

export type CanvasEndpointOutputs = {
	[K in CanvasOperationName]: CanvasResponse;
};

const queryValueSchema = z.union([
	z.string(),
	z.number(),
	z.boolean(),
	z.array(z.string()),
]);

const querySchema = z.record(z.string(), queryValueSchema.optional());
const bodySchema = z.record(z.string(), z.unknown());
const pathParamsSchema = z.record(z.string(), z.string());

function createRequestInputSchema(
	operation: (typeof canvasOperations)[CanvasOperationName],
): z.ZodType<CanvasRequestInput> {
	const method: string = operation.method;
	const needsBody = method === 'POST' || method === 'PUT' || method === 'PATCH';

	if (needsBody) {
		return z.object({
			pathParams: pathParamsSchema.optional(),
			query: querySchema.optional(),
			body: bodySchema,
		});
	}

	return z.object({
		pathParams: pathParamsSchema.optional(),
		query: querySchema.optional(),
		body: bodySchema.optional(),
	});
}

export const CanvasEndpointInputSchemas = Object.fromEntries(
	Object.entries(canvasOperations).map(([name, operation]) => [
		name,
		createRequestInputSchema(operation),
	]),
) as { [K in CanvasOperationName]: z.ZodType<CanvasRequestInput> };

const canvasObjectResponseSchema = z.record(z.string(), z.unknown());
const canvasArrayResponseSchema = z.array(z.unknown());

export const CanvasEndpointOutputSchemas = {
	createCourse: canvasObjectResponseSchema,
	getSingleCourse: canvasObjectResponseSchema,
	getAccountCourse: canvasObjectResponseSchema,
	getCoursePermissions: canvasObjectResponseSchema,
	getCourseLevelParticipationData: canvasObjectResponseSchema,
	addCourseToFavorites: canvasObjectResponseSchema,
	getSingleAccount: canvasObjectResponseSchema,
	getAccountsThatUsersCanCreateCoursesIn: canvasArrayResponseSchema,
	getAccountHelpLinks: canvasObjectResponseSchema,
	getAccountGraphQl: canvasObjectResponseSchema,
	getAccountNotifications: canvasObjectResponseSchema,
	createAccountNotification: canvasObjectResponseSchema,
	closeNotificationForUser: canvasObjectResponseSchema,
	getCurrentUser: canvasObjectResponseSchema,
	getSingleUser: canvasObjectResponseSchema,
	getUserProfile: canvasObjectResponseSchema,
	editUser: canvasObjectResponseSchema,
	getAllUsers: canvasArrayResponseSchema,
	getUserAvatars: canvasArrayResponseSchema,
	getCustomColors: canvasObjectResponseSchema,
	getCustomColor: canvasObjectResponseSchema,
	getDashboardPositions: canvasObjectResponseSchema,
	createUsersTokens: canvasObjectResponseSchema,
	getUsersTokens: canvasArrayResponseSchema,
	deleteAccessToken: canvasObjectResponseSchema,
	createUsersCustomData: canvasObjectResponseSchema,
	getUsersCustomDataScope: canvasArrayResponseSchema,
	deleteCustomData: canvasObjectResponseSchema,
	deleteUsersCustomDataScope: canvasObjectResponseSchema,
	createUserInboxLabel: canvasObjectResponseSchema,
	deleteUserInboxLabel: canvasObjectResponseSchema,
	createEnrollment: canvasObjectResponseSchema,
	concludeDeactivateOrDeleteEnrollment: canvasObjectResponseSchema,
	getEnrollmentInvitations: canvasObjectResponseSchema,
	addLastAttendedDate: canvasObjectResponseSchema,
	createAssignment: canvasObjectResponseSchema,
	getAssignment: canvasObjectResponseSchema,
	getAssignment2: canvasObjectResponseSchema,
	editAssignment: canvasObjectResponseSchema,
	deleteAssignment: canvasObjectResponseSchema,
	getAllAssignments: canvasArrayResponseSchema,
	createAssignmentGraphQl: canvasObjectResponseSchema,
	getSubmissionSummary: canvasObjectResponseSchema,
	createAssignmentGroup: canvasObjectResponseSchema,
	getAnAssignmentGroup: canvasObjectResponseSchema,
	getAssignmentGroup: canvasObjectResponseSchema,
	createAssignmentOverride: canvasObjectResponseSchema,
	getSingleAssignmentOverride: canvasObjectResponseSchema,
	deleteAssignmentOverride: canvasObjectResponseSchema,
	createBatchOverridesInACourse: canvasObjectResponseSchema,
	getCourses12Assignments: canvasArrayResponseSchema,
	getAssignmentRubric: canvasObjectResponseSchema,
	createRubric: canvasObjectResponseSchema,
	getRubricAssessmentsReadState: canvasObjectResponseSchema,
	getRubricsUploadTemplate: canvasObjectResponseSchema,
	createSubmissionDraft: canvasObjectResponseSchema,
	deleteSubmissionDraft: canvasObjectResponseSchema,
	getAUsersMostRecentlyGraded: canvasObjectResponseSchema,
	getAllPeerReviews: canvasArrayResponseSchema,
	getAllPeerReviewsForSectionAssignment: canvasArrayResponseSchema,
	getAllPeerReviewsForSectionSubmission: canvasArrayResponseSchema,
	createModule: canvasObjectResponseSchema,
	createModuleGraphQl: canvasObjectResponseSchema,
	createModuleItem: canvasObjectResponseSchema,
	getModuleItem: canvasObjectResponseSchema,
	getModuleItemSequence: canvasObjectResponseSchema,
	createPageForCourse: canvasObjectResponseSchema,
	getPageForCourse: canvasObjectResponseSchema,
	createPageForGroup: canvasObjectResponseSchema,
	deletePageForGroup: canvasObjectResponseSchema,
	createDiscussionTopic: canvasObjectResponseSchema,
	createDiscussionTopicGraphQl: canvasObjectResponseSchema,
	getSingleTopic: canvasObjectResponseSchema,
	createDiscussionEntry: canvasObjectResponseSchema,
	createDiscussionEntryGraphQl: canvasObjectResponseSchema,
	deleteAnEntry: canvasObjectResponseSchema,
	deleteDiscussionEntry: canvasObjectResponseSchema,
	deleteDiscussionTopicGraphQl: canvasObjectResponseSchema,
	createGroupDiscussionTopic: canvasObjectResponseSchema,
	getSingleTopic2: canvasObjectResponseSchema,
	getFullTopicGroups: canvasObjectResponseSchema,
	deleteAnEntry2: canvasObjectResponseSchema,
	deleteGroupDiscussionTopic: canvasObjectResponseSchema,
	duplicateGroupDiscussionTopic: canvasObjectResponseSchema,
	createQuiz: canvasObjectResponseSchema,
	getSingleQuiz: canvasObjectResponseSchema,
	editQuiz: canvasObjectResponseSchema,
	deleteQuiz: canvasObjectResponseSchema,
	createQuizQuestion: canvasObjectResponseSchema,
	createQuestionGroup: canvasObjectResponseSchema,
	createQuizSubmission: canvasObjectResponseSchema,
	answerQuizQuestions: canvasObjectResponseSchema,
	getQuizStatistics: canvasObjectResponseSchema,
	createQuizReport: canvasObjectResponseSchema,
	getQuizReport: canvasObjectResponseSchema,
	abortQuizReportGeneration: canvasObjectResponseSchema,
	createCalendarEvent: canvasObjectResponseSchema,
	deleteCalendarEvent: canvasObjectResponseSchema,
	createOrUpdateTimetableEvents: canvasObjectResponseSchema,
	createAppointmentGroup: canvasObjectResponseSchema,
	deleteAppointmentGroup: canvasObjectResponseSchema,
	createConversation: canvasObjectResponseSchema,
	createConversationGraphQl: canvasObjectResponseSchema,
	getSingleConversation: canvasObjectResponseSchema,
	editConversation: canvasObjectResponseSchema,
	deleteConversations: canvasObjectResponseSchema,
	deleteConversationMessages: canvasObjectResponseSchema,
	deleteAMessage: canvasObjectResponseSchema,
	addConversationMessage: canvasObjectResponseSchema,
	addRecipientsToConversation: canvasObjectResponseSchema,
	getUnreadCount: canvasObjectResponseSchema,
	findRecipients: canvasArrayResponseSchema,
	createBookmark: canvasObjectResponseSchema,
	getBookmark: canvasObjectResponseSchema,
	deleteBookmark: canvasObjectResponseSchema,
	createFiles: canvasObjectResponseSchema,
	copyFileToFolder: canvasObjectResponseSchema,
	deleteFile: canvasObjectResponseSchema,
	getFolderById: canvasObjectResponseSchema,
	createFolder: canvasObjectResponseSchema,
	createFolderInGroup: canvasObjectResponseSchema,
	copyFolder: canvasObjectResponseSchema,
	deleteFolder: canvasObjectResponseSchema,
	getGroupFolder: canvasObjectResponseSchema,
	getQuotaInformation: canvasObjectResponseSchema,
	createGroup: canvasObjectResponseSchema,
	getGroup: canvasObjectResponseSchema,
	deleteGroup: canvasObjectResponseSchema,
	addGroupToFavorites: canvasObjectResponseSchema,
	getGroupPermissions: canvasObjectResponseSchema,
	getGroupActivityStreamSummary: canvasObjectResponseSchema,
	createGroupCategoryCourses: canvasObjectResponseSchema,
	createGroupSet: canvasObjectResponseSchema,
	createGroupInSet: canvasObjectResponseSchema,
	assignUnassignedMembersToGroupCategory: canvasObjectResponseSchema,
	createMembership: canvasObjectResponseSchema,
	getASingleGroupMembership: canvasObjectResponseSchema,
	getASingleGroupMembership2: canvasObjectResponseSchema,
	createCourseGradingStandard: canvasObjectResponseSchema,
	getSingleGradingStandardIn2: canvasObjectResponseSchema,
	deleteCustomGradeStatus: canvasObjectResponseSchema,
	createCustomGradebookColumn: canvasObjectResponseSchema,
	deleteCustomGradebookColumn: canvasObjectResponseSchema,
	updateCustomGradebookColumnData: canvasObjectResponseSchema,
	deleteCommentBankItem: canvasObjectResponseSchema,
	getALatePolicy: canvasObjectResponseSchema,
	createExternalTool: canvasObjectResponseSchema,
	createExternalToolInCourse: canvasObjectResponseSchema,
	getSingleExternalTool: canvasObjectResponseSchema,
	getASingleExternalTool2: canvasObjectResponseSchema,
	deleteAnExternalTool: canvasObjectResponseSchema,
	createLtiResourceLink: canvasObjectResponseSchema,
	createExternalFeed: canvasObjectResponseSchema,
	createExternalFeedForGroup: canvasObjectResponseSchema,
	deleteExternalFeedFromGroup: canvasObjectResponseSchema,
	createPlannerNote: canvasObjectResponseSchema,
	deletePlannerNote: canvasObjectResponseSchema,
	createPlannerOverride: canvasObjectResponseSchema,
	deletePlannerOverride: canvasObjectResponseSchema,
	createCommunicationChannel: canvasObjectResponseSchema,
	deleteCommunicationChannel: canvasObjectResponseSchema,
	deleteCommunicationChannelByTypeAndAddress: canvasObjectResponseSchema,
	createContentShare: canvasObjectResponseSchema,
	getContentShare: canvasObjectResponseSchema,
	addUsersToContentShare: canvasObjectResponseSchema,
	getContentSharesUnreadCount: canvasObjectResponseSchema,
	createGroupContentMigration: canvasObjectResponseSchema,
	getAContentMigration3: canvasObjectResponseSchema,
	createAContentMigration4: canvasObjectResponseSchema,
	getAContentMigration4: canvasObjectResponseSchema,
	exportContent: canvasObjectResponseSchema,
	exportGroupContent: canvasObjectResponseSchema,
	exportUserContent: canvasObjectResponseSchema,
	createLearningOutcome: canvasObjectResponseSchema,
	getOutcomeResults: canvasObjectResponseSchema,
	getAlignedAssignmentsForAnOutcome: canvasObjectResponseSchema,
	deleteOutcomeLinks: canvasObjectResponseSchema,
	getAllOutcomeGroupsForContext: canvasArrayResponseSchema,
	getAllOutcomeGroupsForContext2: canvasArrayResponseSchema,
	getAllOutcomeLinksForContext: canvasArrayResponseSchema,
	getAllOutcomeLinksForContext2: canvasArrayResponseSchema,
	getGlobalOutcomeGroup: canvasObjectResponseSchema,
	getRootOutcomeGroupForCourse: canvasObjectResponseSchema,
	getAccountsOutcomeGroups: canvasArrayResponseSchema,
	createSubgroupCourses: canvasObjectResponseSchema,
	deleteAnOutcomeGroupCourses: canvasObjectResponseSchema,
	createLinkOutcomeCourses: canvasObjectResponseSchema,
	createSinglePoll: canvasObjectResponseSchema,
	getSinglePoll: canvasObjectResponseSchema,
	deletePoll: canvasObjectResponseSchema,
	createSinglePollChoice: canvasObjectResponseSchema,
	getSinglePollChoice: canvasObjectResponseSchema,
	deletePollChoice: canvasObjectResponseSchema,
	createSinglePollSession: canvasObjectResponseSchema,
	deletePollSession: canvasObjectResponseSchema,
	createSinglePollSubmission: canvasObjectResponseSchema,
	createBlackoutDateForCourse: canvasObjectResponseSchema,
	deleteBlackoutDate: canvasObjectResponseSchema,
	getAllEPortfoliosForUser: canvasArrayResponseSchema,
	createEpubExport: canvasObjectResponseSchema,
	clearCourseNicknames: canvasObjectResponseSchema,
	getAuthenticationProvider: canvasObjectResponseSchema,
	getCoursesBlueprint: canvasArrayResponseSchema,
	getBrandVariables: canvasObjectResponseSchema,
	getKalturaConfig: canvasObjectResponseSchema,
	getInternalSettings: canvasObjectResponseSchema,
	getAuditLogs: canvasObjectResponseSchema,
	getStatusOfLastReport: canvasObjectResponseSchema,
	fetchData: canvasObjectResponseSchema,
	getLegacyNode: canvasObjectResponseSchema,
} as const satisfies { [K in CanvasOperationName]: z.ZodType<unknown> };
