"""Agenty Composio slug -> (method, path, hostType) mappings for all 79 operations."""

from __future__ import annotations

# hostType: main (https://api.agenty.com/v2) | browser (https://browser.agenty.com/api)
RAW_ROUTES: list[tuple[str, str, str, str]] = [
    ("AGENTY_ADD_LIST_ROWS", "POST", "/lists/{list_id}/rows", "main"),
    ("AGENTY_AGENTS_CONTROLLER_CREATE_AGENT", "POST", "/agents", "main"),
    ("AGENTY_AGENTS_CONTROLLER_GET_TEMPLATES", "GET", "/agents/templates", "main"),
    ("AGENTY_AGENTS_DELETE_BY_ID", "DELETE", "/agents/{agent_id}", "main"),
    ("AGENTY_AGENTS_GET_ALL", "GET", "/agents", "main"),
    ("AGENTY_AGENTS_GET_BY_ID", "GET", "/agents/{agent_id}", "main"),
    ("AGENTY_AGENTS_UPDATE_BY_ID", "PUT", "/agents/{agent_id}", "main"),
    ("AGENTY_API_KEYS_CONTROLLER_CREATE_API_KEYS", "POST", "/apikeys", "main"),
    ("AGENTY_API_KEYS_DELETE_BY_ID", "DELETE", "/apikeys", "main"),
    ("AGENTY_API_KEYS_DOWNLOAD", "GET", "/apikeys/download", "main"),
    ("AGENTY_API_KEYS_GET_ALL", "GET", "/apikeys", "main"),
    ("AGENTY_API_KEYS_GET_BY_ID", "GET", "/apikeys/{key_id}", "main"),
    ("AGENTY_API_KEYS_RESET_BY_ID", "GET", "/apikeys/{key_id}/reset", "main"),
    ("AGENTY_API_KEYS_UPDATE_BY_ID", "PUT", "/apikeys/{key_id}", "main"),
    ("AGENTY_CAPTURE_SCREENSHOT", "GET", "/screenshot", "browser"),
    ("AGENTY_CAPTURE_SCREENSHOT_WITH_OPTIONS", "POST", "/screenshot", "browser"),
    ("AGENTY_CHANGE_API_KEY_STATUS_BY_ID", "GET", "/apikeys/{key_id}/status", "main"),
    ("AGENTY_CONNECTIONS_GET_ALL", "GET", "/connections", "main"),
    ("AGENTY_CONVERT_URL_TO_PDF", "GET", "/pdf", "browser"),
    ("AGENTY_CONVERT_URL_TO_PDF_WITH_OPTIONS", "POST", "/pdf", "browser"),
    ("AGENTY_COPY_AGENT", "GET", "/agents/{agent_id}/clone", "main"),
    ("AGENTY_CREATE_WORKFLOW", "POST", "/workflows", "main"),
    ("AGENTY_DASHBOARD_GET_REPORTS_USAGE", "GET", "/dashboard", "main"),
    ("AGENTY_DELETE_LIST_ROW", "DELETE", "/lists/{list_id}/rows/{id}", "main"),
    ("AGENTY_DELETE_LIST_ROWS", "DELETE", "/lists/{list_id}/rows", "main"),
    ("AGENTY_DELETE_PROJECT", "DELETE", "/projects", "main"),
    ("AGENTY_DELETE_SCHEDULE", "DELETE", "/scheduler/{agent_id}", "main"),
    ("AGENTY_DELETE_WORKFLOW", "DELETE", "/workflows/{id}", "main"),
    ("AGENTY_DOWNLOAD_AGENT_RESULT", "GET", "/results/{agent_id}/download", "main"),
    ("AGENTY_DOWNLOAD_LIST_ROWS", "GET", "/lists/{list_id}/rows/download", "main"),
    ("AGENTY_DOWNLOAD_USERS", "GET", "/users/download", "main"),
    ("AGENTY_DOWNLOAD_WORKFLOWS", "GET", "/workflows/download", "main"),
    ("AGENTY_EXTRACT_BROWSER_STRUCTURED_DATA", "POST", "/extract", "browser"),
    ("AGENTY_EXTRACT_STRUCTURED_DATA", "GET", "/extract", "browser"),
    ("AGENTY_GET_AGENT_RESULT", "GET", "/results/{agent_id}", "main"),
    ("AGENTY_GET_ALL_TEAM_MEMBERS", "GET", "/users", "main"),
    ("AGENTY_GET_BROWSER_REDIRECTS", "GET", "/redirects", "browser"),
    ("AGENTY_GET_JOB_RESULT", "GET", "/jobs/{job_id}/result", "main"),
    ("AGENTY_GET_LIST_BY_ID", "GET", "/lists/{list_id}", "main"),
    ("AGENTY_GET_LIST_ROW_BY_ID", "GET", "/lists/{list_id}/rows/{id}", "main"),
    ("AGENTY_GET_PAGE_CONTENT", "GET", "/content", "browser"),
    ("AGENTY_GET_PAGE_CONTENT_WITH_OPTIONS", "POST", "/content", "browser"),
    ("AGENTY_GET_PROJECT_BY_ID", "GET", "/projects/{id}", "main"),
    ("AGENTY_GET_REDIRECTS_WITH_OPTIONS", "POST", "/redirects", "browser"),
    ("AGENTY_GET_SCHEDULE", "GET", "/scheduler/{agent_id}", "main"),
    ("AGENTY_GET_USER_BY_ID", "GET", "/users/{user_id}", "main"),
    ("AGENTY_GET_WORKFLOW_BY_ID", "GET", "/workflows/{id}", "main"),
    ("AGENTY_INPUTS_GET_BY_AGENT_ID", "GET", "/inputs/{agent_id}", "main"),
    ("AGENTY_INPUTS_UPDATE_BY_AGENT_ID", "PUT", "/inputs/{agent_id}", "main"),
    ("AGENTY_JOBS_DOWNLOAD", "GET", "/jobs/download", "main"),
    ("AGENTY_JOBS_DOWNLOAD_FILES_BY_ID", "GET", "/jobs/{job_id}/files/download", "main"),
    ("AGENTY_JOBS_DOWNLOAD_RESULT_BY_ID", "GET", "/jobs/{job_id}/result/download", "main"),
    ("AGENTY_JOBS_GET_ALL", "GET", "/jobs", "main"),
    ("AGENTY_JOBS_GET_BY_ID", "GET", "/jobs/{job_id}", "main"),
    ("AGENTY_JOBS_GET_LOGS_BY_ID", "GET", "/jobs/{job_id}/logs", "main"),
    ("AGENTY_JOBS_LIST_FILES_BY_ID", "GET", "/jobs/{job_id}/files", "main"),
    ("AGENTY_JOBS_START", "POST", "/jobs/start", "main"),
    ("AGENTY_JOBS_STOP_BY_ID", "GET", "/jobs/{job_id}/stop", "main"),
    ("AGENTY_LISTS_CLEAR_ROWS", "DELETE", "/lists/{list_id}/rows/clear", "main"),
    ("AGENTY_LISTS_CONTROLLER_CREATE_LIST", "POST", "/lists", "main"),
    ("AGENTY_LISTS_DELETE_BY_ID", "DELETE", "/lists/{id}", "main"),
    ("AGENTY_LISTS_DOWNLOAD", "GET", "/lists/download", "main"),
    ("AGENTY_LISTS_GET_ALL", "GET", "/lists", "main"),
    ("AGENTY_LISTS_GET_ROWS_BY_ID", "GET", "/lists/{list_id}/rows", "main"),
    ("AGENTY_LISTS_UPDATE_BY_ID", "PUT", "/lists/{list_id}", "main"),
    ("AGENTY_LISTS_UPLOAD_CSV", "POST", "/lists/{list_id}/upload", "main"),
    ("AGENTY_PATCH_WORKFLOW", "PATCH", "/workflows/{id}", "main"),
    ("AGENTY_PROJECTS_ADD_AGENTS", "POST", "/projects/{id}/add", "main"),
    ("AGENTY_PROJECTS_CONTROLLER_CREATE_PROJECT", "POST", "/projects", "main"),
    ("AGENTY_PROJECTS_GET_ALL", "GET", "/projects", "main"),
    ("AGENTY_REMOVE_AGENT_FROM_PROJECT", "DELETE", "/projects/{id}/delete", "main"),
    ("AGENTY_SCRAPE_WEBPAGE_DATA", "POST", "/scrape", "browser"),
    ("AGENTY_TOGGLE_SCHEDULE", "PATCH", "/scheduler/{agent_id}", "main"),
    ("AGENTY_TRANSFER_AGENT_OWNERSHIP", "PUT", "/agents/{agent_id}/transfer", "main"),
    ("AGENTY_UPDATE_LIST_ROW", "PUT", "/lists/{list_id}/rows/{id}", "main"),
    ("AGENTY_UPDATE_PROJECT", "PUT", "/projects/{id}", "main"),
    ("AGENTY_UPDATE_SCHEDULE", "POST", "/scheduler/{agent_id}", "main"),
    ("AGENTY_UPDATE_USER_BY_ID", "PUT", "/users/{user_id}", "main"),
    ("AGENTY_UPDATE_WORKFLOW", "PUT", "/workflows/{id}", "main"),
]

MANUAL_ROUTES: dict[str, tuple[str, str, str]] = {
    slug: (method, path, host) for slug, method, path, host in RAW_ROUTES
}
