import { z } from 'zod';

const FileCapabilities = z.object({
	canAddChildren: z.boolean().optional(),
	canChangeCopyRequiresWriterPermission: z.boolean().optional(),
	canChangeViewersCanCopyContent: z.boolean().optional(),
	canComment: z.boolean().optional(),
	canCopy: z.boolean().optional(),
	canDelete: z.boolean().optional(),
	canDeleteChildren: z.boolean().optional(),
	canDownload: z.boolean().optional(),
	canEdit: z.boolean().optional(),
	canListChildren: z.boolean().optional(),
	canModifyContent: z.boolean().optional(),
	canModifyContentRestriction: z.boolean().optional(),
	canMoveChildrenOutOfDrive: z.boolean().optional(),
	canMoveChildrenOutOfTeamDrive: z.boolean().optional(),
	canMoveChildrenWithinDrive: z.boolean().optional(),
	canMoveItemIntoTeamDrive: z.boolean().optional(),
	canMoveItemOutOfDrive: z.boolean().optional(),
	canMoveItemWithinDrive: z.boolean().optional(),
	canReadRevisions: z.boolean().optional(),
	canReadTeamDrive: z.boolean().optional(),
	canRemoveChildren: z.boolean().optional(),
	canRename: z.boolean().optional(),
	canShare: z.boolean().optional(),
	canTrash: z.boolean().optional(),
	canTrashChildren: z.boolean().optional(),
	canUntrash: z.boolean().optional(),
});

export const GoogleDriveFile = z.object({
	id: z.string(),
	name: z.string().optional(),
	mimeType: z.string().optional(),
	description: z.string().optional(),
	starred: z.boolean().optional(),
	trashed: z.boolean().optional(),
	explicitlyTrashed: z.boolean().optional(),
	parents: z.array(z.string()).optional(),
	properties: z.record(z.string()).optional(),
	appProperties: z.record(z.string()).optional(),
	spaces: z.array(z.string()).optional(),
	version: z.string().optional(),
	webViewLink: z.string().optional(),
	webContentLink: z.string().optional(),
	iconLink: z.string().optional(),
	hasThumbnail: z.boolean().optional(),
	thumbnailLink: z.string().optional(),
	thumbnailVersion: z.string().optional(),
	viewedByMe: z.boolean().optional(),
	viewedByMeTime: z.string().optional(),
	createdTime: z.string().optional(),
	modifiedTime: z.string().optional(),
	modifiedByMeTime: z.string().optional(),
	modifiedByMe: z.boolean().optional(),
	shared: z.boolean().optional(),
	ownedByMe: z.boolean().optional(),
	capabilities: FileCapabilities.optional(),
	viewersCanCopyContent: z.boolean().optional(),
	copyRequiresWriterPermission: z.boolean().optional(),
	writersCanShare: z.boolean().optional(),
	permissionIds: z.array(z.string()).optional(),
	hasAugmentedPermissions: z.boolean().optional(),
	folderColorRgb: z.string().optional(),
	originalFilename: z.string().optional(),
	fullFileExtension: z.string().optional(),
	fileExtension: z.string().optional(),
	md5Checksum: z.string().optional(),
	size: z.string().optional(),
	quotaBytesUsed: z.string().optional(),
	headRevisionId: z.string().optional(),
	isAppAuthorized: z.boolean().optional(),
	resourceKey: z.string().optional(),
	sha1Checksum: z.string().optional(),
	sha256Checksum: z.string().optional(),
	createdAt: z.coerce.date().optional(),
});

export const GoogleDriveFolder = z.object({
	id: z.string(),
	name: z.string().optional(),
	mimeType: z.string().optional(),
	description: z.string().optional(),
	starred: z.boolean().optional(),
	trashed: z.boolean().optional(),
	explicitlyTrashed: z.boolean().optional(),
	parents: z.array(z.string()).optional(),
	properties: z.record(z.string()).optional(),
	appProperties: z.record(z.string()).optional(),
	spaces: z.array(z.string()).optional(),
	version: z.string().optional(),
	webViewLink: z.string().optional(),
	webContentLink: z.string().optional(),
	iconLink: z.string().optional(),
	hasThumbnail: z.boolean().optional(),
	thumbnailLink: z.string().optional(),
	thumbnailVersion: z.string().optional(),
	viewedByMe: z.boolean().optional(),
	viewedByMeTime: z.string().optional(),
	createdTime: z.string().optional(),
	modifiedTime: z.string().optional(),
	modifiedByMeTime: z.string().optional(),
	modifiedByMe: z.boolean().optional(),
	shared: z.boolean().optional(),
	ownedByMe: z.boolean().optional(),
	capabilities: FileCapabilities.optional(),
	viewersCanCopyContent: z.boolean().optional(),
	copyRequiresWriterPermission: z.boolean().optional(),
	writersCanShare: z.boolean().optional(),
	permissionIds: z.array(z.string()).optional(),
	hasAugmentedPermissions: z.boolean().optional(),
	folderColorRgb: z.string().optional(),
	createdAt: z.coerce.date().optional(),
});

export const GoogleDriveSharedDrive = z.object({
	id: z.string(),
	name: z.string().optional(),
	themeId: z.string().optional(),
	colorRgb: z.string().optional(),
	createdTime: z.string().optional(),
	hidden: z.boolean().optional(),
	createdAt: z.coerce.date().optional(),
});

export type GoogleDriveFile = z.infer<typeof GoogleDriveFile>;
export type GoogleDriveFolder = z.infer<typeof GoogleDriveFolder>;
export type GoogleDriveSharedDrive = z.infer<typeof GoogleDriveSharedDrive>;
