/* eslint-disable */
import { boolean, integer, jsonb, pgTable, text, timestamp } from 'drizzle-orm/pg-core';

// This file is generated by Corsair. Do not edit by hand.

export const user = pgTable('user', {
		id: text('id').primaryKey(),
		createdAt: timestamp('createdAt', { withTimezone: true }).notNull().defaultNow(),
		updatedAt: timestamp('updatedAt', { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
		name: text('name').notNull(),
		email: text('email').notNull().unique(),
		emailVerified: boolean('emailVerified').notNull(),
		image: text('image'),
});

export const session = pgTable('session', {
		id: text('id').primaryKey(),
		createdAt: timestamp('createdAt', { withTimezone: true }).notNull().defaultNow(),
		updatedAt: timestamp('updatedAt', { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
		expiresAt: timestamp('expiresAt', { withTimezone: true }).notNull(),
		token: text('token').notNull().unique(),
		ipAddress: text('ipAddress'),
		userAgent: text('userAgent'),
		userId: text('userId').notNull().references(() => user.id, { onDelete: 'cascade' }),
});

export const account = pgTable('account', {
		id: text('id').primaryKey(),
		createdAt: timestamp('createdAt', { withTimezone: true }).notNull().defaultNow(),
		updatedAt: timestamp('updatedAt', { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
		accountId: text('accountId').notNull(),
		providerId: text('providerId').notNull(),
		userId: text('userId').notNull().references(() => user.id, { onDelete: 'cascade' }),
		accessToken: text('accessToken'),
		refreshToken: text('refreshToken'),
		idToken: text('idToken'),
		accessTokenExpiresAt: timestamp('accessTokenExpiresAt', { withTimezone: true }),
		refreshTokenExpiresAt: timestamp('refreshTokenExpiresAt', { withTimezone: true }),
		scope: text('scope'),
});

export const verification = pgTable('verification', {
		id: text('id').primaryKey(),
		createdAt: timestamp('createdAt', { withTimezone: true }).notNull().defaultNow(),
		updatedAt: timestamp('updatedAt', { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
		identifier: text('identifier').notNull(),
		value: text('value').notNull(),
		expiresAt: timestamp('expiresAt', { withTimezone: true }).notNull(),
});

export const slackMember = pgTable('slackMember', {
		id: text('id').primaryKey(),
		createdAt: timestamp('createdAt', { withTimezone: true }).notNull().defaultNow(),
		updatedAt: timestamp('updatedAt', { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
		teamId: text('teamId').notNull(),
		slackId: text('slackId').notNull().unique(),
		name: text('name'),
		realName: text('realName'),
		email: text('email'),
		image: text('image'),
		isBot: boolean('isBot').notNull(),
		deleted: boolean('deleted').notNull(),
});

