import type { SupabaseOperation } from '../endpoints/operation-types';

export const authOperations = [
	{
		key: 'createSsoProvider',
		group: 'auth',
		name: 'createSsoProvider',
		method: 'POST',
		path: '/v1/projects/{ref}/config/auth/sso/providers',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Create an SSO provider',
	},
	{
		key: 'createThirdPartyAuthIntegration',
		group: 'auth',
		name: 'createThirdPartyAuthIntegration',
		method: 'POST',
		path: '/v1/projects/{ref}/config/auth/third-party-auth',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Create a third-party auth integration',
	},
	{
		key: 'createProjectSigningKey',
		group: 'auth',
		name: 'createProjectSigningKey',
		method: 'POST',
		path: '/v1/projects/{ref}/config/auth/signing-keys',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Create a project signing key',
	},
	{
		key: 'deleteThirdPartyAuthIntegration',
		group: 'auth',
		name: 'deleteThirdPartyAuthIntegration',
		method: 'DELETE',
		path: '/v1/projects/{ref}/config/auth/third-party-auth/{tpaId}',
		pathParams: ['ref', 'tpaId'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Delete a third-party auth integration',
	},
	{
		key: 'getSsoProvider',
		group: 'auth',
		name: 'getSsoProvider',
		method: 'GET',
		path: '/v1/projects/{ref}/config/auth/sso/providers/{providerId}',
		pathParams: ['ref', 'providerId'],
		riskLevel: 'read',
		description: 'Get an SSO provider',
	},
	{
		key: 'getThirdPartyIntegration',
		group: 'auth',
		name: 'getThirdPartyIntegration',
		method: 'GET',
		path: '/v1/projects/{ref}/config/auth/third-party-auth/{tpaId}',
		pathParams: ['ref', 'tpaId'],
		riskLevel: 'read',
		description: 'Get a third-party auth integration',
	},
	{
		key: 'getLegacySigningKey',
		group: 'auth',
		name: 'getLegacySigningKey',
		method: 'GET',
		path: '/v1/projects/{ref}/config/auth/signing-keys/legacy',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get legacy signing key',
	},
	{
		key: 'getProjectSigningKeys',
		group: 'auth',
		name: 'getProjectSigningKeys',
		method: 'GET',
		path: '/v1/projects/{ref}/config/auth/signing-keys',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get project signing keys',
	},
	{
		key: 'getProjectAuthConfig',
		group: 'auth',
		name: 'getProjectAuthConfig',
		method: 'GET',
		path: '/v1/projects/{ref}/config/auth',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get project auth config',
	},
	{
		key: 'listSsoProviders',
		group: 'auth',
		name: 'listSsoProviders',
		method: 'GET',
		path: '/v1/projects/{ref}/config/auth/sso/providers',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'List SSO providers',
	},
	{
		key: 'listThirdPartyAuthIntegrations',
		group: 'auth',
		name: 'listThirdPartyAuthIntegrations',
		method: 'GET',
		path: '/v1/projects/{ref}/config/auth/third-party-auth',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'List third-party auth integrations',
	},
	{
		key: 'deleteSsoProvider',
		group: 'auth',
		name: 'deleteSsoProvider',
		method: 'DELETE',
		path: '/v1/projects/{ref}/config/auth/sso/providers/{providerId}',
		pathParams: ['ref', 'providerId'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Remove an SSO provider',
	},
	{
		key: 'updateSsoProvider',
		group: 'auth',
		name: 'updateSsoProvider',
		method: 'PUT',
		path: '/v1/projects/{ref}/config/auth/sso/providers/{providerId}',
		pathParams: ['ref', 'providerId'],
		riskLevel: 'write',
		description: 'Update an SSO provider',
	},
	{
		key: 'updateProjectAuthConfig',
		group: 'auth',
		name: 'updateProjectAuthConfig',
		method: 'PATCH',
		path: '/v1/projects/{ref}/config/auth',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Update project auth config',
	},
] as const satisfies readonly SupabaseOperation[];
