import type { SupabaseOperation } from '../endpoints/operation-types';

export const edgeFunctionOperations = [
	{
		key: 'updateFunctions',
		group: 'edgeFunctions',
		name: 'updateFunctions',
		method: 'PUT',
		path: '/v1/projects/{ref}/functions',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Bulk update Edge Functions',
	},
	{
		key: 'createFunction',
		group: 'edgeFunctions',
		name: 'createFunction',
		method: 'POST',
		path: '/v1/projects/{ref}/functions',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Create an Edge Function',
	},
	{
		key: 'deleteFunction',
		group: 'edgeFunctions',
		name: 'deleteFunction',
		method: 'DELETE',
		path: '/v1/projects/{ref}/functions/{functionSlug}',
		pathParams: ['ref', 'functionSlug'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Delete an Edge Function',
	},
	{
		key: 'deployFunction',
		group: 'edgeFunctions',
		name: 'deployFunction',
		method: 'POST',
		path: '/v1/projects/{ref}/functions/deploy',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Deploy an Edge Function',
	},
	{
		key: 'invokeEdgeFunction',
		group: 'edgeFunctions',
		name: 'invokeEdgeFunction',
		method: 'POST',
		path: '/functions/v1/{functionSlug}',
		kind: 'project',
		pathParams: ['ref', 'functionSlug'],
		riskLevel: 'write',
		description: 'Invoke an Edge Function',
	},
	{
		key: 'listFunctions',
		group: 'edgeFunctions',
		name: 'listFunctions',
		method: 'GET',
		path: '/v1/projects/{ref}/functions',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'List Edge Functions',
	},
	{
		key: 'getFunction',
		group: 'edgeFunctions',
		name: 'getFunction',
		method: 'GET',
		path: '/v1/projects/{ref}/functions/{functionSlug}',
		pathParams: ['ref', 'functionSlug'],
		riskLevel: 'read',
		description: 'Retrieve an Edge Function',
	},
	{
		key: 'getFunctionBody',
		group: 'edgeFunctions',
		name: 'getFunctionBody',
		method: 'GET',
		path: '/v1/projects/{ref}/functions/{functionSlug}/body',
		pathParams: ['ref', 'functionSlug'],
		riskLevel: 'read',
		description: 'Retrieve an Edge Function body',
	},
	{
		key: 'updateFunction',
		group: 'edgeFunctions',
		name: 'updateFunction',
		method: 'PATCH',
		path: '/v1/projects/{ref}/functions/{functionSlug}',
		pathParams: ['ref', 'functionSlug'],
		riskLevel: 'write',
		description: 'Update an Edge Function',
	},
] as const satisfies readonly SupabaseOperation[];
