import type { SupabaseOperation } from '../endpoints/operation-types';

export const projectsOperations = [
	{
		key: 'updateProjectNetworkRestrictions',
		group: 'projects',
		name: 'updateProjectNetworkRestrictions',
		method: 'POST',
		path: '/v1/projects/{ref}/network-restrictions/apply',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Apply project network restrictions',
	},
	{
		key: 'createProject',
		group: 'projects',
		name: 'createProject',
		method: 'POST',
		path: '/v1/projects',
		riskLevel: 'write',
		description: 'Create a project',
	},
	{
		key: 'deleteProject',
		group: 'projects',
		name: 'deleteProject',
		method: 'DELETE',
		path: '/v1/projects/{ref}',
		pathParams: ['ref'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Delete a project',
	},
	{
		key: 'getHealth',
		group: 'projects',
		name: 'getHealth',
		method: 'GET',
		path: '/v1/projects/{ref}/health',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get project API health status',
	},
	{
		key: 'getAvailableRegions',
		group: 'projects',
		name: 'getAvailableRegions',
		method: 'GET',
		path: '/v1/projects/available-regions',
		riskLevel: 'read',
		description: 'Get available project regions',
	},
	{
		key: 'getProjectUpgradeEligibility',
		group: 'projects',
		name: 'getProjectUpgradeEligibility',
		method: 'GET',
		path: '/v1/projects/{ref}/upgrade/eligibility',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get project upgrade eligibility',
	},
	{
		key: 'getProject',
		group: 'projects',
		name: 'getProject',
		method: 'GET',
		path: '/v1/projects/{ref}',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get a project',
	},
	{
		key: 'getProjectNetworkRestrictions',
		group: 'projects',
		name: 'getProjectNetworkRestrictions',
		method: 'GET',
		path: '/v1/projects/{ref}/network-restrictions',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get project network restrictions',
	},
	{
		key: 'getProjectUpgradeStatus',
		group: 'projects',
		name: 'getProjectUpgradeStatus',
		method: 'GET',
		path: '/v1/projects/{ref}/upgrade/status',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get project upgrade status',
	},
	{
		key: 'getProjectServiceHealthStatus',
		group: 'projects',
		name: 'getProjectServiceHealthStatus',
		method: 'GET',
		path: '/v1/projects/{ref}/health',
		pathParams: ['ref'],
		defaultQuery: { services: 'auth,db,pooler,realtime,rest,storage' },
		riskLevel: 'read',
		description: 'Get project service health status',
	},
	{
		key: 'listAllProjects',
		group: 'projects',
		name: 'listAllProjects',
		method: 'GET',
		path: '/v1/projects',
		riskLevel: 'read',
		description: 'List projects',
	},
	{
		key: 'patchNetworkRestrictions',
		group: 'projects',
		name: 'patchNetworkRestrictions',
		method: 'PATCH',
		path: '/v1/projects/{ref}/network-restrictions',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Patch project network restrictions',
	},
	{
		key: 'removeNetworkBans',
		group: 'projects',
		name: 'removeNetworkBans',
		method: 'DELETE',
		path: '/v1/projects/{ref}/network-bans',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Remove project network bans',
	},
	{
		key: 'getProjectNetworkBans',
		group: 'projects',
		name: 'getProjectNetworkBans',
		method: 'POST',
		path: '/v1/projects/{ref}/network-bans/retrieve',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Retrieve project network bans',
	},
	{
		key: 'updateProject',
		group: 'projects',
		name: 'updateProject',
		method: 'PATCH',
		path: '/v1/projects/{ref}',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Update a project',
	},
	{
		key: 'upgradeProjectPostgresVersion',
		group: 'projects',
		name: 'upgradeProjectPostgresVersion',
		method: 'POST',
		path: '/v1/projects/{ref}/upgrade',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Upgrade project PostgreSQL version',
	},
] as const satisfies readonly SupabaseOperation[];
