import type { SupabaseOperation } from '../endpoints/operation-types';

export const secretsOperations = [
	{
		key: 'createBulkSecrets',
		group: 'secrets',
		name: 'createBulkSecrets',
		method: 'POST',
		path: '/v1/projects/{ref}/secrets',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Create multiple project secrets',
	},
	{
		key: 'deleteSecrets',
		group: 'secrets',
		name: 'deleteSecrets',
		method: 'DELETE',
		path: '/v1/projects/{ref}/secrets',
		pathParams: ['ref'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Delete multiple project secrets',
	},
	{
		key: 'createApiKey',
		group: 'secrets',
		name: 'createApiKey',
		method: 'POST',
		path: '/v1/projects/{ref}/api-keys',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Create a project API key',
	},
	{
		key: 'deleteApiKey',
		group: 'secrets',
		name: 'deleteApiKey',
		method: 'DELETE',
		path: '/v1/projects/{ref}/api-keys/{id}',
		pathParams: ['ref', 'id'],
		riskLevel: 'destructive',
		irreversible: true,
		description: 'Delete a project API key',
	},
	{
		key: 'getProjectApiKey',
		group: 'secrets',
		name: 'getProjectApiKey',
		method: 'GET',
		path: '/v1/projects/{ref}/api-keys/{id}',
		pathParams: ['ref', 'id'],
		riskLevel: 'read',
		defaultQuery: { reveal: false },
		description: 'Get a project API key',
	},
	{
		key: 'getProjectApiKeys',
		group: 'secrets',
		name: 'getProjectApiKeys',
		method: 'GET',
		path: '/v1/projects/{ref}/api-keys',
		pathParams: ['ref'],
		riskLevel: 'read',
		defaultQuery: { reveal: false },
		description: 'Get project API keys',
	},
	{
		key: 'getProjectLegacyApiKeys',
		group: 'secrets',
		name: 'getProjectLegacyApiKeys',
		method: 'GET',
		path: '/v1/projects/{ref}/api-keys/legacy',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get project legacy API keys status',
	},
	{
		key: 'getProjectPgsodiumConfig',
		group: 'secrets',
		name: 'getProjectPgsodiumConfig',
		method: 'GET',
		path: '/v1/projects/{ref}/pgsodium',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get project pgsodium config',
	},
	{
		key: 'listSecrets',
		group: 'secrets',
		name: 'listSecrets',
		method: 'GET',
		path: '/v1/projects/{ref}/secrets',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'List project secrets',
	},
	{
		key: 'updateApiKey',
		group: 'secrets',
		name: 'updateApiKey',
		method: 'PATCH',
		path: '/v1/projects/{ref}/api-keys/{id}',
		pathParams: ['ref', 'id'],
		riskLevel: 'write',
		description: 'Update a project API key',
	},
	{
		key: 'updatePgsodiumConfig',
		group: 'secrets',
		name: 'updatePgsodiumConfig',
		method: 'PUT',
		path: '/v1/projects/{ref}/pgsodium',
		pathParams: ['ref'],
		riskLevel: 'destructive',
		description: 'Update pgsodium root key',
	},
	{
		key: 'updateProjectLegacyApiKeys',
		group: 'secrets',
		name: 'updateProjectLegacyApiKeys',
		method: 'PUT',
		path: '/v1/projects/{ref}/api-keys/legacy',
		pathParams: ['ref'],
		riskLevel: 'write',
		description: 'Update project legacy API keys',
	},
] as const satisfies readonly SupabaseOperation[];
