import type { SupabaseOperation } from '../endpoints/operation-types';

export const storageOperations = [
	{
		key: 'getResumableUploadBaseOptions',
		group: 'storage',
		name: 'getResumableUploadBaseOptions',
		method: 'OPTIONS',
		path: '/storage/v1/upload/resumable',
		kind: 'project',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Get TUS resumable upload base options',
	},
	{
		key: 'getResumableUploadOptions',
		group: 'storage',
		name: 'getResumableUploadOptions',
		method: 'OPTIONS',
		path: '/storage/v1/upload/resumable/{uploadId}',
		kind: 'project',
		pathParams: ['ref', 'uploadId'],
		riskLevel: 'read',
		description: 'Get TUS resumable upload options',
	},
	{
		key: 'listBuckets',
		group: 'storage',
		name: 'listBuckets',
		method: 'GET',
		path: '/v1/projects/{ref}/storage/buckets',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'List storage buckets',
	},
	{
		key: 'handleResumableUploadSignOptionsWithId',
		group: 'storage',
		name: 'handleResumableUploadSignOptionsWithId',
		method: 'OPTIONS',
		path: '/storage/v1/upload/resumable/sign/{uploadId}',
		kind: 'project',
		pathParams: ['ref', 'uploadId'],
		riskLevel: 'read',
		description: 'Handle TUS resumable upload sign options with ID',
	},
	{
		key: 'handleResumableUploadSignOptions',
		group: 'storage',
		name: 'handleResumableUploadSignOptions',
		method: 'OPTIONS',
		path: '/storage/v1/upload/resumable/sign',
		kind: 'project',
		pathParams: ['ref'],
		riskLevel: 'read',
		description: 'Handle TUS resumable upload sign options',
	},
] as const satisfies readonly SupabaseOperation[];
