import {
	addGuestToProject,
	addMemberToProject,
	createAttachment,
	createColumn,
	createComment,
	createProject,
	createTask,
	createWebhook,
	deleteProject,
	listActiveProjects,
	listAttachments,
	listColumns,
	listProjects,
	listUsers,
	listWebhooks,
	showAttachment,
	showColumn,
	showOrganization,
	showProjectDetails,
	showUserProjects,
	showUserTasks,
	updateColumn,
	updateProject,
	updateTask,
	uploadAttachment,
} from './bugherd';

export const Bugherd = {
	addGuestToProject,
	addMemberToProject,
	createAttachment,
	createColumn,
	createComment,
	createProject,
	createTask,
	createWebhook,
	deleteProject,
	listActiveProjects,
	listAttachments,
	listColumns,
	listProjects,
	listUsers,
	listWebhooks,
	showAttachment,
	showColumn,
	showOrganization,
	showProjectDetails,
	showUserProjects,
	showUserTasks,
	updateColumn,
	updateProject,
	updateTask,
	uploadAttachment,
};

export * from './types';
