import {
	FinerWorksAddress,
	FinerWorksCompanyInfo,
	FinerWorksFrame,
	FinerWorksFrameCollection,
	FinerWorksGallery,
	FinerWorksGalleryTheme,
	FinerWorksGlazing,
	FinerWorksImage,
	FinerWorksMat,
	FinerWorksMediaType,
	FinerWorksOrder,
	FinerWorksOrderStatusDefinition,
	FinerWorksPrice,
	FinerWorksProductType,
	FinerWorksShipment,
	FinerWorksShippingOption,
	FinerWorksShippingQuote,
	FinerWorksStyleType,
	FinerWorksSubmittedOrder,
	FinerWorksUserAccount,
	FinerWorksVirtualInventoryProduct,
} from './database';

export const FinerWorksSchema = {
	version: '1.0.0',
	entities: {
		addresses: FinerWorksAddress,
		images: FinerWorksImage,
		virtualInventoryProducts: FinerWorksVirtualInventoryProduct,
		orders: FinerWorksOrder,
		shipments: FinerWorksShipment,
		orderStatusDefinitions: FinerWorksOrderStatusDefinition,
		prices: FinerWorksPrice,
		galleries: FinerWorksGallery,
		galleryThemes: FinerWorksGalleryTheme,
		frames: FinerWorksFrame,
		frameCollections: FinerWorksFrameCollection,
		glazing: FinerWorksGlazing,
		mats: FinerWorksMat,
		mediaTypes: FinerWorksMediaType,
		productTypes: FinerWorksProductType,
		styleTypes: FinerWorksStyleType,
		shippingOptions: FinerWorksShippingOption,
		userAccounts: FinerWorksUserAccount,
		companyInfo: FinerWorksCompanyInfo,
		submittedOrders: FinerWorksSubmittedOrder,
		shippingQuotes: FinerWorksShippingQuote,
	},
} as const;

export {
	FinerWorksAddress,
	FinerWorksCompanyInfo,
	FinerWorksConnection,
	FinerWorksDimensions,
	FinerWorksFrame,
	FinerWorksFrameCollection,
	FinerWorksGallery,
	FinerWorksGalleryTheme,
	FinerWorksGlazing,
	FinerWorksImage,
	FinerWorksMat,
	FinerWorksMediaType,
	FinerWorksMountingAddOn,
	FinerWorksOrder,
	FinerWorksOrderStatusDefinition,
	FinerWorksOrderTotals,
	FinerWorksPrice,
	FinerWorksProductPricing,
	FinerWorksProductType,
	FinerWorksShipment,
	FinerWorksShippingOption,
	FinerWorksShippingQuote,
	FinerWorksShippingQuoteOption,
	FinerWorksStyleType,
	FinerWorksSubmittedOrder,
	FinerWorksThirdPartyIntegrations,
	FinerWorksUserAccount,
	FinerWorksVirtualInventoryProduct,
} from './database';
