export type EndpointContractCase = {
	name: string;
	method: string;
	path: string;
	pathParams: string[];
	queryParams: Array<{ name: string; type: string; required: boolean }>;
	hasBody: boolean;
};

export const endpointContractCases: EndpointContractCase[] = [
	{
		name: 'addOrUpdateAccountStamps',
		method: 'POST',
		path: '/signatures',
		pathParams: [],
		queryParams: [
			{
				name: 'decode_only',
				type: 'string',
				required: false,
			},
		],
		hasBody: true,
	},
	{
		name: 'createAccountCustomField',
		method: 'POST',
		path: '/custom_fields',
		pathParams: [],
		queryParams: [
			{
				name: 'apply_to_templates',
				type: 'string',
				required: false,
			},
		],
		hasBody: true,
	},
	{
		name: 'createBccEmailArchiveConfiguration',
		method: 'POST',
		path: '/settings/bcc_email_archives',
		pathParams: [],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'deleteAccountCustomField',
		method: 'DELETE',
		path: '/custom_fields/{customFieldId}',
		pathParams: ['customFieldId'],
		queryParams: [
			{
				name: 'apply_to_templates',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'deleteAccountStamp',
		method: 'DELETE',
		path: '/signatures/{signatureId}',
		pathParams: ['signatureId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'deleteBccEmailArchiveConfiguration',
		method: 'DELETE',
		path: '/settings/bcc_email_archives/{bccEmailArchiveId}',
		pathParams: ['bccEmailArchiveId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'deleteEnoteConfiguration',
		method: 'DELETE',
		path: '/settings/enote_configuration',
		pathParams: [],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'deleteSignatureForCaptiveRecipients',
		method: 'DELETE',
		path: '/captive_recipients/{recipientPart}',
		pathParams: ['recipientPart'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'deleteSpecifiedAccount',
		method: 'DELETE',
		path: '',
		pathParams: [],
		queryParams: [
			{
				name: 'redact_user_data',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'deleteStampImageForAccount',
		method: 'DELETE',
		path: '/signatures/{signatureId}/{imageType}',
		pathParams: ['signatureId', 'imageType'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getAccountBillingChargesList',
		method: 'GET',
		path: '/billing_charges',
		pathParams: [],
		queryParams: [
			{
				name: 'include_charges',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'getAccountPasswordRules',
		method: 'GET',
		path: '/settings/password_rules',
		pathParams: [],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getAccountStampImage',
		method: 'GET',
		path: '/signatures/{signatureId}/{imageType}',
		pathParams: ['signatureId', 'imageType'],
		queryParams: [
			{
				name: 'include_chrome',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'getBccEmailArchiveConfigurations',
		method: 'GET',
		path: '/settings/bcc_email_archives',
		pathParams: [],
		queryParams: [
			{
				name: 'count',
				type: 'string',
				required: false,
			},
			{
				name: 'start_position',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'getBccemailArchiveHistory',
		method: 'GET',
		path: '/settings/bcc_email_archives/{bccEmailArchiveId}',
		pathParams: ['bccEmailArchiveId'],
		queryParams: [
			{
				name: 'count',
				type: 'string',
				required: false,
			},
			{
				name: 'start_position',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'getElectronicRecordAndSignatureDisclosure',
		method: 'GET',
		path: '/consumer_disclosure',
		pathParams: [],
		queryParams: [
			{
				name: 'langCode',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'getEnoteIntegrationSettings',
		method: 'GET',
		path: '/settings/enote_configuration',
		pathParams: [],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getSpecifiedAccountStampInfo',
		method: 'GET',
		path: '/signatures/{signatureId}',
		pathParams: ['signatureId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getSupportedLanguagesForRecipients',
		method: 'GET',
		path: '/supported_languages',
		pathParams: [],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getTabSettingsForAccount',
		method: 'GET',
		path: '/settings/tabs',
		pathParams: [],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getUnsupportedFileTypesList',
		method: 'GET',
		path: '/unsupported_file_types',
		pathParams: [],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getWatermarkDetailsForAccount',
		method: 'GET',
		path: '/watermark',
		pathParams: [],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'listSignatureProvidersForAccount',
		method: 'GET',
		path: '/signatureProviders',
		pathParams: [],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'modifyAccountNotificationSettings',
		method: 'PUT',
		path: '/settings/notification_defaults',
		pathParams: [],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'modifyTabSettingsForAccount',
		method: 'PUT',
		path: '/settings/tabs',
		pathParams: [],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'retrieveAccountEnvelopePurgeConfig',
		method: 'GET',
		path: '/settings/envelope_purge_configuration',
		pathParams: [],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'retrieveAccountInformationForSpecifiedAccount',
		method: 'GET',
		path: '',
		pathParams: [],
		queryParams: [
			{
				name: 'include_account_settings',
				type: 'string',
				required: false,
			},
			{
				name: 'include_trial_eligibility',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'retrieveAccountProvisioningInfo',
		method: 'GET',
		path: '/v2.1/accounts/provisioning',
		pathParams: [],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'retrieveAccountSealProviders',
		method: 'GET',
		path: '/seals',
		pathParams: [],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'retrieveAccountSettingsInformation',
		method: 'GET',
		path: '/settings',
		pathParams: [],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'retrieveAvailableAccountStamps',
		method: 'GET',
		path: '/signatures',
		pathParams: [],
		queryParams: [
			{
				name: 'stamp_format',
				type: 'string',
				required: false,
			},
			{
				name: 'stamp_name',
				type: 'string',
				required: false,
			},
			{
				name: 'stamp_type',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'retrieveSharedItemStatusForUsers',
		method: 'GET',
		path: '/shared_access',
		pathParams: [],
		queryParams: [
			{
				name: 'count',
				type: 'string',
				required: false,
			},
			{
				name: 'envelopes_not_shared_user_status',
				type: 'string',
				required: false,
			},
			{
				name: 'folder_ids',
				type: 'string',
				required: false,
			},
			{
				name: 'item_type',
				type: 'string',
				required: false,
			},
			{
				name: 'search_text',
				type: 'string',
				required: false,
			},
			{
				name: 'shared',
				type: 'string',
				required: false,
			},
			{
				name: 'start_position',
				type: 'string',
				required: false,
			},
			{
				name: 'user_ids',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'setEnvelopePurgeConfigForAccount',
		method: 'PUT',
		path: '/settings/envelope_purge_configuration',
		pathParams: [],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'setSharedAccessForUsersAndTemplates',
		method: 'PUT',
		path: '/shared_access',
		pathParams: [],
		queryParams: [
			{
				name: 'item_type',
				type: 'string',
				required: false,
			},
			{
				name: 'preserve_existing_shared_access',
				type: 'string',
				required: false,
			},
			{
				name: 'user_ids',
				type: 'string',
				required: false,
			},
		],
		hasBody: true,
	},
	{
		name: 'updateAccountCustomField',
		method: 'PUT',
		path: '/custom_fields/{customFieldId}',
		pathParams: ['customFieldId'],
		queryParams: [
			{
				name: 'apply_to_templates',
				type: 'string',
				required: false,
			},
		],
		hasBody: true,
	},
	{
		name: 'updateAccountPasswordRules',
		method: 'PUT',
		path: '/settings/password_rules',
		pathParams: [],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'updateAccountSettings',
		method: 'PUT',
		path: '/settings',
		pathParams: [],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'updateAccountStampById',
		method: 'PUT',
		path: '/signatures/{signatureId}',
		pathParams: ['signatureId'],
		queryParams: [
			{
				name: 'close_existing_signature',
				type: 'string',
				required: false,
			},
		],
		hasBody: true,
	},
	{
		name: 'updateAccountStamps',
		method: 'PUT',
		path: '/signatures',
		pathParams: [],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'updateAccountWatermarkInformation',
		method: 'PUT',
		path: '/watermark',
		pathParams: [],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'updateAccountWatermarkPreview',
		method: 'PUT',
		path: '/watermark/preview',
		pathParams: [],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'updateElectronicRecordDisclosure',
		method: 'PUT',
		path: '/consumer_disclosure/{langCode}',
		pathParams: ['langCode'],
		queryParams: [
			{
				name: 'include_metadata',
				type: 'string',
				required: false,
			},
		],
		hasBody: true,
	},
	{
		name: 'updateEnoteIntegrationConfig',
		method: 'PUT',
		path: '/settings/enote_configuration',
		pathParams: [],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'getDowngradePlanInfoForAccount',
		method: 'GET',
		path: '/billing_plan/downgrade',
		pathParams: [],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'listBillingInvoices',
		method: 'GET',
		path: '/billing_invoices',
		pathParams: [],
		queryParams: [
			{
				name: 'from_date',
				type: 'string',
				required: false,
			},
			{
				name: 'to_date',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'listPastDueInvoices',
		method: 'GET',
		path: '/billing_invoices_past_due',
		pathParams: [],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'listPaymentGatewayAccountsInfo',
		method: 'GET',
		path: '/payment_gateway_accounts',
		pathParams: [],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'postPaymentToInvoice',
		method: 'POST',
		path: '/billing_payments',
		pathParams: [],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'purchaseAdditionalEnvelopes',
		method: 'PUT',
		path: '/billing_plan/purchased_envelopes',
		pathParams: [],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'queueDowngradeBillingPlanRequest',
		method: 'PUT',
		path: '/billing_plan/downgrade',
		pathParams: [],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'retrieveAccountBillingPlan',
		method: 'GET',
		path: '/billing_plan',
		pathParams: [],
		queryParams: [
			{
				name: 'include_credit_card_information',
				type: 'string',
				required: false,
			},
			{
				name: 'include_downgrade_information',
				type: 'string',
				required: false,
			},
			{
				name: 'include_metadata',
				type: 'string',
				required: false,
			},
			{
				name: 'include_successor_plans',
				type: 'string',
				required: false,
			},
			{
				name: 'include_tax_exempt_id',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'retrieveBillingInvoice',
		method: 'GET',
		path: '/billing_invoices/{invoiceId}',
		pathParams: ['invoiceId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'retrieveBillingPaymentInfo',
		method: 'GET',
		path: '/billing_payments/{paymentId}',
		pathParams: ['paymentId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'retrieveCreditCardInfo',
		method: 'GET',
		path: '/billing_plan/credit_card',
		pathParams: [],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'retrieveListOfBillingPlans',
		method: 'GET',
		path: '/v2.1/billing_plans',
		pathParams: [],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'retrievePaymentInformationList',
		method: 'GET',
		path: '/billing_payments',
		pathParams: [],
		queryParams: [
			{
				name: 'from_date',
				type: 'string',
				required: false,
			},
			{
				name: 'to_date',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'updateBillingPlanForAccount',
		method: 'PUT',
		path: '/billing_plan',
		pathParams: [],
		queryParams: [
			{
				name: 'preview_billing_plan',
				type: 'string',
				required: false,
			},
		],
		hasBody: true,
	},
	{
		name: 'createBrandProfilesForAccount',
		method: 'POST',
		path: '/brands',
		pathParams: [],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'deleteAccountBrand',
		method: 'DELETE',
		path: '/brands/{brandId}',
		pathParams: ['brandId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'deleteBrandLogoByType',
		method: 'DELETE',
		path: '/brands/{brandId}/logos/{logoType}',
		pathParams: ['brandId', 'logoType'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'deleteBrandProfiles',
		method: 'DELETE',
		path: '/brands',
		pathParams: [],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'exportBrandToXmlfile',
		method: 'GET',
		path: '/brands/{brandId}/file',
		pathParams: ['brandId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getBrandLogoByType',
		method: 'GET',
		path: '/brands/{brandId}/logos/{logoType}',
		pathParams: ['brandId', 'logoType'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getSpecificBrandResourceFile',
		method: 'GET',
		path: '/brands/{brandId}/resources/{resourceContentType}',
		pathParams: ['brandId', 'resourceContentType'],
		queryParams: [
			{
				name: 'langcode',
				type: 'string',
				required: false,
			},
			{
				name: 'return_master',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'listBrandsForAccount',
		method: 'GET',
		path: '/brands',
		pathParams: [],
		queryParams: [
			{
				name: 'exclude_distributor_brand',
				type: 'string',
				required: false,
			},
			{
				name: 'include_logos',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'retrieveAccountBrandInformation',
		method: 'GET',
		path: '/brands/{brandId}',
		pathParams: ['brandId'],
		queryParams: [
			{
				name: 'include_external_references',
				type: 'string',
				required: false,
			},
			{
				name: 'include_logos',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'returnBrandResourceMetadataForAccount',
		method: 'GET',
		path: '/brands/{brandId}/resources',
		pathParams: ['brandId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'updateAccountBrandSettings',
		method: 'PUT',
		path: '/brands/{brandId}',
		pathParams: ['brandId'],
		queryParams: [
			{
				name: 'replace_brand',
				type: 'string',
				required: false,
			},
		],
		hasBody: true,
	},
	{
		name: 'applyActionToBulkSendEnvelopes',
		method: 'PUT',
		path: '/bulk_send_batch/{bulkSendBatchId}/{bulkAction}',
		pathParams: ['bulkSendBatchId', 'bulkAction'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'createBulkSendRequest',
		method: 'POST',
		path: '/bulk_send_lists/{bulkSendListId}/send',
		pathParams: ['bulkSendListId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'createBulkSendTestRequest',
		method: 'POST',
		path: '/bulk_send_lists/{bulkSendListId}/test',
		pathParams: ['bulkSendListId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'getBulkSendBatchStatus',
		method: 'GET',
		path: '/bulk_send_batch/{bulkSendBatchId}',
		pathParams: ['bulkSendBatchId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getBulkSendListsInformation',
		method: 'GET',
		path: '/bulk_send_lists',
		pathParams: [],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'listBulkSendBatchSummaries',
		method: 'GET',
		path: '/bulk_send_batch',
		pathParams: [],
		queryParams: [
			{
				name: 'batch_ids',
				type: 'string',
				required: false,
			},
			{
				name: 'count',
				type: 'string',
				required: false,
			},
			{
				name: 'from_date',
				type: 'string',
				required: false,
			},
			{
				name: 'search_text',
				type: 'string',
				required: false,
			},
			{
				name: 'start_position',
				type: 'string',
				required: false,
			},
			{
				name: 'status',
				type: 'string',
				required: false,
			},
			{
				name: 'to_date',
				type: 'string',
				required: false,
			},
			{
				name: 'user_id',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'removeBulkSendList',
		method: 'DELETE',
		path: '/bulk_send_lists/{bulkSendListId}',
		pathParams: ['bulkSendListId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'updateBulkSendBatchName',
		method: 'PUT',
		path: '/bulk_send_batch/{bulkSendBatchId}',
		pathParams: ['bulkSendBatchId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'addPartToChunkedUpload',
		method: 'PUT',
		path: '/chunked_uploads/{chunkedUploadId}/{chunkedUploadPartSeq}',
		pathParams: ['chunkedUploadId', 'chunkedUploadPartSeq'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'commitChunkedUploadForEnvelopes',
		method: 'PUT',
		path: '/chunked_uploads/{chunkedUploadId}',
		pathParams: ['chunkedUploadId'],
		queryParams: [
			{
				name: 'action',
				type: 'string',
				required: false,
			},
		],
		hasBody: true,
	},
	{
		name: 'deleteChunkedUpload',
		method: 'DELETE',
		path: '/chunked_uploads/{chunkedUploadId}',
		pathParams: ['chunkedUploadId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'initiateNewChunkedUpload',
		method: 'POST',
		path: '/chunked_uploads',
		pathParams: [],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'retrieveChunkedUploadMetadata',
		method: 'GET',
		path: '/chunked_uploads/{chunkedUploadId}',
		pathParams: ['chunkedUploadId'],
		queryParams: [
			{
				name: 'include',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'configureCloudStorageRedirectUrl',
		method: 'POST',
		path: '/users/{userId}/cloud_storage',
		pathParams: ['userId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'deleteUserAuthForCloudStorageProviders',
		method: 'DELETE',
		path: '/users/{userId}/cloud_storage/{serviceId}',
		pathParams: ['userId', 'serviceId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'deleteUserCloudStorageAuthentication',
		method: 'DELETE',
		path: '/users/{userId}/cloud_storage',
		pathParams: ['userId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getUserCloudStorageProviderConfiguration',
		method: 'GET',
		path: '/users/{userId}/cloud_storage/{serviceId}',
		pathParams: ['userId', 'serviceId'],
		queryParams: [
			{
				name: 'redirectUrl',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'listCloudStorageItems',
		method: 'GET',
		path: '/users/{userId}/cloud_storage/{serviceId}/folders',
		pathParams: ['userId', 'serviceId'],
		queryParams: [
			{
				name: 'cloud_storage_folder_path',
				type: 'string',
				required: false,
			},
			{
				name: 'count',
				type: 'string',
				required: false,
			},
			{
				name: 'order',
				type: 'string',
				required: false,
			},
			{
				name: 'order_by',
				type: 'string',
				required: false,
			},
			{
				name: 'search_text',
				type: 'string',
				required: false,
			},
			{
				name: 'start_position',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'retrieveCloudStorageProviderConfiguration',
		method: 'GET',
		path: '/users/{userId}/cloud_storage',
		pathParams: ['userId'],
		queryParams: [
			{
				name: 'redirectUrl',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'retrieveItemsInCloudStorageFolder',
		method: 'GET',
		path: '/users/{userId}/cloud_storage/{serviceId}/folders/{folderId}',
		pathParams: ['userId', 'serviceId', 'folderId'],
		queryParams: [
			{
				name: 'cloud_storage_folder_path',
				type: 'string',
				required: false,
			},
			{
				name: 'cloud_storage_folderid_plain',
				type: 'string',
				required: false,
			},
			{
				name: 'count',
				type: 'string',
				required: false,
			},
			{
				name: 'order',
				type: 'string',
				required: false,
			},
			{
				name: 'order_by',
				type: 'string',
				required: false,
			},
			{
				name: 'search_text',
				type: 'string',
				required: false,
			},
			{
				name: 'sky_drive_skip_token',
				type: 'string',
				required: false,
			},
			{
				name: 'start_position',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'createConnectConfigurationForAccount',
		method: 'POST',
		path: '/connect',
		pathParams: [],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'deleteConnectConfiguration',
		method: 'DELETE',
		path: '/connect/{connectId}',
		pathParams: ['connectId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'deleteConnectFailureLogEntry',
		method: 'DELETE',
		path: '/connect/failures/{failureId}',
		pathParams: ['failureId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'deleteConnectLogEntries',
		method: 'DELETE',
		path: '/connect/logs',
		pathParams: [],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'deleteConnectOauthConfiguration',
		method: 'DELETE',
		path: '/connect/oauth',
		pathParams: [],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'deleteSpecificConnectLogEntry',
		method: 'DELETE',
		path: '/connect/logs/{logId}',
		pathParams: ['logId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'republishConnectDataForEnvelope',
		method: 'PUT',
		path: '/connect/envelopes/{envelopeId}/retry_queue',
		pathParams: ['envelopeId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'republishConnectInfoForEnvelopes',
		method: 'PUT',
		path: '/connect/envelopes/retry_queue',
		pathParams: [],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'retrieveConnectConfigurationDetails',
		method: 'GET',
		path: '/connect/{connectId}',
		pathParams: ['connectId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'retrieveConnectConfigurations',
		method: 'GET',
		path: '/connect',
		pathParams: [],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'retrieveConnectFailureLogs',
		method: 'GET',
		path: '/connect/failures',
		pathParams: [],
		queryParams: [
			{
				name: 'from_date',
				type: 'string',
				required: false,
			},
			{
				name: 'to_date',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'retrieveConnectLogEntry',
		method: 'GET',
		path: '/connect/logs/{logId}',
		pathParams: ['logId'],
		queryParams: [
			{
				name: 'additional_info',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'retrieveConnectLogs',
		method: 'GET',
		path: '/connect/logs',
		pathParams: [],
		queryParams: [
			{
				name: 'from_date',
				type: 'string',
				required: false,
			},
			{
				name: 'to_date',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'retrieveConnectOauthConfiguration',
		method: 'GET',
		path: '/connect/oauth',
		pathParams: [],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'returnAllConnectServiceUsers',
		method: 'GET',
		path: '/connect/{connectId}/all/users',
		pathParams: ['connectId'],
		queryParams: [
			{
				name: 'count',
				type: 'string',
				required: false,
			},
			{
				name: 'domain_users_only',
				type: 'string',
				required: false,
			},
			{
				name: 'email_substring',
				type: 'string',
				required: false,
			},
			{
				name: 'start_position',
				type: 'string',
				required: false,
			},
			{
				name: 'status',
				type: 'string',
				required: false,
			},
			{
				name: 'user_name_substring',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'returnUsersFromConnectService',
		method: 'GET',
		path: '/connect/{connectId}/users',
		pathParams: ['connectId'],
		queryParams: [
			{
				name: 'count',
				type: 'string',
				required: false,
			},
			{
				name: 'email_substring',
				type: 'string',
				required: false,
			},
			{
				name: 'list_included_users',
				type: 'string',
				required: false,
			},
			{
				name: 'start_position',
				type: 'string',
				required: false,
			},
			{
				name: 'status',
				type: 'string',
				required: false,
			},
			{
				name: 'user_name_substring',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'setUpConnectOauthConfiguration',
		method: 'POST',
		path: '/connect/oauth',
		pathParams: [],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'updateConnectOauthConfiguration',
		method: 'PUT',
		path: '/connect/oauth',
		pathParams: [],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'updateDocusignConnectConfiguration',
		method: 'PUT',
		path: '/connect',
		pathParams: [],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'addContactsToContactsList',
		method: 'POST',
		path: '/contacts',
		pathParams: [],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'deleteContactFromAccount',
		method: 'DELETE',
		path: '/contacts/{contactId}',
		pathParams: ['contactId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'deleteMultipleContactsFromAccount',
		method: 'DELETE',
		path: '/contacts',
		pathParams: [],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getDocusignAccountContacts',
		method: 'GET',
		path: '/contacts/{contactId}',
		pathParams: ['contactId'],
		queryParams: [
			{
				name: 'cloud_provider',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'updateContactsInformation',
		method: 'PUT',
		path: '/contacts',
		pathParams: [],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'createCustomTabWithProperties',
		method: 'POST',
		path: '/tab_definitions',
		pathParams: [],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'deleteCustomTabInformation',
		method: 'DELETE',
		path: '/tab_definitions/{customTabId}',
		pathParams: ['customTabId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'retrieveAllAccountTabs',
		method: 'GET',
		path: '/tab_definitions',
		pathParams: [],
		queryParams: [
			{
				name: 'custom_tab_only',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'retrieveCustomTabInformation',
		method: 'GET',
		path: '/tab_definitions/{customTabId}',
		pathParams: ['customTabId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'updateCustomTabInformationForAccount',
		method: 'PUT',
		path: '/tab_definitions/{customTabId}',
		pathParams: ['customTabId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'deleteRequestLogFiles',
		method: 'DELETE',
		path: '/v2.1/diagnostics/request_logs',
		pathParams: [],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getRequestLoggingLogFile',
		method: 'GET',
		path: '/v2.1/diagnostics/request_logs/{requestLogId}',
		pathParams: ['requestLogId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getRequestLogs',
		method: 'GET',
		path: '/v2.1/diagnostics/request_logs',
		pathParams: [],
		queryParams: [
			{
				name: 'encoding',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'getRequestLogSettings',
		method: 'GET',
		path: '/v2.1/diagnostics/settings',
		pathParams: [],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getResourceInformation',
		method: 'GET',
		path: '/v2.1',
		pathParams: [],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getServiceInformation',
		method: 'GET',
		path: '/service_information',
		pathParams: [],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'toggleApiRequestLogging',
		method: 'PUT',
		path: '/v2.1/diagnostics/settings',
		pathParams: [],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'addEnvelopeAttachments',
		method: 'PUT',
		path: '/envelopes/{envelopeId}/attachments',
		pathParams: ['envelopeId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'createCustomDocumentFieldsInEnvelope',
		method: 'POST',
		path: '/envelopes/{envelopeId}/documents/{documentId}/fields',
		pathParams: ['envelopeId', 'documentId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'createDocumentResponsiveHtmlPreview',
		method: 'POST',
		path: '/envelopes/{envelopeId}/documents/{documentId}/responsive_html_preview',
		pathParams: ['envelopeId', 'documentId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'createPreviewOfResponsiveHtmlInEnvelope',
		method: 'POST',
		path: '/envelopes/{envelopeId}/responsive_html_preview',
		pathParams: ['envelopeId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'deleteCustomDocumentFields',
		method: 'DELETE',
		path: '/envelopes/{envelopeId}/documents/{documentId}/fields',
		pathParams: ['envelopeId', 'documentId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'deleteDraftEnvelopeAttachments',
		method: 'DELETE',
		path: '/envelopes/{envelopeId}/attachments',
		pathParams: ['envelopeId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'deprecatedEndpointForTabBlob',
		method: 'GET',
		path: '/envelopes/{envelopeId}/tabs_blob',
		pathParams: ['envelopeId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getEnvelopeDocGenFormFields',
		method: 'GET',
		path: '/envelopes/{envelopeId}/docGenFormFields',
		pathParams: ['envelopeId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getEnvelopeDocumentFields',
		method: 'GET',
		path: '/envelopes/{envelopeId}/documents/{documentId}/fields',
		pathParams: ['envelopeId', 'documentId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getPdftranscriptOfEnvelopeComments',
		method: 'GET',
		path: '/envelopes/{envelopeId}/comments/transcript',
		pathParams: ['envelopeId'],
		queryParams: [
			{
				name: 'encoding',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'getRecipientDocumentVisibility',
		method: 'GET',
		path: '/envelopes/{envelopeId}/recipients/{recipientId}/document_visibility',
		pathParams: ['envelopeId', 'recipientId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getTabsBlobForEnvelope',
		method: 'GET',
		path: '/envelopes/{envelopeId}/tabs_blob',
		pathParams: ['envelopeId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'listEnvelopeAttachmentsByEnvelopeId',
		method: 'GET',
		path: '/envelopes/{envelopeId}/attachments',
		pathParams: ['envelopeId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'retrieveEnvelopeAttachment',
		method: 'GET',
		path: '/envelopes/{envelopeId}/attachments/{attachmentId}',
		pathParams: ['envelopeId', 'attachmentId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'retrieveEnvelopeDocuments',
		method: 'GET',
		path: '/envelopes/{envelopeId}/documents',
		pathParams: ['envelopeId'],
		queryParams: [
			{
				name: 'documents_by_userid',
				type: 'string',
				required: false,
			},
			{
				name: 'include_agreement_type',
				type: 'string',
				required: false,
			},
			{
				name: 'include_docgen_formfields',
				type: 'string',
				required: false,
			},
			{
				name: 'include_is_edited',
				type: 'string',
				required: false,
			},
			{
				name: 'include_metadata',
				type: 'string',
				required: false,
			},
			{
				name: 'include_tabs',
				type: 'string',
				required: false,
			},
			{
				name: 'recipient_id',
				type: 'string',
				required: false,
			},
			{
				name: 'shared_user_id',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'retrieveEnvelopeHtmlDefinition',
		method: 'GET',
		path: '/envelopes/{envelopeId}/html_definitions',
		pathParams: ['envelopeId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'returnEnvelopeTabDataForExistingEnvelope',
		method: 'GET',
		path: '/envelopes/{envelopeId}/form_data',
		pathParams: ['envelopeId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'updateCustomFieldsInEnvelopeDocument',
		method: 'PUT',
		path: '/envelopes/{envelopeId}/documents/{documentId}/fields',
		pathParams: ['envelopeId', 'documentId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'updateDocumentVisibilityRecipients',
		method: 'PUT',
		path: '/envelopes/{envelopeId}/recipients/document_visibility',
		pathParams: ['envelopeId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'updateEnvelopeAttachment',
		method: 'PUT',
		path: '/envelopes/{envelopeId}/attachments/{attachmentId}',
		pathParams: ['envelopeId', 'attachmentId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'updateEnvelopeDocGenFormFields',
		method: 'PUT',
		path: '/envelopes/{envelopeId}/docGenFormFields',
		pathParams: ['envelopeId'],
		queryParams: [
			{
				name: 'update_docgen_formfields_only',
				type: 'string',
				required: false,
			},
		],
		hasBody: true,
	},
	{
		name: 'updateRecipientDocumentVisibility',
		method: 'PUT',
		path: '/envelopes/{envelopeId}/recipients/{recipientId}/document_visibility',
		pathParams: ['envelopeId', 'recipientId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'deletePageFromDocumentInEnvelope',
		method: 'DELETE',
		path: '/envelopes/{envelopeId}/documents/{documentId}/pages/{pageNumber}',
		pathParams: ['envelopeId', 'documentId', 'pageNumber'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getEnvelopeNotificationDefaults',
		method: 'GET',
		path: '/envelopes/{envelopeId}/notification',
		pathParams: ['envelopeId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getPageImageFromEnvelope',
		method: 'GET',
		path: '/envelopes/{envelopeId}/documents/{documentId}/pages/{pageNumber}/page_image',
		pathParams: ['envelopeId', 'documentId', 'pageNumber'],
		queryParams: [
			{
				name: 'dpi',
				type: 'string',
				required: false,
			},
			{
				name: 'max_height',
				type: 'string',
				required: false,
			},
			{
				name: 'max_width',
				type: 'string',
				required: false,
			},
			{
				name: 'show_changes',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'getSignatureInformationForRecipient',
		method: 'GET',
		path: '/envelopes/{envelopeId}/recipients/{recipientId}/signature',
		pathParams: ['envelopeId', 'recipientId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'retrieveEnvelopeAuditEvents',
		method: 'GET',
		path: '/envelopes/{envelopeId}/audit_events',
		pathParams: ['envelopeId'],
		queryParams: [
			{
				name: 'locale',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'retrieveEnvelopeNotificationDetails',
		method: 'GET',
		path: '/envelopes/{envelopeId}/notification',
		pathParams: ['envelopeId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'retrieveSignerSignatureImageInformation',
		method: 'GET',
		path: '/envelopes/{envelopeId}/recipients/{recipientId}/signature_image',
		pathParams: ['envelopeId', 'recipientId'],
		queryParams: [
			{
				name: 'include_chrome',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'retrieveUserInitialsImageForEnvelopes',
		method: 'GET',
		path: '/envelopes/{envelopeId}/recipients/{recipientId}/initials_image',
		pathParams: ['envelopeId', 'recipientId'],
		queryParams: [
			{
				name: 'include_chrome',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'returnsDocumentPageImagesBasedOnInput',
		method: 'GET',
		path: '/envelopes/{envelopeId}/documents/{documentId}/pages',
		pathParams: ['envelopeId', 'documentId'],
		queryParams: [
			{
				name: 'count',
				type: 'string',
				required: false,
			},
			{
				name: 'dpi',
				type: 'string',
				required: false,
			},
			{
				name: 'max_height',
				type: 'string',
				required: false,
			},
			{
				name: 'max_width',
				type: 'string',
				required: false,
			},
			{
				name: 'nocache',
				type: 'string',
				required: false,
			},
			{
				name: 'show_changes',
				type: 'string',
				required: false,
			},
			{
				name: 'start_position',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'rotatePageImageForEnvelope',
		method: 'PUT',
		path: '/envelopes/{envelopeId}/documents/{documentId}/pages/{pageNumber}/page_image',
		pathParams: ['envelopeId', 'documentId', 'pageNumber'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'setInitialsImageForAccountlessSigner',
		method: 'PUT',
		path: '/envelopes/{envelopeId}/recipients/{recipientId}/initials_image',
		pathParams: ['envelopeId', 'recipientId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'setSignatureImageForNoAccountSigner',
		method: 'PUT',
		path: '/envelopes/{envelopeId}/recipients/{recipientId}/signature_image',
		pathParams: ['envelopeId', 'recipientId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'updateEnvelopeNotificationSettings',
		method: 'PUT',
		path: '/envelopes/{envelopeId}/notification',
		pathParams: ['envelopeId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'createIdproofResourceTokenForRecipient',
		method: 'POST',
		path: '/envelopes/{envelopeId}/recipients/{recipientId}/identity_proof_token',
		pathParams: ['envelopeId', 'recipientId'],
		queryParams: [
			{
				name: 'token_scopes',
				type: 'string',
				required: false,
			},
		],
		hasBody: true,
	},
	{
		name: 'createRecipientManualReviewLink',
		method: 'POST',
		path: '/envelopes/{envelopeId}/recipients/{recipientId}/views/identity_manual_review',
		pathParams: ['envelopeId', 'recipientId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'createRecipientPreviewForEnvelope',
		method: 'POST',
		path: '/envelopes/{envelopeId}/views/recipient_preview',
		pathParams: ['envelopeId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'createSenderViewUrlForEnvelope',
		method: 'POST',
		path: '/envelopes/{envelopeId}/views/sender',
		pathParams: ['envelopeId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'generateEditViewUrlforEnvelope',
		method: 'POST',
		path: '/envelopes/{envelopeId}/views/edit',
		pathParams: ['envelopeId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'generateEnvelopeCorrectionUrl',
		method: 'POST',
		path: '/envelopes/{envelopeId}/views/correct',
		pathParams: ['envelopeId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'generateRecipientSharedViewUrl',
		method: 'POST',
		path: '/envelopes/{envelopeId}/views/shared',
		pathParams: ['envelopeId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'getElectronicDisclosureForRecipient',
		method: 'GET',
		path: '/envelopes/{envelopeId}/recipients/{recipientId}/consumer_disclosure/{langCode}',
		pathParams: ['envelopeId', 'recipientId', 'langCode'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getUrlforEmbeddingDocusignUi',
		method: 'POST',
		path: '/views/console',
		pathParams: [],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'retrieveAccountVerificationWorkflows',
		method: 'GET',
		path: '/identity_verification',
		pathParams: [],
		queryParams: [
			{
				name: 'identity_verification_workflow_status',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'retrieveDefaultDisclosureForEnvelope',
		method: 'GET',
		path: '/envelopes/{envelopeId}/recipients/{recipientId}/consumer_disclosure',
		pathParams: ['envelopeId', 'recipientId'],
		queryParams: [
			{
				name: 'langCode',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'revokeEnvelopeCorrectionUrl',
		method: 'DELETE',
		path: '/envelopes/{envelopeId}/views/correct',
		pathParams: ['envelopeId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'addEmailOverridesToEnvelope',
		method: 'POST',
		path: '/envelopes/{envelopeId}/email_settings',
		pathParams: ['envelopeId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'addStepToEnvelopeWorkflow',
		method: 'POST',
		path: '/envelopes/{envelopeId}/workflow/steps',
		pathParams: ['envelopeId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'addTemplatesToDocumentInEnvelope',
		method: 'POST',
		path: '/envelopes/{envelopeId}/documents/{documentId}/templates',
		pathParams: ['envelopeId', 'documentId'],
		queryParams: [
			{
				name: 'preserve_template_recipient',
				type: 'string',
				required: false,
			},
		],
		hasBody: true,
	},
	{
		name: 'addTemplatesToEnvelope',
		method: 'POST',
		path: '/envelopes/{envelopeId}/templates',
		pathParams: ['envelopeId'],
		queryParams: [
			{
				name: 'preserve_template_recipient',
				type: 'string',
				required: false,
			},
		],
		hasBody: true,
	},
	{
		name: 'createCustomFieldsForEnvelope',
		method: 'POST',
		path: '/envelopes/{envelopeId}/custom_fields',
		pathParams: ['envelopeId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'createTemplateWorkflowStep',
		method: 'POST',
		path: '/templates/{templateId}/workflow/steps',
		pathParams: ['templateId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'deleteDelayedRoutingRuleForEnvelopeStep',
		method: 'DELETE',
		path: '/envelopes/{envelopeId}/workflow/steps/{workflowStepId}/delayedRouting',
		pathParams: ['envelopeId', 'workflowStepId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'deleteDelayedRoutingRulesForTemplate',
		method: 'DELETE',
		path: '/templates/{templateId}/workflow/steps/{workflowStepId}/delayedRouting',
		pathParams: ['templateId', 'workflowStepId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'deleteEnvelopeCustomFields',
		method: 'DELETE',
		path: '/envelopes/{envelopeId}/custom_fields',
		pathParams: ['envelopeId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'deleteEnvelopeEmailSettings',
		method: 'DELETE',
		path: '/envelopes/{envelopeId}/email_settings',
		pathParams: ['envelopeId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'deleteEnvelopeLock',
		method: 'DELETE',
		path: '/envelopes/{envelopeId}/lock',
		pathParams: ['envelopeId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'deleteEnvelopeScheduledSendingRules',
		method: 'DELETE',
		path: '/envelopes/{envelopeId}/workflow/scheduledSending',
		pathParams: ['envelopeId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'deleteEnvelopeTransferRule',
		method: 'DELETE',
		path: '/envelopes/transfer_rules/{envelopeTransferRuleId}',
		pathParams: ['envelopeTransferRuleId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'deleteEnvelopeWorkflowDefinition',
		method: 'DELETE',
		path: '/envelopes/{envelopeId}/workflow',
		pathParams: ['envelopeId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'deleteEnvelopeWorkflowStep',
		method: 'DELETE',
		path: '/envelopes/{envelopeId}/workflow/steps/{workflowStepId}',
		pathParams: ['envelopeId', 'workflowStepId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'deleteScheduledSendingRules',
		method: 'DELETE',
		path: '/templates/{templateId}/workflow/scheduledSending',
		pathParams: ['templateId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'deleteTemplateFromEnvelopeDocument',
		method: 'DELETE',
		path: '/envelopes/{envelopeId}/documents/{documentId}/templates/{templateId}',
		pathParams: ['envelopeId', 'documentId', 'templateId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'deleteTemplateWorkflowStep',
		method: 'DELETE',
		path: '/templates/{templateId}/workflow/steps/{workflowStepId}',
		pathParams: ['templateId', 'workflowStepId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'deleteWorkflowDefinitionForTemplate',
		method: 'DELETE',
		path: '/templates/{templateId}/workflow',
		pathParams: ['templateId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getEnvelopeLockInformation',
		method: 'GET',
		path: '/envelopes/{envelopeId}/lock',
		pathParams: ['envelopeId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getEnvelopeWorkflowDefinition',
		method: 'GET',
		path: '/envelopes/{envelopeId}/workflow',
		pathParams: ['envelopeId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getEnvelopeWorkflowDelayedRoutingDefinition',
		method: 'GET',
		path: '/envelopes/{envelopeId}/workflow/steps/{workflowStepId}/delayedRouting',
		pathParams: ['envelopeId', 'workflowStepId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getTemplateDelayedRoutingRules',
		method: 'GET',
		path: '/templates/{templateId}/workflow/steps/{workflowStepId}/delayedRouting',
		pathParams: ['templateId', 'workflowStepId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getTemplateScheduledSendingSettings',
		method: 'GET',
		path: '/templates/{templateId}/workflow/scheduledSending',
		pathParams: ['templateId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getTemplatesForEnvelopeDocument',
		method: 'GET',
		path: '/envelopes/{envelopeId}/documents/{documentId}/templates',
		pathParams: ['envelopeId', 'documentId'],
		queryParams: [
			{
				name: 'include',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'getTemplatesUsedInEnvelope',
		method: 'GET',
		path: '/envelopes/{envelopeId}/templates',
		pathParams: ['envelopeId'],
		queryParams: [
			{
				name: 'include',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'getWorkflowStepForEnvelope',
		method: 'GET',
		path: '/envelopes/{envelopeId}/workflow/steps/{workflowStepId}',
		pathParams: ['envelopeId', 'workflowStepId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'listEnvelopeAndDocumentCustomFields',
		method: 'GET',
		path: '/envelopes/{envelopeId}/custom_fields',
		pathParams: ['envelopeId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'lockAnEnvelopeForEditing',
		method: 'POST',
		path: '/envelopes/{envelopeId}/lock',
		pathParams: ['envelopeId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'retrieveCustomFieldsForEnvelope',
		method: 'GET',
		path: '/envelopes/{envelopeId}/custom_fields',
		pathParams: ['envelopeId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'retrieveEnvelopeEmailOverrides',
		method: 'GET',
		path: '/envelopes/{envelopeId}/email_settings',
		pathParams: ['envelopeId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'retrieveWorkflowStepForTemplate',
		method: 'GET',
		path: '/templates/{templateId}/workflow/steps/{workflowStepId}',
		pathParams: ['templateId', 'workflowStepId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'returnScheduledSendingRulesForEnvelope',
		method: 'GET',
		path: '/envelopes/{envelopeId}/workflow/scheduledSending',
		pathParams: ['envelopeId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'returnTemplateWorkflowDefinition',
		method: 'GET',
		path: '/templates/{templateId}/workflow',
		pathParams: ['templateId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'submitBatchHistoricalEnvelopesToWebhook',
		method: 'POST',
		path: '/connect/envelopes/publish/historical',
		pathParams: [],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'updateEnvelopeCustomFields',
		method: 'PUT',
		path: '/envelopes/{envelopeId}/custom_fields',
		pathParams: ['envelopeId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'updateEnvelopeDelayedRoutingRules',
		method: 'PUT',
		path: '/envelopes/{envelopeId}/workflow/steps/{workflowStepId}/delayedRouting',
		pathParams: ['envelopeId', 'workflowStepId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'updateEnvelopeEmailSettings',
		method: 'PUT',
		path: '/envelopes/{envelopeId}/email_settings',
		pathParams: ['envelopeId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'updateEnvelopeScheduledSendingRules',
		method: 'PUT',
		path: '/envelopes/{envelopeId}/workflow/scheduledSending',
		pathParams: ['envelopeId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'updateEnvelopeWorkflowDefinition',
		method: 'PUT',
		path: '/envelopes/{envelopeId}/workflow',
		pathParams: ['envelopeId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'updateEnvelopeWorkflowStep',
		method: 'PUT',
		path: '/envelopes/{envelopeId}/workflow/steps/{workflowStepId}',
		pathParams: ['envelopeId', 'workflowStepId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'updateLockForEnvelope',
		method: 'PUT',
		path: '/envelopes/{envelopeId}/lock',
		pathParams: ['envelopeId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'updateTemplateDelayedRoutingRules',
		method: 'PUT',
		path: '/templates/{templateId}/workflow/steps/{workflowStepId}/delayedRouting',
		pathParams: ['templateId', 'workflowStepId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'updateTemplateScheduledSendingRules',
		method: 'PUT',
		path: '/templates/{templateId}/workflow/scheduledSending',
		pathParams: ['templateId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'updateTemplateWorkflowDefinition',
		method: 'PUT',
		path: '/templates/{templateId}/workflow',
		pathParams: ['templateId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'updateWorkflowStepForTemplate',
		method: 'PUT',
		path: '/templates/{templateId}/workflow/steps/{workflowStepId}',
		pathParams: ['templateId', 'workflowStepId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'addExistingBrandToGroup',
		method: 'PUT',
		path: '/groups/{groupId}/brands',
		pathParams: ['groupId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'addMembersToSigningGroup',
		method: 'PUT',
		path: '/signing_groups/{signingGroupId}/users',
		pathParams: ['signingGroupId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'addUsersToExistingGroup',
		method: 'PUT',
		path: '/groups/{groupId}/users',
		pathParams: ['groupId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'createGroupsForAccount',
		method: 'POST',
		path: '/groups',
		pathParams: [],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'createNewAccountPermissionProfile',
		method: 'POST',
		path: '/permission_profiles',
		pathParams: [],
		queryParams: [
			{
				name: 'include',
				type: 'string',
				required: false,
			},
		],
		hasBody: true,
	},
	{
		name: 'createSigningGroup',
		method: 'POST',
		path: '/signing_groups',
		pathParams: [],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'deleteAccountPermissionProfile',
		method: 'DELETE',
		path: '/permission_profiles/{permissionProfileId}',
		pathParams: ['permissionProfileId'],
		queryParams: [
			{
				name: 'move_users_to',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'deleteBrandFromGroup',
		method: 'DELETE',
		path: '/groups/{groupId}/brands',
		pathParams: ['groupId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'deleteMembersFromSigningGroup',
		method: 'DELETE',
		path: '/signing_groups/{signingGroupId}/users',
		pathParams: ['signingGroupId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'deleteOneOrMoreSigningGroups',
		method: 'DELETE',
		path: '/signing_groups',
		pathParams: [],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'deleteUserGroup',
		method: 'DELETE',
		path: '/groups',
		pathParams: [],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'deleteUsersFromGroup',
		method: 'DELETE',
		path: '/groups/{groupId}/users',
		pathParams: ['groupId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'getBrandsInformationForGroup',
		method: 'GET',
		path: '/groups/{groupId}/brands',
		pathParams: ['groupId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getGroupsInformationForAccount',
		method: 'GET',
		path: '/groups',
		pathParams: [],
		queryParams: [
			{
				name: 'count',
				type: 'string',
				required: false,
			},
			{
				name: 'group_type',
				type: 'string',
				required: false,
			},
			{
				name: 'include_usercount',
				type: 'string',
				required: false,
			},
			{
				name: 'search_text',
				type: 'string',
				required: false,
			},
			{
				name: 'start_position',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'getListOfAccountPermissionProfiles',
		method: 'GET',
		path: '/permission_profiles',
		pathParams: [],
		queryParams: [
			{
				name: 'include',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'getMembersOfASigningGroup',
		method: 'GET',
		path: '/signing_groups/{signingGroupId}/users',
		pathParams: ['signingGroupId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getPermissionProfileForAccount',
		method: 'GET',
		path: '/permission_profiles/{permissionProfileId}',
		pathParams: ['permissionProfileId'],
		queryParams: [
			{
				name: 'include',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'getSigningGroupInformation',
		method: 'GET',
		path: '/signing_groups/{signingGroupId}',
		pathParams: ['signingGroupId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getUsersInGroup',
		method: 'GET',
		path: '/groups/{groupId}/users',
		pathParams: ['groupId'],
		queryParams: [
			{
				name: 'count',
				type: 'string',
				required: false,
			},
			{
				name: 'start_position',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'retrieveAccountSigningGroups',
		method: 'GET',
		path: '/signing_groups',
		pathParams: [],
		queryParams: [
			{
				name: 'group_type',
				type: 'string',
				required: false,
			},
			{
				name: 'include_users',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'updateGroupInformation',
		method: 'PUT',
		path: '/groups',
		pathParams: [],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'updatePermissionProfileSettings',
		method: 'PUT',
		path: '/permission_profiles/{permissionProfileId}',
		pathParams: ['permissionProfileId'],
		queryParams: [
			{
				name: 'include',
				type: 'string',
				required: false,
			},
		],
		hasBody: true,
	},
	{
		name: 'updateSigningGroupDetails',
		method: 'PUT',
		path: '/signing_groups/{signingGroupId}',
		pathParams: ['signingGroupId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'updateSigningGroupNames',
		method: 'PUT',
		path: '/signing_groups',
		pathParams: [],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'createNotaryJurisdictionObject',
		method: 'POST',
		path: '/v2.1/current_user/notary/jurisdictions',
		pathParams: [],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'deleteNotaryJurisdiction',
		method: 'DELETE',
		path: '/v2.1/current_user/notary/jurisdictions/{jurisdictionId}',
		pathParams: ['jurisdictionId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getNotaryJournals',
		method: 'GET',
		path: '/v2.1/current_user/notary/journals',
		pathParams: [],
		queryParams: [
			{
				name: 'count',
				type: 'string',
				required: false,
			},
			{
				name: 'search_text',
				type: 'string',
				required: false,
			},
			{
				name: 'start_position',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'getNotaryJurisdictionObject',
		method: 'GET',
		path: '/v2.1/current_user/notary/jurisdictions/{jurisdictionId}',
		pathParams: ['jurisdictionId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getNotaryUserSettings',
		method: 'GET',
		path: '/v2.1/current_user/notary',
		pathParams: [],
		queryParams: [
			{
				name: 'include_jurisdictions',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'listNotaryJournals',
		method: 'GET',
		path: '/v2.1/current_user/notary/journals',
		pathParams: [],
		queryParams: [
			{
				name: 'count',
				type: 'string',
				required: false,
			},
			{
				name: 'search_text',
				type: 'string',
				required: false,
			},
			{
				name: 'start_position',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'listRegisteredNotaryJurisdictions',
		method: 'GET',
		path: '/v2.1/current_user/notary/jurisdictions',
		pathParams: [],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'registerCurrentUserAsNotary',
		method: 'POST',
		path: '/v2.1/current_user/notary',
		pathParams: [],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'updateNotaryJurisdictionInfo',
		method: 'PUT',
		path: '/v2.1/current_user/notary/jurisdictions/{jurisdictionId}',
		pathParams: ['jurisdictionId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'updateUserNotaryInformation',
		method: 'PUT',
		path: '/v2.1/current_user/notary',
		pathParams: [],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'deletePowerFormById',
		method: 'DELETE',
		path: '/powerforms/{powerFormId}',
		pathParams: ['powerFormId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getPowerFormSenders',
		method: 'GET',
		path: '/powerforms/senders',
		pathParams: [],
		queryParams: [
			{
				name: 'start_position',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'retrievePowerFormDataEntries',
		method: 'GET',
		path: '/powerforms/{powerFormId}/form_data',
		pathParams: ['powerFormId'],
		queryParams: [
			{
				name: 'data_layout',
				type: 'string',
				required: false,
			},
			{
				name: 'from_date',
				type: 'string',
				required: false,
			},
			{
				name: 'to_date',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'createCustomFieldsInTemplateDocument',
		method: 'POST',
		path: '/templates/{templateId}/documents/{documentId}/fields',
		pathParams: ['templateId', 'documentId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'createPreviewOfResponsiveHtml',
		method: 'POST',
		path: '/templates/{templateId}/documents/{documentId}/responsive_html_preview',
		pathParams: ['templateId', 'documentId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'createTemplateDocumentCustomFields',
		method: 'POST',
		path: '/templates/{templateId}/custom_fields',
		pathParams: ['templateId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'createTemplateRecipientPreviewUrl',
		method: 'POST',
		path: '/templates/{templateId}/views/recipient_preview',
		pathParams: ['templateId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'createTemplateResponsiveHtmlPreview',
		method: 'POST',
		path: '/templates/{templateId}/responsive_html_preview',
		pathParams: ['templateId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'createUrlforTemplateEditView',
		method: 'POST',
		path: '/templates/{templateId}/views/edit',
		pathParams: ['templateId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'deleteCustomDocumentFieldsFromTemplate',
		method: 'DELETE',
		path: '/templates/{templateId}/documents/{documentId}/fields',
		pathParams: ['templateId', 'documentId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'deleteCustomFieldsInTemplate',
		method: 'DELETE',
		path: '/templates/{templateId}/custom_fields',
		pathParams: ['templateId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'deletePageFromTemplateDocument',
		method: 'DELETE',
		path: '/templates/{templateId}/documents/{documentId}/pages/{pageNumber}',
		pathParams: ['templateId', 'documentId', 'pageNumber'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'deleteTemplateLock',
		method: 'DELETE',
		path: '/templates/{templateId}/lock',
		pathParams: ['templateId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getOriginalHtmlDefinitionForTemplate',
		method: 'GET',
		path: '/templates/{templateId}/html_definitions',
		pathParams: ['templateId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getTemplateDocumentHtmlDefinition',
		method: 'GET',
		path: '/templates/{templateId}/documents/{documentId}/html_definitions',
		pathParams: ['templateId', 'documentId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getTemplateLockInformation',
		method: 'GET',
		path: '/templates/{templateId}/lock',
		pathParams: ['templateId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getTemplateNotificationInformation',
		method: 'GET',
		path: '/templates/{templateId}/notification',
		pathParams: ['templateId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getTemplateRecipientDocumentVisibility',
		method: 'GET',
		path: '/templates/{templateId}/recipients/{recipientId}/document_visibility',
		pathParams: ['templateId', 'recipientId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'lockTemplateForEditing',
		method: 'POST',
		path: '/templates/{templateId}/lock',
		pathParams: ['templateId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'removeGroupSharingPermissionsForTemplate',
		method: 'DELETE',
		path: '/templates/{templateId}/{templatePart}',
		pathParams: ['templateId', 'templatePart'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'removeTemplatesFromFavorites',
		method: 'DELETE',
		path: '/favorite_templates',
		pathParams: [],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'retrieveAccountFavoriteTemplates',
		method: 'GET',
		path: '/favorite_templates',
		pathParams: [],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'retrieveCustomFieldsForTemplate',
		method: 'GET',
		path: '/templates/{templateId}/custom_fields',
		pathParams: ['templateId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'retrievePdfFromSpecifiedTemplate',
		method: 'GET',
		path: '/templates/{templateId}/documents/{documentId}',
		pathParams: ['templateId', 'documentId'],
		queryParams: [
			{
				name: 'encrypt',
				type: 'string',
				required: false,
			},
			{
				name: 'file_type',
				type: 'string',
				required: false,
			},
			{
				name: 'show_changes',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'retrieveTemplateCustomFields',
		method: 'GET',
		path: '/templates/{templateId}/custom_fields',
		pathParams: ['templateId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'retrieveTemplateDocumentPageImages',
		method: 'GET',
		path: '/templates/{templateId}/documents/{documentId}/pages/{pageNumber}/page_image',
		pathParams: ['templateId', 'documentId', 'pageNumber'],
		queryParams: [
			{
				name: 'dpi',
				type: 'string',
				required: false,
			},
			{
				name: 'max_height',
				type: 'string',
				required: false,
			},
			{
				name: 'max_width',
				type: 'string',
				required: false,
			},
			{
				name: 'show_changes',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'retrieveTemplatePageImage',
		method: 'GET',
		path: '/templates/{templateId}/documents/{documentId}/pages',
		pathParams: ['templateId', 'documentId'],
		queryParams: [
			{
				name: 'count',
				type: 'string',
				required: false,
			},
			{
				name: 'dpi',
				type: 'string',
				required: false,
			},
			{
				name: 'max_height',
				type: 'string',
				required: false,
			},
			{
				name: 'max_width',
				type: 'string',
				required: false,
			},
			{
				name: 'nocache',
				type: 'string',
				required: false,
			},
			{
				name: 'show_changes',
				type: 'string',
				required: false,
			},
			{
				name: 'start_position',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'rotateTemplatePageImage',
		method: 'PUT',
		path: '/templates/{templateId}/documents/{documentId}/pages/{pageNumber}/page_image',
		pathParams: ['templateId', 'documentId', 'pageNumber'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'setTemplatesAsAccountFavorites',
		method: 'PUT',
		path: '/favorite_templates',
		pathParams: [],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'shareTemplateWithGroup',
		method: 'PUT',
		path: '/templates/{templateId}/{templatePart}',
		pathParams: ['templateId', 'templatePart'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'updateTemplateCustomFields',
		method: 'PUT',
		path: '/templates/{templateId}/custom_fields',
		pathParams: ['templateId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'updateTemplateDocumentCustomFields',
		method: 'PUT',
		path: '/templates/{templateId}/documents/{documentId}/fields',
		pathParams: ['templateId', 'documentId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'updateTemplateDocVisibility',
		method: 'PUT',
		path: '/templates/{templateId}/recipients/document_visibility',
		pathParams: ['templateId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'updateTemplateLockInformation',
		method: 'PUT',
		path: '/templates/{templateId}/lock',
		pathParams: ['templateId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'updateTemplateNotificationSettings',
		method: 'PUT',
		path: '/templates/{templateId}/notification',
		pathParams: ['templateId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'updateTemplateRecipientDocumentVisibility',
		method: 'PUT',
		path: '/templates/{templateId}/recipients/{recipientId}/document_visibility',
		pathParams: ['templateId', 'recipientId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'addNewUsersToASpecifiedAccount',
		method: 'POST',
		path: '/users',
		pathParams: [],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'addOrUpdateUserCustomSettings',
		method: 'PUT',
		path: '/users/{userId}/custom_settings',
		pathParams: ['userId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'addOrUpdateUserSignature',
		method: 'PUT',
		path: '/users/{userId}/signatures',
		pathParams: ['userId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'addUserSignatureAndInitialsImages',
		method: 'POST',
		path: '/users/{userId}/signatures',
		pathParams: ['userId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'changeUsersInAccount',
		method: 'PUT',
		path: '/users',
		pathParams: [],
		queryParams: [
			{
				name: 'allow_all_languages',
				type: 'string',
				required: false,
			},
		],
		hasBody: true,
	},
	{
		name: 'closeUsersInAccount',
		method: 'DELETE',
		path: '/users',
		pathParams: [],
		queryParams: [
			{
				name: 'delete',
				type: 'string',
				required: false,
			},
		],
		hasBody: true,
	},
	{
		name: 'createOrUpdateUserAuthorizations',
		method: 'POST',
		path: '/users/{userId}/authorizations',
		pathParams: ['userId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'createUserAuthorizationForAgentUser',
		method: 'POST',
		path: '/users/{userId}/authorization',
		pathParams: ['userId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'deleteCustomUserSettings',
		method: 'DELETE',
		path: '/users/{userId}/custom_settings',
		pathParams: ['userId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'deleteUserAuthorization',
		method: 'DELETE',
		path: '/users/{userId}/authorization/{authorizationId}',
		pathParams: ['userId', 'authorizationId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'deleteUserAuthorizations',
		method: 'DELETE',
		path: '/users/{userId}/authorizations',
		pathParams: ['userId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'deleteUserInitialsOrSignatureImage',
		method: 'DELETE',
		path: '/users/{userId}/signatures/{signatureId}/{imageType}',
		pathParams: ['userId', 'signatureId', 'imageType'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'deleteUserProfileImage',
		method: 'DELETE',
		path: '/users/{userId}/profile/image',
		pathParams: ['userId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getAgentUserAuthorizations',
		method: 'GET',
		path: '/users/{userId}/authorizations/agent',
		pathParams: ['userId'],
		queryParams: [
			{
				name: 'active_only',
				type: 'string',
				required: false,
			},
			{
				name: 'count',
				type: 'string',
				required: false,
			},
			{
				name: 'email_substring',
				type: 'string',
				required: false,
			},
			{
				name: 'include_closed_users',
				type: 'string',
				required: false,
			},
			{
				name: 'permissions',
				type: 'string',
				required: false,
			},
			{
				name: 'start_position',
				type: 'string',
				required: false,
			},
			{
				name: 'task_source',
				type: 'string',
				required: false,
			},
			{
				name: 'task_type',
				type: 'string',
				required: false,
			},
			{
				name: 'user_name_substring',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'getUserAuthorizationDetails',
		method: 'GET',
		path: '/users/{userId}/authorization/{authorizationId}',
		pathParams: ['userId', 'authorizationId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getUserAuthorizationsForPrincipal',
		method: 'GET',
		path: '/users/{userId}/authorizations',
		pathParams: ['userId'],
		queryParams: [
			{
				name: 'active_only',
				type: 'string',
				required: false,
			},
			{
				name: 'count',
				type: 'string',
				required: false,
			},
			{
				name: 'email_substring',
				type: 'string',
				required: false,
			},
			{
				name: 'include_closed_users',
				type: 'string',
				required: false,
			},
			{
				name: 'permissions',
				type: 'string',
				required: false,
			},
			{
				name: 'start_position',
				type: 'string',
				required: false,
			},
			{
				name: 'task_source',
				type: 'string',
				required: false,
			},
			{
				name: 'task_type',
				type: 'string',
				required: false,
			},
			{
				name: 'user_name_substring',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'getUserInformationById',
		method: 'GET',
		path: '/users/{userId}',
		pathParams: ['userId'],
		queryParams: [
			{
				name: 'additional_info',
				type: 'string',
				required: false,
			},
			{
				name: 'email',
				type: 'string',
				required: false,
			},
			{
				name: 'include_license',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'listUsersForAccount',
		method: 'GET',
		path: '/users',
		pathParams: [],
		queryParams: [
			{
				name: 'additional_info',
				type: 'string',
				required: false,
			},
			{
				name: 'alternate_admins_only',
				type: 'string',
				required: false,
			},
			{
				name: 'count',
				type: 'string',
				required: false,
			},
			{
				name: 'domain_users_only',
				type: 'string',
				required: false,
			},
			{
				name: 'email',
				type: 'string',
				required: false,
			},
			{
				name: 'email_substring',
				type: 'string',
				required: false,
			},
			{
				name: 'group_id',
				type: 'string',
				required: false,
			},
			{
				name: 'include_license',
				type: 'string',
				required: false,
			},
			{
				name: 'include_usersettings_for_csv',
				type: 'string',
				required: false,
			},
			{
				name: 'login_status',
				type: 'string',
				required: false,
			},
			{
				name: 'not_group_id',
				type: 'string',
				required: false,
			},
			{
				name: 'start_position',
				type: 'string',
				required: false,
			},
			{
				name: 'status',
				type: 'string',
				required: false,
			},
			{
				name: 'user_name_substring',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'removeUserSignatureInformation',
		method: 'DELETE',
		path: '/users/{userId}/signatures/{signatureId}',
		pathParams: ['userId', 'signatureId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'retrieveCustomUserSettings',
		method: 'GET',
		path: '/users/{userId}/custom_settings',
		pathParams: ['userId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'retrieveUserAccountSettings',
		method: 'GET',
		path: '/users/{userId}/settings',
		pathParams: ['userId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'retrieveUserProfileImage',
		method: 'GET',
		path: '/users/{userId}/profile/image',
		pathParams: ['userId'],
		queryParams: [
			{
				name: 'encoding',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'retrieveUserProfileInformation',
		method: 'GET',
		path: '/users/{userId}/profile',
		pathParams: ['userId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'retrieveUserSignatureDefinitions',
		method: 'GET',
		path: '/users/{userId}/signatures',
		pathParams: ['userId'],
		queryParams: [
			{
				name: 'stamp_type',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'retrieveUserSignatureImage',
		method: 'GET',
		path: '/users/{userId}/signatures/{signatureId}/{imageType}',
		pathParams: ['userId', 'signatureId', 'imageType'],
		queryParams: [
			{
				name: 'include_chrome',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'retrieveUserSignatureInformation',
		method: 'GET',
		path: '/users/{userId}/signatures/{signatureId}',
		pathParams: ['userId', 'signatureId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'setUserSignatureImage',
		method: 'PUT',
		path: '/users/{userId}/signatures/{signatureId}/{imageType}',
		pathParams: ['userId', 'signatureId', 'imageType'],
		queryParams: [
			{
				name: 'transparent_png',
				type: 'string',
				required: false,
			},
		],
		hasBody: true,
	},
	{
		name: 'updateUserAccountSettings',
		method: 'PUT',
		path: '/users/{userId}/settings',
		pathParams: ['userId'],
		queryParams: [
			{
				name: 'allow_all_languages',
				type: 'string',
				required: false,
			},
		],
		hasBody: true,
	},
	{
		name: 'updateUserAuthorizationDates',
		method: 'PUT',
		path: '/users/{userId}/authorization/{authorizationId}',
		pathParams: ['userId', 'authorizationId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'updateUserInformationForSpecifiedUser',
		method: 'PUT',
		path: '/users/{userId}',
		pathParams: ['userId'],
		queryParams: [
			{
				name: 'allow_all_languages',
				type: 'string',
				required: false,
			},
		],
		hasBody: true,
	},
	{
		name: 'updateUserProfileImage',
		method: 'PUT',
		path: '/users/{userId}/profile/image',
		pathParams: ['userId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'updateUserProfileInformation',
		method: 'PUT',
		path: '/users/{userId}/profile',
		pathParams: ['userId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'updateUserSignatureById',
		method: 'PUT',
		path: '/users/{userId}/signatures/{signatureId}',
		pathParams: ['userId', 'signatureId'],
		queryParams: [
			{
				name: 'close_existing_signature',
				type: 'string',
				required: false,
			},
		],
		hasBody: true,
	},
	{
		name: 'addFileToWorkspace',
		method: 'POST',
		path: '/workspaces/{workspaceId}/folders/{folderId}/files',
		pathParams: ['workspaceId', 'folderId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'createACollaborativeWorkspace',
		method: 'POST',
		path: '/workspaces',
		pathParams: [],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'deleteExistingWorkspaceLogically',
		method: 'DELETE',
		path: '/workspaces/{workspaceId}',
		pathParams: ['workspaceId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'deleteWorkspaceFilesOrFolders',
		method: 'DELETE',
		path: '/workspaces/{workspaceId}/folders/{folderId}',
		pathParams: ['workspaceId', 'folderId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'getWorkspaceFile',
		method: 'GET',
		path: '/workspaces/{workspaceId}/folders/{folderId}/files/{fileId}',
		pathParams: ['workspaceId', 'folderId', 'fileId'],
		queryParams: [
			{
				name: 'is_download',
				type: 'string',
				required: false,
			},
			{
				name: 'pdf_version',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'getWorkspaceFolderContents',
		method: 'GET',
		path: '/workspaces/{workspaceId}/folders/{folderId}',
		pathParams: ['workspaceId', 'folderId'],
		queryParams: [
			{
				name: 'count',
				type: 'string',
				required: false,
			},
			{
				name: 'include_files',
				type: 'string',
				required: false,
			},
			{
				name: 'include_sub_folders',
				type: 'string',
				required: false,
			},
			{
				name: 'include_thumbnails',
				type: 'string',
				required: false,
			},
			{
				name: 'include_user_detail',
				type: 'string',
				required: false,
			},
			{
				name: 'start_position',
				type: 'string',
				required: false,
			},
			{
				name: 'workspace_user_id',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'listWorkspaceFilePages',
		method: 'GET',
		path: '/workspaces/{workspaceId}/folders/{folderId}/files/{fileId}/pages',
		pathParams: ['workspaceId', 'folderId', 'fileId'],
		queryParams: [
			{
				name: 'count',
				type: 'string',
				required: false,
			},
			{
				name: 'dpi',
				type: 'string',
				required: false,
			},
			{
				name: 'max_height',
				type: 'string',
				required: false,
			},
			{
				name: 'max_width',
				type: 'string',
				required: false,
			},
			{
				name: 'start_position',
				type: 'string',
				required: false,
			},
		],
		hasBody: false,
	},
	{
		name: 'listWorkspaces',
		method: 'GET',
		path: '/workspaces',
		pathParams: [],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'retrievePropertiesAboutWorkspace',
		method: 'GET',
		path: '/workspaces/{workspaceId}',
		pathParams: ['workspaceId'],
		queryParams: [],
		hasBody: false,
	},
	{
		name: 'updateWorkspaceInformation',
		method: 'PUT',
		path: '/workspaces/{workspaceId}',
		pathParams: ['workspaceId'],
		queryParams: [],
		hasBody: true,
	},
	{
		name: 'updateWorkspaceItemMetadata',
		method: 'PUT',
		path: '/workspaces/{workspaceId}/folders/{folderId}/files/{fileId}',
		pathParams: ['workspaceId', 'folderId', 'fileId'],
		queryParams: [],
		hasBody: true,
	},
];
