import crypto from "node:crypto";
import path from "path";
import fs from "fs-extra";

import { PKG_ROOT } from "~/consts.js";
import { type Installer } from "~/installers/index.js";

export const envVariablesInstaller: Installer = ({
  projectDir,
  packages,
  scopedAppName,
}) => {
  const usingPrisma = packages?.prisma.inUse;
  const usingDrizzle = packages?.drizzle.inUse;
  const usingDb = usingPrisma === true || usingDrizzle === true;

  const envContent = getEnvContent(
    !!usingPrisma,
    !!usingDrizzle,
    scopedAppName
  );

  // Always use with-better-auth-db.js since we always have betterAuth and always have a db
  const envFile = usingDb ? "with-better-auth-db.js" : "with-better-auth.js";

  const envSchemaSrc = path.join(PKG_ROOT, "template/extras/src/env", envFile);
  const envSchemaDest = path.join(projectDir, "src/env.js");
  fs.copyFileSync(envSchemaSrc, envSchemaDest);

  const envDest = path.join(projectDir, ".env");
  const envExampleDest = path.join(projectDir, ".env.example");

  const _exampleEnvContent = exampleEnvContent + envContent;

  // Generate an auth secret and put in .env, not .env.example
  const secret = Buffer.from(
    crypto.getRandomValues(new Uint8Array(32))
  ).toString("base64");
  const _envContent = envContent.replace(
    'BETTER_AUTH_SECRET=""',
    `BETTER_AUTH_SECRET="${secret}" # Generated by create-t3-app.`
  );

  fs.writeFileSync(envDest, _envContent, "utf-8");
  fs.writeFileSync(envExampleDest, _exampleEnvContent, "utf-8");
};

const getEnvContent = (
  usingPrisma: boolean,
  usingDrizzle: boolean,
  scopedAppName: string
) => {
  let content = `
# When adding additional environment variables, the schema in "/src/env.js"
# should be updated accordingly.
`
    .trim()
    .concat("\n");

  // Always include BetterAuth env vars
  content += `
# Better Auth
# Secret used by Better Auth
BETTER_AUTH_SECRET=""

# Better Auth GitHub OAuth
BETTER_AUTH_GITHUB_CLIENT_ID=""
BETTER_AUTH_GITHUB_CLIENT_SECRET=""
`;

  if (usingPrisma)
    content += `
# Prisma
# https://www.prisma.io/docs/reference/database-reference/connection-urls#env
`;

  if (usingDrizzle) content += "\n# Drizzle\n";

  if (usingPrisma || usingDrizzle) {
    // Always use PostgreSQL
    content += `DATABASE_URL="postgresql://postgres:password@localhost:5432/${scopedAppName}"`;
    content += "\n";
  }

  return content;
};

const exampleEnvContent = `
# Since the ".env" file is gitignored, you can use the ".env.example" file to
# build a new ".env" file when you clone the repo. Keep this file up-to-date
# when you add new variables to \`.env\`.

# This file will be committed to version control, so make sure not to have any
# secrets in it. If you are cloning this repo, create a copy of this file named
# ".env" and populate it with your secrets.
`
  .trim()
  .concat("\n\n");
