import crypto from 'node:crypto';
import fs from 'fs-extra';
import path from 'path';

import type { Installer } from '@/installers/index.js';

export const envVariablesInstaller: Installer = ({
	projectDir,
	scopedAppName,
}) => {
	// Always use Drizzle since it's always included
	const envContent = getEnvContent(scopedAppName);

	const envDest = path.join(projectDir, '.env');
	const envExampleDest = path.join(projectDir, '.env.example');

	const _exampleEnvContent = exampleEnvContent + envContent;

	// Generate an auth secret and put in .env, not .env.example
	const secret = Buffer.from(
		crypto.getRandomValues(new Uint8Array(32)),
	).toString('base64');
	const _envContent = envContent.replace(
		'BETTER_AUTH_SECRET=""',
		`BETTER_AUTH_SECRET="${secret}" # Generated by create-t3-app.`,
	);

	fs.writeFileSync(envDest, _envContent, 'utf-8');
	fs.writeFileSync(envExampleDest, _exampleEnvContent, 'utf-8');
};

const getEnvContent = (scopedAppName: string) => {
	let content = `
# When adding additional environment variables, the schema in "/src/env.js"
# should be updated accordingly.
`
		.trim()
		.concat('\n');

	// Always include BetterAuth env vars
	content += `
# Better Auth
# Secret used by Better Auth
BETTER_AUTH_SECRET=""

# Better Auth GitHub OAuth
BETTER_AUTH_GITHUB_CLIENT_ID=""
BETTER_AUTH_GITHUB_CLIENT_SECRET=""
`;

	// Always use Drizzle with PostgreSQL
	content += `
# Drizzle
DATABASE_URL="postgresql://postgres:password@localhost:5432/${scopedAppName}"

# Corsair
NEXT_PUBLIC_CORSAIR_API_ROUTE="/api/corsair"
`;

	return content;
};

const exampleEnvContent = `
# Since the ".env" file is gitignored, you can use the ".env.example" file to
# build a new ".env" file when you clone the repo. Keep this file up-to-date
# when you add new variables to \`.env\`.

# This file will be committed to version control, so make sure not to have any
# secrets in it. If you are cloning this repo, create a copy of this file named
# ".env" and populate it with your secrets.
`
	.trim()
	.concat('\n\n');
