import { logEventFromContext } from 'corsair/core';
import { makeApifyRequest } from '../client';
import { ApifyEndpointInputSchemas, ApifyEndpointOutputSchemas } from './types';

export type ApifyEndpointInput = {
	path?: Record<string, string>;
	query?: Record<string, string | number | boolean>;
	body?: unknown;
	headers?: Record<string, string>;
};

const interpolatePath = (template: string, params?: Record<string, string>) =>
	template.replace(/\{([^}]+)\}/g, (_: string, key: string) => params?.[key] ?? `{${key}}`);

const makeEndpoint =
	(pathTemplate: string, method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'HEAD' | 'OPTIONS',
	 eventName: string) =>
	async (ctx: any, input: ApifyEndpointInput = {}) => {
		const corsairMethod =
			method === 'HEAD' || method === 'OPTIONS' ? 'GET' : method;
		const path = interpolatePath(pathTemplate, input.path);
		// Base URL already includes `/v2`, so endpoint templates should be relative.
		const relativePath = path.startsWith('/v2/') ? path.slice(3) : path;
		const response = await makeApifyRequest<unknown>(relativePath, ctx.key, {
			method: corsairMethod,
			query: input.query,
			body: input.body as Record<string, unknown> | undefined,
		});
		await logEventFromContext(ctx, eventName, input ?? {}, 'completed');
		return response;
	};

export const ActorBuilds = {
	actorbuildAbortPost: makeEndpoint('/v2/actor-builds/{buildId}/abort', 'POST', 'apify.actorBuilds.actorbuildAbortPost'),
	actorbuildDelete: makeEndpoint('/v2/actor-builds/{buildId}', 'DELETE', 'apify.actorBuilds.actorbuildDelete'),
	actorbuildGet: makeEndpoint('/v2/actor-builds/{buildId}', 'GET', 'apify.actorBuilds.actorbuildGet'),
	actorbuildLogGet: makeEndpoint('/v2/actor-builds/{buildId}/log', 'GET', 'apify.actorBuilds.actorbuildLogGet'),
	actorbuildOpenapiJsonGet: makeEndpoint('/v2/actor-builds/{buildId}/openapi.json', 'GET', 'apify.actorBuilds.actorbuildOpenapiJsonGet'),
	actorbuildsGet: makeEndpoint('/v2/actor-builds', 'GET', 'apify.actorBuilds.actorbuildsGet'),
} as const;

export const ActorRuns = {
	actorrunAbortPost: makeEndpoint('/v2/actor-runs/{runId}/abort', 'POST', 'apify.actorRuns.actorrunAbortPost'),
	actorrunDelete: makeEndpoint('/v2/actor-runs/{runId}', 'DELETE', 'apify.actorRuns.actorrunDelete'),
	actorrunGet: makeEndpoint('/v2/actor-runs/{runId}', 'GET', 'apify.actorRuns.actorrunGet'),
	actorrunMetamorphPost: makeEndpoint('/v2/actor-runs/{runId}/metamorph', 'POST', 'apify.actorRuns.actorrunMetamorphPost'),
	actorrunPut: makeEndpoint('/v2/actor-runs/{runId}', 'PUT', 'apify.actorRuns.actorrunPut'),
	actorrunRebootPost: makeEndpoint('/v2/actor-runs/{runId}/reboot', 'POST', 'apify.actorRuns.actorrunRebootPost'),
	actorrunsGet: makeEndpoint('/v2/actor-runs', 'GET', 'apify.actorRuns.actorrunsGet'),
	postchargerun: makeEndpoint('/v2/actor-runs/{runId}/charge', 'POST', 'apify.actorRuns.postchargerun'),
	postresurrectrun: makeEndpoint('/v2/actor-runs/{runId}/resurrect', 'POST', 'apify.actorRuns.postresurrectrun'),
} as const;

export const ActorTasks = {
	actortaskDelete: makeEndpoint('/v2/actor-tasks/{actorTaskId}', 'DELETE', 'apify.actorTasks.actortaskDelete'),
	actortaskGet: makeEndpoint('/v2/actor-tasks/{actorTaskId}', 'GET', 'apify.actorTasks.actortaskGet'),
	actortaskInputGet: makeEndpoint('/v2/actor-tasks/{actorTaskId}/input', 'GET', 'apify.actorTasks.actortaskInputGet'),
	actortaskInputPut: makeEndpoint('/v2/actor-tasks/{actorTaskId}/input', 'PUT', 'apify.actorTasks.actortaskInputPut'),
	actortaskPut: makeEndpoint('/v2/actor-tasks/{actorTaskId}', 'PUT', 'apify.actorTasks.actortaskPut'),
	actortaskRunsGet: makeEndpoint('/v2/actor-tasks/{actorTaskId}/runs', 'GET', 'apify.actorTasks.actortaskRunsGet'),
	actortaskRunsLastGet: makeEndpoint('/v2/actor-tasks/{actorTaskId}/runs/last', 'GET', 'apify.actorTasks.actortaskRunsLastGet'),
	actortaskRunsPost: makeEndpoint('/v2/actor-tasks/{actorTaskId}/runs', 'POST', 'apify.actorTasks.actortaskRunsPost'),
	actortaskRunsyncGet: makeEndpoint('/v2/actor-tasks/{actorTaskId}/run-sync', 'GET', 'apify.actorTasks.actortaskRunsyncGet'),
	actortaskRunsyncPost: makeEndpoint('/v2/actor-tasks/{actorTaskId}/run-sync', 'POST', 'apify.actorTasks.actortaskRunsyncPost'),
	actortaskRunsyncgetdatasetitemsGet: makeEndpoint('/v2/actor-tasks/{actorTaskId}/run-sync-get-dataset-items', 'GET', 'apify.actorTasks.actortaskRunsyncgetdatasetitemsGet'),
	actortaskRunsyncgetdatasetitemsPost: makeEndpoint('/v2/actor-tasks/{actorTaskId}/run-sync-get-dataset-items', 'POST', 'apify.actorTasks.actortaskRunsyncgetdatasetitemsPost'),
	actortaskWebhooksGet: makeEndpoint('/v2/actor-tasks/{actorTaskId}/webhooks', 'GET', 'apify.actorTasks.actortaskWebhooksGet'),
	actortasksGet: makeEndpoint('/v2/actor-tasks', 'GET', 'apify.actorTasks.actortasksGet'),
	actortasksPost: makeEndpoint('/v2/actor-tasks', 'POST', 'apify.actorTasks.actortasksPost'),
} as const;

export const Actors = {
	actDelete: makeEndpoint('/v2/acts/{actorId}', 'DELETE', 'apify.actors.actDelete'),
	actGet: makeEndpoint('/v2/acts/{actorId}', 'GET', 'apify.actors.actGet'),
	actPut: makeEndpoint('/v2/acts/{actorId}', 'PUT', 'apify.actors.actPut'),
	actsGet: makeEndpoint('/v2/acts', 'GET', 'apify.actors.actsGet'),
	actsPost: makeEndpoint('/v2/acts', 'POST', 'apify.actors.actsPost'),
} as const;

export const ActorsActorBuilds = {
	actBuildAbortPost: makeEndpoint('/v2/acts/{actorId}/builds/{buildId}/abort', 'POST', 'apify.actorsActorBuilds.actBuildAbortPost'),
	actBuildDefaultGet: makeEndpoint('/v2/acts/{actorId}/builds/default', 'GET', 'apify.actorsActorBuilds.actBuildDefaultGet'),
	actBuildGet: makeEndpoint('/v2/acts/{actorId}/builds/{buildId}', 'GET', 'apify.actorsActorBuilds.actBuildGet'),
	actBuildsGet: makeEndpoint('/v2/acts/{actorId}/builds', 'GET', 'apify.actorsActorBuilds.actBuildsGet'),
	actBuildsPost: makeEndpoint('/v2/acts/{actorId}/builds', 'POST', 'apify.actorsActorBuilds.actBuildsPost'),
	actOpenapiJsonGet: makeEndpoint('/v2/acts/{actorId}/builds/{buildId}/openapi.json', 'GET', 'apify.actorsActorBuilds.actOpenapiJsonGet'),
} as const;

export const ActorsActorRuns = {
	actRunAbortPost: makeEndpoint('/v2/acts/{actorId}/runs/{runId}/abort', 'POST', 'apify.actorsActorRuns.actRunAbortPost'),
	actRunGet: makeEndpoint('/v2/acts/{actorId}/runs/{runId}', 'GET', 'apify.actorsActorRuns.actRunGet'),
	actRunMetamorphPost: makeEndpoint('/v2/acts/{actorId}/runs/{runId}/metamorph', 'POST', 'apify.actorsActorRuns.actRunMetamorphPost'),
	actRunResurrectPost: makeEndpoint('/v2/acts/{actorId}/runs/{runId}/resurrect', 'POST', 'apify.actorsActorRuns.actRunResurrectPost'),
	actRunsGet: makeEndpoint('/v2/acts/{actorId}/runs', 'GET', 'apify.actorsActorRuns.actRunsGet'),
	actRunsLastGet: makeEndpoint('/v2/acts/{actorId}/runs/last', 'GET', 'apify.actorsActorRuns.actRunsLastGet'),
	actRunsPost: makeEndpoint('/v2/acts/{actorId}/runs', 'POST', 'apify.actorsActorRuns.actRunsPost'),
	actRunsyncGet: makeEndpoint('/v2/acts/{actorId}/run-sync', 'GET', 'apify.actorsActorRuns.actRunsyncGet'),
	actRunsyncPost: makeEndpoint('/v2/acts/{actorId}/run-sync', 'POST', 'apify.actorsActorRuns.actRunsyncPost'),
	actRunsyncgetdatasetitemsGet: makeEndpoint('/v2/acts/{actorId}/run-sync-get-dataset-items', 'GET', 'apify.actorsActorRuns.actRunsyncgetdatasetitemsGet'),
	actRunsyncgetdatasetitemsPost: makeEndpoint('/v2/acts/{actorId}/run-sync-get-dataset-items', 'POST', 'apify.actorsActorRuns.actRunsyncgetdatasetitemsPost'),
} as const;

export const ActorsActorVersions = {
	actVersionDelete: makeEndpoint('/v2/acts/{actorId}/versions/{versionNumber}', 'DELETE', 'apify.actorsActorVersions.actVersionDelete'),
	actVersionEnvvarDelete: makeEndpoint('/v2/acts/{actorId}/versions/{versionNumber}/env-vars/{envVarName}', 'DELETE', 'apify.actorsActorVersions.actVersionEnvvarDelete'),
	actVersionEnvvarGet: makeEndpoint('/v2/acts/{actorId}/versions/{versionNumber}/env-vars/{envVarName}', 'GET', 'apify.actorsActorVersions.actVersionEnvvarGet'),
	actVersionEnvvarPost: makeEndpoint('/v2/acts/{actorId}/versions/{versionNumber}/env-vars/{envVarName}', 'POST', 'apify.actorsActorVersions.actVersionEnvvarPost'),
	actVersionEnvvarPut: makeEndpoint('/v2/acts/{actorId}/versions/{versionNumber}/env-vars/{envVarName}', 'PUT', 'apify.actorsActorVersions.actVersionEnvvarPut'),
	actVersionEnvvarsGet: makeEndpoint('/v2/acts/{actorId}/versions/{versionNumber}/env-vars', 'GET', 'apify.actorsActorVersions.actVersionEnvvarsGet'),
	actVersionEnvvarsPost: makeEndpoint('/v2/acts/{actorId}/versions/{versionNumber}/env-vars', 'POST', 'apify.actorsActorVersions.actVersionEnvvarsPost'),
	actVersionGet: makeEndpoint('/v2/acts/{actorId}/versions/{versionNumber}', 'GET', 'apify.actorsActorVersions.actVersionGet'),
	actVersionPost: makeEndpoint('/v2/acts/{actorId}/versions/{versionNumber}', 'POST', 'apify.actorsActorVersions.actVersionPost'),
	actVersionPut: makeEndpoint('/v2/acts/{actorId}/versions/{versionNumber}', 'PUT', 'apify.actorsActorVersions.actVersionPut'),
	actVersionsGet: makeEndpoint('/v2/acts/{actorId}/versions', 'GET', 'apify.actorsActorVersions.actVersionsGet'),
	actVersionsPost: makeEndpoint('/v2/acts/{actorId}/versions', 'POST', 'apify.actorsActorVersions.actVersionsPost'),
} as const;

export const ActorsWebhookCollection = {
	actWebhooksGet: makeEndpoint('/v2/acts/{actorId}/webhooks', 'GET', 'apify.actorsWebhookCollection.actWebhooksGet'),
} as const;

export const Logs = {
	logGet: makeEndpoint('/v2/logs/{buildOrRunId}', 'GET', 'apify.logs.logGet'),
} as const;

export const Schedules = {
	scheduleDelete: makeEndpoint('/v2/schedules/{scheduleId}', 'DELETE', 'apify.schedules.scheduleDelete'),
	scheduleGet: makeEndpoint('/v2/schedules/{scheduleId}', 'GET', 'apify.schedules.scheduleGet'),
	scheduleLogGet: makeEndpoint('/v2/schedules/{scheduleId}/log', 'GET', 'apify.schedules.scheduleLogGet'),
	schedulePut: makeEndpoint('/v2/schedules/{scheduleId}', 'PUT', 'apify.schedules.schedulePut'),
	schedulesGet: makeEndpoint('/v2/schedules', 'GET', 'apify.schedules.schedulesGet'),
	schedulesPost: makeEndpoint('/v2/schedules', 'POST', 'apify.schedules.schedulesPost'),
} as const;

export const StorageDatasets = {
	datasetDelete: makeEndpoint('/v2/datasets/{datasetId}', 'DELETE', 'apify.storageDatasets.datasetDelete'),
	datasetGet: makeEndpoint('/v2/datasets/{datasetId}', 'GET', 'apify.storageDatasets.datasetGet'),
	datasetItemsGet: makeEndpoint('/v2/datasets/{datasetId}/items', 'GET', 'apify.storageDatasets.datasetItemsGet'),
	datasetItemsHead: makeEndpoint('/v2/datasets/{datasetId}/items', 'HEAD', 'apify.storageDatasets.datasetItemsHead'),
	datasetItemsPost: makeEndpoint('/v2/datasets/{datasetId}/items', 'POST', 'apify.storageDatasets.datasetItemsPost'),
	datasetPut: makeEndpoint('/v2/datasets/{datasetId}', 'PUT', 'apify.storageDatasets.datasetPut'),
	datasetStatisticsGet: makeEndpoint('/v2/datasets/{datasetId}/statistics', 'GET', 'apify.storageDatasets.datasetStatisticsGet'),
	datasetsGet: makeEndpoint('/v2/datasets', 'GET', 'apify.storageDatasets.datasetsGet'),
	datasetsPost: makeEndpoint('/v2/datasets', 'POST', 'apify.storageDatasets.datasetsPost'),
} as const;

export const StorageKeyValueStores = {
	keyvaluestoreDelete: makeEndpoint('/v2/key-value-stores/{storeId}', 'DELETE', 'apify.storageKeyValueStores.keyvaluestoreDelete'),
	keyvaluestoreGet: makeEndpoint('/v2/key-value-stores/{storeId}', 'GET', 'apify.storageKeyValueStores.keyvaluestoreGet'),
	keyvaluestoreKeysGet: makeEndpoint('/v2/key-value-stores/{storeId}/keys', 'GET', 'apify.storageKeyValueStores.keyvaluestoreKeysGet'),
	keyvaluestorePut: makeEndpoint('/v2/key-value-stores/{storeId}', 'PUT', 'apify.storageKeyValueStores.keyvaluestorePut'),
	keyvaluestoreRecordDelete: makeEndpoint('/v2/key-value-stores/{storeId}/records/{recordKey}', 'DELETE', 'apify.storageKeyValueStores.keyvaluestoreRecordDelete'),
	keyvaluestoreRecordGet: makeEndpoint('/v2/key-value-stores/{storeId}/records/{recordKey}', 'GET', 'apify.storageKeyValueStores.keyvaluestoreRecordGet'),
	keyvaluestoreRecordHead: makeEndpoint('/v2/key-value-stores/{storeId}/records/{recordKey}', 'HEAD', 'apify.storageKeyValueStores.keyvaluestoreRecordHead'),
	keyvaluestoreRecordPost: makeEndpoint('/v2/key-value-stores/{storeId}/records/{recordKey}', 'POST', 'apify.storageKeyValueStores.keyvaluestoreRecordPost'),
	keyvaluestoreRecordPut: makeEndpoint('/v2/key-value-stores/{storeId}/records/{recordKey}', 'PUT', 'apify.storageKeyValueStores.keyvaluestoreRecordPut'),
	keyvaluestoreRecordsGet: makeEndpoint('/v2/key-value-stores/{storeId}/records', 'GET', 'apify.storageKeyValueStores.keyvaluestoreRecordsGet'),
	keyvaluestoresGet: makeEndpoint('/v2/key-value-stores', 'GET', 'apify.storageKeyValueStores.keyvaluestoresGet'),
	keyvaluestoresPost: makeEndpoint('/v2/key-value-stores', 'POST', 'apify.storageKeyValueStores.keyvaluestoresPost'),
} as const;

export const StorageRequestQueues = {
	requestqueueDelete: makeEndpoint('/v2/request-queues/{queueId}', 'DELETE', 'apify.storageRequestQueues.requestqueueDelete'),
	requestqueueGet: makeEndpoint('/v2/request-queues/{queueId}', 'GET', 'apify.storageRequestQueues.requestqueueGet'),
	requestqueuePut: makeEndpoint('/v2/request-queues/{queueId}', 'PUT', 'apify.storageRequestQueues.requestqueuePut'),
	requestqueueRequestsBatchDelete: makeEndpoint('/v2/request-queues/{queueId}/requests/batch', 'DELETE', 'apify.storageRequestQueues.requestqueueRequestsBatchDelete'),
	requestqueueRequestsBatchPost: makeEndpoint('/v2/request-queues/{queueId}/requests/batch', 'POST', 'apify.storageRequestQueues.requestqueueRequestsBatchPost'),
	requestqueuesGet: makeEndpoint('/v2/request-queues', 'GET', 'apify.storageRequestQueues.requestqueuesGet'),
	requestqueuesPost: makeEndpoint('/v2/request-queues', 'POST', 'apify.storageRequestQueues.requestqueuesPost'),
} as const;

export const StorageRequestQueuesRequests = {
	requestqueueRequestDelete: makeEndpoint('/v2/request-queues/{queueId}/requests/{requestId}', 'DELETE', 'apify.storageRequestQueuesRequests.requestqueueRequestDelete'),
	requestqueueRequestGet: makeEndpoint('/v2/request-queues/{queueId}/requests/{requestId}', 'GET', 'apify.storageRequestQueuesRequests.requestqueueRequestGet'),
	requestqueueRequestPut: makeEndpoint('/v2/request-queues/{queueId}/requests/{requestId}', 'PUT', 'apify.storageRequestQueuesRequests.requestqueueRequestPut'),
	requestqueueRequestsGet: makeEndpoint('/v2/request-queues/{queueId}/requests', 'GET', 'apify.storageRequestQueuesRequests.requestqueueRequestsGet'),
	requestqueueRequestsPost: makeEndpoint('/v2/request-queues/{queueId}/requests', 'POST', 'apify.storageRequestQueuesRequests.requestqueueRequestsPost'),
} as const;

export const StorageRequestQueuesRequestsLocks = {
	requestqueueHeadGet: makeEndpoint('/v2/request-queues/{queueId}/head', 'GET', 'apify.storageRequestQueuesRequestsLocks.requestqueueHeadGet'),
	requestqueueHeadLockPost: makeEndpoint('/v2/request-queues/{queueId}/head/lock', 'POST', 'apify.storageRequestQueuesRequestsLocks.requestqueueHeadLockPost'),
	requestqueueRequestLockDelete: makeEndpoint('/v2/request-queues/{queueId}/requests/{requestId}/lock', 'DELETE', 'apify.storageRequestQueuesRequestsLocks.requestqueueRequestLockDelete'),
	requestqueueRequestLockPut: makeEndpoint('/v2/request-queues/{queueId}/requests/{requestId}/lock', 'PUT', 'apify.storageRequestQueuesRequestsLocks.requestqueueRequestLockPut'),
	requestqueueRequestsUnlockPost: makeEndpoint('/v2/request-queues/{queueId}/requests/unlock', 'POST', 'apify.storageRequestQueuesRequestsLocks.requestqueueRequestsUnlockPost'),
} as const;

export const Store = {
	storeGet: makeEndpoint('/v2/store', 'GET', 'apify.store.storeGet'),
} as const;

export const Tools = {
	toolsBrowserInfoDelete: makeEndpoint('/v2/browser-info', 'DELETE', 'apify.tools.toolsBrowserInfoDelete'),
	toolsBrowserInfoGet: makeEndpoint('/v2/browser-info', 'GET', 'apify.tools.toolsBrowserInfoGet'),
	toolsBrowserInfoPost: makeEndpoint('/v2/browser-info', 'POST', 'apify.tools.toolsBrowserInfoPost'),
	toolsBrowserInfoPut: makeEndpoint('/v2/browser-info', 'PUT', 'apify.tools.toolsBrowserInfoPut'),
	toolsDecodeAndVerifyPost: makeEndpoint('/v2/tools/decode-and-verify', 'POST', 'apify.tools.toolsDecodeAndVerifyPost'),
	toolsEncodeAndSignPost: makeEndpoint('/v2/tools/encode-and-sign', 'POST', 'apify.tools.toolsEncodeAndSignPost'),
} as const;

export const Users = {
	userGet: makeEndpoint('/v2/users/{userId}', 'GET', 'apify.users.userGet'),
	usersMeGet: makeEndpoint('/v2/users/me', 'GET', 'apify.users.usersMeGet'),
	usersMeLimitsGet: makeEndpoint('/v2/users/me/limits', 'GET', 'apify.users.usersMeLimitsGet'),
	usersMeLimitsPut: makeEndpoint('/v2/users/me/limits', 'PUT', 'apify.users.usersMeLimitsPut'),
	usersMeUsageMonthlyGet: makeEndpoint('/v2/users/me/usage/monthly', 'GET', 'apify.users.usersMeUsageMonthlyGet'),
} as const;

export const WebhooksWebhookDispatches = {
	webhookdispatchGet: makeEndpoint('/v2/webhook-dispatches/{dispatchId}', 'GET', 'apify.webhooksWebhookDispatches.webhookdispatchGet'),
	webhookdispatchesGet: makeEndpoint('/v2/webhook-dispatches', 'GET', 'apify.webhooksWebhookDispatches.webhookdispatchesGet'),
} as const;

export const WebhooksWebhooks = {
	webhookDelete: makeEndpoint('/v2/webhooks/{webhookId}', 'DELETE', 'apify.webhooksWebhooks.webhookDelete'),
	webhookGet: makeEndpoint('/v2/webhooks/{webhookId}', 'GET', 'apify.webhooksWebhooks.webhookGet'),
	webhookPut: makeEndpoint('/v2/webhooks/{webhookId}', 'PUT', 'apify.webhooksWebhooks.webhookPut'),
	webhookTestPost: makeEndpoint('/v2/webhooks/{webhookId}/test', 'POST', 'apify.webhooksWebhooks.webhookTestPost'),
	webhookWebhookdispatchesGet: makeEndpoint('/v2/webhooks/{webhookId}/dispatches', 'GET', 'apify.webhooksWebhooks.webhookWebhookdispatchesGet'),
	webhooksGet: makeEndpoint('/v2/webhooks', 'GET', 'apify.webhooksWebhooks.webhooksGet'),
	webhooksPost: makeEndpoint('/v2/webhooks', 'POST', 'apify.webhooksWebhooks.webhooksPost'),
} as const;

export const apifyEndpointsNested = {
	actorBuilds: ActorBuilds,
	actorRuns: ActorRuns,
	actorTasks: ActorTasks,
	actors: Actors,
	actorsActorBuilds: ActorsActorBuilds,
	actorsActorRuns: ActorsActorRuns,
	actorsActorVersions: ActorsActorVersions,
	actorsWebhookCollection: ActorsWebhookCollection,
	logs: Logs,
	schedules: Schedules,
	storageDatasets: StorageDatasets,
	storageKeyValueStores: StorageKeyValueStores,
	storageRequestQueues: StorageRequestQueues,
	storageRequestQueuesRequests: StorageRequestQueuesRequests,
	storageRequestQueuesRequestsLocks: StorageRequestQueuesRequestsLocks,
	store: Store,
	tools: Tools,
	users: Users,
	webhooksWebhookDispatches: WebhooksWebhookDispatches,
	webhooksWebhooks: WebhooksWebhooks,
} as const;

export const apifyEndpointSchemas = {
	'actorBuilds.actorbuildAbortPost': { input: ApifyEndpointInputSchemas.actorbuildAbortPost, output: ApifyEndpointOutputSchemas.actorbuildAbortPost },
	'actorBuilds.actorbuildDelete': { input: ApifyEndpointInputSchemas.actorbuildDelete, output: ApifyEndpointOutputSchemas.actorbuildDelete },
	'actorBuilds.actorbuildGet': { input: ApifyEndpointInputSchemas.actorbuildGet, output: ApifyEndpointOutputSchemas.actorbuildGet },
	'actorBuilds.actorbuildLogGet': { input: ApifyEndpointInputSchemas.actorbuildLogGet, output: ApifyEndpointOutputSchemas.actorbuildLogGet },
	'actorBuilds.actorbuildOpenapiJsonGet': { input: ApifyEndpointInputSchemas.actorbuildOpenapiJsonGet, output: ApifyEndpointOutputSchemas.actorbuildOpenapiJsonGet },
	'actorBuilds.actorbuildsGet': { input: ApifyEndpointInputSchemas.actorbuildsGet, output: ApifyEndpointOutputSchemas.actorbuildsGet },
	'actorRuns.actorrunAbortPost': { input: ApifyEndpointInputSchemas.actorrunAbortPost, output: ApifyEndpointOutputSchemas.actorrunAbortPost },
	'actorRuns.actorrunDelete': { input: ApifyEndpointInputSchemas.actorrunDelete, output: ApifyEndpointOutputSchemas.actorrunDelete },
	'actorRuns.actorrunGet': { input: ApifyEndpointInputSchemas.actorrunGet, output: ApifyEndpointOutputSchemas.actorrunGet },
	'actorRuns.actorrunMetamorphPost': { input: ApifyEndpointInputSchemas.actorrunMetamorphPost, output: ApifyEndpointOutputSchemas.actorrunMetamorphPost },
	'actorRuns.actorrunPut': { input: ApifyEndpointInputSchemas.actorrunPut, output: ApifyEndpointOutputSchemas.actorrunPut },
	'actorRuns.actorrunRebootPost': { input: ApifyEndpointInputSchemas.actorrunRebootPost, output: ApifyEndpointOutputSchemas.actorrunRebootPost },
	'actorRuns.actorrunsGet': { input: ApifyEndpointInputSchemas.actorrunsGet, output: ApifyEndpointOutputSchemas.actorrunsGet },
	'actorRuns.postchargerun': { input: ApifyEndpointInputSchemas.postchargerun, output: ApifyEndpointOutputSchemas.postchargerun },
	'actorRuns.postresurrectrun': { input: ApifyEndpointInputSchemas.postresurrectrun, output: ApifyEndpointOutputSchemas.postresurrectrun },
	'actorTasks.actortaskDelete': { input: ApifyEndpointInputSchemas.actortaskDelete, output: ApifyEndpointOutputSchemas.actortaskDelete },
	'actorTasks.actortaskGet': { input: ApifyEndpointInputSchemas.actortaskGet, output: ApifyEndpointOutputSchemas.actortaskGet },
	'actorTasks.actortaskInputGet': { input: ApifyEndpointInputSchemas.actortaskInputGet, output: ApifyEndpointOutputSchemas.actortaskInputGet },
	'actorTasks.actortaskInputPut': { input: ApifyEndpointInputSchemas.actortaskInputPut, output: ApifyEndpointOutputSchemas.actortaskInputPut },
	'actorTasks.actortaskPut': { input: ApifyEndpointInputSchemas.actortaskPut, output: ApifyEndpointOutputSchemas.actortaskPut },
	'actorTasks.actortaskRunsGet': { input: ApifyEndpointInputSchemas.actortaskRunsGet, output: ApifyEndpointOutputSchemas.actortaskRunsGet },
	'actorTasks.actortaskRunsLastGet': { input: ApifyEndpointInputSchemas.actortaskRunsLastGet, output: ApifyEndpointOutputSchemas.actortaskRunsLastGet },
	'actorTasks.actortaskRunsPost': { input: ApifyEndpointInputSchemas.actortaskRunsPost, output: ApifyEndpointOutputSchemas.actortaskRunsPost },
	'actorTasks.actortaskRunsyncGet': { input: ApifyEndpointInputSchemas.actortaskRunsyncGet, output: ApifyEndpointOutputSchemas.actortaskRunsyncGet },
	'actorTasks.actortaskRunsyncPost': { input: ApifyEndpointInputSchemas.actortaskRunsyncPost, output: ApifyEndpointOutputSchemas.actortaskRunsyncPost },
	'actorTasks.actortaskRunsyncgetdatasetitemsGet': { input: ApifyEndpointInputSchemas.actortaskRunsyncgetdatasetitemsGet, output: ApifyEndpointOutputSchemas.actortaskRunsyncgetdatasetitemsGet },
	'actorTasks.actortaskRunsyncgetdatasetitemsPost': { input: ApifyEndpointInputSchemas.actortaskRunsyncgetdatasetitemsPost, output: ApifyEndpointOutputSchemas.actortaskRunsyncgetdatasetitemsPost },
	'actorTasks.actortaskWebhooksGet': { input: ApifyEndpointInputSchemas.actortaskWebhooksGet, output: ApifyEndpointOutputSchemas.actortaskWebhooksGet },
	'actorTasks.actortasksGet': { input: ApifyEndpointInputSchemas.actortasksGet, output: ApifyEndpointOutputSchemas.actortasksGet },
	'actorTasks.actortasksPost': { input: ApifyEndpointInputSchemas.actortasksPost, output: ApifyEndpointOutputSchemas.actortasksPost },
	'actors.actDelete': { input: ApifyEndpointInputSchemas.actDelete, output: ApifyEndpointOutputSchemas.actDelete },
	'actors.actGet': { input: ApifyEndpointInputSchemas.actGet, output: ApifyEndpointOutputSchemas.actGet },
	'actors.actPut': { input: ApifyEndpointInputSchemas.actPut, output: ApifyEndpointOutputSchemas.actPut },
	'actors.actsGet': { input: ApifyEndpointInputSchemas.actsGet, output: ApifyEndpointOutputSchemas.actsGet },
	'actors.actsPost': { input: ApifyEndpointInputSchemas.actsPost, output: ApifyEndpointOutputSchemas.actsPost },
	'actorsActorBuilds.actBuildAbortPost': { input: ApifyEndpointInputSchemas.actBuildAbortPost, output: ApifyEndpointOutputSchemas.actBuildAbortPost },
	'actorsActorBuilds.actBuildDefaultGet': { input: ApifyEndpointInputSchemas.actBuildDefaultGet, output: ApifyEndpointOutputSchemas.actBuildDefaultGet },
	'actorsActorBuilds.actBuildGet': { input: ApifyEndpointInputSchemas.actBuildGet, output: ApifyEndpointOutputSchemas.actBuildGet },
	'actorsActorBuilds.actBuildsGet': { input: ApifyEndpointInputSchemas.actBuildsGet, output: ApifyEndpointOutputSchemas.actBuildsGet },
	'actorsActorBuilds.actBuildsPost': { input: ApifyEndpointInputSchemas.actBuildsPost, output: ApifyEndpointOutputSchemas.actBuildsPost },
	'actorsActorBuilds.actOpenapiJsonGet': { input: ApifyEndpointInputSchemas.actOpenapiJsonGet, output: ApifyEndpointOutputSchemas.actOpenapiJsonGet },
	'actorsActorRuns.actRunAbortPost': { input: ApifyEndpointInputSchemas.actRunAbortPost, output: ApifyEndpointOutputSchemas.actRunAbortPost },
	'actorsActorRuns.actRunGet': { input: ApifyEndpointInputSchemas.actRunGet, output: ApifyEndpointOutputSchemas.actRunGet },
	'actorsActorRuns.actRunMetamorphPost': { input: ApifyEndpointInputSchemas.actRunMetamorphPost, output: ApifyEndpointOutputSchemas.actRunMetamorphPost },
	'actorsActorRuns.actRunResurrectPost': { input: ApifyEndpointInputSchemas.actRunResurrectPost, output: ApifyEndpointOutputSchemas.actRunResurrectPost },
	'actorsActorRuns.actRunsGet': { input: ApifyEndpointInputSchemas.actRunsGet, output: ApifyEndpointOutputSchemas.actRunsGet },
	'actorsActorRuns.actRunsLastGet': { input: ApifyEndpointInputSchemas.actRunsLastGet, output: ApifyEndpointOutputSchemas.actRunsLastGet },
	'actorsActorRuns.actRunsPost': { input: ApifyEndpointInputSchemas.actRunsPost, output: ApifyEndpointOutputSchemas.actRunsPost },
	'actorsActorRuns.actRunsyncGet': { input: ApifyEndpointInputSchemas.actRunsyncGet, output: ApifyEndpointOutputSchemas.actRunsyncGet },
	'actorsActorRuns.actRunsyncPost': { input: ApifyEndpointInputSchemas.actRunsyncPost, output: ApifyEndpointOutputSchemas.actRunsyncPost },
	'actorsActorRuns.actRunsyncgetdatasetitemsGet': { input: ApifyEndpointInputSchemas.actRunsyncgetdatasetitemsGet, output: ApifyEndpointOutputSchemas.actRunsyncgetdatasetitemsGet },
	'actorsActorRuns.actRunsyncgetdatasetitemsPost': { input: ApifyEndpointInputSchemas.actRunsyncgetdatasetitemsPost, output: ApifyEndpointOutputSchemas.actRunsyncgetdatasetitemsPost },
	'actorsActorVersions.actVersionDelete': { input: ApifyEndpointInputSchemas.actVersionDelete, output: ApifyEndpointOutputSchemas.actVersionDelete },
	'actorsActorVersions.actVersionEnvvarDelete': { input: ApifyEndpointInputSchemas.actVersionEnvvarDelete, output: ApifyEndpointOutputSchemas.actVersionEnvvarDelete },
	'actorsActorVersions.actVersionEnvvarGet': { input: ApifyEndpointInputSchemas.actVersionEnvvarGet, output: ApifyEndpointOutputSchemas.actVersionEnvvarGet },
	'actorsActorVersions.actVersionEnvvarPost': { input: ApifyEndpointInputSchemas.actVersionEnvvarPost, output: ApifyEndpointOutputSchemas.actVersionEnvvarPost },
	'actorsActorVersions.actVersionEnvvarPut': { input: ApifyEndpointInputSchemas.actVersionEnvvarPut, output: ApifyEndpointOutputSchemas.actVersionEnvvarPut },
	'actorsActorVersions.actVersionEnvvarsGet': { input: ApifyEndpointInputSchemas.actVersionEnvvarsGet, output: ApifyEndpointOutputSchemas.actVersionEnvvarsGet },
	'actorsActorVersions.actVersionEnvvarsPost': { input: ApifyEndpointInputSchemas.actVersionEnvvarsPost, output: ApifyEndpointOutputSchemas.actVersionEnvvarsPost },
	'actorsActorVersions.actVersionGet': { input: ApifyEndpointInputSchemas.actVersionGet, output: ApifyEndpointOutputSchemas.actVersionGet },
	'actorsActorVersions.actVersionPost': { input: ApifyEndpointInputSchemas.actVersionPost, output: ApifyEndpointOutputSchemas.actVersionPost },
	'actorsActorVersions.actVersionPut': { input: ApifyEndpointInputSchemas.actVersionPut, output: ApifyEndpointOutputSchemas.actVersionPut },
	'actorsActorVersions.actVersionsGet': { input: ApifyEndpointInputSchemas.actVersionsGet, output: ApifyEndpointOutputSchemas.actVersionsGet },
	'actorsActorVersions.actVersionsPost': { input: ApifyEndpointInputSchemas.actVersionsPost, output: ApifyEndpointOutputSchemas.actVersionsPost },
	'actorsWebhookCollection.actWebhooksGet': { input: ApifyEndpointInputSchemas.actWebhooksGet, output: ApifyEndpointOutputSchemas.actWebhooksGet },
	'logs.logGet': { input: ApifyEndpointInputSchemas.logGet, output: ApifyEndpointOutputSchemas.logGet },
	'schedules.scheduleDelete': { input: ApifyEndpointInputSchemas.scheduleDelete, output: ApifyEndpointOutputSchemas.scheduleDelete },
	'schedules.scheduleGet': { input: ApifyEndpointInputSchemas.scheduleGet, output: ApifyEndpointOutputSchemas.scheduleGet },
	'schedules.scheduleLogGet': { input: ApifyEndpointInputSchemas.scheduleLogGet, output: ApifyEndpointOutputSchemas.scheduleLogGet },
	'schedules.schedulePut': { input: ApifyEndpointInputSchemas.schedulePut, output: ApifyEndpointOutputSchemas.schedulePut },
	'schedules.schedulesGet': { input: ApifyEndpointInputSchemas.schedulesGet, output: ApifyEndpointOutputSchemas.schedulesGet },
	'schedules.schedulesPost': { input: ApifyEndpointInputSchemas.schedulesPost, output: ApifyEndpointOutputSchemas.schedulesPost },
	'storageDatasets.datasetDelete': { input: ApifyEndpointInputSchemas.datasetDelete, output: ApifyEndpointOutputSchemas.datasetDelete },
	'storageDatasets.datasetGet': { input: ApifyEndpointInputSchemas.datasetGet, output: ApifyEndpointOutputSchemas.datasetGet },
	'storageDatasets.datasetItemsGet': { input: ApifyEndpointInputSchemas.datasetItemsGet, output: ApifyEndpointOutputSchemas.datasetItemsGet },
	'storageDatasets.datasetItemsHead': { input: ApifyEndpointInputSchemas.datasetItemsHead, output: ApifyEndpointOutputSchemas.datasetItemsHead },
	'storageDatasets.datasetItemsPost': { input: ApifyEndpointInputSchemas.datasetItemsPost, output: ApifyEndpointOutputSchemas.datasetItemsPost },
	'storageDatasets.datasetPut': { input: ApifyEndpointInputSchemas.datasetPut, output: ApifyEndpointOutputSchemas.datasetPut },
	'storageDatasets.datasetStatisticsGet': { input: ApifyEndpointInputSchemas.datasetStatisticsGet, output: ApifyEndpointOutputSchemas.datasetStatisticsGet },
	'storageDatasets.datasetsGet': { input: ApifyEndpointInputSchemas.datasetsGet, output: ApifyEndpointOutputSchemas.datasetsGet },
	'storageDatasets.datasetsPost': { input: ApifyEndpointInputSchemas.datasetsPost, output: ApifyEndpointOutputSchemas.datasetsPost },
	'storageKeyValueStores.keyvaluestoreDelete': { input: ApifyEndpointInputSchemas.keyvaluestoreDelete, output: ApifyEndpointOutputSchemas.keyvaluestoreDelete },
	'storageKeyValueStores.keyvaluestoreGet': { input: ApifyEndpointInputSchemas.keyvaluestoreGet, output: ApifyEndpointOutputSchemas.keyvaluestoreGet },
	'storageKeyValueStores.keyvaluestoreKeysGet': { input: ApifyEndpointInputSchemas.keyvaluestoreKeysGet, output: ApifyEndpointOutputSchemas.keyvaluestoreKeysGet },
	'storageKeyValueStores.keyvaluestorePut': { input: ApifyEndpointInputSchemas.keyvaluestorePut, output: ApifyEndpointOutputSchemas.keyvaluestorePut },
	'storageKeyValueStores.keyvaluestoreRecordDelete': { input: ApifyEndpointInputSchemas.keyvaluestoreRecordDelete, output: ApifyEndpointOutputSchemas.keyvaluestoreRecordDelete },
	'storageKeyValueStores.keyvaluestoreRecordGet': { input: ApifyEndpointInputSchemas.keyvaluestoreRecordGet, output: ApifyEndpointOutputSchemas.keyvaluestoreRecordGet },
	'storageKeyValueStores.keyvaluestoreRecordHead': { input: ApifyEndpointInputSchemas.keyvaluestoreRecordHead, output: ApifyEndpointOutputSchemas.keyvaluestoreRecordHead },
	'storageKeyValueStores.keyvaluestoreRecordPost': { input: ApifyEndpointInputSchemas.keyvaluestoreRecordPost, output: ApifyEndpointOutputSchemas.keyvaluestoreRecordPost },
	'storageKeyValueStores.keyvaluestoreRecordPut': { input: ApifyEndpointInputSchemas.keyvaluestoreRecordPut, output: ApifyEndpointOutputSchemas.keyvaluestoreRecordPut },
	'storageKeyValueStores.keyvaluestoreRecordsGet': { input: ApifyEndpointInputSchemas.keyvaluestoreRecordsGet, output: ApifyEndpointOutputSchemas.keyvaluestoreRecordsGet },
	'storageKeyValueStores.keyvaluestoresGet': { input: ApifyEndpointInputSchemas.keyvaluestoresGet, output: ApifyEndpointOutputSchemas.keyvaluestoresGet },
	'storageKeyValueStores.keyvaluestoresPost': { input: ApifyEndpointInputSchemas.keyvaluestoresPost, output: ApifyEndpointOutputSchemas.keyvaluestoresPost },
	'storageRequestQueues.requestqueueDelete': { input: ApifyEndpointInputSchemas.requestqueueDelete, output: ApifyEndpointOutputSchemas.requestqueueDelete },
	'storageRequestQueues.requestqueueGet': { input: ApifyEndpointInputSchemas.requestqueueGet, output: ApifyEndpointOutputSchemas.requestqueueGet },
	'storageRequestQueues.requestqueuePut': { input: ApifyEndpointInputSchemas.requestqueuePut, output: ApifyEndpointOutputSchemas.requestqueuePut },
	'storageRequestQueues.requestqueueRequestsBatchDelete': { input: ApifyEndpointInputSchemas.requestqueueRequestsBatchDelete, output: ApifyEndpointOutputSchemas.requestqueueRequestsBatchDelete },
	'storageRequestQueues.requestqueueRequestsBatchPost': { input: ApifyEndpointInputSchemas.requestqueueRequestsBatchPost, output: ApifyEndpointOutputSchemas.requestqueueRequestsBatchPost },
	'storageRequestQueues.requestqueuesGet': { input: ApifyEndpointInputSchemas.requestqueuesGet, output: ApifyEndpointOutputSchemas.requestqueuesGet },
	'storageRequestQueues.requestqueuesPost': { input: ApifyEndpointInputSchemas.requestqueuesPost, output: ApifyEndpointOutputSchemas.requestqueuesPost },
	'storageRequestQueuesRequests.requestqueueRequestDelete': { input: ApifyEndpointInputSchemas.requestqueueRequestDelete, output: ApifyEndpointOutputSchemas.requestqueueRequestDelete },
	'storageRequestQueuesRequests.requestqueueRequestGet': { input: ApifyEndpointInputSchemas.requestqueueRequestGet, output: ApifyEndpointOutputSchemas.requestqueueRequestGet },
	'storageRequestQueuesRequests.requestqueueRequestPut': { input: ApifyEndpointInputSchemas.requestqueueRequestPut, output: ApifyEndpointOutputSchemas.requestqueueRequestPut },
	'storageRequestQueuesRequests.requestqueueRequestsGet': { input: ApifyEndpointInputSchemas.requestqueueRequestsGet, output: ApifyEndpointOutputSchemas.requestqueueRequestsGet },
	'storageRequestQueuesRequests.requestqueueRequestsPost': { input: ApifyEndpointInputSchemas.requestqueueRequestsPost, output: ApifyEndpointOutputSchemas.requestqueueRequestsPost },
	'storageRequestQueuesRequestsLocks.requestqueueHeadGet': { input: ApifyEndpointInputSchemas.requestqueueHeadGet, output: ApifyEndpointOutputSchemas.requestqueueHeadGet },
	'storageRequestQueuesRequestsLocks.requestqueueHeadLockPost': { input: ApifyEndpointInputSchemas.requestqueueHeadLockPost, output: ApifyEndpointOutputSchemas.requestqueueHeadLockPost },
	'storageRequestQueuesRequestsLocks.requestqueueRequestLockDelete': { input: ApifyEndpointInputSchemas.requestqueueRequestLockDelete, output: ApifyEndpointOutputSchemas.requestqueueRequestLockDelete },
	'storageRequestQueuesRequestsLocks.requestqueueRequestLockPut': { input: ApifyEndpointInputSchemas.requestqueueRequestLockPut, output: ApifyEndpointOutputSchemas.requestqueueRequestLockPut },
	'storageRequestQueuesRequestsLocks.requestqueueRequestsUnlockPost': { input: ApifyEndpointInputSchemas.requestqueueRequestsUnlockPost, output: ApifyEndpointOutputSchemas.requestqueueRequestsUnlockPost },
	'store.storeGet': { input: ApifyEndpointInputSchemas.storeGet, output: ApifyEndpointOutputSchemas.storeGet },
	'tools.toolsBrowserInfoDelete': { input: ApifyEndpointInputSchemas.toolsBrowserInfoDelete, output: ApifyEndpointOutputSchemas.toolsBrowserInfoDelete },
	'tools.toolsBrowserInfoGet': { input: ApifyEndpointInputSchemas.toolsBrowserInfoGet, output: ApifyEndpointOutputSchemas.toolsBrowserInfoGet },
	'tools.toolsBrowserInfoPost': { input: ApifyEndpointInputSchemas.toolsBrowserInfoPost, output: ApifyEndpointOutputSchemas.toolsBrowserInfoPost },
	'tools.toolsBrowserInfoPut': { input: ApifyEndpointInputSchemas.toolsBrowserInfoPut, output: ApifyEndpointOutputSchemas.toolsBrowserInfoPut },
	'tools.toolsDecodeAndVerifyPost': { input: ApifyEndpointInputSchemas.toolsDecodeAndVerifyPost, output: ApifyEndpointOutputSchemas.toolsDecodeAndVerifyPost },
	'tools.toolsEncodeAndSignPost': { input: ApifyEndpointInputSchemas.toolsEncodeAndSignPost, output: ApifyEndpointOutputSchemas.toolsEncodeAndSignPost },
	'users.userGet': { input: ApifyEndpointInputSchemas.userGet, output: ApifyEndpointOutputSchemas.userGet },
	'users.usersMeGet': { input: ApifyEndpointInputSchemas.usersMeGet, output: ApifyEndpointOutputSchemas.usersMeGet },
	'users.usersMeLimitsGet': { input: ApifyEndpointInputSchemas.usersMeLimitsGet, output: ApifyEndpointOutputSchemas.usersMeLimitsGet },
	'users.usersMeLimitsPut': { input: ApifyEndpointInputSchemas.usersMeLimitsPut, output: ApifyEndpointOutputSchemas.usersMeLimitsPut },
	'users.usersMeUsageMonthlyGet': { input: ApifyEndpointInputSchemas.usersMeUsageMonthlyGet, output: ApifyEndpointOutputSchemas.usersMeUsageMonthlyGet },
	'webhooksWebhookDispatches.webhookdispatchGet': { input: ApifyEndpointInputSchemas.webhookdispatchGet, output: ApifyEndpointOutputSchemas.webhookdispatchGet },
	'webhooksWebhookDispatches.webhookdispatchesGet': { input: ApifyEndpointInputSchemas.webhookdispatchesGet, output: ApifyEndpointOutputSchemas.webhookdispatchesGet },
	'webhooksWebhooks.webhookDelete': { input: ApifyEndpointInputSchemas.webhookDelete, output: ApifyEndpointOutputSchemas.webhookDelete },
	'webhooksWebhooks.webhookGet': { input: ApifyEndpointInputSchemas.webhookGet, output: ApifyEndpointOutputSchemas.webhookGet },
	'webhooksWebhooks.webhookPut': { input: ApifyEndpointInputSchemas.webhookPut, output: ApifyEndpointOutputSchemas.webhookPut },
	'webhooksWebhooks.webhookTestPost': { input: ApifyEndpointInputSchemas.webhookTestPost, output: ApifyEndpointOutputSchemas.webhookTestPost },
	'webhooksWebhooks.webhookWebhookdispatchesGet': { input: ApifyEndpointInputSchemas.webhookWebhookdispatchesGet, output: ApifyEndpointOutputSchemas.webhookWebhookdispatchesGet },
	'webhooksWebhooks.webhooksGet': { input: ApifyEndpointInputSchemas.webhooksGet, output: ApifyEndpointOutputSchemas.webhooksGet },
	'webhooksWebhooks.webhooksPost': { input: ApifyEndpointInputSchemas.webhooksPost, output: ApifyEndpointOutputSchemas.webhooksPost },
} as const;

export const apifyEndpointMeta = {
	'actorBuilds.actorbuildAbortPost': { riskLevel: 'write', description: 'Abort build' },
	'actorBuilds.actorbuildDelete': { riskLevel: 'destructive', description: 'Delete build' },
	'actorBuilds.actorbuildGet': { riskLevel: 'read', description: 'Get build' },
	'actorBuilds.actorbuildLogGet': { riskLevel: 'read', description: 'Get log' },
	'actorBuilds.actorbuildOpenapiJsonGet': { riskLevel: 'read', description: 'Get OpenAPI definition' },
	'actorBuilds.actorbuildsGet': { riskLevel: 'read', description: 'Get user builds list' },
	'actorRuns.actorrunAbortPost': { riskLevel: 'write', description: 'Abort run' },
	'actorRuns.actorrunDelete': { riskLevel: 'destructive', description: 'Delete run' },
	'actorRuns.actorrunGet': { riskLevel: 'read', description: 'Get run' },
	'actorRuns.actorrunMetamorphPost': { riskLevel: 'write', description: 'Metamorph run' },
	'actorRuns.actorrunPut': { riskLevel: 'write', description: 'Update run' },
	'actorRuns.actorrunRebootPost': { riskLevel: 'write', description: 'Reboot run' },
	'actorRuns.actorrunsGet': { riskLevel: 'read', description: 'Get user runs list' },
	'actorRuns.postchargerun': { riskLevel: 'write', description: 'Charge events in run' },
	'actorRuns.postresurrectrun': { riskLevel: 'write', description: 'Resurrect run' },
	'actorTasks.actortaskDelete': { riskLevel: 'destructive', description: 'Delete task' },
	'actorTasks.actortaskGet': { riskLevel: 'read', description: 'Get task' },
	'actorTasks.actortaskInputGet': { riskLevel: 'read', description: 'Get task input' },
	'actorTasks.actortaskInputPut': { riskLevel: 'write', description: 'Update task input' },
	'actorTasks.actortaskPut': { riskLevel: 'write', description: 'Update task' },
	'actorTasks.actortaskRunsGet': { riskLevel: 'read', description: 'Get list of task runs' },
	'actorTasks.actortaskRunsLastGet': { riskLevel: 'read', description: 'Get last run' },
	'actorTasks.actortaskRunsPost': { riskLevel: 'write', description: 'Run task' },
	'actorTasks.actortaskRunsyncGet': { riskLevel: 'read', description: 'Run task synchronously' },
	'actorTasks.actortaskRunsyncPost': { riskLevel: 'write', description: 'Run task synchronously' },
	'actorTasks.actortaskRunsyncgetdatasetitemsGet': { riskLevel: 'read', description: 'Run task synchronously and get dataset items' },
	'actorTasks.actortaskRunsyncgetdatasetitemsPost': { riskLevel: 'write', description: 'Run task synchronously and get dataset items' },
	'actorTasks.actortaskWebhooksGet': { riskLevel: 'read', description: 'Get list of webhooks' },
	'actorTasks.actortasksGet': { riskLevel: 'read', description: 'Get list of tasks' },
	'actorTasks.actortasksPost': { riskLevel: 'write', description: 'Create task' },
	'actors.actDelete': { riskLevel: 'destructive', description: 'Delete Actor' },
	'actors.actGet': { riskLevel: 'read', description: 'Get Actor' },
	'actors.actPut': { riskLevel: 'write', description: 'Update Actor' },
	'actors.actsGet': { riskLevel: 'read', description: 'Get list of Actors' },
	'actors.actsPost': { riskLevel: 'write', description: 'Create Actor' },
	'actorsActorBuilds.actBuildAbortPost': { riskLevel: 'write', description: 'Abort build' },
	'actorsActorBuilds.actBuildDefaultGet': { riskLevel: 'read', description: 'Get default build' },
	'actorsActorBuilds.actBuildGet': { riskLevel: 'read', description: 'Get build' },
	'actorsActorBuilds.actBuildsGet': { riskLevel: 'read', description: 'Get list of builds' },
	'actorsActorBuilds.actBuildsPost': { riskLevel: 'write', description: 'Build Actor' },
	'actorsActorBuilds.actOpenapiJsonGet': { riskLevel: 'read', description: 'Get OpenAPI definition' },
	'actorsActorRuns.actRunAbortPost': { riskLevel: 'write', description: 'Abort run' },
	'actorsActorRuns.actRunGet': { riskLevel: 'read', description: 'Get run' },
	'actorsActorRuns.actRunMetamorphPost': { riskLevel: 'write', description: 'Metamorph run' },
	'actorsActorRuns.actRunResurrectPost': { riskLevel: 'write', description: 'Resurrect run' },
	'actorsActorRuns.actRunsGet': { riskLevel: 'read', description: 'Get list of runs' },
	'actorsActorRuns.actRunsLastGet': { riskLevel: 'read', description: 'Get last run' },
	'actorsActorRuns.actRunsPost': { riskLevel: 'write', description: 'Run Actor' },
	'actorsActorRuns.actRunsyncGet': { riskLevel: 'read', description: 'Without input' },
	'actorsActorRuns.actRunsyncPost': { riskLevel: 'write', description: 'Run Actor synchronously with input and return output' },
	'actorsActorRuns.actRunsyncgetdatasetitemsGet': { riskLevel: 'read', description: 'Run Actor synchronously without input and get dataset items' },
	'actorsActorRuns.actRunsyncgetdatasetitemsPost': { riskLevel: 'write', description: 'Run Actor synchronously with input and get dataset items' },
	'actorsActorVersions.actVersionDelete': { riskLevel: 'destructive', description: 'Delete version' },
	'actorsActorVersions.actVersionEnvvarDelete': { riskLevel: 'destructive', description: 'Delete environment variable' },
	'actorsActorVersions.actVersionEnvvarGet': { riskLevel: 'read', description: 'Get environment variable' },
	'actorsActorVersions.actVersionEnvvarPost': { riskLevel: 'write', description: 'Update environment variable (POST)' },
	'actorsActorVersions.actVersionEnvvarPut': { riskLevel: 'write', description: 'Update environment variable' },
	'actorsActorVersions.actVersionEnvvarsGet': { riskLevel: 'read', description: 'Get list of environment variables' },
	'actorsActorVersions.actVersionEnvvarsPost': { riskLevel: 'write', description: 'Create environment variable' },
	'actorsActorVersions.actVersionGet': { riskLevel: 'read', description: 'Get version' },
	'actorsActorVersions.actVersionPost': { riskLevel: 'write', description: 'Update version (POST)' },
	'actorsActorVersions.actVersionPut': { riskLevel: 'write', description: 'Update version' },
	'actorsActorVersions.actVersionsGet': { riskLevel: 'read', description: 'Get list of versions' },
	'actorsActorVersions.actVersionsPost': { riskLevel: 'write', description: 'Create version' },
	'actorsWebhookCollection.actWebhooksGet': { riskLevel: 'read', description: 'Get list of webhooks' },
	'logs.logGet': { riskLevel: 'read', description: 'Get log' },
	'schedules.scheduleDelete': { riskLevel: 'destructive', description: 'Delete schedule' },
	'schedules.scheduleGet': { riskLevel: 'read', description: 'Get schedule' },
	'schedules.scheduleLogGet': { riskLevel: 'read', description: 'Get schedule log' },
	'schedules.schedulePut': { riskLevel: 'write', description: 'Update schedule' },
	'schedules.schedulesGet': { riskLevel: 'read', description: 'Get list of schedules' },
	'schedules.schedulesPost': { riskLevel: 'write', description: 'Create schedule' },
	'storageDatasets.datasetDelete': { riskLevel: 'destructive', description: 'Delete dataset' },
	'storageDatasets.datasetGet': { riskLevel: 'read', description: 'Get dataset' },
	'storageDatasets.datasetItemsGet': { riskLevel: 'read', description: 'Get dataset items' },
	'storageDatasets.datasetItemsHead': { riskLevel: 'read', description: 'Get dataset items headers' },
	'storageDatasets.datasetItemsPost': { riskLevel: 'write', description: 'Store items' },
	'storageDatasets.datasetPut': { riskLevel: 'write', description: 'Update dataset' },
	'storageDatasets.datasetStatisticsGet': { riskLevel: 'read', description: 'Get dataset statistics' },
	'storageDatasets.datasetsGet': { riskLevel: 'read', description: 'Get list of datasets' },
	'storageDatasets.datasetsPost': { riskLevel: 'write', description: 'Create dataset' },
	'storageKeyValueStores.keyvaluestoreDelete': { riskLevel: 'destructive', description: 'Delete store' },
	'storageKeyValueStores.keyvaluestoreGet': { riskLevel: 'read', description: 'Get store' },
	'storageKeyValueStores.keyvaluestoreKeysGet': { riskLevel: 'read', description: 'Get list of keys' },
	'storageKeyValueStores.keyvaluestorePut': { riskLevel: 'write', description: 'Update store' },
	'storageKeyValueStores.keyvaluestoreRecordDelete': { riskLevel: 'destructive', description: 'Delete record' },
	'storageKeyValueStores.keyvaluestoreRecordGet': { riskLevel: 'read', description: 'Get record' },
	'storageKeyValueStores.keyvaluestoreRecordHead': { riskLevel: 'read', description: 'Check if a record exists' },
	'storageKeyValueStores.keyvaluestoreRecordPost': { riskLevel: 'write', description: 'Store record (POST)' },
	'storageKeyValueStores.keyvaluestoreRecordPut': { riskLevel: 'write', description: 'Store record' },
	'storageKeyValueStores.keyvaluestoreRecordsGet': { riskLevel: 'read', description: 'Download records' },
	'storageKeyValueStores.keyvaluestoresGet': { riskLevel: 'read', description: 'Get list of key-value stores' },
	'storageKeyValueStores.keyvaluestoresPost': { riskLevel: 'write', description: 'Create key-value store' },
	'storageRequestQueues.requestqueueDelete': { riskLevel: 'destructive', description: 'Delete request queue' },
	'storageRequestQueues.requestqueueGet': { riskLevel: 'read', description: 'Get request queue' },
	'storageRequestQueues.requestqueuePut': { riskLevel: 'write', description: 'Update request queue' },
	'storageRequestQueues.requestqueueRequestsBatchDelete': { riskLevel: 'destructive', description: 'Delete requests' },
	'storageRequestQueues.requestqueueRequestsBatchPost': { riskLevel: 'write', description: 'Add requests' },
	'storageRequestQueues.requestqueuesGet': { riskLevel: 'read', description: 'Get list of request queues' },
	'storageRequestQueues.requestqueuesPost': { riskLevel: 'write', description: 'Create request queue' },
	'storageRequestQueuesRequests.requestqueueRequestDelete': { riskLevel: 'destructive', description: 'Delete request' },
	'storageRequestQueuesRequests.requestqueueRequestGet': { riskLevel: 'read', description: 'Get request' },
	'storageRequestQueuesRequests.requestqueueRequestPut': { riskLevel: 'write', description: 'Update request' },
	'storageRequestQueuesRequests.requestqueueRequestsGet': { riskLevel: 'read', description: 'List requests' },
	'storageRequestQueuesRequests.requestqueueRequestsPost': { riskLevel: 'write', description: 'Add request' },
	'storageRequestQueuesRequestsLocks.requestqueueHeadGet': { riskLevel: 'read', description: 'Get head' },
	'storageRequestQueuesRequestsLocks.requestqueueHeadLockPost': { riskLevel: 'write', description: 'Get head and lock' },
	'storageRequestQueuesRequestsLocks.requestqueueRequestLockDelete': { riskLevel: 'destructive', description: 'Delete request lock' },
	'storageRequestQueuesRequestsLocks.requestqueueRequestLockPut': { riskLevel: 'write', description: 'Prolong request lock' },
	'storageRequestQueuesRequestsLocks.requestqueueRequestsUnlockPost': { riskLevel: 'write', description: 'Unlock requests' },
	'store.storeGet': { riskLevel: 'read', description: 'Get list of Actors in store' },
	'tools.toolsBrowserInfoDelete': { riskLevel: 'destructive', description: 'Get browser info' },
	'tools.toolsBrowserInfoGet': { riskLevel: 'read', description: 'Get browser info' },
	'tools.toolsBrowserInfoPost': { riskLevel: 'write', description: 'Get browser info' },
	'tools.toolsBrowserInfoPut': { riskLevel: 'write', description: 'Get browser info' },
	'tools.toolsDecodeAndVerifyPost': { riskLevel: 'write', description: 'Decode and verify object' },
	'tools.toolsEncodeAndSignPost': { riskLevel: 'write', description: 'Encode and sign object' },
	'users.userGet': { riskLevel: 'read', description: 'Get public user data' },
	'users.usersMeGet': { riskLevel: 'read', description: 'Get private user data' },
	'users.usersMeLimitsGet': { riskLevel: 'read', description: 'Get limits' },
	'users.usersMeLimitsPut': { riskLevel: 'write', description: 'Update limits' },
	'users.usersMeUsageMonthlyGet': { riskLevel: 'read', description: 'Get monthly usage' },
	'webhooksWebhookDispatches.webhookdispatchGet': { riskLevel: 'read', description: 'Get webhook dispatch' },
	'webhooksWebhookDispatches.webhookdispatchesGet': { riskLevel: 'read', description: 'Get list of webhook dispatches' },
	'webhooksWebhooks.webhookDelete': { riskLevel: 'destructive', description: 'Delete webhook' },
	'webhooksWebhooks.webhookGet': { riskLevel: 'read', description: 'Get webhook' },
	'webhooksWebhooks.webhookPut': { riskLevel: 'write', description: 'Update webhook' },
	'webhooksWebhooks.webhookTestPost': { riskLevel: 'write', description: 'Test webhook' },
	'webhooksWebhooks.webhookWebhookdispatchesGet': { riskLevel: 'read', description: 'Get collection' },
	'webhooksWebhooks.webhooksGet': { riskLevel: 'read', description: 'Get list of webhooks' },
	'webhooksWebhooks.webhooksPost': { riskLevel: 'write', description: 'Create webhook' },
} as const;

export * from './types';
