import type { EndpointRiskLevel } from 'corsair/core';

export type ApifyOperationMethod =
	| 'GET'
	| 'POST'
	| 'PUT'
	| 'DELETE'
	| 'PATCH'
	| 'HEAD';

export type ApifyOperationDefinition = {
	method: ApifyOperationMethod;
	path: string;
	pathParams: readonly string[];
	queryParams?: readonly string[];
	riskLevel: EndpointRiskLevel;
	irreversible?: boolean;
	description: string;
};

export type ApifyOperationTree = {
	readonly [key: string]: ApifyOperationDefinition | ApifyOperationTree;
};

export const apifyOperations = {
	act: {
		buildAbortPost: {
			method: 'POST',
			path: '/v2/actors/{actorId}/builds/{buildId}/abort',
			pathParams: ['actorId', 'buildId'],
			riskLevel: 'write',
			description: 'Deprecated. Abort build',
		},
		buildDefaultGet: {
			method: 'GET',
			path: '/v2/actors/{actorId}/builds/default',
			pathParams: ['actorId'],
			queryParams: ['waitForFinish'],
			riskLevel: 'read',
			description: 'Get default build',
		},
		buildGet: {
			method: 'GET',
			path: '/v2/actors/{actorId}/builds/{buildId}',
			pathParams: ['actorId', 'buildId'],
			queryParams: ['waitForFinish'],
			riskLevel: 'read',
			description: 'Deprecated. Get build',
		},
		buildsGet: {
			method: 'GET',
			path: '/v2/actors/{actorId}/builds',
			pathParams: ['actorId'],
			queryParams: ['offset', 'limit', 'desc'],
			riskLevel: 'read',
			description: 'Get list of builds',
		},
		buildsPost: {
			method: 'POST',
			path: '/v2/actors/{actorId}/builds',
			pathParams: ['actorId'],
			queryParams: [
				'version',
				'useCache',
				'betaPackages',
				'tag',
				'waitForFinish',
			],
			riskLevel: 'write',
			description: 'Build Actor',
		},
		delete: {
			method: 'DELETE',
			path: '/v2/actors/{actorId}',
			pathParams: ['actorId'],
			riskLevel: 'destructive',
			irreversible: true,
			description: 'Delete Actor',
		},
		get: {
			method: 'GET',
			path: '/v2/actors/{actorId}',
			pathParams: ['actorId'],
			riskLevel: 'read',
			description: 'Get Actor',
		},
		openapiJsonGet: {
			method: 'GET',
			path: '/v2/actors/{actorId}/builds/{buildId}/openapi.json',
			pathParams: ['actorId', 'buildId'],
			riskLevel: 'read',
			description: 'Get OpenAPI definition',
		},
		put: {
			method: 'PUT',
			path: '/v2/actors/{actorId}',
			pathParams: ['actorId'],
			riskLevel: 'write',
			description: 'Update Actor',
		},
		runAbortPost: {
			method: 'POST',
			path: '/v2/actors/{actorId}/runs/{runId}/abort',
			pathParams: ['actorId', 'runId'],
			queryParams: ['gracefully'],
			riskLevel: 'write',
			description: 'Deprecated. Abort run',
		},
		runGet: {
			method: 'GET',
			path: '/v2/actors/{actorId}/runs/{runId}',
			pathParams: ['actorId', 'runId'],
			queryParams: ['waitForFinish'],
			riskLevel: 'read',
			description: 'Deprecated. Get run',
		},
		runMetamorphPost: {
			method: 'POST',
			path: '/v2/actors/{actorId}/runs/{runId}/metamorph',
			pathParams: ['actorId', 'runId'],
			queryParams: ['targetActorId', 'build'],
			riskLevel: 'write',
			description: 'Deprecated. Metamorph run',
		},
		runResurrectPost: {
			method: 'POST',
			path: '/v2/actors/{actorId}/runs/{runId}/resurrect',
			pathParams: ['actorId', 'runId'],
			queryParams: ['build', 'timeout', 'memory', 'restartOnError'],
			riskLevel: 'write',
			description: 'Resurrect run',
		},
		runsGet: {
			method: 'GET',
			path: '/v2/actors/{actorId}/runs',
			pathParams: ['actorId'],
			queryParams: [
				'offset',
				'limit',
				'desc',
				'status',
				'startedAfter',
				'startedBefore',
			],
			riskLevel: 'read',
			description: 'Get list of runs',
		},
		runsLastAbortPost: {
			method: 'POST',
			path: '/v2/actors/{actorId}/runs/last/abort',
			pathParams: ['actorId'],
			queryParams: ['status', 'origin', 'gracefully'],
			riskLevel: 'write',
			description: "Abort Actor's last run",
		},
		runsLastDatasetDelete: {
			method: 'DELETE',
			path: '/v2/actors/{actorId}/runs/last/dataset',
			pathParams: ['actorId'],
			queryParams: ['status', 'origin'],
			riskLevel: 'destructive',
			irreversible: true,
			description: "Delete last run's default dataset",
		},
		runsLastDatasetGet: {
			method: 'GET',
			path: '/v2/actors/{actorId}/runs/last/dataset',
			pathParams: ['actorId'],
			queryParams: ['status', 'origin'],
			riskLevel: 'read',
			description: "Get last run's default dataset",
		},
		runsLastDatasetItemsGet: {
			method: 'GET',
			path: '/v2/actors/{actorId}/runs/last/dataset/items',
			pathParams: ['actorId'],
			queryParams: [
				'status',
				'origin',
				'format',
				'clean',
				'offset',
				'limit',
				'fields',
				'outputFields',
				'omit',
				'unwind',
				'flatten',
				'desc',
				'attachment',
				'delimiter',
				'bom',
				'xmlRoot',
				'xmlRow',
				'skipHeaderRow',
				'skipHidden',
				'skipEmpty',
				'simplified',
				'view',
				'skipFailedPages',
				'feedTitle',
				'feedDescription',
				'signature',
			],
			riskLevel: 'read',
			description: "Get last run's dataset items",
		},
		runsLastDatasetItemsPost: {
			method: 'POST',
			path: '/v2/actors/{actorId}/runs/last/dataset/items',
			pathParams: ['actorId'],
			queryParams: ['status', 'origin'],
			riskLevel: 'write',
			description: "Store items in last run's dataset",
		},
		runsLastDatasetPut: {
			method: 'PUT',
			path: '/v2/actors/{actorId}/runs/last/dataset',
			pathParams: ['actorId'],
			queryParams: ['status', 'origin'],
			riskLevel: 'write',
			description: "Update last run's default dataset",
		},
		runsLastDatasetStatisticsGet: {
			method: 'GET',
			path: '/v2/actors/{actorId}/runs/last/dataset/statistics',
			pathParams: ['actorId'],
			queryParams: ['status', 'origin'],
			riskLevel: 'read',
			description: "Get last run's dataset statistics",
		},
		runsLastGet: {
			method: 'GET',
			path: '/v2/actors/{actorId}/runs/last',
			pathParams: ['actorId'],
			queryParams: ['status', 'origin', 'waitForFinish'],
			riskLevel: 'read',
			description: 'Get last run',
		},
		runsLastKeyValueStoreDelete: {
			method: 'DELETE',
			path: '/v2/actors/{actorId}/runs/last/key-value-store',
			pathParams: ['actorId'],
			queryParams: ['status', 'origin'],
			riskLevel: 'destructive',
			irreversible: true,
			description: "Delete last run's default store",
		},
		runsLastKeyValueStoreGet: {
			method: 'GET',
			path: '/v2/actors/{actorId}/runs/last/key-value-store',
			pathParams: ['actorId'],
			queryParams: ['status', 'origin'],
			riskLevel: 'read',
			description: "Get last run's default store",
		},
		runsLastKeyValueStoreKeysGet: {
			method: 'GET',
			path: '/v2/actors/{actorId}/runs/last/key-value-store/keys',
			pathParams: ['actorId'],
			queryParams: [
				'status',
				'origin',
				'exclusiveStartKey',
				'limit',
				'collection',
				'prefix',
				'signature',
			],
			riskLevel: 'read',
			description: "Get last run's default store's list of keys",
		},
		runsLastKeyValueStorePut: {
			method: 'PUT',
			path: '/v2/actors/{actorId}/runs/last/key-value-store',
			pathParams: ['actorId'],
			queryParams: ['status', 'origin'],
			riskLevel: 'write',
			description: "Update last run's default store",
		},
		runsLastKeyValueStoreRecordDelete: {
			method: 'DELETE',
			path: '/v2/actors/{actorId}/runs/last/key-value-store/records/{recordKey}',
			pathParams: ['actorId', 'recordKey'],
			queryParams: ['status', 'origin'],
			riskLevel: 'destructive',
			irreversible: true,
			description: "Delete last run's default store's record",
		},
		runsLastKeyValueStoreRecordGet: {
			method: 'GET',
			path: '/v2/actors/{actorId}/runs/last/key-value-store/records/{recordKey}',
			pathParams: ['actorId', 'recordKey'],
			queryParams: ['status', 'origin', 'signature', 'attachment'],
			riskLevel: 'read',
			description: "Get last run's default store's record",
		},
		runsLastKeyValueStoreRecordPost: {
			method: 'POST',
			path: '/v2/actors/{actorId}/runs/last/key-value-store/records/{recordKey}',
			pathParams: ['actorId', 'recordKey'],
			queryParams: ['status', 'origin'],
			riskLevel: 'write',
			description: "Store record in last run's default store (POST)",
		},
		runsLastKeyValueStoreRecordPut: {
			method: 'PUT',
			path: '/v2/actors/{actorId}/runs/last/key-value-store/records/{recordKey}',
			pathParams: ['actorId', 'recordKey'],
			queryParams: ['status', 'origin'],
			riskLevel: 'write',
			description: "Store record in last run's default store",
		},
		runsLastKeyValueStoreRecordsGet: {
			method: 'GET',
			path: '/v2/actors/{actorId}/runs/last/key-value-store/records',
			pathParams: ['actorId'],
			queryParams: ['status', 'origin', 'collection', 'prefix', 'signature'],
			riskLevel: 'read',
			description: "Download last run's default store's records",
		},
		runsLastLogGet: {
			method: 'GET',
			path: '/v2/actors/{actorId}/runs/last/log',
			pathParams: ['actorId'],
			queryParams: ['status', 'origin', 'stream', 'download', 'raw'],
			riskLevel: 'read',
			description: "Get last Actor run's log",
		},
		runsLastMetamorphPost: {
			method: 'POST',
			path: '/v2/actors/{actorId}/runs/last/metamorph',
			pathParams: ['actorId'],
			queryParams: ['status', 'origin', 'targetActorId', 'build'],
			riskLevel: 'write',
			description: "Metamorph Actor's last run",
		},
		runsLastRebootPost: {
			method: 'POST',
			path: '/v2/actors/{actorId}/runs/last/reboot',
			pathParams: ['actorId'],
			queryParams: ['status', 'origin'],
			riskLevel: 'write',
			description: "Reboot Actor's last run",
		},
		runsLastRequestQueueDelete: {
			method: 'DELETE',
			path: '/v2/actors/{actorId}/runs/last/request-queue',
			pathParams: ['actorId'],
			queryParams: ['status', 'origin'],
			riskLevel: 'destructive',
			irreversible: true,
			description: "Delete last run's default request queue",
		},
		runsLastRequestQueueGet: {
			method: 'GET',
			path: '/v2/actors/{actorId}/runs/last/request-queue',
			pathParams: ['actorId'],
			queryParams: ['status', 'origin'],
			riskLevel: 'read',
			description: "Get last run's default request queue",
		},
		runsLastRequestQueueHeadGet: {
			method: 'GET',
			path: '/v2/actors/{actorId}/runs/last/request-queue/head',
			pathParams: ['actorId'],
			queryParams: ['status', 'origin', 'limit', 'clientKey'],
			riskLevel: 'read',
			description: "Get last run's default request queue head",
		},
		runsLastRequestQueueHeadLockPost: {
			method: 'POST',
			path: '/v2/actors/{actorId}/runs/last/request-queue/head/lock',
			pathParams: ['actorId'],
			queryParams: ['status', 'origin', 'lockSecs', 'limit', 'clientKey'],
			riskLevel: 'write',
			description: "Get and lock last run's default request queue head",
		},
		runsLastRequestQueuePut: {
			method: 'PUT',
			path: '/v2/actors/{actorId}/runs/last/request-queue',
			pathParams: ['actorId'],
			queryParams: ['status', 'origin'],
			riskLevel: 'write',
			description: "Update last run's default request queue",
		},
		runsLastRequestQueueRequestDelete: {
			method: 'DELETE',
			path: '/v2/actors/{actorId}/runs/last/request-queue/requests/{requestId}',
			pathParams: ['actorId', 'requestId'],
			queryParams: ['status', 'origin', 'clientKey'],
			riskLevel: 'destructive',
			irreversible: true,
			description: "Delete request from last run's default request queue",
		},
		runsLastRequestQueueRequestGet: {
			method: 'GET',
			path: '/v2/actors/{actorId}/runs/last/request-queue/requests/{requestId}',
			pathParams: ['actorId', 'requestId'],
			queryParams: ['status', 'origin'],
			riskLevel: 'read',
			description: "Get request from last run's default request queue",
		},
		runsLastRequestQueueRequestLockDelete: {
			method: 'DELETE',
			path: '/v2/actors/{actorId}/runs/last/request-queue/requests/{requestId}/lock',
			pathParams: ['actorId', 'requestId'],
			queryParams: ['status', 'origin', 'clientKey', 'forefront'],
			riskLevel: 'write',
			description: "Delete lock on request in last run's default request queue",
		},
		runsLastRequestQueueRequestLockPut: {
			method: 'PUT',
			path: '/v2/actors/{actorId}/runs/last/request-queue/requests/{requestId}/lock',
			pathParams: ['actorId', 'requestId'],
			queryParams: ['status', 'origin', 'lockSecs', 'clientKey', 'forefront'],
			riskLevel: 'write',
			description:
				"Prolong lock on request in last run's default request queue",
		},
		runsLastRequestQueueRequestPut: {
			method: 'PUT',
			path: '/v2/actors/{actorId}/runs/last/request-queue/requests/{requestId}',
			pathParams: ['actorId', 'requestId'],
			queryParams: ['status', 'origin', 'forefront', 'clientKey'],
			riskLevel: 'write',
			description: "Update request in last run's default request queue",
		},
		runsLastRequestQueueRequestsBatchDelete: {
			method: 'DELETE',
			path: '/v2/actors/{actorId}/runs/last/request-queue/requests/batch',
			pathParams: ['actorId'],
			queryParams: ['status', 'origin', 'clientKey'],
			riskLevel: 'destructive',
			irreversible: true,
			description:
				"Batch delete requests from last run's default request queue",
		},
		runsLastRequestQueueRequestsBatchPost: {
			method: 'POST',
			path: '/v2/actors/{actorId}/runs/last/request-queue/requests/batch',
			pathParams: ['actorId'],
			queryParams: ['status', 'origin', 'clientKey', 'forefront'],
			riskLevel: 'write',
			description: "Batch add requests to last run's default request queue",
		},
		runsLastRequestQueueRequestsGet: {
			method: 'GET',
			path: '/v2/actors/{actorId}/runs/last/request-queue/requests',
			pathParams: ['actorId'],
			queryParams: [
				'status',
				'origin',
				'clientKey',
				'exclusiveStartId',
				'limit',
				'cursor',
				'filter',
			],
			riskLevel: 'read',
			description: "List last run's default request queue's requests",
		},
		runsLastRequestQueueRequestsPost: {
			method: 'POST',
			path: '/v2/actors/{actorId}/runs/last/request-queue/requests',
			pathParams: ['actorId'],
			queryParams: ['status', 'origin', 'clientKey', 'forefront'],
			riskLevel: 'write',
			description: "Add request to last run's default request queue",
		},
		runsLastRequestQueueRequestsUnlockPost: {
			method: 'POST',
			path: '/v2/actors/{actorId}/runs/last/request-queue/requests/unlock',
			pathParams: ['actorId'],
			queryParams: ['status', 'origin', 'clientKey'],
			riskLevel: 'write',
			description: "Unlock requests in last run's default request queue",
		},
		runsPost: {
			method: 'POST',
			path: '/v2/actors/{actorId}/runs',
			pathParams: ['actorId'],
			queryParams: [
				'timeout',
				'memory',
				'maxItems',
				'maxTotalChargeUsd',
				'restartOnError',
				'build',
				'waitForFinish',
				'webhooks',
				'forcePermissionLevel',
			],
			riskLevel: 'write',
			description: 'Run Actor',
		},
		runSyncGet: {
			method: 'GET',
			path: '/v2/actors/{actorId}/run-sync',
			pathParams: ['actorId'],
			queryParams: [
				'outputRecordKey',
				'timeout',
				'memory',
				'maxItems',
				'maxTotalChargeUsd',
				'restartOnError',
				'build',
				'webhooks',
			],
			riskLevel: 'write',
			description: 'Run Actor synchronously without input',
		},
		runSyncGetDatasetItemsGet: {
			method: 'GET',
			path: '/v2/actors/{actorId}/run-sync-get-dataset-items',
			pathParams: ['actorId'],
			queryParams: [
				'timeout',
				'memory',
				'maxItems',
				'maxTotalChargeUsd',
				'restartOnError',
				'build',
				'webhooks',
				'format',
				'clean',
				'offset',
				'limit',
				'fields',
				'outputFields',
				'omit',
				'unwind',
				'flatten',
				'desc',
				'attachment',
				'delimiter',
				'bom',
				'xmlRoot',
				'xmlRow',
				'skipHeaderRow',
				'skipHidden',
				'skipEmpty',
				'simplified',
				'view',
				'skipFailedPages',
				'feedTitle',
				'feedDescription',
			],
			riskLevel: 'write',
			description:
				'Run Actor synchronously without input and get dataset items',
		},
		runSyncGetDatasetItemsPost: {
			method: 'POST',
			path: '/v2/actors/{actorId}/run-sync-get-dataset-items',
			pathParams: ['actorId'],
			queryParams: [
				'timeout',
				'memory',
				'maxItems',
				'maxTotalChargeUsd',
				'restartOnError',
				'build',
				'webhooks',
				'format',
				'clean',
				'offset',
				'limit',
				'fields',
				'outputFields',
				'omit',
				'unwind',
				'flatten',
				'desc',
				'attachment',
				'delimiter',
				'bom',
				'xmlRoot',
				'xmlRow',
				'skipHeaderRow',
				'skipHidden',
				'skipEmpty',
				'simplified',
				'view',
				'skipFailedPages',
				'feedTitle',
				'feedDescription',
			],
			riskLevel: 'write',
			description: 'Run Actor synchronously and get dataset items',
		},
		runSyncPost: {
			method: 'POST',
			path: '/v2/actors/{actorId}/run-sync',
			pathParams: ['actorId'],
			queryParams: [
				'outputRecordKey',
				'timeout',
				'memory',
				'maxItems',
				'maxTotalChargeUsd',
				'restartOnError',
				'build',
				'webhooks',
			],
			riskLevel: 'write',
			description: 'Run Actor synchronously and return key-value store record',
		},
		validateInputPost: {
			method: 'POST',
			path: '/v2/actors/{actorId}/validate-input',
			pathParams: ['actorId'],
			queryParams: ['build'],
			riskLevel: 'write',
			description: 'Validate Actor input',
		},
		versionDelete: {
			method: 'DELETE',
			path: '/v2/actors/{actorId}/versions/{versionNumber}',
			pathParams: ['actorId', 'versionNumber'],
			riskLevel: 'destructive',
			irreversible: true,
			description: 'Delete version',
		},
		versionEnvVarDelete: {
			method: 'DELETE',
			path: '/v2/actors/{actorId}/versions/{versionNumber}/env-vars/{envVarName}',
			pathParams: ['actorId', 'versionNumber', 'envVarName'],
			riskLevel: 'destructive',
			irreversible: true,
			description: 'Delete environment variable',
		},
		versionEnvVarGet: {
			method: 'GET',
			path: '/v2/actors/{actorId}/versions/{versionNumber}/env-vars/{envVarName}',
			pathParams: ['actorId', 'versionNumber', 'envVarName'],
			riskLevel: 'read',
			description: 'Get environment variable',
		},
		versionEnvVarPost: {
			method: 'POST',
			path: '/v2/actors/{actorId}/versions/{versionNumber}/env-vars/{envVarName}',
			pathParams: ['actorId', 'versionNumber', 'envVarName'],
			riskLevel: 'write',
			description: 'Update environment variable (POST)',
		},
		versionEnvVarPut: {
			method: 'PUT',
			path: '/v2/actors/{actorId}/versions/{versionNumber}/env-vars/{envVarName}',
			pathParams: ['actorId', 'versionNumber', 'envVarName'],
			riskLevel: 'write',
			description: 'Update environment variable',
		},
		versionEnvVarsGet: {
			method: 'GET',
			path: '/v2/actors/{actorId}/versions/{versionNumber}/env-vars',
			pathParams: ['actorId', 'versionNumber'],
			riskLevel: 'read',
			description: 'Get list of environment variables',
		},
		versionEnvVarsPost: {
			method: 'POST',
			path: '/v2/actors/{actorId}/versions/{versionNumber}/env-vars',
			pathParams: ['actorId', 'versionNumber'],
			riskLevel: 'write',
			description: 'Create environment variable',
		},
		versionGet: {
			method: 'GET',
			path: '/v2/actors/{actorId}/versions/{versionNumber}',
			pathParams: ['actorId', 'versionNumber'],
			riskLevel: 'read',
			description: 'Get version',
		},
		versionPost: {
			method: 'POST',
			path: '/v2/actors/{actorId}/versions/{versionNumber}',
			pathParams: ['actorId', 'versionNumber'],
			riskLevel: 'write',
			description: 'Update version (POST)',
		},
		versionPut: {
			method: 'PUT',
			path: '/v2/actors/{actorId}/versions/{versionNumber}',
			pathParams: ['actorId', 'versionNumber'],
			riskLevel: 'write',
			description: 'Update version',
		},
		versionsGet: {
			method: 'GET',
			path: '/v2/actors/{actorId}/versions',
			pathParams: ['actorId'],
			riskLevel: 'read',
			description: 'Get list of versions',
		},
		versionsPost: {
			method: 'POST',
			path: '/v2/actors/{actorId}/versions',
			pathParams: ['actorId'],
			riskLevel: 'write',
			description: 'Create version',
		},
		webhooksGet: {
			method: 'GET',
			path: '/v2/actors/{actorId}/webhooks',
			pathParams: ['actorId'],
			queryParams: ['offset', 'limit', 'desc'],
			riskLevel: 'read',
			description: 'Get list of webhooks',
		},
	},
	actorBuild: {
		abortPost: {
			method: 'POST',
			path: '/v2/actor-builds/{buildId}/abort',
			pathParams: ['buildId'],
			riskLevel: 'write',
			description: 'Abort build',
		},
		delete: {
			method: 'DELETE',
			path: '/v2/actor-builds/{buildId}',
			pathParams: ['buildId'],
			riskLevel: 'destructive',
			irreversible: true,
			description: 'Delete build',
		},
		get: {
			method: 'GET',
			path: '/v2/actor-builds/{buildId}',
			pathParams: ['buildId'],
			queryParams: ['waitForFinish'],
			riskLevel: 'read',
			description: 'Get build',
		},
		logGet: {
			method: 'GET',
			path: '/v2/actor-builds/{buildId}/log',
			pathParams: ['buildId'],
			queryParams: ['stream', 'download'],
			riskLevel: 'read',
			description: "Get build's Log",
		},
		openapiJsonGet: {
			method: 'GET',
			path: '/v2/actor-builds/{buildId}/openapi.json',
			pathParams: ['buildId'],
			riskLevel: 'read',
			description: 'Get OpenAPI definition',
		},
	},
	actorBuilds: {
		get: {
			method: 'GET',
			path: '/v2/actor-builds',
			pathParams: [],
			queryParams: ['offset', 'limit', 'desc'],
			riskLevel: 'read',
			description: 'Get user builds list',
		},
	},
	actorRun: {
		abortPost: {
			method: 'POST',
			path: '/v2/actor-runs/{runId}/abort',
			pathParams: ['runId'],
			queryParams: ['gracefully'],
			riskLevel: 'write',
			description: 'Abort run',
		},
		datasetDelete: {
			method: 'DELETE',
			path: '/v2/actor-runs/{runId}/dataset',
			pathParams: ['runId'],
			riskLevel: 'destructive',
			irreversible: true,
			description: 'Delete default dataset',
		},
		datasetGet: {
			method: 'GET',
			path: '/v2/actor-runs/{runId}/dataset',
			pathParams: ['runId'],
			riskLevel: 'read',
			description: 'Get default dataset',
		},
		datasetItemsGet: {
			method: 'GET',
			path: '/v2/actor-runs/{runId}/dataset/items',
			pathParams: ['runId'],
			queryParams: [
				'format',
				'clean',
				'offset',
				'limit',
				'fields',
				'outputFields',
				'omit',
				'unwind',
				'flatten',
				'desc',
				'attachment',
				'delimiter',
				'bom',
				'xmlRoot',
				'xmlRow',
				'skipHeaderRow',
				'skipHidden',
				'skipEmpty',
				'simplified',
				'view',
				'skipFailedPages',
				'feedTitle',
				'feedDescription',
				'signature',
			],
			riskLevel: 'read',
			description: 'Get default dataset items',
		},
		datasetItemsPost: {
			method: 'POST',
			path: '/v2/actor-runs/{runId}/dataset/items',
			pathParams: ['runId'],
			riskLevel: 'write',
			description: 'Store items',
		},
		datasetPut: {
			method: 'PUT',
			path: '/v2/actor-runs/{runId}/dataset',
			pathParams: ['runId'],
			riskLevel: 'write',
			description: 'Update default dataset',
		},
		datasetStatisticsGet: {
			method: 'GET',
			path: '/v2/actor-runs/{runId}/dataset/statistics',
			pathParams: ['runId'],
			riskLevel: 'read',
			description: 'Get default dataset statistics',
		},
		delete: {
			method: 'DELETE',
			path: '/v2/actor-runs/{runId}',
			pathParams: ['runId'],
			riskLevel: 'destructive',
			irreversible: true,
			description: 'Delete run',
		},
		get: {
			method: 'GET',
			path: '/v2/actor-runs/{runId}',
			pathParams: ['runId'],
			queryParams: ['waitForFinish'],
			riskLevel: 'read',
			description: 'Get run',
		},
		keyValueStoreDelete: {
			method: 'DELETE',
			path: '/v2/actor-runs/{runId}/key-value-store',
			pathParams: ['runId'],
			riskLevel: 'destructive',
			irreversible: true,
			description: 'Delete default store',
		},
		keyValueStoreGet: {
			method: 'GET',
			path: '/v2/actor-runs/{runId}/key-value-store',
			pathParams: ['runId'],
			riskLevel: 'read',
			description: 'Get default store',
		},
		keyValueStoreKeysGet: {
			method: 'GET',
			path: '/v2/actor-runs/{runId}/key-value-store/keys',
			pathParams: ['runId'],
			queryParams: [
				'exclusiveStartKey',
				'limit',
				'collection',
				'prefix',
				'signature',
			],
			riskLevel: 'read',
			description: "Get default store's list of keys",
		},
		keyValueStorePut: {
			method: 'PUT',
			path: '/v2/actor-runs/{runId}/key-value-store',
			pathParams: ['runId'],
			riskLevel: 'write',
			description: 'Update default store',
		},
		keyValueStoreRecordDelete: {
			method: 'DELETE',
			path: '/v2/actor-runs/{runId}/key-value-store/records/{recordKey}',
			pathParams: ['runId', 'recordKey'],
			riskLevel: 'destructive',
			irreversible: true,
			description: "Delete default store's record",
		},
		keyValueStoreRecordGet: {
			method: 'GET',
			path: '/v2/actor-runs/{runId}/key-value-store/records/{recordKey}',
			pathParams: ['runId', 'recordKey'],
			queryParams: ['signature', 'attachment'],
			riskLevel: 'read',
			description: "Get default store's record",
		},
		keyValueStoreRecordPost: {
			method: 'POST',
			path: '/v2/actor-runs/{runId}/key-value-store/records/{recordKey}',
			pathParams: ['runId', 'recordKey'],
			riskLevel: 'write',
			description: 'Store record in default store (POST)',
		},
		keyValueStoreRecordPut: {
			method: 'PUT',
			path: '/v2/actor-runs/{runId}/key-value-store/records/{recordKey}',
			pathParams: ['runId', 'recordKey'],
			riskLevel: 'write',
			description: 'Store record in default store',
		},
		keyValueStoreRecordsGet: {
			method: 'GET',
			path: '/v2/actor-runs/{runId}/key-value-store/records',
			pathParams: ['runId'],
			queryParams: ['collection', 'prefix', 'signature'],
			riskLevel: 'read',
			description: "Download default store's records",
		},
		logGet: {
			method: 'GET',
			path: '/v2/actor-runs/{runId}/log',
			pathParams: ['runId'],
			queryParams: ['stream', 'download', 'raw'],
			riskLevel: 'read',
			description: "Get run's log",
		},
		metamorphPost: {
			method: 'POST',
			path: '/v2/actor-runs/{runId}/metamorph',
			pathParams: ['runId'],
			queryParams: ['targetActorId', 'build'],
			riskLevel: 'write',
			description: 'Metamorph run',
		},
		put: {
			method: 'PUT',
			path: '/v2/actor-runs/{runId}',
			pathParams: ['runId'],
			riskLevel: 'write',
			description: 'Update run',
		},
		rebootPost: {
			method: 'POST',
			path: '/v2/actor-runs/{runId}/reboot',
			pathParams: ['runId'],
			riskLevel: 'write',
			description: 'Reboot run',
		},
		requestQueueDelete: {
			method: 'DELETE',
			path: '/v2/actor-runs/{runId}/request-queue',
			pathParams: ['runId'],
			riskLevel: 'destructive',
			irreversible: true,
			description: 'Delete default request queue',
		},
		requestQueueGet: {
			method: 'GET',
			path: '/v2/actor-runs/{runId}/request-queue',
			pathParams: ['runId'],
			riskLevel: 'read',
			description: 'Get default request queue',
		},
		requestQueueHeadGet: {
			method: 'GET',
			path: '/v2/actor-runs/{runId}/request-queue/head',
			pathParams: ['runId'],
			queryParams: ['limit', 'clientKey'],
			riskLevel: 'read',
			description: 'Get default request queue head',
		},
		requestQueueHeadLockPost: {
			method: 'POST',
			path: '/v2/actor-runs/{runId}/request-queue/head/lock',
			pathParams: ['runId'],
			queryParams: ['lockSecs', 'limit', 'clientKey'],
			riskLevel: 'write',
			description: 'Get and lock default request queue head',
		},
		requestQueuePut: {
			method: 'PUT',
			path: '/v2/actor-runs/{runId}/request-queue',
			pathParams: ['runId'],
			riskLevel: 'write',
			description: 'Update default request queue',
		},
		requestQueueRequestDelete: {
			method: 'DELETE',
			path: '/v2/actor-runs/{runId}/request-queue/requests/{requestId}',
			pathParams: ['runId', 'requestId'],
			queryParams: ['clientKey'],
			riskLevel: 'destructive',
			irreversible: true,
			description: 'Delete request from default request queue',
		},
		requestQueueRequestGet: {
			method: 'GET',
			path: '/v2/actor-runs/{runId}/request-queue/requests/{requestId}',
			pathParams: ['runId', 'requestId'],
			riskLevel: 'read',
			description: 'Get request from default request queue',
		},
		requestQueueRequestLockDelete: {
			method: 'DELETE',
			path: '/v2/actor-runs/{runId}/request-queue/requests/{requestId}/lock',
			pathParams: ['runId', 'requestId'],
			queryParams: ['clientKey', 'forefront'],
			riskLevel: 'write',
			description: 'Delete lock on request in default request queue',
		},
		requestQueueRequestLockPut: {
			method: 'PUT',
			path: '/v2/actor-runs/{runId}/request-queue/requests/{requestId}/lock',
			pathParams: ['runId', 'requestId'],
			queryParams: ['lockSecs', 'clientKey', 'forefront'],
			riskLevel: 'write',
			description: 'Prolong lock on request in default request queue',
		},
		requestQueueRequestPut: {
			method: 'PUT',
			path: '/v2/actor-runs/{runId}/request-queue/requests/{requestId}',
			pathParams: ['runId', 'requestId'],
			queryParams: ['forefront', 'clientKey'],
			riskLevel: 'write',
			description: 'Update request in default request queue',
		},
		requestQueueRequestsBatchDelete: {
			method: 'DELETE',
			path: '/v2/actor-runs/{runId}/request-queue/requests/batch',
			pathParams: ['runId'],
			queryParams: ['clientKey'],
			riskLevel: 'destructive',
			irreversible: true,
			description: 'Batch delete requests from default request queue',
		},
		requestQueueRequestsBatchPost: {
			method: 'POST',
			path: '/v2/actor-runs/{runId}/request-queue/requests/batch',
			pathParams: ['runId'],
			queryParams: ['clientKey', 'forefront'],
			riskLevel: 'write',
			description: 'Batch add requests to default request queue',
		},
		requestQueueRequestsGet: {
			method: 'GET',
			path: '/v2/actor-runs/{runId}/request-queue/requests',
			pathParams: ['runId'],
			queryParams: [
				'clientKey',
				'exclusiveStartId',
				'limit',
				'cursor',
				'filter',
			],
			riskLevel: 'read',
			description: "List default request queue's requests",
		},
		requestQueueRequestsPost: {
			method: 'POST',
			path: '/v2/actor-runs/{runId}/request-queue/requests',
			pathParams: ['runId'],
			queryParams: ['clientKey', 'forefront'],
			riskLevel: 'write',
			description: 'Add request to default request queue',
		},
		requestQueueRequestsUnlockPost: {
			method: 'POST',
			path: '/v2/actor-runs/{runId}/request-queue/requests/unlock',
			pathParams: ['runId'],
			queryParams: ['clientKey'],
			riskLevel: 'write',
			description: 'Unlock requests in default request queue',
		},
	},
	actorRuns: {
		get: {
			method: 'GET',
			path: '/v2/actor-runs',
			pathParams: [],
			queryParams: [
				'offset',
				'limit',
				'desc',
				'status',
				'startedAfter',
				'startedBefore',
			],
			riskLevel: 'read',
			description: 'Get user runs list',
		},
	},
	actorTask: {
		delete: {
			method: 'DELETE',
			path: '/v2/actor-tasks/{actorTaskId}',
			pathParams: ['actorTaskId'],
			riskLevel: 'destructive',
			irreversible: true,
			description: 'Delete task',
		},
		get: {
			method: 'GET',
			path: '/v2/actor-tasks/{actorTaskId}',
			pathParams: ['actorTaskId'],
			riskLevel: 'read',
			description: 'Get task',
		},
		inputGet: {
			method: 'GET',
			path: '/v2/actor-tasks/{actorTaskId}/input',
			pathParams: ['actorTaskId'],
			riskLevel: 'read',
			description: 'Get task input',
		},
		inputPut: {
			method: 'PUT',
			path: '/v2/actor-tasks/{actorTaskId}/input',
			pathParams: ['actorTaskId'],
			riskLevel: 'write',
			description: 'Update task input',
		},
		lastLogGet: {
			method: 'GET',
			path: '/v2/actor-tasks/{actorTaskId}/runs/last/log',
			pathParams: ['actorTaskId'],
			queryParams: ['status', 'origin', 'stream', 'download', 'raw'],
			riskLevel: 'read',
			description: "Get last Actor task run's log",
		},
		put: {
			method: 'PUT',
			path: '/v2/actor-tasks/{actorTaskId}',
			pathParams: ['actorTaskId'],
			riskLevel: 'write',
			description: 'Update task',
		},
		runsGet: {
			method: 'GET',
			path: '/v2/actor-tasks/{actorTaskId}/runs',
			pathParams: ['actorTaskId'],
			queryParams: ['offset', 'limit', 'desc', 'status'],
			riskLevel: 'read',
			description: 'Get list of task runs',
		},
		runsLastAbortPost: {
			method: 'POST',
			path: '/v2/actor-tasks/{actorTaskId}/runs/last/abort',
			pathParams: ['actorTaskId'],
			queryParams: ['status', 'origin', 'gracefully'],
			riskLevel: 'write',
			description: "Abort Actor task's last run",
		},
		runsLastDatasetDelete: {
			method: 'DELETE',
			path: '/v2/actor-tasks/{actorTaskId}/runs/last/dataset',
			pathParams: ['actorTaskId'],
			queryParams: ['status', 'origin'],
			riskLevel: 'destructive',
			irreversible: true,
			description: "Delete last task run's default dataset",
		},
		runsLastDatasetGet: {
			method: 'GET',
			path: '/v2/actor-tasks/{actorTaskId}/runs/last/dataset',
			pathParams: ['actorTaskId'],
			queryParams: ['status', 'origin'],
			riskLevel: 'read',
			description: "Get last task run's default dataset",
		},
		runsLastDatasetItemsGet: {
			method: 'GET',
			path: '/v2/actor-tasks/{actorTaskId}/runs/last/dataset/items',
			pathParams: ['actorTaskId'],
			queryParams: [
				'status',
				'origin',
				'format',
				'clean',
				'offset',
				'limit',
				'fields',
				'outputFields',
				'omit',
				'unwind',
				'flatten',
				'desc',
				'attachment',
				'delimiter',
				'bom',
				'xmlRoot',
				'xmlRow',
				'skipHeaderRow',
				'skipHidden',
				'skipEmpty',
				'simplified',
				'view',
				'skipFailedPages',
				'feedTitle',
				'feedDescription',
				'signature',
			],
			riskLevel: 'read',
			description: "Get last task run's dataset items",
		},
		runsLastDatasetItemsPost: {
			method: 'POST',
			path: '/v2/actor-tasks/{actorTaskId}/runs/last/dataset/items',
			pathParams: ['actorTaskId'],
			queryParams: ['status', 'origin'],
			riskLevel: 'write',
			description: "Store items in last task run's dataset",
		},
		runsLastDatasetPut: {
			method: 'PUT',
			path: '/v2/actor-tasks/{actorTaskId}/runs/last/dataset',
			pathParams: ['actorTaskId'],
			queryParams: ['status', 'origin'],
			riskLevel: 'write',
			description: "Update last task run's default dataset",
		},
		runsLastDatasetStatisticsGet: {
			method: 'GET',
			path: '/v2/actor-tasks/{actorTaskId}/runs/last/dataset/statistics',
			pathParams: ['actorTaskId'],
			queryParams: ['status', 'origin'],
			riskLevel: 'read',
			description: "Get last task run's dataset statistics",
		},
		runsLastGet: {
			method: 'GET',
			path: '/v2/actor-tasks/{actorTaskId}/runs/last',
			pathParams: ['actorTaskId'],
			queryParams: ['status', 'origin', 'waitForFinish'],
			riskLevel: 'read',
			description: 'Get last run',
		},
		runsLastKeyValueStoreDelete: {
			method: 'DELETE',
			path: '/v2/actor-tasks/{actorTaskId}/runs/last/key-value-store',
			pathParams: ['actorTaskId'],
			queryParams: ['status', 'origin'],
			riskLevel: 'destructive',
			irreversible: true,
			description: "Delete last task run's default store",
		},
		runsLastKeyValueStoreGet: {
			method: 'GET',
			path: '/v2/actor-tasks/{actorTaskId}/runs/last/key-value-store',
			pathParams: ['actorTaskId'],
			queryParams: ['status', 'origin'],
			riskLevel: 'read',
			description: "Get last task run's default store",
		},
		runsLastKeyValueStoreKeysGet: {
			method: 'GET',
			path: '/v2/actor-tasks/{actorTaskId}/runs/last/key-value-store/keys',
			pathParams: ['actorTaskId'],
			queryParams: [
				'status',
				'origin',
				'exclusiveStartKey',
				'limit',
				'collection',
				'prefix',
				'signature',
			],
			riskLevel: 'read',
			description: "Get last task run's default store's list of keys",
		},
		runsLastKeyValueStorePut: {
			method: 'PUT',
			path: '/v2/actor-tasks/{actorTaskId}/runs/last/key-value-store',
			pathParams: ['actorTaskId'],
			queryParams: ['status', 'origin'],
			riskLevel: 'write',
			description: "Update last task run's default store",
		},
		runsLastKeyValueStoreRecordDelete: {
			method: 'DELETE',
			path: '/v2/actor-tasks/{actorTaskId}/runs/last/key-value-store/records/{recordKey}',
			pathParams: ['actorTaskId', 'recordKey'],
			queryParams: ['status', 'origin'],
			riskLevel: 'destructive',
			irreversible: true,
			description: "Delete last task run's default store's record",
		},
		runsLastKeyValueStoreRecordGet: {
			method: 'GET',
			path: '/v2/actor-tasks/{actorTaskId}/runs/last/key-value-store/records/{recordKey}',
			pathParams: ['actorTaskId', 'recordKey'],
			queryParams: ['status', 'origin', 'signature', 'attachment'],
			riskLevel: 'read',
			description: "Get last task run's default store's record",
		},
		runsLastKeyValueStoreRecordPost: {
			method: 'POST',
			path: '/v2/actor-tasks/{actorTaskId}/runs/last/key-value-store/records/{recordKey}',
			pathParams: ['actorTaskId', 'recordKey'],
			queryParams: ['status', 'origin'],
			riskLevel: 'write',
			description: "Store record in last task run's default store (POST)",
		},
		runsLastKeyValueStoreRecordPut: {
			method: 'PUT',
			path: '/v2/actor-tasks/{actorTaskId}/runs/last/key-value-store/records/{recordKey}',
			pathParams: ['actorTaskId', 'recordKey'],
			queryParams: ['status', 'origin'],
			riskLevel: 'write',
			description: "Store record in last task run's default store",
		},
		runsLastKeyValueStoreRecordsGet: {
			method: 'GET',
			path: '/v2/actor-tasks/{actorTaskId}/runs/last/key-value-store/records',
			pathParams: ['actorTaskId'],
			queryParams: ['status', 'origin', 'collection', 'prefix', 'signature'],
			riskLevel: 'read',
			description: "Download last task run's default store's records",
		},
		runsLastMetamorphPost: {
			method: 'POST',
			path: '/v2/actor-tasks/{actorTaskId}/runs/last/metamorph',
			pathParams: ['actorTaskId'],
			queryParams: ['status', 'origin', 'targetActorId', 'build'],
			riskLevel: 'write',
			description: "Metamorph Actor task's last run",
		},
		runsLastRebootPost: {
			method: 'POST',
			path: '/v2/actor-tasks/{actorTaskId}/runs/last/reboot',
			pathParams: ['actorTaskId'],
			queryParams: ['status', 'origin'],
			riskLevel: 'write',
			description: "Reboot Actor task's last run",
		},
		runsLastRequestQueueDelete: {
			method: 'DELETE',
			path: '/v2/actor-tasks/{actorTaskId}/runs/last/request-queue',
			pathParams: ['actorTaskId'],
			queryParams: ['status', 'origin'],
			riskLevel: 'destructive',
			irreversible: true,
			description: "Delete last task run's default request queue",
		},
		runsLastRequestQueueGet: {
			method: 'GET',
			path: '/v2/actor-tasks/{actorTaskId}/runs/last/request-queue',
			pathParams: ['actorTaskId'],
			queryParams: ['status', 'origin'],
			riskLevel: 'read',
			description: "Get last task run's default request queue",
		},
		runsLastRequestQueueHeadGet: {
			method: 'GET',
			path: '/v2/actor-tasks/{actorTaskId}/runs/last/request-queue/head',
			pathParams: ['actorTaskId'],
			queryParams: ['status', 'origin', 'limit', 'clientKey'],
			riskLevel: 'read',
			description: "Get last task run's default request queue head",
		},
		runsLastRequestQueueHeadLockPost: {
			method: 'POST',
			path: '/v2/actor-tasks/{actorTaskId}/runs/last/request-queue/head/lock',
			pathParams: ['actorTaskId'],
			queryParams: ['status', 'origin', 'lockSecs', 'limit', 'clientKey'],
			riskLevel: 'write',
			description: "Get and lock last task run's default request queue head",
		},
		runsLastRequestQueuePut: {
			method: 'PUT',
			path: '/v2/actor-tasks/{actorTaskId}/runs/last/request-queue',
			pathParams: ['actorTaskId'],
			queryParams: ['status', 'origin'],
			riskLevel: 'write',
			description: "Update last task run's default request queue",
		},
		runsLastRequestQueueRequestDelete: {
			method: 'DELETE',
			path: '/v2/actor-tasks/{actorTaskId}/runs/last/request-queue/requests/{requestId}',
			pathParams: ['actorTaskId', 'requestId'],
			queryParams: ['status', 'origin', 'clientKey'],
			riskLevel: 'destructive',
			irreversible: true,
			description: "Delete request from last task run's default request queue",
		},
		runsLastRequestQueueRequestGet: {
			method: 'GET',
			path: '/v2/actor-tasks/{actorTaskId}/runs/last/request-queue/requests/{requestId}',
			pathParams: ['actorTaskId', 'requestId'],
			queryParams: ['status', 'origin'],
			riskLevel: 'read',
			description: "Get request from last task run's default request queue",
		},
		runsLastRequestQueueRequestLockDelete: {
			method: 'DELETE',
			path: '/v2/actor-tasks/{actorTaskId}/runs/last/request-queue/requests/{requestId}/lock',
			pathParams: ['actorTaskId', 'requestId'],
			queryParams: ['status', 'origin', 'clientKey', 'forefront'],
			riskLevel: 'write',
			description:
				"Delete lock on request in last task run's default request queue",
		},
		runsLastRequestQueueRequestLockPut: {
			method: 'PUT',
			path: '/v2/actor-tasks/{actorTaskId}/runs/last/request-queue/requests/{requestId}/lock',
			pathParams: ['actorTaskId', 'requestId'],
			queryParams: ['status', 'origin', 'lockSecs', 'clientKey', 'forefront'],
			riskLevel: 'write',
			description:
				"Prolong lock on request in last task run's default request queue",
		},
		runsLastRequestQueueRequestPut: {
			method: 'PUT',
			path: '/v2/actor-tasks/{actorTaskId}/runs/last/request-queue/requests/{requestId}',
			pathParams: ['actorTaskId', 'requestId'],
			queryParams: ['status', 'origin', 'forefront', 'clientKey'],
			riskLevel: 'write',
			description: "Update request in last task run's default request queue",
		},
		runsLastRequestQueueRequestsBatchDelete: {
			method: 'DELETE',
			path: '/v2/actor-tasks/{actorTaskId}/runs/last/request-queue/requests/batch',
			pathParams: ['actorTaskId'],
			queryParams: ['status', 'origin', 'clientKey'],
			riskLevel: 'destructive',
			irreversible: true,
			description:
				"Batch delete requests from last task run's default request queue",
		},
		runsLastRequestQueueRequestsBatchPost: {
			method: 'POST',
			path: '/v2/actor-tasks/{actorTaskId}/runs/last/request-queue/requests/batch',
			pathParams: ['actorTaskId'],
			queryParams: ['status', 'origin', 'clientKey', 'forefront'],
			riskLevel: 'write',
			description:
				"Batch add requests to last task run's default request queue",
		},
		runsLastRequestQueueRequestsGet: {
			method: 'GET',
			path: '/v2/actor-tasks/{actorTaskId}/runs/last/request-queue/requests',
			pathParams: ['actorTaskId'],
			queryParams: [
				'status',
				'origin',
				'clientKey',
				'exclusiveStartId',
				'limit',
				'cursor',
				'filter',
			],
			riskLevel: 'read',
			description: "List last task run's default request queue's requests",
		},
		runsLastRequestQueueRequestsPost: {
			method: 'POST',
			path: '/v2/actor-tasks/{actorTaskId}/runs/last/request-queue/requests',
			pathParams: ['actorTaskId'],
			queryParams: ['status', 'origin', 'clientKey', 'forefront'],
			riskLevel: 'write',
			description: "Add request to last task run's default request queue",
		},
		runsLastRequestQueueRequestsUnlockPost: {
			method: 'POST',
			path: '/v2/actor-tasks/{actorTaskId}/runs/last/request-queue/requests/unlock',
			pathParams: ['actorTaskId'],
			queryParams: ['status', 'origin', 'clientKey'],
			riskLevel: 'write',
			description: "Unlock requests in last task run's default request queue",
		},
		runsPost: {
			method: 'POST',
			path: '/v2/actor-tasks/{actorTaskId}/runs',
			pathParams: ['actorTaskId'],
			queryParams: [
				'timeout',
				'memory',
				'maxItems',
				'maxTotalChargeUsd',
				'restartOnError',
				'build',
				'waitForFinish',
				'webhooks',
			],
			riskLevel: 'write',
			description: 'Run task',
		},
		runSyncGet: {
			method: 'GET',
			path: '/v2/actor-tasks/{actorTaskId}/run-sync',
			pathParams: ['actorTaskId'],
			queryParams: [
				'timeout',
				'memory',
				'maxItems',
				'build',
				'outputRecordKey',
				'webhooks',
			],
			riskLevel: 'write',
			description: 'Run task synchronously',
		},
		runSyncGetDatasetItemsGet: {
			method: 'GET',
			path: '/v2/actor-tasks/{actorTaskId}/run-sync-get-dataset-items',
			pathParams: ['actorTaskId'],
			queryParams: [
				'timeout',
				'memory',
				'maxItems',
				'build',
				'webhooks',
				'format',
				'clean',
				'offset',
				'limit',
				'fields',
				'outputFields',
				'omit',
				'unwind',
				'flatten',
				'desc',
				'attachment',
				'delimiter',
				'bom',
				'xmlRoot',
				'xmlRow',
				'skipHeaderRow',
				'skipHidden',
				'skipEmpty',
				'simplified',
				'view',
				'skipFailedPages',
				'feedTitle',
				'feedDescription',
			],
			riskLevel: 'write',
			description: 'Run task synchronously and get dataset items',
		},
		runSyncGetDatasetItemsPost: {
			method: 'POST',
			path: '/v2/actor-tasks/{actorTaskId}/run-sync-get-dataset-items',
			pathParams: ['actorTaskId'],
			queryParams: [
				'timeout',
				'memory',
				'maxItems',
				'maxTotalChargeUsd',
				'restartOnError',
				'build',
				'webhooks',
				'format',
				'clean',
				'offset',
				'limit',
				'fields',
				'outputFields',
				'omit',
				'unwind',
				'flatten',
				'desc',
				'attachment',
				'delimiter',
				'bom',
				'xmlRoot',
				'xmlRow',
				'skipHeaderRow',
				'skipHidden',
				'skipEmpty',
				'simplified',
				'view',
				'skipFailedPages',
				'feedTitle',
				'feedDescription',
			],
			riskLevel: 'write',
			description: 'Run task synchronously and get dataset items',
		},
		runSyncPost: {
			method: 'POST',
			path: '/v2/actor-tasks/{actorTaskId}/run-sync',
			pathParams: ['actorTaskId'],
			queryParams: [
				'timeout',
				'memory',
				'maxItems',
				'maxTotalChargeUsd',
				'restartOnError',
				'build',
				'outputRecordKey',
				'webhooks',
			],
			riskLevel: 'write',
			description: 'Run task synchronously',
		},
		webhooksGet: {
			method: 'GET',
			path: '/v2/actor-tasks/{actorTaskId}/webhooks',
			pathParams: ['actorTaskId'],
			queryParams: ['offset', 'limit', 'desc'],
			riskLevel: 'read',
			description: 'Get list of webhooks',
		},
	},
	actorTasks: {
		get: {
			method: 'GET',
			path: '/v2/actor-tasks',
			pathParams: [],
			queryParams: ['offset', 'limit', 'desc'],
			riskLevel: 'read',
			description: 'Get list of tasks',
		},
		post: {
			method: 'POST',
			path: '/v2/actor-tasks',
			pathParams: [],
			riskLevel: 'write',
			description: 'Create task',
		},
	},
	acts: {
		get: {
			method: 'GET',
			path: '/v2/actors',
			pathParams: [],
			queryParams: ['my', 'offset', 'limit', 'desc', 'sortBy'],
			riskLevel: 'read',
			description: 'Get list of Actors',
		},
		post: {
			method: 'POST',
			path: '/v2/actors',
			pathParams: [],
			riskLevel: 'write',
			description: 'Create Actor',
		},
	},
	dataset: {
		delete: {
			method: 'DELETE',
			path: '/v2/datasets/{datasetId}',
			pathParams: ['datasetId'],
			riskLevel: 'destructive',
			irreversible: true,
			description: 'Delete dataset',
		},
		get: {
			method: 'GET',
			path: '/v2/datasets/{datasetId}',
			pathParams: ['datasetId'],
			riskLevel: 'read',
			description: 'Get dataset',
		},
		itemsGet: {
			method: 'GET',
			path: '/v2/datasets/{datasetId}/items',
			pathParams: ['datasetId'],
			queryParams: [
				'format',
				'clean',
				'offset',
				'limit',
				'fields',
				'outputFields',
				'omit',
				'unwind',
				'flatten',
				'desc',
				'attachment',
				'delimiter',
				'bom',
				'xmlRoot',
				'xmlRow',
				'skipHeaderRow',
				'skipHidden',
				'skipEmpty',
				'simplified',
				'view',
				'skipFailedPages',
				'feedTitle',
				'feedDescription',
				'signature',
			],
			riskLevel: 'read',
			description: 'Get dataset items',
		},
		itemsHead: {
			method: 'HEAD',
			path: '/v2/datasets/{datasetId}/items',
			pathParams: ['datasetId'],
			queryParams: [
				'format',
				'clean',
				'offset',
				'limit',
				'fields',
				'outputFields',
				'omit',
				'unwind',
				'flatten',
				'desc',
				'attachment',
				'delimiter',
				'bom',
				'xmlRoot',
				'xmlRow',
				'skipHeaderRow',
				'skipHidden',
				'skipEmpty',
				'simplified',
				'view',
				'skipFailedPages',
				'feedTitle',
				'feedDescription',
				'signature',
			],
			riskLevel: 'read',
			description: 'Get dataset items headers',
		},
		itemsPost: {
			method: 'POST',
			path: '/v2/datasets/{datasetId}/items',
			pathParams: ['datasetId'],
			riskLevel: 'write',
			description: 'Store items',
		},
		put: {
			method: 'PUT',
			path: '/v2/datasets/{datasetId}',
			pathParams: ['datasetId'],
			riskLevel: 'write',
			description: 'Update dataset',
		},
		statisticsGet: {
			method: 'GET',
			path: '/v2/datasets/{datasetId}/statistics',
			pathParams: ['datasetId'],
			riskLevel: 'read',
			description: 'Get dataset statistics',
		},
	},
	datasets: {
		get: {
			method: 'GET',
			path: '/v2/datasets',
			pathParams: [],
			queryParams: ['offset', 'limit', 'desc', 'unnamed', 'ownership'],
			riskLevel: 'read',
			description: 'Get list of datasets',
		},
		post: {
			method: 'POST',
			path: '/v2/datasets',
			pathParams: [],
			queryParams: ['name'],
			riskLevel: 'write',
			description: 'Create dataset',
		},
	},
	keyValueStore: {
		delete: {
			method: 'DELETE',
			path: '/v2/key-value-stores/{storeId}',
			pathParams: ['storeId'],
			riskLevel: 'destructive',
			irreversible: true,
			description: 'Delete store',
		},
		get: {
			method: 'GET',
			path: '/v2/key-value-stores/{storeId}',
			pathParams: ['storeId'],
			riskLevel: 'read',
			description: 'Get store',
		},
		keysGet: {
			method: 'GET',
			path: '/v2/key-value-stores/{storeId}/keys',
			pathParams: ['storeId'],
			queryParams: [
				'exclusiveStartKey',
				'limit',
				'collection',
				'prefix',
				'signature',
			],
			riskLevel: 'read',
			description: 'Get list of keys',
		},
		put: {
			method: 'PUT',
			path: '/v2/key-value-stores/{storeId}',
			pathParams: ['storeId'],
			riskLevel: 'write',
			description: 'Update store',
		},
		recordDelete: {
			method: 'DELETE',
			path: '/v2/key-value-stores/{storeId}/records/{recordKey}',
			pathParams: ['storeId', 'recordKey'],
			riskLevel: 'destructive',
			irreversible: true,
			description: 'Delete record',
		},
		recordGet: {
			method: 'GET',
			path: '/v2/key-value-stores/{storeId}/records/{recordKey}',
			pathParams: ['storeId', 'recordKey'],
			queryParams: ['attachment', 'signature'],
			riskLevel: 'read',
			description: 'Get record',
		},
		recordHead: {
			method: 'HEAD',
			path: '/v2/key-value-stores/{storeId}/records/{recordKey}',
			pathParams: ['storeId', 'recordKey'],
			riskLevel: 'read',
			description: 'Check if a record exists',
		},
		recordPost: {
			method: 'POST',
			path: '/v2/key-value-stores/{storeId}/records/{recordKey}',
			pathParams: ['storeId', 'recordKey'],
			riskLevel: 'write',
			description: 'Store record (POST)',
		},
		recordPut: {
			method: 'PUT',
			path: '/v2/key-value-stores/{storeId}/records/{recordKey}',
			pathParams: ['storeId', 'recordKey'],
			riskLevel: 'write',
			description: 'Store record',
		},
		recordsGet: {
			method: 'GET',
			path: '/v2/key-value-stores/{storeId}/records',
			pathParams: ['storeId'],
			queryParams: ['collection', 'prefix', 'signature'],
			riskLevel: 'read',
			description: 'Download records',
		},
	},
	keyValueStores: {
		get: {
			method: 'GET',
			path: '/v2/key-value-stores',
			pathParams: [],
			queryParams: ['offset', 'limit', 'desc', 'unnamed', 'ownership'],
			riskLevel: 'read',
			description: 'Get list of key-value stores',
		},
		post: {
			method: 'POST',
			path: '/v2/key-value-stores',
			pathParams: [],
			queryParams: ['name'],
			riskLevel: 'write',
			description: 'Create key-value store',
		},
	},
	log: {
		get: {
			method: 'GET',
			path: '/v2/logs/{buildOrRunId}',
			pathParams: ['buildOrRunId'],
			queryParams: ['stream', 'download', 'raw'],
			riskLevel: 'read',
			description: 'Get log',
		},
	},
	postChargeRun: {
		method: 'POST',
		path: '/v2/actor-runs/{runId}/charge',
		pathParams: ['runId'],
		riskLevel: 'write',
		description: 'Charge events in run',
	},
	postResurrectRun: {
		method: 'POST',
		path: '/v2/actor-runs/{runId}/resurrect',
		pathParams: ['runId'],
		queryParams: [
			'build',
			'timeout',
			'memory',
			'maxItems',
			'maxTotalChargeUsd',
			'restartOnError',
		],
		riskLevel: 'write',
		description: 'Resurrect run',
	},
	requestQueue: {
		delete: {
			method: 'DELETE',
			path: '/v2/request-queues/{queueId}',
			pathParams: ['queueId'],
			riskLevel: 'destructive',
			irreversible: true,
			description: 'Delete request queue',
		},
		get: {
			method: 'GET',
			path: '/v2/request-queues/{queueId}',
			pathParams: ['queueId'],
			riskLevel: 'read',
			description: 'Get request queue',
		},
		headGet: {
			method: 'GET',
			path: '/v2/request-queues/{queueId}/head',
			pathParams: ['queueId'],
			queryParams: ['limit', 'clientKey'],
			riskLevel: 'read',
			description: 'Get head',
		},
		headLockPost: {
			method: 'POST',
			path: '/v2/request-queues/{queueId}/head/lock',
			pathParams: ['queueId'],
			queryParams: ['lockSecs', 'limit', 'clientKey'],
			riskLevel: 'write',
			description: 'Get head and lock',
		},
		put: {
			method: 'PUT',
			path: '/v2/request-queues/{queueId}',
			pathParams: ['queueId'],
			riskLevel: 'write',
			description: 'Update request queue',
		},
		requestDelete: {
			method: 'DELETE',
			path: '/v2/request-queues/{queueId}/requests/{requestId}',
			pathParams: ['queueId', 'requestId'],
			queryParams: ['clientKey'],
			riskLevel: 'destructive',
			irreversible: true,
			description: 'Delete request',
		},
		requestGet: {
			method: 'GET',
			path: '/v2/request-queues/{queueId}/requests/{requestId}',
			pathParams: ['queueId', 'requestId'],
			riskLevel: 'read',
			description: 'Get request',
		},
		requestLockDelete: {
			method: 'DELETE',
			path: '/v2/request-queues/{queueId}/requests/{requestId}/lock',
			pathParams: ['queueId', 'requestId'],
			queryParams: ['clientKey', 'forefront'],
			riskLevel: 'write',
			description: 'Delete request lock',
		},
		requestLockPut: {
			method: 'PUT',
			path: '/v2/request-queues/{queueId}/requests/{requestId}/lock',
			pathParams: ['queueId', 'requestId'],
			queryParams: ['lockSecs', 'clientKey', 'forefront'],
			riskLevel: 'write',
			description: 'Prolong request lock',
		},
		requestPut: {
			method: 'PUT',
			path: '/v2/request-queues/{queueId}/requests/{requestId}',
			pathParams: ['queueId', 'requestId'],
			queryParams: ['forefront', 'clientKey'],
			riskLevel: 'write',
			description: 'Update request',
		},
		requestsBatchDelete: {
			method: 'DELETE',
			path: '/v2/request-queues/{queueId}/requests/batch',
			pathParams: ['queueId'],
			queryParams: ['clientKey'],
			riskLevel: 'destructive',
			irreversible: true,
			description: 'Delete requests',
		},
		requestsBatchPost: {
			method: 'POST',
			path: '/v2/request-queues/{queueId}/requests/batch',
			pathParams: ['queueId'],
			queryParams: ['clientKey', 'forefront'],
			riskLevel: 'write',
			description: 'Add requests',
		},
		requestsGet: {
			method: 'GET',
			path: '/v2/request-queues/{queueId}/requests',
			pathParams: ['queueId'],
			queryParams: [
				'clientKey',
				'exclusiveStartId',
				'limit',
				'cursor',
				'filter',
			],
			riskLevel: 'read',
			description: 'List requests',
		},
		requestsPost: {
			method: 'POST',
			path: '/v2/request-queues/{queueId}/requests',
			pathParams: ['queueId'],
			queryParams: ['clientKey', 'forefront'],
			riskLevel: 'write',
			description: 'Add request',
		},
		requestsUnlockPost: {
			method: 'POST',
			path: '/v2/request-queues/{queueId}/requests/unlock',
			pathParams: ['queueId'],
			queryParams: ['clientKey'],
			riskLevel: 'write',
			description: 'Unlock requests',
		},
	},
	requestQueues: {
		get: {
			method: 'GET',
			path: '/v2/request-queues',
			pathParams: [],
			queryParams: ['offset', 'limit', 'desc', 'unnamed', 'ownership'],
			riskLevel: 'read',
			description: 'Get list of request queues',
		},
		post: {
			method: 'POST',
			path: '/v2/request-queues',
			pathParams: [],
			queryParams: ['name'],
			riskLevel: 'write',
			description: 'Create request queue',
		},
	},
	schedule: {
		delete: {
			method: 'DELETE',
			path: '/v2/schedules/{scheduleId}',
			pathParams: ['scheduleId'],
			riskLevel: 'destructive',
			irreversible: true,
			description: 'Delete schedule',
		},
		get: {
			method: 'GET',
			path: '/v2/schedules/{scheduleId}',
			pathParams: ['scheduleId'],
			riskLevel: 'read',
			description: 'Get schedule',
		},
		logGet: {
			method: 'GET',
			path: '/v2/schedules/{scheduleId}/log',
			pathParams: ['scheduleId'],
			riskLevel: 'read',
			description: 'Get schedule log',
		},
		put: {
			method: 'PUT',
			path: '/v2/schedules/{scheduleId}',
			pathParams: ['scheduleId'],
			riskLevel: 'write',
			description: 'Update schedule',
		},
	},
	schedules: {
		get: {
			method: 'GET',
			path: '/v2/schedules',
			pathParams: [],
			queryParams: ['offset', 'limit', 'desc'],
			riskLevel: 'read',
			description: 'Get list of schedules',
		},
		post: {
			method: 'POST',
			path: '/v2/schedules',
			pathParams: [],
			riskLevel: 'write',
			description: 'Create schedule',
		},
	},
	store: {
		get: {
			method: 'GET',
			path: '/v2/store',
			pathParams: [],
			queryParams: [
				'limit',
				'offset',
				'search',
				'sortBy',
				'category',
				'username',
				'pricingModel',
				'allowsAgenticUsers',
				'responseFormat',
				'includeUnrunnableActors',
			],
			riskLevel: 'read',
			description: 'Get list of Actors in Store',
		},
	},
	tools: {
		browserInfoDelete: {
			method: 'DELETE',
			path: '/v2/browser-info',
			pathParams: [],
			queryParams: ['skipHeaders', 'rawHeaders'],
			riskLevel: 'destructive',
			irreversible: true,
			description: 'Get browser info',
		},
		browserInfoGet: {
			method: 'GET',
			path: '/v2/browser-info',
			pathParams: [],
			queryParams: ['skipHeaders', 'rawHeaders'],
			riskLevel: 'read',
			description: 'Get browser info',
		},
		browserInfoPost: {
			method: 'POST',
			path: '/v2/browser-info',
			pathParams: [],
			queryParams: ['skipHeaders', 'rawHeaders'],
			riskLevel: 'write',
			description: 'Get browser info',
		},
		browserInfoPut: {
			method: 'PUT',
			path: '/v2/browser-info',
			pathParams: [],
			queryParams: ['skipHeaders', 'rawHeaders'],
			riskLevel: 'write',
			description: 'Get browser info',
		},
		decodeAndVerifyPost: {
			method: 'POST',
			path: '/v2/tools/decode-and-verify',
			pathParams: [],
			riskLevel: 'write',
			description: 'Decode and verify object',
		},
		encodeAndSignPost: {
			method: 'POST',
			path: '/v2/tools/encode-and-sign',
			pathParams: [],
			riskLevel: 'write',
			description: 'Encode and sign object',
		},
	},
	user: {
		get: {
			method: 'GET',
			path: '/v2/users/{userId}',
			pathParams: ['userId'],
			riskLevel: 'read',
			description: 'Get public user data',
		},
	},
	users: {
		meGet: {
			method: 'GET',
			path: '/v2/users/me',
			pathParams: [],
			riskLevel: 'read',
			description: 'Get private user data',
		},
		meLimitsGet: {
			method: 'GET',
			path: '/v2/users/me/limits',
			pathParams: [],
			riskLevel: 'read',
			description: 'Get limits',
		},
		meLimitsPut: {
			method: 'PUT',
			path: '/v2/users/me/limits',
			pathParams: [],
			riskLevel: 'write',
			description: 'Update limits',
		},
		meUsageMonthlyGet: {
			method: 'GET',
			path: '/v2/users/me/usage/monthly',
			pathParams: [],
			queryParams: ['date'],
			riskLevel: 'read',
			description: 'Get monthly usage',
		},
	},
	webhook: {
		delete: {
			method: 'DELETE',
			path: '/v2/webhooks/{webhookId}',
			pathParams: ['webhookId'],
			riskLevel: 'destructive',
			irreversible: true,
			description: 'Delete webhook',
		},
		get: {
			method: 'GET',
			path: '/v2/webhooks/{webhookId}',
			pathParams: ['webhookId'],
			riskLevel: 'read',
			description: 'Get webhook',
		},
		put: {
			method: 'PUT',
			path: '/v2/webhooks/{webhookId}',
			pathParams: ['webhookId'],
			riskLevel: 'write',
			description: 'Update webhook',
		},
		testPost: {
			method: 'POST',
			path: '/v2/webhooks/{webhookId}/test',
			pathParams: ['webhookId'],
			riskLevel: 'write',
			description: 'Test webhook',
		},
		webhookDispatchesGet: {
			method: 'GET',
			path: '/v2/webhooks/{webhookId}/dispatches',
			pathParams: ['webhookId'],
			riskLevel: 'read',
			description: 'Get collection',
		},
	},
	webhookDispatch: {
		get: {
			method: 'GET',
			path: '/v2/webhook-dispatches/{dispatchId}',
			pathParams: ['dispatchId'],
			riskLevel: 'read',
			description: 'Get webhook dispatch',
		},
	},
	webhookDispatches: {
		get: {
			method: 'GET',
			path: '/v2/webhook-dispatches',
			pathParams: [],
			queryParams: ['offset', 'limit', 'desc'],
			riskLevel: 'read',
			description: 'Get list of webhook dispatches',
		},
	},
	webhooks: {
		get: {
			method: 'GET',
			path: '/v2/webhooks',
			pathParams: [],
			queryParams: ['offset', 'limit', 'desc'],
			riskLevel: 'read',
			description: 'Get list of webhooks',
		},
		post: {
			method: 'POST',
			path: '/v2/webhooks',
			pathParams: [],
			riskLevel: 'write',
			description: 'Create webhook',
		},
	},
} as const satisfies ApifyOperationTree;
